# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: kombu
  version: "5.6.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/kombu-${{ version }}.tar.gz
  sha256: 8060497058066c6f5aed7c26d7cd0d3b574990b09de842a8c5aaed0b92cc5a55

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    # See https://pypi.org/pypi/kombu/{{ version }}/json
    - amqp >=5.1.1,<6.0.0
    - vine ==5.1.0
    - python-tzdata >=2025.2
    - packaging
    - boto3 >=1.26.143  # for sqs option

tests:
  - python:
      imports:
        - kombu
        - kombu.asynchronous
        - kombu.asynchronous.aws
        - kombu.asynchronous.http
        - kombu.transport
        - kombu.transport.virtual
        - kombu.utils
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Messaging library for Python.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://kombu.readthedocs.io
  repository: https://github.com/celery/kombu
  documentation: https://pythonhosted.org/kombu/

extra:
  recipe-maintainers:
    - chrisburr
    - anguslees
    - kwilcox
    - jamesmyatt
