# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: dg-sqlmesh
  version: "1.10.1"
  python_check_max: "3.12"
  python_min: '3.11'
  # dg-sqlmesh 1.10.1 depends on Python <3.13,>=3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dg_sqlmesh-${{ version }}.tar.gz
  sha256: 0dbf9ab546d0233dcff99f8752a9007ae372b47cd87495cfa924dde8896b2e90

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }},<4
    - dagster >=1.11.8
    - pandas >=2.2.1
    - sqlmesh >=0.214.0
    - anyio >=4.9.0
    - vulture >=2.14
    - jinja2 >=3.0.0

tests:
  - python:
      imports:
        - dg_sqlmesh
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  summary: Seamless integration between Dagster and SQLMesh for modern data engineering workflows
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/fosk06/dagster-sqlmesh

extra:
  recipe-maintainers:
    - rxm7706
