# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-rath
  version: "0.1.0"
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # This will be the PyPI URL after publication
  url: https://github.com/yourusername/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: TO_BE_DETERMINED

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=${{ python_min }}
    - django >=3.2
    - pandas >=1.0.0
    - pygwalker >=0.4.0

tests:
  - python:
      imports:
        - django_rath
        - django_rath.views
        - django_rath.mixins
        - django_rath.templatetags.rath_tags
      pip_check: true

about:
  homepage: https://github.com/yourusername/django-rath
  repository: https://github.com/yourusername/django-rath
  documentation: https://django-rath.readthedocs.io
  summary: Django integration for Kanaries Rath automated data exploration
  description: |
    django-rath provides seamless integration of Kanaries Rath (automated data
    exploration and visualization platform) into Django applications.

    Features:
    - RathView class-based views for easy integration
    - RathMixin for adding Rath to existing views
    - Template tags for embedding visualizations
    - Support for Django querysets, DataFrames, and CSV files
    - Saved visualizations with Django models
    - Optional Rath cloud integration
    - Auto insights and causal inference capabilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
