# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.0.0"

package:
  name: simpervisor
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/simpervisor/simpervisor-${{ version }}.tar.gz
  sha256: 7eb87ca86d5e276976f5bb0290975a05d452c6a7b7f58062daea7d8369c823c1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - simpervisor
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pypi.org/project/simpervisor/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Simple async process supervisor
  description: |
    Simple async process supervisor
  repository: https://github.com/jupyterhub/simpervisor
  documentation: https://github.com/jupyterhub/simpervisor#readme

extra:
  recipe-maintainers:
    - consideratio
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: simpervisor
  cfe-upstream-registry: pypi
  cfe-upstream-name: simpervisor
  cfe-purls:
    - pkg:conda/simpervisor@${{ version }}?channel=conda-forge
    - pkg:pypi/simpervisor@${{ version }}
  cfe-upstream-repo: https://github.com/jupyterhub/simpervisor
  cfe-upstream-homepage: https://pypi.org/project/simpervisor/
  cfe-import-names: [simpervisor]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/simpervisor-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-1.0.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T05:28:31Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T05:28:31Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T05:28:31Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
