# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: mozilla-django-oidc
  version: "5.0.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mozilla_django_oidc-${{ version }}.tar.gz
  sha256: ed9eaba7b0023e984f4859f01504e5006fad6ff132c9741a01318cc045bf2c7f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - pyjwt
    - requests
    - cryptography

tests:
  - python:
      imports:
        - mozilla_django_oidc
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A lightweight authentication and access management library for integration with OpenID Connect enabled authentication services.
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/mozilla/mozilla-django-oidc

extra:
  recipe-maintainers:
    - rxm7706
