schema_version: 1

context:
  name: reactpy-forms
  version: 0.0.8

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reactpy_forms-${{ version }}.tar.gz
  sha256: 869571444faeb4e8654bc31a579639673633c34f12554d769e0cb00c1369d1fb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - reactpy >=1.1.0,<2.0.0

tests:
  - python:
      imports:
        - reactpy_forms
      pip_check: true

about:
  summary:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/stevej2608/reactpy-forms/README.md

extra:
  recipe-maintainers:
    - rxm7706
