# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.11.0"

package:
  name: nbclient
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nbclient/nbclient-${{ version }}.tar.gz
  sha256: 04a134a5b087f2c5887f228aca155db50169b8cd9334dee6942c8e927e56081a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.10.0
  run:
    - python >=${{ python_min }}
    - jupyter-client >=7.0.0
    - jupyter-core >=5.4.0
    - nbformat >=5.2.0
    - traitlets >=5.13

tests:
  - python:
      imports:
        - nbclient
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A client library for executing notebooks. Formerly nbconvert's ExecutePreprocessor.
  description: |
    A client library for executing notebooks. Formerly nbconvert's ExecutePreprocessor.
  repository: https://github.com/jupyter/nbclient
  documentation: https://nbclient.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: nbclient
  cfe-upstream-registry: pypi
  cfe-upstream-name: nbclient
  cfe-purls:
    - pkg:conda/nbclient@${{ version }}?channel=conda-forge
    - pkg:pypi/nbclient@${{ version }}
  cfe-upstream-repo: https://github.com/jupyter/nbclient
  cfe-upstream-homepage: https://jupyter.org
  cfe-import-names: [nbclient]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/nbclient-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.11.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T01:57:27Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T01:57:27Z
  cfe-local-build-status: build-clean-test-blocked
  cfe-local-build-datetime: 2026-08-18T01:57:27Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
