# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: confluence-markdown-exporter
  version: "3.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/confluence_markdown_exporter-${{ version }}.tar.gz
  sha256: c850dce2b55121d85ddd1387c790d0a3a79197f9cf7ee2db8bae4370419a8998

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - confluence-markdown-exporter = confluence_markdown_exporter.main:app
      - cf-export = confluence_markdown_exporter.main:app

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - atlassian-python-api
    - jmespath
    - markdownify
    - pandas
    - pydantic-settings
    - pyyaml
    - questionary
    - tabulate
    - tqdm
    - typer
    - python-dateutil

tests:
  - python:
      imports:
        - confluence_markdown_exporter
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - confluence-markdown-exporter --help
      - cf-export --help

about:
  summary: A tool to export Confluence pages to Markdown
  homepage: https://pypi.org/project/confluence-markdown-exporter
  repository: https://github.com/Spenhouet/confluence-markdown-exporter
  description: |
    The confluence-markdown-exporter exports Confluence pages in Markdown format. 
    This exporter helps in migrating content from Confluence to platforms that support Markdown. 
    e.g. Obsidian, Gollum, Azure DevOps (ADO), Foam, Dendron and more.
  documentation: https://github.com/Spenhouet/confluence-markdown-exporter/blob/main/README.md
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
