# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: reloading
  version: "1.1.2"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reloading-${{ version }}.tar.gz
  sha256: 8c28fc66f458a795ea63f543f4282b14de45b7158cc53b1f895057f5308fca95

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - reloading
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Reloads source code of a running program without losing state
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/julvo/reloading

extra:
  recipe-maintainers:
    - rxm7706
