# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: dremio-local-mcp
  version: "0.5.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dremio_local_mcp-${{ version }}.tar.gz
  sha256: 466ed4a655c43ef01c6bf0b53ab801a84a6e3bd3366a0ba1124386f22a4661aa

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dremio-local-mcp = dremio_mcp.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - fastmcp
    - requests
    - pyyaml
    - rich
    - dremio-cli >=1.11.0
    - pytest
    - pytest-asyncio

tests:
  - python:
      imports:
        - dist
        - docs
        - dremio_mcp
        - dremiodocs
        - planning
      pip_check: true
      python_version:
        - ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - dremio-local-mcp --help

about:
  summary: A Model Context Protocol (MCP) server for Dremio
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/AlexMercedCoder/dremio-local-mcp

extra:
  recipe-maintainers:
    - rxm7706