#!/usr/bin/env python3
"""Regenerate the kedro-viz prototype's stub DAG from the REAL pyforge-atlas.

The prototype (``src/prototype/packages/pyforge-atlas-kedro-viz``) is a
dependency-free, MemoryDataset-only Kedro project whose sole purpose is to
visualize (``kedro viz``) / smoke-run (``kedro run``) the *shape* of the real
pyforge-atlas DAG without installing its heavy stack.

This keeps it faithful. It statically parses (AST — **no imports**, so no
pandas / duckdb / dagster needed) each real
``pyforge-atlas/.../pipelines/<name>/pipeline.py`` ``create_pipeline()`` for its
node graph (func name, inputs, outputs, node name), then emits matching stub
pipelines + a MemoryDataset catalog whose ``kedro-viz.layer`` metadata is copied
from the real catalog (falling back to a name heuristic).

Re-run after any pyforge-atlas pipeline change:
    pixi run -e local-recipes regenerate-kedro-viz-proto
"""
from __future__ import annotations

import ast
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[5]
ATLAS_PIPES = REPO / "src/shared/packages/pyforge-atlas/src/pyforge/atlas/pipelines"
ATLAS_CATALOG = REPO / "src/shared/packages/pyforge-atlas/conf/base/catalog.yml"
PROTO_PIPES = REPO / "src/prototype/packages/pyforge-atlas-kedro-viz/src/pyforge/atlas_kedro_viz/pipelines"
PROTO_CONF = REPO / "src/prototype/packages/pyforge-atlas-kedro-viz/conf/base"


# ---- AST parsing of the real pipelines -------------------------------------

def _lit(node):
    """AST node -> python value for the str / [str,...] / dict / None cases."""
    if node is None or isinstance(node, ast.Constant):
        return None if node is None else node.value
    if isinstance(node, (ast.List, ast.Tuple)):
        return [_lit(e) for e in node.elts]
    if isinstance(node, ast.Dict):  # kedro dict inputs {arg: dataset}
        return [_lit(v) for v in node.values]
    return "<dynamic>"  # a variable/expression we can't resolve statically


def _as_list(x):
    if x is None:
        return []
    return [i for i in x if i is not None] if isinstance(x, list) else [x]


def parse_pipeline(pyfile: Path) -> list[dict]:
    """Extract [{name, inputs:[...], outputs:[...]}] from every node(...) call."""
    tree = ast.parse(pyfile.read_text(encoding="utf-8"))
    out = []
    for call in ast.walk(tree):
        if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Name)
                and call.func.id == "node"):
            continue
        kw = {k.arg: k.value for k in call.keywords}

        def pick(key, pos):
            if key in kw:
                return kw[key]
            return call.args[pos] if len(call.args) > pos else None

        name_node = pick("name", 3)
        if not isinstance(name_node, ast.Constant) or not isinstance(name_node.value, str):
            continue  # only real, named nodes
        out.append({
            "name": name_node.value,
            "inputs": _as_list(_lit(pick("inputs", 1))),
            "outputs": _as_list(_lit(pick("outputs", 2))),
        })
    return out


# ---- layer assignment ------------------------------------------------------

def load_real_layers() -> dict[str, str]:
    doc = yaml.safe_load(ATLAS_CATALOG.read_text(encoding="utf-8")) or {}
    layers = {}
    for ds, spec in doc.items():
        if isinstance(spec, dict):
            layer = (spec.get("metadata", {}) or {}).get("kedro-viz", {}).get("layer")
            if layer:
                layers[ds] = layer
    return layers


def layer_for(ds: str, real_layers: dict[str, str]) -> str:
    if ds in real_layers:
        return real_layers[ds]
    if ds.endswith("_raw"):
        return "raw"
    if ds.endswith(("_report", "_bom", "_sbom", "_export")):
        return "derived"
    return "atlas"


# ---- emit ------------------------------------------------------------------

def _fmt(vals: list[str]):
    """Format a node inputs/outputs list back to a str | [list] | None literal."""
    if not vals:
        return "None"
    if len(vals) == 1:
        return repr(vals[0])
    inner = ", ".join(repr(v) for v in vals)
    return f"[{inner}]"


PIPE_HEADER = '''"""``{name}`` pipeline — GENERATED stub mirror of pyforge-atlas.

Auto-generated by tools/regenerate_from_atlas.py from
src/shared/packages/pyforge-atlas/.../pipelines/{name}/. Do not edit by hand;
re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.
"""
from kedro.pipeline import Pipeline, node, pipeline

from pyforge.atlas_kedro_viz.nodes import stub


def create_pipeline() -> Pipeline:
    return pipeline(
        [
'''
PIPE_FOOTER = "        ]\n    )\n"


def main() -> int:
    real_layers = load_real_layers()
    pipe_files = sorted(ATLAS_PIPES.glob("*/pipeline.py"), key=lambda p: p.parent.name)
    parsed = {p.parent.name: parse_pipeline(p) for p in pipe_files}

    # global produced set + free-input detection
    produced: set[str] = set()
    for nodes in parsed.values():
        for n in nodes:
            produced.update(n["outputs"])

    def is_param(ds: str) -> bool:
        return ds == "parameters" or ds.startswith("params:")

    all_datasets: set[str] = set()
    param_paths: set[str] = set()
    free_inputs: set[str] = set()
    for nodes in parsed.values():
        for n in nodes:
            for ds in n["inputs"] + n["outputs"]:
                if is_param(ds):
                    if ds.startswith("params:"):
                        param_paths.add(ds[len("params:"):])
                    continue
                if ds == "<dynamic>":
                    continue
                all_datasets.add(ds)
            for ds in n["inputs"]:
                if not is_param(ds) and ds != "<dynamic>" and ds not in produced:
                    free_inputs.add(ds)

    # assign each free input to the first pipeline (sorted) that consumes it
    assigned: dict[str, str] = {}
    for name in sorted(parsed):
        for n in parsed[name]:
            for ds in n["inputs"]:
                if ds in free_inputs and ds not in assigned:
                    assigned[ds] = name

    # ---- write pipelines ----
    for f in PROTO_PIPES.glob("*.py"):
        if f.name != "__init__.py":
            f.unlink()
    for name in sorted(parsed):
        lines = []
        # extraction stubs for free inputs first-consumed here (inputs=None)
        for ds in sorted(d for d, p in assigned.items() if p == name):
            lines.append(
                f'            node(stub("extract_{ds}"), None, {ds!r}, '
                f'name="extract_{ds}"),'
            )
        for n in parsed[name]:
            n_out = len(n["outputs"])
            stub_call = f'stub("{n["name"]}"' + (f", n_outputs={n_out}" if n_out > 1 else "") + ")"
            inp = [d for d in n["inputs"] if d != "<dynamic>"]
            lines.append(
                f'            node({stub_call}, {_fmt(inp)}, {_fmt(n["outputs"])}, '
                f'name="{n["name"]}"),'
            )
        (PROTO_PIPES / f"{name}.py").write_text(
            PIPE_HEADER.format(name=name) + "\n".join(lines) + "\n" + PIPE_FOOTER,
            encoding="utf-8",
        )

    # ---- catalog.yml (every dataset = MemoryDataset + viz layer) ----
    cat_lines = [
        "# GENERATED by tools/regenerate_from_atlas.py — do not edit by hand.",
        "# Every dataset is a MemoryDataset (stub run, no IO); the kedro-viz",
        "# `layer` mirrors the real pyforge-atlas storage tiers.",
        "",
    ]
    for ds in sorted(all_datasets):
        cat_lines += [
            f"{ds}:",
            "  type: MemoryDataset",
            "  metadata:",
            "    kedro-viz:",
            f"      layer: {layer_for(ds, real_layers)}",
            "",
        ]
    (PROTO_CONF / "catalog.yml").write_text("\n".join(cat_lines), encoding="utf-8")

    # ---- parameters.yml (nested from params: paths, stub values) ----
    params: dict = {}
    for path in sorted(param_paths):
        cur = params
        parts = path.split(".")
        for p in parts[:-1]:
            cur = cur.setdefault(p, {})
        cur[parts[-1]] = None  # stub value; viz only needs the key to exist
    header = "# GENERATED by tools/regenerate_from_atlas.py — stub params for the viz DAG.\n"
    (PROTO_CONF / "parameters.yml").write_text(
        header + (yaml.safe_dump(params, sort_keys=True) if params else "{}\n"),
        encoding="utf-8",
    )

    # ---- pipeline_registry.py (explicit registration — GENERATED) ----
    # find_pipelines() does not discover single-file pipeline modules in this
    # kedro version, so emit an explicit registry (kept in sync by re-running).
    names = sorted(parsed)
    reg_imports = ",\n    ".join(names)
    reg_body = "\n".join(f'        "{n}": {n}.create_pipeline(),' for n in names)
    (PROTO_PIPES.parent / "pipeline_registry.py").write_text(
        '"""Register the prototype pipelines (GENERATED — do not edit by hand).\n\n'
        "Emitted by tools/regenerate_from_atlas.py to mirror the real pyforge-atlas\n"
        'pipeline set. Re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.\n"""\n\n'
        "from kedro.pipeline import Pipeline\n\n"
        f"from pyforge.atlas_kedro_viz.pipelines import (\n    {reg_imports},\n)\n\n\n"
        "def register_pipelines() -> dict[str, Pipeline]:\n"
        "    pipelines = {\n"
        f"{reg_body}\n"
        "    }\n"
        '    pipelines["__default__"] = sum(pipelines.values(), Pipeline([]))\n'
        "    return pipelines\n",
        encoding="utf-8",
    )

    n_nodes = sum(len(v) for v in parsed.values()) + len(assigned)
    print(f"pipelines: {sorted(parsed)}")
    print(f"nodes: {n_nodes} ({len(assigned)} extraction + "
          f"{sum(len(v) for v in parsed.values())} real-mirrored)")
    print(f"datasets: {len(all_datasets)} | params: {len(param_paths)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
