# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: prometheus_client
  version: "0.26.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/prometheus_client-${{ version }}.tar.gz
  sha256: 04a91bcf94e2cf74a44a1a874d651a2e853ed354b6e822f3b7487751465d5c2b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - prometheus_client
        - prometheus_client.bridge
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: Apache-2.0
  summary: Python client for the Prometheus monitoring system
  license_file:
    - NOTICE
    - LICENSE
  homepage: https://github.com/prometheus/client_python

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
