# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.4.0"

package:
  name: sortedcontainers
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sortedcontainers/sortedcontainers-${{ version }}.tar.gz
  sha256: 25caa5a06cc30b6b83d11423433f65d1f9d76c4c6a0c90e3379eaa43b9bfdb88

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - sortedcontainers
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache-2.0
  license_file: LICENSE
  summary: Sorted Containers -- Sorted List, Sorted Dict, Sorted Set
  description: |
    Sorted Containers -- Sorted List, Sorted Dict, Sorted Set

extra:
  recipe-maintainers:
    - grantjenks
    - msarahan
    - richafrank
    - nehaljwani

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: sortedcontainers
  cfe-upstream-registry: pypi
  cfe-upstream-name: sortedcontainers
  cfe-purls:
    - pkg:conda/sortedcontainers@${{ version }}?channel=conda-forge
    - pkg:pypi/sortedcontainers@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: http://www.grantjenks.com/docs/sortedcontainers/
  cfe-import-names: [sortedcontainers]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/sortedcontainers-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-2.4.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T05:39:14Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T05:39:14Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T05:39:14Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
