# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.65b0"

package:
  name: opentelemetry-instrumentation-redis
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/opentelemetry-instrumentation-redis/opentelemetry_instrumentation_redis-${{ version }}.tar.gz
  sha256: f16409f189092984ff922f26939e7be79509365f5c9d202308c13fddf1368147

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - redis
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.65b0
    - opentelemetry-semantic-conventions ==0.65b0
    - wrapt >=1.12.1

tests:
  - python:
      imports:
        - opentelemetry.instrumentation.redis
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenTelemetry Redis instrumentation
  description: |
    OpenTelemetry Redis instrumentation
  repository: https://github.com/open-telemetry/opentelemetry-python-contrib

extra:
  recipe-maintainers:
    - mariusvniekerk

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: opentelemetry-instrumentation-redis
  cfe-upstream-registry: pypi
  cfe-upstream-name: opentelemetry-instrumentation-redis
  cfe-purls:
    - pkg:conda/opentelemetry-instrumentation-redis@${{ version }}?channel=conda-forge
    - pkg:pypi/opentelemetry-instrumentation-redis@${{ version }}
  cfe-upstream-repo: https://github.com/open-telemetry/opentelemetry-python-contrib
  cfe-upstream-homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-redis
  cfe-import-names: [opentelemetry.instrumentation.redis]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/opentelemetry-instrumentation-redis-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.65b0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T10:45:13Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T10:45:13Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T10:45:13Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
#    # added run deps from import test: ['redis']
####
