# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.3"

package:
  name: extensionclass
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/ExtensionClass/extensionclass-${{ version }}.tar.gz
  sha256: 0d0b980848a09329c229dc838b4288bdb7cfe7dad713fec62036fad087e81f84

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - ExtensionClass
        - MethodObject
      pip_check: true

about:
  homepage: https://pypi.org/project/ExtensionClass/
  license: ZPL-2.1
  license_file: LICENSE.txt
  summary: Metaclass for subclassable extension types
  description: |
    Metaclass for subclassable extension types
  repository: https://github.com/zopefoundation/ExtensionClass

extra:
  recipe-maintainers:
    - rxm7706

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: extensionclass
  cfe-upstream-registry: pypi
  cfe-upstream-name: ExtensionClass
  cfe-purls:
    - pkg:conda/extensionclass@${{ version }}?channel=conda-forge
    - pkg:pypi/extensionclass@${{ version }}
  cfe-upstream-repo: https://github.com/zopefoundation/ExtensionClass
  cfe-upstream-homepage: https://pypi.org/project/ExtensionClass/
  cfe-import-names: [MethodObject]
  cfe-source-kind: pypi-sdist
  cfe-noarch: false
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: pending-submission-to-conda-forge
  cfe-on-conda-forge-feedstock: none
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-16T17:27:24Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-16T17:27:24Z
  cfe-local-build-status: not-attempted
  cfe-local-build-datetime: none
  cfe-local-build-platform: none
  cfe-local-build-tool: none
####
# CFE comments
# Header:
#    # P4 Create-recipe local-only. extensionclass.
####
