{% set name = "dagster-vertexai" %}
{% set version = "0.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dagster_vertexai-{{ version }}.tar.gz
  sha256: cb4cb9e88ec0cdddfa0d0a4f5907ff1fbaf512eb9358406b39b90487e9b2075e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }},<4.0
    - dagster >=1.11.9
    - google-cloud-aiplatform >=1.55.0
    - google-auth

test:
  imports:
    - dagster_vertexai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Dagster integration for Google Cloud Vertex AI
  license: 'Apache-2.0'
  license_file: LICENSE
  home: https://github.com/dagster-io/community-integrations

extra:
  recipe-maintainers:
    - rxm7706
