# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: rpaframework-core
  version: "12.0.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rpaframework_core-${{ version }}.tar.gz
  sha256: 5eff2761491e187be56aa4668eb3ba3ce852f1dc7a1fd27c0a401ff04c354b4d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - selenium >=4.0.0,<5.0.0
    - webdriver-manager >=4.0.2,<5.0.0
    - if: win
      then: psutil >=5.9.0
    - if: win and match(python, "!=3.8")
      then: pywin32-on-windows >=300,<400
    - if: win
      then: uiautomation >=2.0.15
    - pillow >=10.2.0
    - packaging >=24.0

tests:
  - python:
      imports:
        - RPA
        - RPA.core
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://rpaframework.org/
  summary: Core utilities used by RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kariharju
    - osrjv
    - rxm7706
    - xylix
