# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: uptrace
  version: "1.41.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/uptrace-${{ version }}.tar.gz
  sha256: 1bb985e0dc43675d40228c53ecb77380ffca117b6369c0544c622c5618e2ff04

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - opentelemetry-api >=1.41.0,<1.42.dev0
    - opentelemetry-sdk >=1.41.0,<1.42.dev0
    - opentelemetry-exporter-otlp >=1.41.0,<1.42.dev0
    - opentelemetry-instrumentation >=0.62b1,<0.63a0

tests:
  - python:
      imports:
        - uptrace
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: OpenTelemetry Python distribution for Uptrace
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://uptrace.dev

extra:
  recipe-maintainers:
    - timkpaine
