# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.0.0"

package:
  name: jiwer
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jiwer/jiwer-${{ version }}.tar.gz
  sha256: ae9c051469102a61ef0927100baeeb4546f78d180c9b0948281d08eaf44c191e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - click >=8.1.8
    - rapidfuzz >=3.9.7

tests:
  - python:
      imports:
        - jiwer
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pypi.org/project/jiwer/
  license: Apache-2.0
  license_file: LICENSE
  summary: Evaluate your speech-to-text system with similarity measures such as word error rate (WER)
  description: |
    Evaluate your speech-to-text system with similarity measures such as word error rate (WER)

extra:
  recipe-maintainers:
    - janjagusch

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: jiwer
  cfe-upstream-registry: pypi
  cfe-upstream-name: jiwer
  cfe-purls:
    - pkg:conda/jiwer@${{ version }}?channel=conda-forge
    - pkg:pypi/jiwer@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://pypi.org/project/jiwer/
  cfe-import-names: [jiwer]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/jiwer-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T00:18:34Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T00:18:34Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T00:18:34Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
