# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: langchain
  version: "0.3.27"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain-${{ version }}.tar.gz
  sha256: aa6f1e6274ff055d0fd36254176770f356ed0a8994297d1df47df341953cec62

build:
  number: 1
  noarch: python
  #skip: py>=400 or match(python, ">=2,<3")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - langchain-server = langchain.server:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - langchain-core >=0.3.72,<1.0.0
    - langchain-text-splitters >=0.3.9,<1.0.0
    - langsmith >=0.1.17
    - pydantic >=2.7.4,<3.0.0
    - sqlalchemy >=1.4,<3
    - requests >=2,<3
    - pyyaml >=5.3
    - async-timeout >=4.0.0,<5.0.0
  run_constraints:
    # based on https://github.com/langchain-ai/langchain/blob/master/libs/langchain/extended_testing_deps.txt
    - jsonschema >=4.22.0,<5
    - numexpr >=2.8.6,<3
    - rapidfuzz >=3.1.1,<4
    - aiosqlite >=0.19.0,<0.20
    # copied from langchain-openai-feedstock
    - openai >=1.26.0,<2.0.0
    - tiktoken >=0.7,<1
    # copied from langchain-anthropic-feedstock
    - anthropic >=0.28.0,<1
    - defusedxml >=0.7.1,<0.8.0
    # copied from langchain-fireworks-feedstock and langchain-together-feedstock
    - fireworks-ai >=0.13.0
    - openai >=1.10.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0
    # copied from langchain-mistralai-feedstock
    - tokenizers >=0.15.1,<1
    - httpx >=0.25.2,<1
    - httpx-sse >=0.3.1,<1
    # copied from langchain-groq-feedstock
    - groq >=0.4.1,<1

tests:
  - python:
      imports:
        - langchain
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://python.langchain.com/
  summary: Building applications with LLMs through composability
  license: MIT
  license_file: LICENSE
  repository: https://github.com/langchain-ai/langchain
  documentation: https://python.langchain.com/docs/introduction/

extra:
  recipe-maintainers:
    - YYYasin19
    - baskaryan
    - ccurme
    - dlqqq
    - hinthornw
    - jan-janssen
    - pavelzw
    - rxm7706
    - sydney-runkle
