{% set name = "jupyterlab-rise" %}
{% set version = "0.43.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_rise-{{ version }}.tar.gz
  sha256: 264ec00e2cb5cc68e2042a054eea2d42925f47f36d883eba9c475b6dd2fe87d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.1.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_server >=2.0.1,<3
    - jupyterlab >=4.1.0,<5
    - jupyterlab-mathjax3

test:
  imports:
    - jupyterlab_rise
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'RISE: "Live" Reveal.js JupyterLab Slideshow extension.'
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/jupyterlab-contrib/rise

extra:
  recipe-maintainers:
    - rxm7706
