# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.16"

package:
  name: python-louvain
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-louvain/python-louvain-${{ version }}.tar.gz
  sha256: b7ba2df5002fd28d3ee789a49532baad11fe648e4f2117cf0798e7520a1da56b
  patches:
    - 0000-use-entry-points.patch

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -c "__import__('pathlib').Path('bin/community').rename('community/_cli.py')"
    - ${{ PYTHON }} -m pip install . --no-deps -vv
  python:
    entry_points:
      - community = community._cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}
    - setuptools
  run:
    - networkx
    - numpy
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - community
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - which community || where community

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Louvain Community Detection
  description: |
    This module implements community detection.

    It uses the louvain method described in Fast unfolding of communities in
    large networks, Vincent D Blondel, Jean-Loup Guillaume, Renaud Lambiotte,
    Renaud Lefebvre, Journal of Statistical Mechanics: Theory and Experiment
    2008(10), P10008 (12pp)

  homepage: https://github.com/taynaud/python-louvain
  repository: https://github.com/taynaud/python-louvain
  documentation: https://python-louvain.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ericmjl
    - MridulS
    - bollwyvl

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: python-louvain
  cfe-upstream-registry: pypi
  cfe-upstream-name: python-louvain
  cfe-purls:
    - pkg:conda/python-louvain@${{ version }}?channel=conda-forge
    - pkg:pypi/python-louvain@${{ version }}
  cfe-upstream-repo: https://github.com/taynaud/python-louvain
  cfe-upstream-homepage: https://github.com/taynaud/python-louvain
  cfe-import-names: [community]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/python-louvain-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.16

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T04:25:41Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T04:25:41Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-18T04:25:41Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
