"""Story 14.2 — CAP-2 deliberate apply: branch-first, refuse legacy, preserve custom.

Story 14.6 — CAP-6: the installer is driven on purpose (``--directory`` /
``--modules`` from the manifest, stdin closed, pixi-bin PATH fallback) and an
exit-0 apply that changed nothing is a refusal (trap 12), never a green.

Story 14.7 — CAP-7: a ``source: custom`` module (fixture: skf) survives the
core apply — catalog-annotated config paths are snapshotted and restored, the
module's own installer runs from the repo root, skill dirs are verified against
the packaged source (finding only), and the regenerated ``[modules.<name>]``
block is reported as a diff (traps 13/14 replayed with fake installers only).

Story 14.8 — CAP-8: a marker-free byte-diff scan finds installer-owned skill
files and ``_bmad/scripts/*.py`` edited in place (trap 16); after the core
installer regenerates them, a real ``git merge-file`` three-way merge lands
the clean ones and flags genuine conflicts with a ``.customization-conflict``
sibling, repo bytes left exactly as the installer wrote them.

Story 14.9 — CAP-9: ``--no-shims`` inserts literally on the installer argv
right after ``--modules``, before any ``--pin`` pair; a same-version run that
really deletes a shim is a real diff (never trap 12); the sole refusal under
``--no-shims`` is the pre-existing trap-2 legacy-custom check, unchanged.
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import shutil
import subprocess
import textwrap
from collections.abc import Sequence
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

import pytest
import yaml

from pyforge.steward.cli import EXIT_FAILED, EXIT_OK, main
from pyforge.steward.upgrade import (
    TRAP_CUSTOM_MODULE_CONFIG_REGENERATED,
    TRAP_CUSTOM_MODULE_DESELECTED,
    TRAP_LOCAL_CUSTOMIZATION,
    UpgradeError,
    apply_bmad_core_upgrade,
    assert_clean_tree,
    build_preflight_report,
    default_apply_branch,
    default_installer_runner,
    fingerprint_custom_tree,
    format_apply,
    format_preflight,
    load_custom_modules,
    load_release_catalog,
    read_installed_module_sources,
    read_installed_modules,
    reapply_local_customizations,
    resolve_installer_environment,
)

_DEFAULT_MODULES: tuple[str, ...] = ("core", "bmm", "skf")


@pytest.fixture(autouse=True)
def _no_real_home(monkeypatch, tmp_path):
    """Never resolve to the REAL machine's home dir.

    Every ``apply_bmad_core_upgrade``/``build_preflight_report`` call that does
    not pass ``installed_package_root=`` falls through to
    ``default_installed_package_root``'s live ``~/.cache/rattler/cache/pkgs``
    glob. Fixtures in this file are deterministic today only by accident of
    which fake installed-version strings happen to (not) have a real cached
    package on the machine running the tests. A test that deliberately wants
    the real glob passes ``cache_root=`` explicitly (bypassing ``Path.home()``
    entirely) or re-patches ``Path.home`` itself after this fixture runs —
    both keep working since a later ``monkeypatch.setattr`` simply overrides.
    """
    monkeypatch.setattr(Path, "home", lambda: tmp_path / "fake-home-never-real")


# ── Story 14.7 fixture shapes (mirror the live repo layout) ────────────────
_PACKAGED_SOURCE_REL = ".pixi/envs/pyforge-guild/lib/node_modules/bmad-module-skill-forge/src"
_SKF_CONFIG_REL = "_bmad/skf/config.yaml"
# Hand-set keys the 6.12 installer regenerated away (customization-inventory C7).
_SKF_CONFIG_TEXT = (
    "# SKF Module Configuration\n"
    "# Generated by BMAD installer\n"
    "user_name: Test\n"
    "ides:\n"
    "  - claude-code\n"
    "  - other\n"
    "skills_output_folder: .claude/skills\n"
    "snippet_skill_root_override: .claude/skills/\n"
    "forge_data_folder: _bmad-output/forge-data\n"
)
_OWN_INSTALLER_APPENDED = "health_check_repo: example/skf\n"
_CONFIG_TOML_TEXT = (
    "[project]\n"
    'name = "fixture"\n'
    "\n"
    "[modules.skf]\n"
    'sidecar_path = "{project-root}/_bmad/_memory/forger-sidecar"\n'
    'skills_output_folder = "{project-root}/.claude/skills"\n'
    "\n"
    "[agents.bmad-agent-analyst]\n"
    'module = "bmm"\n'
)
# Packaged source: two `skf-*` skills (campaign = undeclared in marketplace.json),
# knowledge + shared, and a module.yaml file (not a dir → not a skill).
_PACKAGED_FILES = {
    "skf-alpha/SKILL.md": "# skf-alpha\n",
    "skf-alpha/steps/step-01.md": "alpha step\n",
    "skf-campaign/SKILL.md": "# skf-campaign (undeclared in marketplace.json)\n",
    "knowledge/index.md": "knowledge\n",
    "shared/helpers.md": "shared\n",
    "module.yaml": "name: skf\n",
}
_CUSTOM_MODULE_DIRS = ("skf-alpha", "skf-campaign", "knowledge", "shared")


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )


def _manifest_text(modules: Sequence[str] | None, *, custom: Sequence[str] = ("skf",)) -> str:
    """Installed manifest in the real shape: ``modules:`` is a list of mappings.

    ``None`` omits the key entirely; ``()`` writes an empty list. Names in
    *custom* carry ``source: custom``; every other module is ``built-in``.
    """
    lines = ["installation:", "  version: 6.10.0"]
    if modules is not None:
        lines.append("modules:" if modules else "modules: []")
        for name in modules:
            lines.extend(
                [
                    f"  - name: {name}",
                    "    version: 6.10.0",
                    f"    source: {'custom' if name in custom else 'built-in'}",
                ]
            )
    return "\n".join(lines) + "\n"


def _write_repo(
    root: Path,
    *,
    with_legacy_custom: bool = False,
    with_team_custom: bool = True,
    modules: Sequence[str] | None = _DEFAULT_MODULES,
    custom: Sequence[str] = ("skf",),
    with_custom_module: bool = False,
) -> Path:
    """Minimal installed-shaped repo with git history (clean tree).

    ``with_custom_module`` (Story 14.7) adds the skf module tree
    (``_bmad/skf/{VERSION,config.yaml,<dirs>}``), its IDE skill dirs under
    ``.claude/skills/``, a packaged source under the ignored ``.pixi/`` path
    (byte-equal to the installed dirs), and an ``_bmad/config.toml`` with a
    pinned ``[modules.skf]`` block — all committed in the baseline.
    """
    (root / "scripts").mkdir(parents=True)
    (root / "scripts" / "bmad-loop-worktree").write_text("#!/bin/sh\n", encoding="utf-8")

    manifest_dir = root / "_bmad" / "_config"
    manifest_dir.mkdir(parents=True)
    (manifest_dir / "manifest.yaml").write_text(_manifest_text(modules, custom=custom), encoding="utf-8")
    (manifest_dir / "skill-manifest.csv").write_text(
        'canonicalId,name\n"bmad-dev-auto","bmad-dev-auto"\n',
        encoding="utf-8",
    )

    scripts = root / "_bmad" / "scripts"
    scripts.mkdir(parents=True)
    (scripts / "resolve_config.py").write_text(
        "BMAD_ACTIVE_PROJECT = True\nmarker = '.active-project'\n",
        encoding="utf-8",
    )

    # Installer-owned trees start empty / stub — only installer may write them.
    (root / "_bmad" / "bmm").mkdir(parents=True)
    (root / "_bmad" / "bmm" / ".keep").write_text("owned-by-installer\n", encoding="utf-8")
    (root / "_bmad" / "core").mkdir(parents=True)
    (root / "_bmad" / "core" / ".keep").write_text("owned-by-installer\n", encoding="utf-8")

    custom = root / "_bmad" / "custom"
    custom.mkdir(parents=True)
    if with_team_custom:
        (custom / "config.toml").write_text("# team custom — must survive apply\nteam = true\n", encoding="utf-8")
    if with_legacy_custom:
        (custom / "bmad-dev-auto.toml").write_text("# legacy — shim HALT\n", encoding="utf-8")

    if with_custom_module:
        packaged = root / _PACKAGED_SOURCE_REL
        for rel, body in _PACKAGED_FILES.items():
            target = packaged / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")
        skills = root / ".claude" / "skills"
        skf = root / "_bmad" / "skf"
        skf.mkdir(parents=True)
        for name in _CUSTOM_MODULE_DIRS:
            shutil.copytree(packaged / name, skills / name)
            shutil.copytree(packaged / name, skf / name)
        (skf / "VERSION").write_text("2.1.0\n", encoding="utf-8")
        (skf / "config.yaml").write_text(_SKF_CONFIG_TEXT, encoding="utf-8")
        (root / "_bmad" / "config.toml").write_text(_CONFIG_TOML_TEXT, encoding="utf-8")
        # The packaged source is an ignored env dir in the real repo too.
        (root / ".gitignore").write_text(".pixi/\n", encoding="utf-8")

    _git(root, "init")
    _git(root, "config", "user.email", "test@example.com")
    _git(root, "config", "user.name", "test")
    _git(root, "add", "-A")
    _git(root, "commit", "-m", "fixture baseline")
    return root


def _fake_installer_script(
    path: Path,
    *,
    clobber_custom: bool = False,
    exit_code: int = 0,
    no_changes: bool = False,
    record: Path | None = None,
    clobber_custom_module: bool = False,
    no_shims: bool = False,
) -> Path:
    """Write a tiny 'bmad-method' stand-in that mutates bmm/core only (unless clobber).

    ``no_changes`` mimics trap 12 (exit 0 having written nothing); ``record``
    dumps the argv the fake received as JSON so tests can assert the exact shape.
    ``clobber_custom_module`` replays trap 14 on the skf fixture: delete
    ``_bmad/skf/**``, regenerate ``config.yaml`` from defaults with a literal
    ``{project-root}/{value}``, drop the undeclared ``skf-campaign`` skill dir,
    and rewrite the ``[modules.skf]`` block of ``_bmad/config.toml`` with defaults.
    ``no_shims`` (Story 14.9 / CAP-9) asserts ``--no-shims`` really is on argv
    and deletes a fixture shim-shaped dir (``_bmad/bmm/v6-shims/bmad-dev-auto``,
    when present) to mimic a real shim-retirement diff.
    """
    record_str = str(record) if record is not None else ""
    body = textwrap.dedent(
        f"""\
        #!/usr/bin/env python3
        import json, pathlib, shutil, sys
        repo = pathlib.Path.cwd()
        # Mimic argv contract (CAP-6):
        #   bmad-method install --action update -y --directory <repo> --modules <csv>
        assert sys.argv[1:4] == ["install", "--action", "update"], sys.argv
        assert "-y" in sys.argv
        directory = pathlib.Path(sys.argv[sys.argv.index("--directory") + 1])
        assert directory.resolve() == repo.resolve(), sys.argv
        assert sys.argv[sys.argv.index("--modules") + 1], sys.argv
        if {no_shims!r}:
            assert "--no-shims" in sys.argv, sys.argv
        if {record_str!r}:
            pathlib.Path({record_str!r}).write_text(json.dumps(sys.argv), encoding="utf-8")
        if {no_changes!r}:
            sys.exit({exit_code})
        (repo / "_bmad" / "bmm" / "updated.txt").write_text("from-installer\\n", encoding="utf-8")
        (repo / "_bmad" / "core" / "updated.txt").write_text("from-installer\\n", encoding="utf-8")
        if {no_shims!r}:
            shutil.rmtree(
                repo / "_bmad" / "bmm" / "v6-shims" / "bmad-dev-auto", ignore_errors=True
            )
        if {clobber_custom!r}:
            custom = repo / "_bmad" / "custom" / "config.toml"
            if custom.is_file():
                custom.write_text("# CLOBBERED\\n", encoding="utf-8")
        if {clobber_custom_module!r}:
            skf = repo / "_bmad" / "skf"
            shutil.rmtree(skf, ignore_errors=True)
            skf.mkdir(parents=True)
            (skf / "config.yaml").write_text(
                '# SKF Module Configuration\\n# Generated by BMAD installer\\n'
                'user_name: Test\\nsidecar_path: "{{project-root}}/{{value}}"\\n',
                encoding="utf-8",
            )
            shutil.rmtree(repo / ".claude" / "skills" / "skf-campaign", ignore_errors=True)
            toml = repo / "_bmad" / "config.toml"
            kept, skipping = [], False
            for line in toml.read_text(encoding="utf-8").splitlines():
                if line.strip() == "[modules.skf]":
                    skipping = True
                    kept.extend(["[modules.skf]", 'sidecar_path = "{{project-root}}/{{value}}"', ""])
                    continue
                if skipping and line.startswith("["):
                    skipping = False
                if not skipping:
                    kept.append(line)
            toml.write_text("\\n".join(kept) + "\\n", encoding="utf-8")
        sys.exit({exit_code})
        """
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(0o755)
    return path


def _fake_own_installer_script(
    path: Path,
    *,
    exit_code: int = 0,
    record: Path | None = None,
    corrupt_skill: str | None = None,
    clobber_custom: bool = False,
) -> Path:
    """Write a 'bmad-module-skill-forge' stand-in (argv: ``<bin> update``).

    Mirrors the real own installer's contract: runs from the repo root, rebuilds
    ``_bmad/skf/**`` and re-copies every ``skf-*`` / ``knowledge`` / ``shared``
    dir from the packaged source, preserves an existing ``config.yaml`` verbatim
    and only appends its own key. ``corrupt_skill`` drops an extra file into
    that installed skill dir (a packaged-source mismatch for verification).
    ``clobber_custom`` writes into ``_bmad/custom/config.toml`` — simulates the
    own installer touching the repo's top-priority preserved surface (never
    exercised by the real installer, but the fingerprint must still catch it).
    """
    record_str = str(record) if record is not None else ""
    corrupt = corrupt_skill or ""
    body = textwrap.dedent(
        f"""\
        #!/usr/bin/env python3
        import json, pathlib, shutil, sys
        repo = pathlib.Path.cwd()
        # CAP-7: the own installer runs from the repo root with argv `<bin> update`.
        assert (repo / "scripts" / "bmad-loop-worktree").is_file(), repo
        assert sys.argv[1:] == ["update"], sys.argv
        if {record_str!r}:
            pathlib.Path({record_str!r}).write_text(json.dumps(sys.argv), encoding="utf-8")
        packaged = repo / {_PACKAGED_SOURCE_REL!r}
        skf = repo / "_bmad" / "skf"
        config = skf / "config.yaml"
        existing = config.read_text(encoding="utf-8") if config.is_file() else ""
        if skf.is_dir():
            for child in skf.iterdir():
                if child.name == "config.yaml":
                    continue
                if child.is_dir():
                    shutil.rmtree(child)
                else:
                    child.unlink()
        skf.mkdir(parents=True, exist_ok=True)
        (skf / "VERSION").write_text("2.1.0\\n", encoding="utf-8")
        skills = repo / ".claude" / "skills"
        for entry in sorted(packaged.iterdir()):
            if not entry.is_dir():
                continue
            shutil.copytree(entry, skf / entry.name)
            if entry.name.startswith("skf-") or entry.name in ("knowledge", "shared"):
                shutil.rmtree(skills / entry.name, ignore_errors=True)
                shutil.copytree(entry, skills / entry.name)
        config.write_text(existing + {_OWN_INSTALLER_APPENDED!r}, encoding="utf-8")
        if {corrupt!r}:
            (skills / {corrupt!r} / "EXTRA.md").write_text("not packaged\\n", encoding="utf-8")
        if {clobber_custom!r}:
            custom = repo / "_bmad" / "custom" / "config.toml"
            if custom.is_file():
                custom.write_text("# CLOBBERED\\n", encoding="utf-8")
        sys.exit({exit_code})
        """
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(0o755)
    return path


def _write_custom_catalog(
    directory: Path,
    *,
    own_installer: Sequence[str] = ("bmad-module-skill-forge", "update"),
    config_paths: Sequence[str] = (_SKF_CONFIG_REL,),
    pin: str | None = None,
    packaged_source: str | None = _PACKAGED_SOURCE_REL,
    name: str = "skf",
    raw_entries: list[object] | None = None,
) -> Path:
    """Minimal ``6.11.0.yaml`` with a ``custom_modules`` list in a tmp catalog dir.

    ``raw_entries`` replaces the generated skf entry verbatim (malformed shapes).
    """
    directory.mkdir(parents=True, exist_ok=True)
    entries: list[object] = (
        raw_entries
        if raw_entries is not None
        else [
            {
                "name": name,
                "own_installer": list(own_installer),
                "config_paths": list(config_paths),
                "pin": pin,
                "packaged_source": packaged_source,
                "notes": "fixture entry (traps 13/14)",
            }
        ]
    )
    (directory / "6.11.0.yaml").write_text(
        yaml.safe_dump(
            {
                "version": "6.11.0",
                "baseline_pair_from": "6.10.0",
                "custom_modules": entries,
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    return directory


def _tree_digest(root: Path) -> dict[str, str]:
    return {
        str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(root.rglob("*"))
        if p.is_file()
    }


def _custom_module_fixture(
    tmp_path: Path,
    *,
    clobber: bool = True,
    core_exit: int = 0,
    core_no_changes: bool = False,
    own_exit: int = 0,
    corrupt_skill: str | None = None,
    own_clobber_custom: bool = False,
    pin: str | None = None,
    config_paths: Sequence[str] = (_SKF_CONFIG_REL,),
    packaged_source: str | None = _PACKAGED_SOURCE_REL,
    modules: Sequence[str] | None = _DEFAULT_MODULES,
    custom: Sequence[str] = ("skf",),
) -> dict[str, Path]:
    """Repo + two fakes + custom catalog; returns the paths a test asserts on."""
    repo = _write_repo(tmp_path / "repo", modules=modules, custom=custom, with_custom_module=True)
    core_record = tmp_path / "core-argv.json"
    own_record = tmp_path / "own-argv.json"
    core = _fake_installer_script(
        tmp_path / "fake-bmad-method",
        record=core_record,
        clobber_custom_module=clobber,
        exit_code=core_exit,
        no_changes=core_no_changes,
    )
    own = _fake_own_installer_script(
        tmp_path / "fake-skill-forge",
        exit_code=own_exit,
        record=own_record,
        corrupt_skill=corrupt_skill,
        clobber_custom=own_clobber_custom,
    )
    catalog = _write_custom_catalog(
        tmp_path / "catalog",
        own_installer=(str(own), "update"),
        pin=pin,
        config_paths=config_paths,
        packaged_source=packaged_source,
    )
    return {
        "repo": repo,
        "core": core,
        "own": own,
        "catalog": catalog,
        "core_record": core_record,
        "own_record": own_record,
    }


def test_default_apply_branch_name():
    assert default_apply_branch("6.11.0") == "steward/bmad-core-upgrade-6.11.0"


def test_refuse_dirty_tree(tmp_path):
    repo = _write_repo(tmp_path / "repo")
    (repo / "dirty.txt").write_text("nope\n", encoding="utf-8")
    with pytest.raises(UpgradeError, match="clean working tree"):
        assert_clean_tree(repo)


def test_apply_refuses_legacy_custom_before_branch(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=True)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    before_branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    with pytest.raises(UpgradeError, match="legacy-name"):
        apply_bmad_core_upgrade(
            repo=repo,
            target_version="6.11.0",
            installer_bin=str(installer),
        )

    # Must not have created a review branch or mutated trees.
    after_branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    assert after_branch == before_branch
    assert not (repo / "_bmad" / "bmm" / "updated.txt").exists()


def test_apply_branches_first_runs_installer_preserves_custom(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    custom_before = fingerprint_custom_tree(repo)
    base_sha = _git(repo, "rev-parse", "HEAD").stdout.strip()

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/test-apply",
    )

    assert report.branch == "review/test-apply"
    assert report.snapshot_sha == base_sha
    assert report.installer_exit == 0
    assert report.custom_identical is True
    assert report.custom_failure_reason is None
    assert fingerprint_custom_tree(repo) == custom_before

    current = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    assert current == "review/test-apply"
    assert (repo / "_bmad" / "bmm" / "updated.txt").is_file()
    assert (repo / "_bmad" / "core" / "updated.txt").is_file()
    assert any(p.endswith("updated.txt") for p in report.changed_paths)
    assert report.installer_cmd == (
        str(installer),
        "install",
        "--action",
        "update",
        "-y",
        "--directory",
        str(repo),
        "--modules",
        "core,bmm,skf",
    )
    assert report.zero_diff is False


def test_apply_reports_when_custom_clobbered(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", clobber_custom=True)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/clobber",
    )

    assert report.installer_exit == 0
    assert report.custom_identical is False
    assert any("config.toml" in d for d in report.custom_differs)
    assert report.custom_failure_reason is not None
    assert "NOT byte-identical" in report.custom_failure_reason


def test_apply_refuses_existing_review_branch(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    _git(repo, "branch", "review/exists")

    with pytest.raises(UpgradeError, match="already exists"):
        apply_bmad_core_upgrade(
            repo=repo,
            target_version="6.11.0",
            installer_bin=str(installer),
            branch="review/exists",
        )


def test_cli_apply_ok(tmp_path, capsys):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    record = tmp_path / "argv.json"
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", record=record)
    rc = main(
        [
            "upgrade",
            "bmad-core",
            "--target",
            "6.11.0",
            "--apply",
            "--repo-root",
            str(repo),
            "--installer",
            str(installer),
            "--branch",
            "review/cli-apply",
            "--json",
        ]
    )
    assert rc == EXIT_OK
    payload = json.loads(capsys.readouterr().out)
    assert payload["branch"] == "review/cli-apply"
    assert payload["custom_identical"] is True
    assert payload["installer_exit"] == 0
    # CAP-6: the fake received --directory <repo> / --modules core,bmm,skf and
    # the payload records the same argv; a real diff is not zero-diff.
    expected_cmd = [
        str(installer),
        "install",
        "--action",
        "update",
        "-y",
        "--directory",
        str(repo),
        "--modules",
        "core,bmm,skf",
    ]
    assert payload["installer_cmd"] == expected_cmd
    assert json.loads(record.read_text(encoding="utf-8")) == expected_cmd
    assert payload["zero_diff"] is False


def test_cli_apply_refuses_dirty_tree(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    (repo / "uncommitted.txt").write_text("dirty\n", encoding="utf-8")
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(repo),
                "--installer",
                str(installer),
            ]
        )
    assert rc == EXIT_FAILED
    text = out.getvalue() + err.getvalue()
    assert "clean working tree" in text


def test_cli_apply_refuses_legacy_names_paths(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=True)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(repo),
                "--installer",
                str(installer),
            ]
        )
    assert rc == EXIT_FAILED
    text = out.getvalue() + err.getvalue()
    assert "legacy-name" in text
    assert "bmad-dev-auto.toml" in text


def test_steward_never_writes_bmm_core_itself(tmp_path):
    """Installer runner is the only mutator of bmm/core — steward only invokes it.

    The runner is a pre-14.6 two-positional fake: it must still be accepted and
    called without ``env`` (a keyword would raise TypeError here).
    """
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    calls: list[tuple[str, ...]] = []

    def runner(cwd: Path, cmd) -> subprocess.CompletedProcess[str]:
        calls.append(tuple(cmd))
        # Installer writes; steward must not have written these already.
        assert not (cwd / "_bmad" / "bmm" / "updated.txt").exists()
        (cwd / "_bmad" / "bmm" / "updated.txt").write_text("ok\n", encoding="utf-8")
        return subprocess.CompletedProcess(list(cmd), 0, "", "")

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_runner=runner,
        branch="review/sole-writer",
    )
    assert calls == [
        (
            "bmad-method",
            "install",
            "--action",
            "update",
            "-y",
            "--directory",
            str(repo),
            "--modules",
            "core,bmm,skf",
        )
    ]
    assert report.custom_identical is True


# ── Story 14.6 / CAP-6 — the installer is driven on purpose ────────────────


def test_read_installed_modules_core_first_and_deduplicated(tmp_path):
    repo = _write_repo(tmp_path / "repo", modules=("bmm", "skf", "core", "bmm"))
    assert read_installed_modules(repo) == ("core", "bmm", "skf")


def test_apply_argv_carries_directory_and_manifest_modules_core_first(tmp_path):
    repo = _write_repo(tmp_path / "repo", modules=("bmm", "skf", "core"))
    record = tmp_path / "argv.json"
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", record=record)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/argv",
    )

    expected = (
        str(installer),
        "install",
        "--action",
        "update",
        "-y",
        "--directory",
        str(repo),
        "--modules",
        "core,bmm,skf",
    )
    assert report.installer_cmd == expected
    assert tuple(json.loads(record.read_text(encoding="utf-8"))) == expected
    assert report.installer_exit == 0
    assert report.zero_diff is False
    assert report.to_dict()["installer_cmd"] == list(expected)
    assert any("core,bmm,skf" in n and "trap 13" in n for n in report.notes)


@pytest.mark.parametrize("modules", [None, ()], ids=["missing", "empty"])
def test_apply_refuses_manifest_without_modules_before_branch(tmp_path, modules):
    repo = _write_repo(tmp_path / "repo", modules=modules)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    before_branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    with pytest.raises(UpgradeError, match="trap 13"):
        apply_bmad_core_upgrade(
            repo=repo,
            target_version="6.11.0",
            installer_bin=str(installer),
            branch="review/no-modules",
        )

    # Refused before the review branch existed; installer never ran.
    assert _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip() == before_branch
    assert not _git(repo, "branch", "--list", "review/no-modules").stdout.strip()
    assert not (repo / "_bmad" / "bmm" / "updated.txt").exists()


def test_apply_zero_diff_exit_zero_is_a_refusal(tmp_path):
    repo = _write_repo(tmp_path / "repo")
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", no_changes=True)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/zero-diff",
    )

    assert report.installer_exit == 0
    assert report.changed_paths == ()
    assert report.zero_diff is True
    assert report.to_dict()["zero_diff"] is True
    note = next(n for n in report.notes if "trap 12" in n)
    assert "exited 0 but changed nothing" in note
    assert "refuse to call this green" in note
    assert "review/zero-diff" in note
    # The review branch is left in place for the operator.
    assert _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip() == "review/zero-diff"
    text = format_apply(report, as_json=False)
    assert "zero-diff: REFUSED" in text
    assert "review/zero-diff" in text


def test_apply_non_zero_exit_without_changes_is_not_zero_diff(tmp_path):
    """A non-zero exit already fails through the exit gate — never double-reported as trap 12."""
    repo = _write_repo(tmp_path / "repo")
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", no_changes=True, exit_code=2)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/exit-2",
    )

    assert report.installer_exit == 2
    assert report.changed_paths == ()
    assert report.zero_diff is False
    assert not any("trap 12" in n for n in report.notes)
    assert "zero-diff: REFUSED" not in format_apply(report, as_json=False)


def test_cli_apply_zero_diff_returns_failed_and_names_trap_12(tmp_path):
    repo = _write_repo(tmp_path / "repo")
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", no_changes=True)
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(repo),
                "--installer",
                str(installer),
                "--branch",
                "review/cli-zero-diff",
                "--json",
            ]
        )
    assert rc == EXIT_FAILED
    # ok=False routes the summary to stderr.
    payload = json.loads(err.getvalue())
    assert payload["zero_diff"] is True
    assert payload["installer_exit"] == 0
    assert payload["changed_paths"] == []
    assert any("trap 12" in n and "review/cli-zero-diff" in n for n in payload["notes"])
    assert _git(repo, "branch", "--list", "review/cli-zero-diff").stdout.strip()


def test_cli_apply_zero_diff_text_prints_refused_line(tmp_path):
    repo = _write_repo(tmp_path / "repo")
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", no_changes=True)
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(repo),
                "--installer",
                str(installer),
            ]
        )
    assert rc == EXIT_FAILED
    assert "zero-diff: REFUSED" in out.getvalue() + err.getvalue()


def test_apply_passes_env_to_keyword_aware_runner_and_prepends_pixi_bin(tmp_path, monkeypatch):
    repo = _write_repo(tmp_path / "repo")
    monkeypatch.setattr(shutil, "which", lambda name, *a, **k: None)
    seen: dict[str, object] = {}

    def runner(cwd: Path, cmd, *, env=None) -> subprocess.CompletedProcess[str]:
        seen["env"] = env
        seen["cmd"] = tuple(cmd)
        (cwd / "_bmad" / "bmm" / "updated.txt").write_text("ok\n", encoding="utf-8")
        return subprocess.CompletedProcess(list(cmd), 0, "", "")

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_runner=runner,
        branch="review/env",
    )

    pixi_bin = repo / ".pixi" / "envs" / "pyforge-guild" / "bin"
    env = seen["env"]
    assert isinstance(env, dict)
    assert env["PATH"] == f"{pixi_bin}{os.pathsep}{os.environ['PATH']}"
    note = next(n for n in report.notes if "not on PATH" in n)
    assert str(pixi_bin) in note
    assert "bmad-method" in note and "node" in note
    assert report.zero_diff is False


def test_apply_env_untouched_when_binaries_on_path(tmp_path, monkeypatch):
    repo = _write_repo(tmp_path / "repo")
    monkeypatch.setattr(shutil, "which", lambda name, *a, **k: f"/resolved/{name}")
    seen: dict[str, object] = {}

    def runner(cwd: Path, cmd, **kwargs) -> subprocess.CompletedProcess[str]:
        seen.update(kwargs)
        (cwd / "_bmad" / "bmm" / "updated.txt").write_text("ok\n", encoding="utf-8")
        return subprocess.CompletedProcess(list(cmd), 0, "", "")

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_runner=runner,
        branch="review/env-on-path",
    )

    env = seen["env"]
    assert isinstance(env, dict)
    assert env["PATH"] == os.environ["PATH"]
    assert any("resolved from PATH" in n for n in report.notes)


def test_resolve_installer_environment_pixi_bin_is_derived_from_repo(tmp_path, monkeypatch):
    repo = tmp_path / "repo"
    repo.mkdir()
    pixi_bin = repo / ".pixi" / "envs" / "pyforge-guild" / "bin"

    monkeypatch.setattr(shutil, "which", lambda name, *a, **k: None)
    env, note = resolve_installer_environment(repo, "bmad-method")
    assert env["PATH"].startswith(f"{pixi_bin}{os.pathsep}")
    assert env["PATH"].endswith(os.environ["PATH"])
    assert str(pixi_bin) in note and "bmad-method" in note and "node" in note

    monkeypatch.setattr(shutil, "which", lambda name, *a, **k: None if name == "node" else f"/bin/{name}")
    env, note = resolve_installer_environment(repo, "bmad-method")
    assert env["PATH"].startswith(f"{pixi_bin}{os.pathsep}")
    assert "(node)" in note  # only the missing name is listed

    monkeypatch.setattr(shutil, "which", lambda name, *a, **k: f"/bin/{name}")
    env, note = resolve_installer_environment(repo, "bmad-method")
    assert env["PATH"] == os.environ["PATH"]
    assert "resolved from PATH" in note


def test_default_installer_runner_closes_stdin_and_uses_resolved_env(tmp_path, monkeypatch):
    repo = tmp_path / "repo"
    repo.mkdir()
    monkeypatch.setattr(shutil, "which", lambda name, *a, **k: None)
    env, _note = resolve_installer_environment(repo, "bmad-method")
    pixi_bin = repo / ".pixi" / "envs" / "pyforge-guild" / "bin"

    seen: dict[str, object] = {}

    def fake_run(args, **kwargs):
        seen["args"] = list(args)
        seen.update(kwargs)
        return subprocess.CompletedProcess(list(args), 0, "", "")

    monkeypatch.setattr(subprocess, "run", fake_run)
    result = default_installer_runner(repo, ("bmad-method", "install"), env=env)

    assert result.returncode == 0
    assert seen["args"] == ["bmad-method", "install"]
    assert seen["cwd"] == repo
    assert seen["stdin"] is subprocess.DEVNULL
    assert seen["capture_output"] is True and seen["text"] is True
    run_env = seen["env"]
    assert isinstance(run_env, dict)
    assert run_env["PATH"].startswith(f"{pixi_bin}{os.pathsep}")


def test_read_installed_modules_accepts_bare_string_entries(tmp_path):
    """The installer's manifest writer also allows bare ``- name`` entries."""
    repo = tmp_path / "repo"
    manifest_dir = repo / "_bmad" / "_config"
    manifest_dir.mkdir(parents=True)
    (manifest_dir / "manifest.yaml").write_text(
        "installation:\n  version: 6.10.0\n"
        "modules:\n"
        "  - bmm\n"
        "  - name: skf\n    source: custom\n"
        "  - core\n"
        "  - name: bmm\n    source: built-in\n",
        encoding="utf-8",
    )
    assert read_installed_modules(repo) == ("core", "bmm", "skf")


def test_apply_refuses_unresolvable_installer_binary_before_branch(tmp_path):
    """Default runner: a binary steward cannot resolve is a pre-branch refusal, not a crash."""
    repo = _write_repo(tmp_path / "repo")
    missing_bin = tmp_path / "nonexistent" / "bmad-method"
    before_branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    with pytest.raises(UpgradeError, match="not found") as excinfo:
        apply_bmad_core_upgrade(
            repo=repo,
            target_version="6.11.0",
            installer_bin=str(missing_bin),
            branch="review/no-binary",
        )

    message = str(excinfo.value)
    assert str(missing_bin) in message
    assert str(repo / ".pixi" / "envs" / "pyforge-guild" / "bin") in message
    assert _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip() == before_branch
    assert not _git(repo, "branch", "--list", "review/no-binary").stdout.strip()
    assert not (repo / "_bmad" / "bmm" / "updated.txt").exists()


# ── Story 14.7 / CAP-7 — custom modules survive the core apply ─────────────


def test_apply_custom_module_survives_core_apply_trap_13_14_replay(tmp_path):
    """Happy path: config restored + own installer rebuilds the tree (2026-09-06 replay)."""
    fx = _custom_module_fixture(tmp_path)
    repo = fx["repo"]

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7",
    )

    # Working tree: pre-apply config bytes + the own installer's appended key.
    expected_config = _SKF_CONFIG_TEXT.encode() + _OWN_INSTALLER_APPENDED.encode()
    assert (repo / _SKF_CONFIG_REL).read_bytes() == expected_config
    packaged = repo / _PACKAGED_SOURCE_REL
    for name in ("skf-alpha", "skf-campaign"):
        assert _tree_digest(repo / ".claude" / "skills" / name) == _tree_digest(packaged / name)
    assert (repo / "_bmad" / "skf" / "VERSION").is_file()

    assert len(report.custom_modules) == 1
    module = report.custom_modules[0]
    assert module.name == "skf"
    assert module.selected is True
    assert module.pin is None
    assert module.config_paths[0].path == _SKF_CONFIG_REL
    assert module.config_paths[0].status == "restored"
    assert module.own_installer_cmd == (str(fx["own"]), "update")
    assert module.own_installer_exit == 0
    assert module.own_installer_error is None
    assert module.verification is not None
    assert module.verification.expected == 2
    assert module.verification.equal == 2
    assert module.verification.ok is True
    assert module.config_toml_block_changed is True
    assert "sidecar_path" in module.config_toml_block_diff
    assert module.ok is True
    assert report.custom_modules_ok is True

    # Core argv carries no --pin (catalog pin: null); both fakes saw the argv reported.
    assert "--pin" not in report.installer_cmd
    assert json.loads(fx["core_record"].read_text(encoding="utf-8")) == list(report.installer_cmd)
    assert json.loads(fx["own_record"].read_text(encoding="utf-8")) == list(module.own_installer_cmd)
    assert report.installer_exit == 0
    assert report.zero_diff is False
    assert report.custom_identical is True
    assert _SKF_CONFIG_REL in report.changed_paths
    assert any("trap 14" in n for n in report.notes)

    payload = report.to_dict()
    assert payload["custom_modules_ok"] is True
    assert payload["custom_modules"][0]["config_paths"][0]["status"] == "restored"
    assert payload["custom_modules"][0]["own_installer_exit"] == 0

    text = format_apply(report, as_json=False)
    assert "## CAP-7 custom modules" in text
    assert _SKF_CONFIG_REL in text and "restored" in text
    assert "sidecar_path" in text


def test_apply_custom_module_catalog_pin_lands_on_core_argv(tmp_path):
    fx = _custom_module_fixture(tmp_path, pin="v2.1.0")
    repo = fx["repo"]

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-pin",
    )

    expected = (
        str(fx["core"]),
        "install",
        "--action",
        "update",
        "-y",
        "--directory",
        str(repo),
        "--modules",
        "core,bmm,skf",
        "--pin",
        "skf=v2.1.0",
    )
    assert report.installer_cmd == expected
    assert tuple(json.loads(fx["core_record"].read_text(encoding="utf-8"))) == expected
    assert report.custom_modules[0].pin == "v2.1.0"
    assert any("skf=v2.1.0" in n for n in report.notes)
    assert report.custom_modules_ok is True


def test_real_catalog_pins_skf_v2_1_0():
    """Story 46.7: the REAL packaged 6.12.0 catalog carries the skf pin (CAP-7).

    ``test_apply_custom_module_catalog_pin_lands_on_core_argv`` above proves the
    generic pin-to-argv mechanism works once a pin exists, but it only ever
    reads a synthetic fixture catalog. This test loads the actual packaged
    ``bmad_core_releases/6.12.0.yaml`` so an accidental revert of the pin back
    to ``null`` is caught here, not just in the mechanism test.
    """
    catalog = load_release_catalog("6.12.0")
    (skf,) = load_custom_modules(catalog)
    assert skf.name == "skf"
    assert skf.pin == "v2.1.0"


def test_apply_custom_module_own_installer_binary_missing_is_reported(tmp_path):
    """Default custom runner: an unresolvable own installer is reported, never raised."""
    fx = _custom_module_fixture(tmp_path)
    repo = fx["repo"]
    catalog = _write_custom_catalog(tmp_path / "catalog-missing", own_installer=("nonexistent-skf-installer", "update"))

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=catalog,
        branch="review/cap7-no-binary",
    )

    module = report.custom_modules[0]
    # Config still restored by steward itself; the own installer never ran.
    assert (repo / _SKF_CONFIG_REL).read_bytes() == _SKF_CONFIG_TEXT.encode()
    assert module.config_paths[0].status == "restored"
    assert module.own_installer_exit is None
    assert module.own_installer_error is not None
    assert "nonexistent-skf-installer" in module.own_installer_error
    assert str(repo / ".pixi" / "envs" / "pyforge-guild" / "bin") in module.own_installer_error
    assert module.ok is False
    assert report.custom_modules_ok is False
    assert not fx["own_record"].exists()


def test_cli_apply_custom_module_own_installer_missing_returns_failed_json(tmp_path):
    fx = _custom_module_fixture(tmp_path)
    catalog = _write_custom_catalog(tmp_path / "catalog-missing", own_installer=("nonexistent-skf-installer", "update"))
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(fx["repo"]),
                "--installer",
                str(fx["core"]),
                "--catalog-dir",
                str(catalog),
                "--branch",
                "review/cli-cap7-no-binary",
                "--json",
            ]
        )
    assert rc == EXIT_FAILED
    assert "Traceback" not in out.getvalue() + err.getvalue()
    payload = json.loads(err.getvalue())
    assert payload["custom_modules_ok"] is False
    module = payload["custom_modules"][0]
    assert module["own_installer_exit"] is None
    assert "nonexistent-skf-installer" in module["own_installer_error"]
    assert module["config_paths"][0]["status"] == "restored"


def test_apply_custom_module_own_installer_non_zero_exit(tmp_path):
    fx = _custom_module_fixture(tmp_path, own_exit=3)

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-own-exit-3",
    )

    module = report.custom_modules[0]
    assert module.own_installer_exit == 3
    assert module.own_installer_error is None
    assert module.config_paths[0].status == "restored"
    assert module.ok is False
    assert report.custom_modules_ok is False
    assert report.installer_exit == 0


def test_cli_apply_custom_module_own_installer_non_zero_exit_returns_failed(tmp_path):
    fx = _custom_module_fixture(tmp_path, own_exit=3)
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(fx["repo"]),
                "--installer",
                str(fx["core"]),
                "--catalog-dir",
                str(fx["catalog"]),
                "--branch",
                "review/cli-cap7-own-exit-3",
                "--json",
            ]
        )
    assert rc == EXIT_FAILED
    payload = json.loads(err.getvalue())
    assert payload["installer_exit"] == 0
    assert payload["custom_modules_ok"] is False
    assert payload["custom_modules"][0]["own_installer_exit"] == 3


def test_apply_custom_module_config_left_unchanged_by_core_installer(tmp_path):
    fx = _custom_module_fixture(tmp_path, clobber=False)

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-unchanged",
    )

    module = report.custom_modules[0]
    assert module.config_paths[0].status == "unchanged"
    assert "left it unchanged" in module.config_paths[0].detail
    assert module.own_installer_exit == 0
    assert module.ok is True
    assert module.config_toml_block_changed is False
    assert module.config_toml_block_diff == ""
    assert report.custom_modules_ok is True


def test_apply_custom_module_skill_dir_mismatch_is_a_finding_not_a_gate(tmp_path):
    fx = _custom_module_fixture(tmp_path, corrupt_skill="skf-alpha")

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-mismatch",
    )

    module = report.custom_modules[0]
    assert module.verification is not None
    assert module.verification.mismatched == ("skf-alpha",)
    assert module.verification.missing == ()
    assert module.verification.ok is False
    assert module.ok is True
    assert report.custom_modules_ok is True
    assert any("skf-alpha" in n for n in module.notes)
    assert any("skf-alpha" in n for n in report.notes)
    text = format_apply(report, as_json=False)
    assert "mismatched: skf-alpha" in text


def test_apply_custom_module_packaged_source_absent_skips_verification(tmp_path):
    fx = _custom_module_fixture(tmp_path, packaged_source="nonexistent/packaged/src")

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-no-source",
    )

    module = report.custom_modules[0]
    assert module.verification is None
    assert any("skipped" in n and "nonexistent/packaged/src" in n for n in module.notes)
    assert module.own_installer_exit == 0
    assert module.ok is True
    assert report.custom_modules_ok is True
    assert "skill-dir verification: skipped" in format_apply(report, as_json=False)


def test_apply_custom_module_zero_diff_core_run_skips_own_installer(tmp_path):
    """Trap 12 stays a refusal: the own installer must never turn a no-op into a diff."""
    fx = _custom_module_fixture(tmp_path, clobber=False, core_no_changes=True)

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-zero-diff",
    )

    assert report.zero_diff is True
    assert report.changed_paths == ()
    module = report.custom_modules[0]
    assert module.config_paths[0].status == "unchanged"
    assert module.own_installer_exit is None
    assert module.own_installer_error is not None
    assert "skipped" in module.own_installer_error
    assert "trap 12" in module.own_installer_error
    assert module.ok is False
    assert report.custom_modules_ok is False
    assert not fx["own_record"].exists()
    assert "zero-diff: REFUSED" in format_apply(report, as_json=False)


def test_apply_custom_module_core_non_zero_exit_restores_config_skips_own_installer(
    tmp_path,
):
    fx = _custom_module_fixture(tmp_path, core_exit=2)
    repo = fx["repo"]

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-core-exit-2",
    )

    assert report.installer_exit == 2
    assert report.zero_diff is False
    module = report.custom_modules[0]
    assert module.config_paths[0].status == "restored"
    assert (repo / _SKF_CONFIG_REL).read_bytes() == _SKF_CONFIG_TEXT.encode()
    assert module.own_installer_exit is None
    assert module.own_installer_error is not None
    assert "skipped" in module.own_installer_error and "exited 2" in module.own_installer_error
    assert module.ok is False
    assert report.custom_modules_ok is False
    assert not fx["own_record"].exists()
    # The core fake's clobber_custom_module=True (fixture default) deletes the
    # undeclared skf-campaign skill dir; the own installer never runs to
    # rebuild it, so verification must surface it as missing (a finding).
    assert module.verification.missing == ("skf-campaign",)
    assert module.verification.ok is False
    assert any("missing: skf-campaign" in n for n in report.notes)


def test_apply_custom_module_config_path_absent_before_apply_is_missing(tmp_path):
    fx = _custom_module_fixture(tmp_path, clobber=False, config_paths=("_bmad/skf/absent.yaml",))

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-config-missing",
    )

    module = report.custom_modules[0]
    assert module.config_paths[0].path == "_bmad/skf/absent.yaml"
    assert module.config_paths[0].status == "missing"
    assert module.config_paths[0].detail == "absent before apply — nothing to restore"
    assert module.own_installer_exit == 0
    assert module.ok is False
    assert report.custom_modules_ok is False


@pytest.mark.parametrize(
    ("modules", "custom"),
    [(("core", "bmm"), ("skf",)), (("core", "bmm", "skf"), ())],
    ids=["not-listed", "listed-not-custom"],
)
def test_catalog_module_not_installed_is_unselected_and_a_preflight_mismatch(tmp_path, modules, custom):
    fx = _custom_module_fixture(tmp_path, clobber=False, modules=modules, custom=custom)
    repo = fx["repo"]

    preflight = build_preflight_report(repo=repo, target_version="6.11.0", catalog_directory=fx["catalog"])
    finding = next(f for f in preflight.custom_modules if f.name == "skf")
    assert finding.in_catalog is True
    assert finding.matched is False
    assert TRAP_CUSTOM_MODULE_DESELECTED in preflight.trap_ids
    assert "MISMATCH" in format_preflight(preflight, as_json=False)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-not-installed",
    )
    module = report.custom_modules[0]
    assert module.selected is False
    assert module.config_paths == ()
    assert module.own_installer_exit is None
    assert module.ok is True
    assert report.custom_modules_ok is True
    assert not fx["own_record"].exists()
    assert (repo / _SKF_CONFIG_REL).read_bytes() == _SKF_CONFIG_TEXT.encode()


def test_installed_custom_module_absent_from_catalog_is_a_finding_not_a_gate(tmp_path):
    """Packaged 6.11.0 catalog (no custom_modules) + manifest skf source: custom."""
    repo = _write_repo(tmp_path / "repo", with_custom_module=True)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")

    preflight = build_preflight_report(repo=repo, target_version="6.11.0")
    finding = next(f for f in preflight.custom_modules if f.name == "skf")
    assert finding.in_catalog is False
    assert finding.manifest_source == "custom"
    assert finding.matched is False
    assert "trap 14" in finding.detail
    assert finding.trap_id == TRAP_CUSTOM_MODULE_CONFIG_REGENERATED
    assert TRAP_CUSTOM_MODULE_CONFIG_REGENERATED in preflight.trap_ids
    assert "[MISMATCH] [trap 14] skf" in format_preflight(preflight, as_json=False)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/cap7-uncatalogued",
    )
    assert report.custom_modules == ()
    assert report.custom_modules_ok is True
    assert any("absent from the release catalog" in n and "trap 14" in n for n in report.notes)
    assert "(none in catalog)" in format_apply(report, as_json=False)


def test_preflight_custom_module_matched_row(tmp_path):
    fx = _custom_module_fixture(tmp_path)
    report = build_preflight_report(repo=fx["repo"], target_version="6.11.0", catalog_directory=fx["catalog"])
    assert len(report.custom_modules) == 1
    finding = report.custom_modules[0]
    assert finding.name == "skf"
    assert finding.in_catalog is True
    assert finding.manifest_source == "custom"
    assert finding.matched is True
    assert finding.own_installer == (str(fx["own"]), "update")
    assert finding.pin is None
    assert TRAP_CUSTOM_MODULE_DESELECTED not in report.trap_ids
    text = format_preflight(report, as_json=False)
    assert "## Custom modules (catalog vs installed manifest)" in text
    assert "[ok] skf:" in text
    assert report.to_dict()["custom_modules"][0]["matched"] is True


@pytest.mark.parametrize(
    "raw_entries",
    [
        [{"own_installer": ["x", "update"]}],
        [{"name": "", "own_installer": ["x", "update"]}],
        [{"name": "skf"}],
        [{"name": "skf", "own_installer": []}],
        [{"name": "skf", "own_installer": "bmad-module-skill-forge update"}],
        ["skf"],
    ],
    ids=["no-name", "empty-name", "no-own-installer", "empty-argv", "string-argv", "not-mapping"],
)
def test_malformed_custom_module_catalog_entry_raises_before_branch(tmp_path, raw_entries):
    repo = _write_repo(tmp_path / "repo", with_custom_module=True)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    catalog = _write_custom_catalog(tmp_path / "catalog", raw_entries=raw_entries)
    before_branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    data = yaml.safe_load((catalog / "6.11.0.yaml").read_text(encoding="utf-8"))
    with pytest.raises(UpgradeError, match="custom_modules"):
        load_custom_modules(data)

    with pytest.raises(UpgradeError, match="custom_modules"):
        apply_bmad_core_upgrade(
            repo=repo,
            target_version="6.11.0",
            installer_bin=str(installer),
            catalog_directory=catalog,
            branch="review/cap7-malformed",
        )
    assert _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip() == before_branch
    assert not _git(repo, "branch", "--list", "review/cap7-malformed").stdout.strip()
    assert not (repo / "_bmad" / "bmm" / "updated.txt").exists()


def test_load_custom_modules_tolerates_missing_key_and_normalises_pin():
    assert load_custom_modules({}) == ()
    assert load_custom_modules({"custom_modules": None}) == ()
    (module,) = load_custom_modules(
        {"custom_modules": [{"name": " skf ", "own_installer": ["bmad-module-skill-forge", "update"], "pin": "  "}]}
    )
    assert module.name == "skf"
    assert module.pin is None
    assert module.config_paths == ()
    assert module.packaged_source is None
    assert module.notes == ""


def test_read_installed_module_sources_incl_bare_string_entries(tmp_path):
    repo = tmp_path / "repo"
    manifest_dir = repo / "_bmad" / "_config"
    manifest_dir.mkdir(parents=True)
    (manifest_dir / "manifest.yaml").write_text(
        "installation:\n  version: 6.10.0\n"
        "modules:\n"
        "  - bmm\n"
        "  - name: skf\n    source: custom\n"
        "  - core\n"
        "  - name: bmm\n    source: built-in\n",
        encoding="utf-8",
    )
    assert read_installed_module_sources(repo) == {"bmm": None, "skf": "custom", "core": None}
    # Same parsing as read_installed_modules — the two never disagree on names.
    assert set(read_installed_modules(repo)) == set(read_installed_module_sources(repo))

    assert read_installed_module_sources(_write_repo(tmp_path / "no-key", modules=None)) == {}
    assert read_installed_module_sources(_write_repo(tmp_path / "empty", modules=())) == {}
    assert read_installed_module_sources(tmp_path / "no-manifest") == {}


def test_cli_apply_custom_module_ok_json(tmp_path, capsys):
    fx = _custom_module_fixture(tmp_path)
    repo = fx["repo"]
    rc = main(
        [
            "upgrade",
            "bmad-core",
            "--target",
            "6.11.0",
            "--apply",
            "--repo-root",
            str(repo),
            "--installer",
            str(fx["core"]),
            "--catalog-dir",
            str(fx["catalog"]),
            "--branch",
            "review/cli-cap7",
            "--json",
        ]
    )
    assert rc == EXIT_OK
    payload = json.loads(capsys.readouterr().out)
    assert payload["custom_modules_ok"] is True
    module = payload["custom_modules"][0]
    assert module["config_paths"][0] == {
        "path": _SKF_CONFIG_REL,
        "status": "restored",
        "detail": module["config_paths"][0]["detail"],
    }
    assert module["own_installer_cmd"] == [str(fx["own"]), "update"]
    assert module["own_installer_exit"] == 0
    assert payload["installer_cmd"] == json.loads(fx["core_record"].read_text(encoding="utf-8"))
    assert payload["installer_exit"] == 0
    assert (repo / _SKF_CONFIG_REL).read_bytes() == (_SKF_CONFIG_TEXT.encode() + _OWN_INSTALLER_APPENDED.encode())
    packaged = repo / _PACKAGED_SOURCE_REL
    for name in ("skf-alpha", "skf-campaign"):
        assert _tree_digest(repo / ".claude" / "skills" / name) == _tree_digest(packaged / name)


def test_apply_custom_module_own_installer_clobbers_custom_is_reported(tmp_path):
    """The own installer touching _bmad/custom/** (never real, but must still be caught)."""
    fx = _custom_module_fixture(tmp_path, own_clobber_custom=True)

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-own-clobbers-custom",
    )

    assert report.custom_identical is False
    assert any("config.toml" in d for d in report.custom_differs)
    assert report.custom_failure_reason is not None
    assert "NOT byte-identical" in report.custom_failure_reason
    # The custom-module phase itself is otherwise unaffected — this is purely
    # the post-phase _bmad/custom/** fingerprint doing its job.
    assert report.custom_modules[0].ok is True


def test_cli_apply_custom_module_own_installer_clobbers_custom_returns_failed(tmp_path):
    fx = _custom_module_fixture(tmp_path, own_clobber_custom=True)
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(fx["repo"]),
                "--installer",
                str(fx["core"]),
                "--catalog-dir",
                str(fx["catalog"]),
                "--branch",
                "review/cli-cap7-own-clobbers-custom",
                "--json",
            ]
        )
    assert rc == EXIT_FAILED
    payload = json.loads(err.getvalue())
    assert payload["custom_identical"] is False
    assert any("config.toml" in d for d in payload["custom_differs"])


def test_apply_custom_module_own_installer_oserror_is_reported(tmp_path):
    """An own-installer binary that resolves on PATH but cannot be exec'd (ENOEXEC)."""
    fx = _custom_module_fixture(tmp_path)
    unexecutable = tmp_path / "not-executable-skf-installer"
    unexecutable.write_bytes(b"")  # empty file, executable bit set, no shebang
    unexecutable.chmod(0o755)
    catalog = _write_custom_catalog(tmp_path / "catalog-oserror", own_installer=(str(unexecutable), "update"))

    report = apply_bmad_core_upgrade(
        repo=fx["repo"],
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=catalog,
        branch="review/cap7-oserror",
    )

    module = report.custom_modules[0]
    assert module.own_installer_exit is None
    assert module.own_installer_error is not None
    assert "could not be spawned" in module.own_installer_error
    assert module.ok is False
    assert report.custom_modules_ok is False


def test_apply_custom_installer_runner_is_injected_and_receives_env(tmp_path):
    """An injected custom_installer_runner (mirrors 14.6's installer_runner pattern)."""
    fx = _custom_module_fixture(tmp_path)
    repo = fx["repo"]
    seen: dict[str, object] = {}

    def runner(cwd: Path, cmd, *, env=None):
        seen["cwd"] = cwd
        seen["cmd"] = tuple(cmd)
        seen["env"] = env
        (repo / _SKF_CONFIG_REL).write_text(_SKF_CONFIG_TEXT + "injected: true\n", encoding="utf-8")
        return subprocess.CompletedProcess(list(cmd), 0, "", "")

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/cap7-injected-runner",
        custom_installer_runner=runner,
    )

    assert seen["cwd"] == repo
    assert seen["cmd"] == (str(fx["own"]), "update")
    assert isinstance(seen["env"], dict)
    module = report.custom_modules[0]
    assert module.own_installer_exit == 0
    assert module.ok is True
    # The injected runner's return value is what steward acted on — not the
    # (never-invoked) real fake own-installer script.
    assert not fx["own_record"].exists()
    assert (repo / _SKF_CONFIG_REL).read_text(encoding="utf-8").endswith("injected: true\n")


def test_apply_custom_module_config_path_deleted_by_core_installer(tmp_path):
    """Config existed pre-apply, core installer deletes it outright (not regenerates)."""
    fx = _custom_module_fixture(tmp_path, clobber=False)
    repo = fx["repo"]
    # Overwrite the fixture's core fake: this one deletes config.yaml outright.
    core = tmp_path / "fake-bmad-method-deletes"
    core.write_text(
        "#!/usr/bin/env python3\n"
        "import pathlib, sys\n"
        "repo = pathlib.Path.cwd()\n"
        "(repo / '_bmad' / 'bmm' / 'updated.txt').write_text('x', encoding='utf-8')\n"
        "(repo / '_bmad' / 'core' / 'updated.txt').write_text('x', encoding='utf-8')\n"
        "(repo / '_bmad' / 'skf' / 'config.yaml').unlink()\n"
        "sys.exit(0)\n",
        encoding="utf-8",
    )
    core.chmod(0o755)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(core),
        catalog_directory=fx["catalog"],
        branch="review/cap7-config-deleted",
    )

    module = report.custom_modules[0]
    assert module.config_paths[0].status == "restored"
    assert "deleted" in module.config_paths[0].detail
    # Own installer still runs (core changed, exit 0): restored bytes + its append.
    assert (repo / _SKF_CONFIG_REL).read_bytes() == (_SKF_CONFIG_TEXT.encode() + _OWN_INSTALLER_APPENDED.encode())


def test_cli_apply_help_names_real_argv_shape(capsys, monkeypatch):
    """14.6's deferred item: the --apply help quotes the argv the apply really builds."""
    # argparse wraps help at the terminal width and hyphen-breaks long tokens
    # (`bmad-module-\nskill-forge`); a wide COLUMNS keeps every token whole.
    monkeypatch.setenv("COLUMNS", "400")
    rc = main(["upgrade", "bmad-core", "--help"])
    assert rc == EXIT_OK
    text = " ".join(capsys.readouterr().out.split())
    assert "--directory" in text
    assert "--modules" in text
    assert "--pin" in text
    assert "bmad-module-skill-forge update" in text


# ── Story 14.8 / CAP-8 — local customizations found & re-applied ───────────

_CAP8_SKILL_NAME = "bmad-dev-auto"
_CAP8_SCRIPT_NAME = "helper.py"

# File A: `_bmad/scripts/helper.py` — clean auto-merge (repo edit + upstream's
# own old→new edit sit on different, non-adjacent lines; `MID_A` is the
# unchanged context line git's diff3 needs to keep the two hunks separate).
_CAP8_SCRIPT_BASE = 'A = "same"\nMID_A = "x"\nB = "same"\nTRAIL = "same"\n'
_CAP8_SCRIPT_OURS = 'A = "custom"\nMID_A = "x"\nB = "same"\nTRAIL = "same"\n'
_CAP8_SCRIPT_NEW = 'A = "same"\nMID_A = "x"\nB = "new"\nTRAIL = "same"\n'
_CAP8_SCRIPT_MERGED = 'A = "custom"\nMID_A = "x"\nB = "new"\nTRAIL = "same"\n'

# File B: `.claude/skills/bmad-dev-auto/step-01.md` — clean auto-merge.
_CAP8_SKILL1_BASE = "# step-01\nC = same\nMID_B = x\nD = same\n"
_CAP8_SKILL1_OURS = "# step-01\nC = custom\nMID_B = x\nD = same\n"
_CAP8_SKILL1_NEW = "# step-01\nC = same\nMID_B = x\nD = new\n"
_CAP8_SKILL1_MERGED = "# step-01\nC = custom\nMID_B = x\nD = new\n"

# File C: `.claude/skills/bmad-dev-auto/step-02.md` — a real conflict: ours,
# base, and theirs are three genuinely different values at the same line.
_CAP8_SKILL2_BASE = "ROUTE = old\nMID_C = x\nTAIL = same\n"
_CAP8_SKILL2_OURS = "ROUTE = old  # kept by repo\nMID_C = x\nTAIL = same\n"
_CAP8_SKILL2_NEW = "ROUTE = new\nMID_C = x\nTAIL = same\n"


def _write_cap8_package(root: Path, *, script_body: str, skill1_body: str, skill2_body: str) -> Path:
    """Minimal package tree: one bmm-skills skill dir (2 files) + one script."""
    scripts = root / "src" / "scripts"
    scripts.mkdir(parents=True)
    (scripts / _CAP8_SCRIPT_NAME).write_text(script_body, encoding="utf-8")
    skill_dir = root / "src" / "bmm-skills" / _CAP8_SKILL_NAME
    skill_dir.mkdir(parents=True)
    (skill_dir / "step-01.md").write_text(skill1_body, encoding="utf-8")
    (skill_dir / "step-02.md").write_text(skill2_body, encoding="utf-8")
    return root


def _write_cap8_repo(root: Path) -> Path:
    """`_write_repo` (no skf) plus the three CAP-8-flagged files, committed."""
    repo = _write_repo(root, modules=("core", "bmm"), custom=(), with_legacy_custom=False)
    skill_dir = repo / ".claude" / "skills" / _CAP8_SKILL_NAME
    skill_dir.mkdir(parents=True)
    (skill_dir / "step-01.md").write_text(_CAP8_SKILL1_OURS, encoding="utf-8")
    (skill_dir / "step-02.md").write_text(_CAP8_SKILL2_OURS, encoding="utf-8")
    (repo / "_bmad" / "scripts" / _CAP8_SCRIPT_NAME).write_text(_CAP8_SCRIPT_OURS, encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", "cap8 fixture: three installer-owned files edited in place")
    return repo


def _fake_cap8_installer_script(path: Path, *, target_package_root: Path) -> Path:
    """Fake ``bmad-method`` that regenerates the three CAP-8 files from *target_package_root*.

    Mirrors trap 16 live: the installer rewrites every installer-owned file it
    ships with the target release's content, dropping the repo's edits.
    """
    body = textwrap.dedent(
        f"""\
        #!/usr/bin/env python3
        import pathlib, shutil, sys
        repo = pathlib.Path.cwd()
        assert sys.argv[1:4] == ["install", "--action", "update"], sys.argv
        assert "-y" in sys.argv
        directory = pathlib.Path(sys.argv[sys.argv.index("--directory") + 1])
        assert directory.resolve() == repo.resolve(), sys.argv
        assert sys.argv[sys.argv.index("--modules") + 1], sys.argv
        (repo / "_bmad" / "bmm" / "updated.txt").write_text("from-installer\\n", encoding="utf-8")
        (repo / "_bmad" / "core" / "updated.txt").write_text("from-installer\\n", encoding="utf-8")
        pkg = pathlib.Path({str(target_package_root)!r})
        shutil.copy(
            pkg / "src" / "scripts" / {_CAP8_SCRIPT_NAME!r},
            repo / "_bmad" / "scripts" / {_CAP8_SCRIPT_NAME!r},
        )
        skills = repo / ".claude" / "skills" / {_CAP8_SKILL_NAME!r}
        shutil.copy(pkg / "src" / "bmm-skills" / {_CAP8_SKILL_NAME!r} / "step-01.md", skills / "step-01.md")
        shutil.copy(pkg / "src" / "bmm-skills" / {_CAP8_SKILL_NAME!r} / "step-02.md", skills / "step-02.md")
        sys.exit(0)
        """
    )
    path.write_text(body, encoding="utf-8")
    path.chmod(0o755)
    return path


def _cap8_fixture(tmp_path: Path) -> dict[str, Path]:
    repo = _write_cap8_repo(tmp_path / "repo")
    installed_pkg = _write_cap8_package(
        tmp_path / "installed-pkg",
        script_body=_CAP8_SCRIPT_BASE,
        skill1_body=_CAP8_SKILL1_BASE,
        skill2_body=_CAP8_SKILL2_BASE,
    )
    target_pkg = _write_cap8_package(
        tmp_path / "target-pkg",
        script_body=_CAP8_SCRIPT_NEW,
        skill1_body=_CAP8_SKILL1_NEW,
        skill2_body=_CAP8_SKILL2_NEW,
    )
    installer = _fake_cap8_installer_script(tmp_path / "fake-bmad-method", target_package_root=target_pkg)
    return {
        "repo": repo,
        "installed_pkg": installed_pkg,
        "target_pkg": target_pkg,
        "installer": installer,
    }


def test_preflight_finds_all_three_cap8_local_customizations(tmp_path):
    paths = _cap8_fixture(tmp_path)
    report = build_preflight_report(
        repo=paths["repo"],
        target_version="6.11.0",
        installed_package_root=paths["installed_pkg"],
    )
    assert TRAP_LOCAL_CUSTOMIZATION in report.trap_ids
    flagged = {f.path for f in report.local_customizations}
    assert flagged == {
        "_bmad/scripts/helper.py",
        ".claude/skills/bmad-dev-auto/step-01.md",
        ".claude/skills/bmad-dev-auto/step-02.md",
    }


def test_apply_cap8_three_files_two_clean_one_conflict(tmp_path):
    paths = _cap8_fixture(tmp_path)
    report = apply_bmad_core_upgrade(
        repo=paths["repo"],
        target_version="6.11.0",
        installer_bin=str(paths["installer"]),
        installed_package_root=paths["installed_pkg"],
        package_root=paths["target_pkg"],
        branch="review/cap8",
    )
    assert report.installer_exit == 0
    reapply = report.local_customizations_reapply
    assert reapply is not None
    by_path = {f.path: f for f in reapply.findings}
    assert set(by_path) == {
        "_bmad/scripts/helper.py",
        ".claude/skills/bmad-dev-auto/step-01.md",
        ".claude/skills/bmad-dev-auto/step-02.md",
    }

    script_finding = by_path["_bmad/scripts/helper.py"]
    assert script_finding.action == "merged_clean"
    assert (paths["repo"] / "_bmad" / "scripts" / "helper.py").read_text(encoding="utf-8") == _CAP8_SCRIPT_MERGED

    skill1_finding = by_path[".claude/skills/bmad-dev-auto/step-01.md"]
    assert skill1_finding.action == "merged_clean"
    assert (paths["repo"] / ".claude" / "skills" / "bmad-dev-auto" / "step-01.md").read_text(
        encoding="utf-8"
    ) == _CAP8_SKILL1_MERGED

    skill2_finding = by_path[".claude/skills/bmad-dev-auto/step-02.md"]
    assert skill2_finding.action == "conflict_needs_manual_merge"
    skill2_path = paths["repo"] / ".claude" / "skills" / "bmad-dev-auto" / "step-02.md"
    # Repo bytes are left EXACTLY as the (fake) installer wrote them — untouched.
    assert skill2_path.read_text(encoding="utf-8") == _CAP8_SKILL2_NEW
    conflict_path = paths["repo"] / ".claude" / "skills" / "bmad-dev-auto" / "step-02.md.customization-conflict"
    assert skill2_finding.conflict_path == ".claude/skills/bmad-dev-auto/step-02.md.customization-conflict"
    conflict_text = conflict_path.read_text(encoding="utf-8")
    assert "<<<<<<<" in conflict_text
    assert "=======" in conflict_text
    assert ">>>>>>>" in conflict_text
    # Meaningful labels, not the ephemeral temp-dir paths git defaults to —
    # the tempdir is gone by the time a human opens this file to resolve it.
    assert "repo customization" in conflict_text
    assert "new upstream (target)" in conflict_text

    assert reapply.all_clean is False
    assert report.local_customizations_ok is False

    text = format_apply(report, as_json=False)
    assert "## CAP-8 local customizations re-applied" in text
    assert "[merged_clean] _bmad/scripts/helper.py" in text
    assert "[conflict_needs_manual_merge] .claude/skills/bmad-dev-auto/step-02.md" in text
    assert "conflict file: .claude/skills/bmad-dev-auto/step-02.md.customization-conflict" in text


def test_cli_apply_cap8_conflict_gates_ok_false(tmp_path):
    paths = _cap8_fixture(tmp_path)
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = main(
            [
                "upgrade",
                "bmad-core",
                "--target",
                "6.11.0",
                "--apply",
                "--repo-root",
                str(paths["repo"]),
                "--installer",
                str(paths["installer"]),
                "--installed-package-root",
                str(paths["installed_pkg"]),
                "--package-root",
                str(paths["target_pkg"]),
                "--branch",
                "review/cli-cap8",
                "--json",
            ]
        )
    assert rc == EXIT_FAILED
    # ok=False routes the summary to stderr.
    payload = json.loads(err.getvalue())
    assert payload["local_customizations_ok"] is False
    actions = {f["action"] for f in payload["local_customizations_reapply"]["findings"]}
    assert actions == {"merged_clean", "conflict_needs_manual_merge"}


def test_reapply_local_customizations_unchanged_when_installer_leaves_file_alone(
    tmp_path,
):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installed_pkg = _write_cap8_package(
        tmp_path / "installed-pkg",
        script_body=_CAP8_SCRIPT_BASE,
        skill1_body=_CAP8_SKILL1_BASE,
        skill2_body=_CAP8_SKILL2_BASE,
    )
    target_pkg = _write_cap8_package(
        tmp_path / "target-pkg",
        script_body=_CAP8_SCRIPT_NEW,
        skill1_body=_CAP8_SKILL1_NEW,
        skill2_body=_CAP8_SKILL2_NEW,
    )
    (repo / "_bmad" / "scripts" / _CAP8_SCRIPT_NAME).write_text(_CAP8_SCRIPT_OURS, encoding="utf-8")
    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={"_bmad/scripts/helper.py": _CAP8_SCRIPT_OURS.encode()},
        installed_package_root=installed_pkg,
        package_root=target_pkg,
    )
    assert report.findings[0].action == "unchanged"
    assert (repo / "_bmad" / "scripts" / _CAP8_SCRIPT_NAME).read_text(encoding="utf-8") == _CAP8_SCRIPT_OURS


def test_reapply_local_customizations_skipped_no_package_match(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installed_pkg = _write_cap8_package(
        tmp_path / "installed-pkg",
        script_body=_CAP8_SCRIPT_BASE,
        skill1_body=_CAP8_SKILL1_BASE,
        skill2_body=_CAP8_SKILL2_BASE,
    )
    target_pkg = _write_cap8_package(
        tmp_path / "target-pkg",
        script_body=_CAP8_SCRIPT_NEW,
        skill1_body=_CAP8_SKILL1_NEW,
        skill2_body=_CAP8_SKILL2_NEW,
    )
    ghost = repo / "_bmad" / "scripts" / "ghost.py"
    ghost.write_text("print('repo-only, no packaged counterpart')\n", encoding="utf-8")
    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={"_bmad/scripts/ghost.py": ghost.read_bytes()},
        installed_package_root=installed_pkg,
        package_root=target_pkg,
    )
    assert report.findings[0].action == "skipped_no_package_match"
    assert report.all_clean is True


def test_reapply_local_customizations_new_side_missing_is_the_realistic_shape(tmp_path):
    """The only way a file gets flagged at all is a match on the OLD (installed)
    side (that is how the pre-flight scan found it) — so the realistic trigger
    for `skipped_no_package_match` in real operation is the NEW (target) side
    lacking a match (e.g. upstream renamed/retired the file), not neither side
    matching at all.
    """
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installed_pkg = _write_cap8_package(
        tmp_path / "installed-pkg",
        script_body=_CAP8_SCRIPT_BASE,
        skill1_body=_CAP8_SKILL1_BASE,
        skill2_body=_CAP8_SKILL2_BASE,
    )
    target_pkg = tmp_path / "target-pkg"
    (target_pkg / "src" / "scripts").mkdir(parents=True)
    (repo / "_bmad" / "scripts" / _CAP8_SCRIPT_NAME).write_text(_CAP8_SCRIPT_OURS, encoding="utf-8")
    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={"_bmad/scripts/helper.py": _CAP8_SCRIPT_OURS.encode()},
        installed_package_root=installed_pkg,
        package_root=target_pkg,
    )
    assert report.findings[0].action == "skipped_no_package_match"
    assert "new (--package-root)" in report.findings[0].detail
    assert report.all_clean is True


def test_reapply_local_customizations_nested_skill_file_merges_cleanly(tmp_path):
    """The real trap-16 incident's flagged files sit 2+ dirs deep in the skill
    (e.g. `scripts/tests/test_sprint_plan.py`) — the three-way-merge path must
    resolve nested `rest` paths correctly, not just flat top-level files.
    """
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    nested = Path("scripts") / "tests" / "test_helper.py"

    installed_pkg = tmp_path / "installed-pkg"
    (installed_pkg / "src" / "bmm-skills" / _CAP8_SKILL_NAME / nested.parent).mkdir(parents=True)
    (installed_pkg / "src" / "bmm-skills" / _CAP8_SKILL_NAME / nested).write_text(_CAP8_SKILL1_BASE, encoding="utf-8")

    target_pkg = tmp_path / "target-pkg"
    (target_pkg / "src" / "bmm-skills" / _CAP8_SKILL_NAME / nested.parent).mkdir(parents=True)
    (target_pkg / "src" / "bmm-skills" / _CAP8_SKILL_NAME / nested).write_text(_CAP8_SKILL1_NEW, encoding="utf-8")

    repo_file = repo / ".claude" / "skills" / _CAP8_SKILL_NAME / nested
    repo_file.parent.mkdir(parents=True)
    # The core installer already regenerated this path with the new upstream
    # content, as if it had just run.
    repo_file.write_text(_CAP8_SKILL1_NEW, encoding="utf-8")

    rel = str(repo_file.relative_to(repo)).replace("\\", "/")
    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={rel: _CAP8_SKILL1_OURS.encode()},
        installed_package_root=installed_pkg,
        package_root=target_pkg,
    )
    assert report.findings[0].action == "merged_clean"
    assert repo_file.read_text(encoding="utf-8") == _CAP8_SKILL1_MERGED
    assert report.all_clean is True


def test_reapply_local_customizations_clears_stale_conflict_sibling_on_clean_merge(
    tmp_path,
):
    """A `.customization-conflict` sibling left by an earlier failed apply must
    not keep looking conflicted once a later run merges the same file cleanly.
    """
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installed_pkg = _write_cap8_package(
        tmp_path / "installed-pkg",
        script_body=_CAP8_SCRIPT_BASE,
        skill1_body=_CAP8_SKILL1_BASE,
        skill2_body=_CAP8_SKILL2_BASE,
    )
    target_pkg = _write_cap8_package(
        tmp_path / "target-pkg",
        script_body=_CAP8_SCRIPT_NEW,
        skill1_body=_CAP8_SKILL1_NEW,
        skill2_body=_CAP8_SKILL2_NEW,
    )
    # The core installer already regenerated this file with the new upstream
    # content, as if it had just run (required for a merge to be attempted at
    # all — matching bytes would short-circuit to "unchanged" instead).
    (repo / "_bmad" / "scripts" / _CAP8_SCRIPT_NAME).write_text(_CAP8_SCRIPT_NEW, encoding="utf-8")
    stale_conflict = repo / "_bmad" / "scripts" / f"{_CAP8_SCRIPT_NAME}.customization-conflict"
    stale_conflict.write_text("<<<<<<< stale from an earlier failed apply\n", encoding="utf-8")

    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={"_bmad/scripts/helper.py": _CAP8_SCRIPT_OURS.encode()},
        installed_package_root=installed_pkg,
        package_root=target_pkg,
    )
    assert report.findings[0].action == "merged_clean"
    assert not stale_conflict.exists()


def test_reapply_local_customizations_skipped_installer_removed_file(tmp_path):
    """The installer deleted the flagged file outright — a clean merge must not recreate it."""
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installed_pkg = _write_cap8_package(
        tmp_path / "installed-pkg",
        script_body=_CAP8_SCRIPT_BASE,
        skill1_body=_CAP8_SKILL1_BASE,
        skill2_body=_CAP8_SKILL2_BASE,
    )
    target_pkg = _write_cap8_package(
        tmp_path / "target-pkg",
        script_body=_CAP8_SCRIPT_NEW,
        skill1_body=_CAP8_SKILL1_NEW,
        skill2_body=_CAP8_SKILL2_NEW,
    )
    # No `_bmad/scripts/helper.py` in the repo at all — unlike the "unchanged"
    # case, the installer removed it rather than leaving it in place.
    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={"_bmad/scripts/helper.py": _CAP8_SCRIPT_OURS.encode()},
        installed_package_root=installed_pkg,
        package_root=target_pkg,
    )
    assert report.findings[0].action == "skipped_installer_removed_file"
    assert not (repo / "_bmad" / "scripts" / "helper.py").exists()
    assert report.all_clean is True


def test_reapply_local_customizations_removed_file_wins_over_no_package_match(tmp_path):
    """Both conditions hold: the installer deleted the file outright AND neither
    package root has a matching counterpart (e.g. a retired/renamed file). The
    more specific `skipped_installer_removed_file` must win, not the generic
    `skipped_no_package_match` — this is why the installer-removed check runs
    before the package-match lookup.
    """
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    installed_pkg = tmp_path / "installed-pkg"
    (installed_pkg / "src" / "scripts").mkdir(parents=True)
    target_pkg = tmp_path / "target-pkg"
    (target_pkg / "src" / "scripts").mkdir(parents=True)
    # No `_bmad/scripts/retired.py` in the repo, and neither package root has
    # a `src/scripts/retired.py` either.
    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={"_bmad/scripts/retired.py": b"old repo customization\n"},
        installed_package_root=installed_pkg,
        package_root=target_pkg,
    )
    assert report.findings[0].action == "skipped_installer_removed_file"
    assert report.all_clean is True


def test_reapply_local_customizations_no_roots_is_a_noop(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    report = reapply_local_customizations(
        repo,
        pre_apply_snapshots={"_bmad/scripts/helper.py": b"anything"},
        installed_package_root=None,
        package_root=None,
    )
    assert report.findings == ()
    assert report.all_clean is True
    assert any("unavailable" in n for n in report.notes)


def test_cli_apply_help_names_installed_package_root_flag(capsys, monkeypatch):
    monkeypatch.setenv("COLUMNS", "400")
    rc = main(["upgrade", "bmad-core", "--help"])
    assert rc == EXIT_OK
    text = " ".join(capsys.readouterr().out.split())
    assert "--installed-package-root" in text
    assert "run `bmad-method install --action update -y`," not in text


# ── Story 14.9 / CAP-9 — --no-shims deliberate shim retirement ─────────────


def _add_fixture_shim(repo: Path) -> Path:
    """Commit a ``_bmad/bmm/v6-shims/bmad-dev-auto`` dir so the fake installer's
    ``no_shims`` deletion has something real to remove."""
    shim = repo / "_bmad" / "bmm" / "v6-shims" / "bmad-dev-auto"
    shim.mkdir(parents=True)
    (shim / "SKILL.md").write_text("# bmad-dev-auto shim\n", encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", "fixture: add v6-shims/bmad-dev-auto")
    return shim


def test_apply_no_shims_argv_carries_flag_after_modules_before_pins(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    _add_fixture_shim(repo)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", no_shims=True)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/no-shims-argv",
        no_shims=True,
    )

    assert report.installer_cmd == (
        str(installer),
        "install",
        "--action",
        "update",
        "-y",
        "--directory",
        str(repo),
        "--modules",
        "core,bmm,skf",
        "--no-shims",
    )
    assert any("--no-shims requested" in n for n in report.notes)


def test_apply_no_shims_same_version_target_is_a_real_diff_not_zero_diff(tmp_path):
    """Same-version + --no-shims that actually deletes a shim dir is a real
    diff — never mistaken for the trap-12 silent no-op."""
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    shim_dir = _add_fixture_shim(repo)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", no_shims=True)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installed_version="6.11.0",
        installer_bin=str(installer),
        branch="review/no-shims-same-version",
        no_shims=True,
    )

    assert report.preflight.installed_version == report.preflight.target_version
    assert report.zero_diff is False
    # Proves the shim-directory deletion itself (not just the routine
    # updated.txt writes) produced the diff.
    assert not shim_dir.exists()
    assert any("v6-shims/bmad-dev-auto" in p for p in report.changed_paths)


def test_apply_no_shims_legacy_custom_still_halts_before_branch(tmp_path):
    """Trap 2's unconditional refusal holds unchanged under --no-shims."""
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=True)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method")
    before_branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    with pytest.raises(UpgradeError, match="legacy-name"):
        apply_bmad_core_upgrade(
            repo=repo,
            target_version="6.11.0",
            installer_bin=str(installer),
            no_shims=True,
        )

    after_branch = _git(repo, "rev-parse", "--abbrev-ref", "HEAD").stdout.strip()
    assert after_branch == before_branch
    assert not (repo / "_bmad" / "bmm" / "updated.txt").exists()


def test_apply_no_shims_proceeds_normally(tmp_path):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    _add_fixture_shim(repo)
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", no_shims=True)

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(installer),
        branch="review/no-shims-clear",
        no_shims=True,
    )

    assert report.installer_exit == 0
    assert "--no-shims" in report.installer_cmd
    assert report.zero_diff is False


def test_apply_no_shims_argv_order_holds_with_custom_module_pins(tmp_path):
    """--no-shims combined with a pin-bearing custom module: argv still shows
    ``--modules``, then ``--no-shims``, then ``--pin`` — in that exact order."""
    fx = _custom_module_fixture(tmp_path, pin="v2.1.0")
    repo = fx["repo"]

    report = apply_bmad_core_upgrade(
        repo=repo,
        target_version="6.11.0",
        installer_bin=str(fx["core"]),
        catalog_directory=fx["catalog"],
        branch="review/no-shims-with-pins",
        no_shims=True,
    )

    expected = (
        str(fx["core"]),
        "install",
        "--action",
        "update",
        "-y",
        "--directory",
        str(repo),
        "--modules",
        "core,bmm,skf",
        "--no-shims",
        "--pin",
        "skf=v2.1.0",
    )
    assert report.installer_cmd == expected
    assert tuple(json.loads(fx["core_record"].read_text(encoding="utf-8"))) == expected


def test_cli_apply_help_names_no_shims_flag(capsys, monkeypatch):
    monkeypatch.setenv("COLUMNS", "400")
    rc = main(["upgrade", "bmad-core", "--help"])
    assert rc == EXIT_OK
    text = " ".join(capsys.readouterr().out.split())
    assert "--no-shims" in text


def test_cli_apply_no_shims_flag_reaches_apply(tmp_path, capsys):
    repo = _write_repo(tmp_path / "repo", with_legacy_custom=False)
    _add_fixture_shim(repo)
    record = tmp_path / "argv.json"
    installer = _fake_installer_script(tmp_path / "fake-bmad-method", record=record, no_shims=True)
    rc = main(
        [
            "upgrade",
            "bmad-core",
            "--target",
            "6.11.0",
            "--apply",
            "--repo-root",
            str(repo),
            "--installer",
            str(installer),
            "--branch",
            "review/cli-no-shims",
            "--no-shims",
            "--json",
        ]
    )
    assert rc == EXIT_OK
    payload = json.loads(capsys.readouterr().out)
    assert "--no-shims" in payload["installer_cmd"]
    assert json.loads(record.read_text(encoding="utf-8")) == payload["installer_cmd"]
