{% set name = "feast" %}
{% set version = "0.52.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/feast-{{ version }}.tar.gz
  sha256: d10846e66c6f333713f9c954c3b06660404eb998902387345511084c9d279471

build:
  entry_points:
    - feast = feast.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pybindgen >=0.22.1  # Pinned to ==0.22.0, which is not available
    - setuptools >=60,<77
    - setuptools-scm >=6.2
    - sphinx !=4.0.0
    - wheel
    - pip
  run:
    - transformers >=4.36.0
    - python >={{ python_min }}
    - click >=7.0.0,<9.0.0
    - colorama >=0.3.9,<1
    - dill >=0.3.0,<0.4.dev0
    - protobuf >=4.24.0
    - jinja2 >=2,<4
    - jsonschema
    - mmh3
    - numpy >=2.0.0,<3
    - pandas >=1.4.3,<3
    - pyarrow <=17.0.0
    - pydantic ==2.10.6
    - pygments >=2.12.0,<3
    - pyyaml >=5.4.0,<7
    - requests
    - sqlalchemy >1
    - tabulate >=0.8.0,<1
    - tenacity >=7,<9
    - toml >=0.10.0,<1
    - tqdm >=4,<5
    - typeguard >=4.0.0
    - fastapi >=0.68.0
    - uvicorn >=0.30.6,<=0.34.0
    - uvicorn-worker
    - gunicorn
    - dask-core >=2024.2.1
    - prometheus_client
    - psutil
    - bigtree >=0.19.2
    - pyjwt

test:
  imports:
    - feast
  commands:
    - pip check
    - feast --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/feast-dev/feast
  summary: Python SDK for Feast
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
