# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: feast
  version: "0.54.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/feast-${{ version }}.tar.gz
  sha256: 9e7f9be608902febbf813f8cf5730d3227d4d18262039d3601427319d1da3800

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - feast = feast.cli.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pybindgen >=0.22.0  # Pinned to ==0.22.0, which is not available
    - setuptools >=60,<81
    - setuptools-scm >=6.2
    - sphinx !=4.0.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - click >=7.0.0,<9.0.0
    - colorama >=0.3.9,<1
    - dill >=0.3.0,<0.4.dev0
    - protobuf >=4.24.0
    - jinja2 >=2,<4
    - jsonschema
    - mmh3
    - numpy >=2.0.0,<3
    - pandas >=1.4.3,<3
    - pyarrow <=17.0.0
    - pydantic ==2.10.6
    - pygments >=2.12.0,<3
    - pyyaml >=5.4.0,<7
    - requests
    - sqlalchemy >1
    - tabulate >=0.8.0,<1
    - tenacity >=7,<9
    - toml >=0.10.0,<1
    - tqdm >=4,<5
    - typeguard >=4.0.0
    - fastapi >=0.68.0
    - uvicorn >=0.30.6,<=0.34.0
    - uvicorn-worker
    - gunicorn
    - dask-core >=2024.2.1
    - prometheus_client
    - psutil
    - bigtree >=0.19.2
    - pyjwt

tests:
  - python:
      imports:
        - feast
      pip_check: true
      # multiprocess 0.70.18 has requirement dill>=0.4.0, but you have dill 0.3.9.
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - feast --help

about:
  summary: Python SDK for Feast
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/feast-dev/feast

extra:
  recipe-maintainers:
    - rxm7706
