# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ydata-profiling
  version: "4.18.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ydata_profiling-${{ version }}.tar.gz
  sha256: c3a0afd82e605c6903dd140b5fc41dabad8ee690601ad3d6c27da28e80b07cc6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ydata_profiling = ydata_profiling.controller.console:main
      - pandas_profiling = ydata_profiling.controller.console:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=72.0.0,<80.0.0
    - setuptools-scm >=8.0.0,<9.0.0
    - wheel >=0.38.4,<1.0.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - scipy >=1.8,<1.17
    - pandas >1.5,<3.0,!=1.4.0
    - matplotlib-base >=3.5,<=3.10
    - pydantic >=2,<3
    - pyyaml >=6.0.3,<6.1
    - jinja2 >=3.1.6,<3.2
    - visions >=0.7.5,<0.8.2
    - numpy >=1.22,<2.4
    - minify-html >=0.15.0
    - filetype >=1.0.0
    - phik >=0.12.5,<0.13
    - requests >=2.32.0,<3
    - tqdm >=4.66.3,<5
    - seaborn >=0.10.1,<0.14
    - multimethod >=1.4,<2
    - statsmodels >=0.13.2,<1
    - typeguard >=4,<5
    - imagehash ==4.3.2
    - wordcloud >=1.9.4
    - dacite >=1.9,<2
    - numba >=0.60,<0.63
    #- ipython <9.0
  run_constraints:
    - jupyter >=1.0.0
    - ipywidgets >=7.5.1
    - tangled-up-in-unicode ==0.2.0
    - visions >=0.7.5,<0.7.7

tests:
  - python:
      imports:
        #- pandas_profiling
        - ydata_profiling
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - ydata_profiling --help
      #- pandas_profiling --help
      # make sure the version reported by pip is correct
      #- "pip show ${{ name }} | grep -Fx 'Version: ${{ version }}'"

about:
  homepage : https://github.com/ydataai/ydata-profiling
  summary: Generate profile report for pandas DataFrame
  license: MIT
  license_file: LICENSE
  documentation: https://ydata-profiling.ydata.ai

extra:
  recipe-maintainers:
    - rxm7706
