{% set name = "cookiecutter-django" %}
{% set version = "2025.05.23" %}
{% set python_min = "3.12" %}

{% set cookiecutter = "{{cookiecutter" %}
{% set project_slug = "project_slug}}" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cookiecutter/cookiecutter-django/archive/{{ version }}.tar.gz
  sha256: 51a7e9416e2362d101b498abedaf1b8951b1d54c243b1348c21c479ddcac737b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
# https://github.com/cookiecutter/cookiecutter-django/blob/master/pyproject.toml
# ------------------------------------------------------------------------------
    - cookiecutter >=2.6.0
    - sh >=2.1  # [unix]
    # Keep the package noarch but allow for the osx and linux only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]
    - binaryornot >=0.4.4
# Code quality
# ------------------------------------------------------------------------------
    - ruff >=0.11.11
    - django-upgrade >=1.22.2
    - djlint >=1.36.4
    - pre-commit >=4.1.0
# Testing
# ------------------------------------------------------------------------------
    - tox >=4.23.2
    - tox-uv >=1.17.0
    - pytest >=8.3.4
    - pytest-xdist >=3.6.1
    - pytest-cookies >=0.7.0
    - pytest-instafail >=0.5.0
    - pyyaml >=6.0.2
# Scripting
# ------------------------------------------------------------------------------
    - pygithub >=2.5.0
    - gitpython >=3.1.43
    - jinja2 >=3.1.5
    - requests >=2.32.3
# Base Not Optional ; Limit to Django LTS and Include DRF, Redis and Asyc
# https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt
    - python-slugify >=8.0.4  # https://github.com/un33k/python-slugify
    - pillow >=11.1.0  # https://github.com/python-pillow/Pillow
    - argon2-cffi >=23.1.0  # https://github.com/hynek/argon2_cffi
    - redis-py >=6.1.0  # https://github.com/redis/redis-py
# Base
# https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/base.txt
# ------------------------------------------------------------------------------
    - django >=4.2.20,<5.3  # https://www.djangoproject.com/
    - django-environ >=0.12.0  # https://github.com/joke2k/django-environ
    - django-model-utils >=5.0.0  # https://github.com/jazzband/django-model-utils
    - django-allauth >=65.8.1  # https://github.com/pennersr/django-allauth
    #- fido2 <2  # https://github.com/Yubico/python-fido2 - dependency of django-allauth mfa NOTE https://github.com/cookiecutter/cookiecutter-django/pull/5854
    - django-crispy-forms >=2.4  # https://github.com/django-crispy-forms/django-crispy-forms
    - crispy-bootstrap5 >=2025.4  # https://github.com/django-crispy-forms/crispy-bootstrap5
    - django-redis >=5.4.0  # https://github.com/jazzband/django-redis
# Base - # Django REST Framework
    - djangorestframework >=3.16.0  # https://github.com/encode/django-rest-framework
    - django-cors-headers >=4.7.0  # https://github.com/adamchainz/django-cors-headers
# Base - # DRF-spectacular for api documentation
    - drf-spectacular >=0.28.0  # https://github.com/tfranzel/drf-spectacular
# Base - # Use Async
    - uvicorn-standard >=0.34.2  # https://github.com/encode/uvicorn
    - uvicorn-worker >=0.3.0  # [not win]  # https://github.com/Kludex/uvicorn-worker
# Local
# https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/local.txt
    - psycopg >=3.2.8  # https://github.com/psycopg/psycopg
    - werkzeug >=3.1.3  # https://github.com/pallets/werkzeug
    # https://github.com/pallets/werkzeug/blob/main/pyproject.toml#L36C22-L36C27
    - watchdog >=2.3  # https://github.com/pallets/werkzeug
    - ipdb >=0.13.13  # https://github.com/gotcha/ipdb
    - watchfiles >=1.0.5  # https://github.com/samuelcolvin/watchfiles
# Local # Testing
    - mypy >=1.15.0  # https://github.com/python/mypy
    - django-stubs >=5.2.0  # https://github.com/typeddjango/django-stubs
    - pytest-sugar >=1.0.0  # https://github.com/Teemu/pytest-sugar
    - djangorestframework-stubs >=3.16.0  # https://github.com/typeddjango/djangorestframework-stubs
# Local # Documentation
# Local # Code quality
# ------------------------------------------------------------------------------
# https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/local.txt#L29
    - coverage >=7.8.1  # https://github.com/nedbat/coveragepy
    - djlint >=1.36.3  # https://github.com/Riverside-Healthcare/djLint
# Local # Django
# ------------------------------------------------------------------------------
# https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/local.txt#L36C
    - factory_boy >=3.3.2  # https://github.com/FactoryBoy/factory_boy
    - django-debug-toolbar >=5.2.0  # https://github.com/jazzband/django-debug-toolbar
    - django-extensions >=4.1  # https://github.com/django-extensions/django-extensions
    - django_coverage_plugin >=3.1.0  # https://github.com/nedbat/django_coverage_plugin
    - pytest-django >=4.11.1  # https://github.com/pytest-dev/pytest-django
# ------------------------------------------------------------------------------
# Production
# https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/requirements/production.txt
# ------------------------------------------------------------------------------
    - gunicorn >=23.0.0  # [not win]  # https://github.com/benoitc/gunicorn
  run_constrained:
# Database
# ------------------------------------------------------------------------------
    - postgresql >=12.0,<18.0
    - sqlite >=3.46.0
    - psycopg-c >=3.2.8
# Docs
# ------------------------------------------------------------------------------
# https://github.com/cookiecutter/cookiecutter-django/blob/master/docs/requirements.txt
    - sphinx >=8.0.2
    - sphinx-autobuild >=2024.10.3
    - sphinx-rtd-theme >=3.0.0
    - myst-parser >=4.0.0
# Docker
# ------------------------------------------------------------------------------
    - docker-py >=6.0.0

test:
  imports:
    - cookiecutter
  commands:
    #- cookiecutter cookiecutter-django --no-input --directory {{ SRC_DIR }}  # [unix]
    - cookiecutter cookiecutter-django --help
    - pip check  # [unix]
    # pip check
    #cookiecutter-django 2025.4.30 has requirement django-upgrade==1.22.2, but you have django-upgrade 1.24.0.
    #cookiecutter-django 2025.4.30 has requirement gitpython==3.1.43, but you have gitpython 3.1.44.
    #cookiecutter-django 2025.4.30 has requirement jinja2==3.1.5, but you have jinja2 3.1.6.
    #cookiecutter-django 2025.4.30 has requirement pre-commit==4.1.0, but you have pre-commit 4.2.0.
    #cookiecutter-django 2025.4.30 has requirement pygithub==2.5, but you have pygithub 2.6.1.
    #cookiecutter-django 2025.4.30 has requirement pytest==8.3.4, but you have pytest 8.3.5.
    #cookiecutter-django 2025.4.30 has requirement ruff==0.11.8, but you have ruff 0.11.7.
    #cookiecutter-django 2025.4.30 has requirement sh==2.1; sys_platform != "win23", but you have sh 2.2.2.
    #cookiecutter-django 2025.4.30 has requirement tox==4.23.2, but you have tox 4.25.0.
    #tox-uv 1.25.0 has requirement tox<5,>=4.24.1, but you have tox 4.23.2
    #fido2 1.1.3 has requirement cryptography!=35,<45,>=2.6, but you have cryptography 45.0.2.
  requires:
    - python {{ python_min }}
    - pip
    - django-upgrade ==1.22.2
    - gitpython ==3.1.43
    - jinja2 ==3.1.5
    - pre-commit ==4.1.0
    - pygithub ==2.5
    - pytest ==8.3.4
    - ruff ==0.11.11
    - sh ==2.1  # [unix]
    - tox ==4.23.2
    - tox-uv ==1.19.1
    - cryptography >=2.6,!=35,<45

about:
  summary: A Cookiecutter template for creating production-ready Django projects quickly
  home: https://github.com/cookiecutter/cookiecutter-django
  description: |
    "Powered by Cookiecutter, Cookiecutter Django is a project template for jumpstarting 
    production-ready Django projects. The template offers a number of generation options, 
    we invite you to check the https://cookiecutter-django.readthedocs.io/en/latest/project-generation-options.html#template-options 
    to learn more about each of them."
  doc_url: https://cookiecutter-django.readthedocs.io/en/latest/
  dev_url: https://github.com/cookiecutter/cookiecutter-django
  license_family: BSD
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - '{{ cookiecutter }}.{{ project_slug }}/LICENSE'
    - '{{ cookiecutter }}.{{ project_slug }}/COPYING'

extra:
  recipe-maintainers:
    - rxm7706
