schema_version: 1

context:
  name: gorilla
  version: 0.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gorilla-${{ version }}.tar.gz
  sha256: 005ab8853b037162a7c77bb824604c6e081878ee03c09ad01ef41744856019d3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - gorilla
      pip_check: true

about:
  summary: Convenient approach to monkey patching
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/christophercrouzet/gorilla

extra:
  recipe-maintainers:
    - rxm7706
