# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-flags
  version: "5.1.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 47f33efba238fe83a2c1f6f5764147fe62d770039f64b3a039e0e461bbc36e79

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=63
    - setuptools-scm >=8
    - pip
    #- wheel
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    # - pymdown-extensions >=4.11
    # - mkdocs-rtd-dropdown >=0.0.11
    # - mkdocs >=0.17
    # - jinja2
    # - django-debug-toolbar
    # - coverage

tests:
  - python:
      imports:
        - flags
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Feature flags for Django projects
  license: CC0-1.0
  license_file: LICENSE
  homepage: https://github.com/cfpb/django-flags

extra:
  recipe-maintainers:
    - rxm7706
