# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: rpaframework
  version: "31.0.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rpaframework-${{ version }}.tar.gz
  sha256: b5170c7ceb5b845a47a82ec2949b7b581349261614fdb170bd2303b32146c413

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  #python:
    #entry_points:
      #- rpa-crypto = RPA.scripts.crypto:main
      #- use-robocorp-vault = RPA.scripts.robocorp_cloud:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - docutils >=0.21.2
    - rpaframework-core >=12.0.2
    - rpaframework-pdf >=9.0.0
    - if: win
      then: rpaframework-windows >=10.0.0
    - java-access-bridge-wrapper >=1.1.0
    - robocorp-storage >=1.0.2
    - jsonpath-ng >=1.5.2
    - robotframework >=4.0.0,!=4.0.1,!=6.1.0,<8.0.0
    - if: win
      then: robotframework-sapguilibrary >=1.1
    - robotframework-seleniumlibrary >=6.7.1
    - robotframework-seleniumtestability >=2.0.0
    - robotframework-requests >=0.9.1
    - if: win
      then: pywinauto >=0.6.8
    - if: win
      then: pywin32-on-windows >=302,<307
    - if: win
      then: comtypes >=1.1.11
    - robotframework-pythonlibcore >=4.2.0
    - pynput-robocorp-fork >=5.0.0
    - if: linux
      then: python-xlib >=0.17
    - if: win
      then: psutil >=5.7.0
    - pyperclip >=1.8.0
    - exchangelib >=5.1.0
    - tzlocal >=4.2
    - xlrd >=2.0.1
    - xlwt >=1.3.0
    - xlutils >=2.0.0
    - openpyxl >=3.0.9
    - pillow >=10.2.0
    - simple-salesforce >=1.0.0
    - netsuitesdk >=1.1.0
    - tweepy >=3.8.0
    - python-graphviz >=0.13.2
    - notifiers >=1.3.3
    - cryptography >=44.0.1,<45
    - python-mss >=6.0.0
    - chardet >=3.0.0
    - pysocks >=1.5.6,!=1.5.7,<2.0.0
    - selenium ==4.15.2
    - click >=8.1.2
    - pyyaml >=5.4.1,<7.0.0
    - tenacity >=8.0.1
    - htmldocx >=0.0.6
    - python-docx >=0.8.11
    - beautifulsoup4 >=4.7.0
    - pyotp >=2.6.0
    - importlib-metadata >=4.13.0
    - o365 >=2.0.21,<2.0.27
    - requests >=2.28.1
    - oauthlib >=3.2.2
    - requests-oauthlib >=1.3.1
    - pyjwt >=2.6.0
    - validators >=0.34.0
    - smartsheet-python-sdk ==3.0.2
    - pendulum >=3.0.0
    - wrapt >=1.14.0,<2.0.0
    - holidays >=0.45

tests:
#  - files:
#       source:
#         - tests/
  - python:
      imports:
        #- rpaframework
        - RPA
        #- RPA.Browser
        #- ModuleNotFoundError: No module named 'RPA.Browser'
      pip_check: false
      # rpaframework-pdf 10.0.0 has requirement pdfminer-six==20250506, but you have pdfminer-six 0.0.0.
      python_version: ${{ python_min }}.*
#  - requirements:
#      run:
#        - python ${{ python_min }}.*
#        - pip
#        - mock >=2
#        - pytest >=3.4,!=3.10.0
#        - pytest-mock >=1.8
#        - pytest-cov
    #script:
      #- rpa-crypto --help
      # ModuleNotFoundError: No module named 'RPA.scripts'
      #- use-robocorp-vault --help
#      - pytest -k "not browser and not pdf" tests/
#      # - pip check  # [linux]
#      # google-oauth is optional dependency, script fails if it's not installed
#      # - rpa-google-oauth --help

about:
  homepage: https://rpaframework.org/
  summary: A collection of tools and libraries for RPA
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - rxm7706
