{% set name = "dagster-ducklake" %}
{% set version = "0.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dagster_ducklake-{{ version }}.tar.gz
  sha256: 6982dd76a2e98703cdff94027924ca3d69a18fa883e6cd45a9dab29643ea0b57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }},<4.0
    - dagster >=1.11.9
    - python-duckdb >=1.4.0
    - pydantic >=2.0.0
    - sqlalchemy >=2.0.43,<2.1.dev0

test:
  imports:
    - dagster_ducklake
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Dagster integration for Ducklake
  license: 'Apache-2.0'
  license_file: LICENSE
  home: https://github.com/dagster-io/community-integrations

extra:
  recipe-maintainers:
    - rxm7706
