# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: sseclient-py
  version: "1.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sseclient-py-${{ version }}.tar.gz
  sha256: c547c5c1a7633230a38dc599a21a2dc638f9b5c297286b48b46b935c71fac3e8

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - sseclient
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: SSE client for Python
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/mpetazzoni/sseclient

extra:
  recipe-maintainers:
    - sanurielf
    - mpetazzoni
