# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-guardian
  version: "3.2.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_guardian-${{ version }}.tar.gz
  sha256: 9e18ecd2e211b665972690c2d03d27bce0ea4932b5efac24a4bb9d526950a69e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61,<81.0.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<4
    - django >=3.2
    - typing_extensions >=4.12.0
    - django-environ
    - guardian

tests:
  - python:
      imports:
        - guardian
      pip_check: false
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
        - django-environ >=0.12.0
        - pip
        - pytest >=8.3.4
        - pytest-django >=4.9.0
    script:
      - pip check
      - DJANGO_SETTINGS_MODULE=guardian.testapp.testsettings pytest --pyargs guardian

about:
  homepage: http://github.com/django-guardian/django-guardian
  summary: Implementation of per object permissions for Django.
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - abraha2d
    - rxm7706
