# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.18.0"

package:
  name: babel
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/babel/babel-${{ version }}.tar.gz
  sha256: b80b99a14bd085fcacfa15c9165f651fbb3406e66cc603abf11c5750937c992d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pytz >=2015.7
    - if: win
      then:
        - python-tzdata

tests:
  - python:
      imports:
        - babel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://babel.pocoo.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Internationalization utilities
  description: |
    Internationalization utilities
  repository: https://github.com/python-babel/babel

extra:
  recipe-maintainers:
    - frol
    - nehaljwani
    - thewchan

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: babel
  cfe-upstream-registry: pypi
  cfe-upstream-name: babel
  cfe-purls:
    - pkg:conda/babel@${{ version }}?channel=conda-forge
    - pkg:pypi/babel@${{ version }}
  cfe-upstream-repo: https://github.com/python-babel/babel
  cfe-upstream-homepage: https://babel.pocoo.org/
  cfe-import-names: [babel]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/babel-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T06:33:13Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T06:33:13Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-17T06:33:13Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
#    # generate failed rc=1: Fetching info for babel...
Error: Compressed file ended before the end-of-stream marker was reached

####
