# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: langsmith-mcp-server
  version: "0.0.7"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langsmith_mcp_server-${{ version }}.tar.gz
  sha256: b0bc26053b1541a2a0c2469398d252d7270c4944f8fbfa6ac2ad218fd93ce274

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - langsmith-mcp-server = langsmith_mcp_server.server:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - mcp >=1.3.0
    - langsmith >=0.3.37
    - langchain-core >=0.3.56

tests:
  - python:
      imports:
        - langsmith_mcp_server
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - langsmith-mcp-server --help

about:
  summary: MCP server for Langsmith SDK integration
  homepage: https://github.com/langchain-ai/langsmith-mcp-server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
