# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-celery-results
  version: "2.6.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_celery_results-${{ version }}.tar.gz
  sha256: 9abcd836ae6b61063779244d8887a88fe80bbfaba143df36d3cb07034671277c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pytest
    - pip
    - setuptools <81.0.0
  run:
    - python >=${{ python_min }},<4
    - celery >=5.2.7,<6.0
    - django >=3.2.25

tests:
  - python:
      imports:
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: Celery result backends for Django.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/celery/django-celery-results

extra:
  recipe-maintainers:
    - rxm7706
