# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: aiobotocore
  version: 3.8.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 80a1eb64ea915f3af3c1518669975bae74a17b2f37c14eb0fa2f83b915974670

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77.0.0
  run:
    - python >=${{ python_min }}
    - aiohttp >=3.12.0,<4.0.0
    - aioitertools >=0.5.1,<1.0.0
    - botocore >=1.43.3,<1.43.47
    - python-dateutil >=2.1,<3.0.0
    - jmespath >=0.7.1,<2.0.0
    - multidict >=6.0.0,<7.0.0
    - wrapt >=1.10.10,<3.0.0
    - typing_extensions >=4.14.0,<5.0.0
tests:
  - python:
      imports:
        - aiobotocore
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  homepage: https://github.com/aio-libs/aiobotocore
  repository: https://github.com/aio-libs/aiobotocore
  documentation: http://aiobotocore.readthedocs.io

extra:
  recipe-maintainers:
    - TRNWWZ
    - claytonparnell
    - nehaljwani
    - fhoehle
