# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.0.0"

package:
  name: mcp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mcp/mcp-${{ version }}.tar.gz
  sha256: 0f440e735c13ece8bb19bc62cf0b86f4313448432fbb77d35e14034f4e050728

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - anyio >=4.9
    - httpx2 >=2.5.0
    - jsonschema >=4.20.0
    - mcp-types ==2.0.0
    - opentelemetry-api >=1.28.0
    - pydantic >=2.12.0
    - pyjwt >=2.10.1
    - python-multipart >=0.0.9
    - sse-starlette >=3.0.0
    - starlette >=0.27
    - typing_extensions >=4.13.0
    - typing-inspection >=0.4.1
    - if: win
      then:
        - pywin32

tests:
  - python:
      imports:
        - mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://modelcontextprotocol.io
  license: MIT
  license_file: LICENSE
  summary: Model Context Protocol SDK
  description: |
    Model Context Protocol SDK
  repository: https://github.com/modelcontextprotocol/python-sdk
  documentation: https://py.sdk.modelcontextprotocol.io/

extra:
  recipe-maintainers:
    - dbast
    - pb01ka

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: mcp
  cfe-upstream-registry: pypi
  cfe-upstream-name: mcp
  cfe-purls:
    - pkg:conda/mcp@${{ version }}?channel=conda-forge
    - pkg:pypi/mcp@${{ version }}
  cfe-upstream-repo: https://github.com/modelcontextprotocol/python-sdk
  cfe-upstream-homepage: https://modelcontextprotocol.io
  cfe-import-names: [mcp]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/mcp-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-2.0.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T01:32:34Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T01:32:34Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-18T01:32:34Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
