# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: robotframework-assertion-engine
  version: "3.0.3"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robotframework_assertion_engine-${{ version }}.tar.gz
  sha256: 1c608d4c69d96520986a1ddc6def0fc7f7e849520f1e6882a633b51dbb98fd88

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - robotframework >=5.0.1
    - robotframework-pythonlibcore >=3.0.0,<4.0.0|,>=4.0.0,<5.0.0

tests:
  - python:
      imports:
        - robotframework_assertion_engine
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Generic way to create meaningful and easy to use assertions for the Robot Framework libraries.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/MarketSquare/AssertionEngine

extra:
  recipe-maintainers:
    - rxm7706
