{% set name = "gw-dsl-parser" %}
{% set version = "0.1.49.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gw_dsl_parser-{{ version }}.tar.gz
  sha256: f0c086e4c1015355935b26ae471244523e9f5c2821c888fb9fe245252268a027

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - hatchling
    - pip
  run:
    - python >=3.6
    - wasmtime-py >=12.0.0

test:
  imports:
    - gw_dsl_parser

about:
  home: https://github.com/Kanaries/gw-dsl-parser-py
  summary: Convert your graphic-walker workflow to SQL
  description: |
    gw-dsl-parser is a Python library that converts graphic-walker workflows
    into SQL queries. It provides a parser and converter for the Graphic Walker
    domain-specific language (DSL) used in data visualization workflows.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/Kanaries/gw-dsl-parser-py

extra:
  recipe-maintainers:
    - rxm7706
