# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.122.0"

package:
  name: anthropic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/anthropic/anthropic-${{ version }}.tar.gz
  sha256: ffec56ae96657c8d19fa575ec96f140f380c353a07ab7d61b92eb18ee6536601

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling ==1.26.3
    - hatch-fancy-pypi-readme >=22.4,<26
  run:
    - python >=${{ python_min }}
    - anyio <5,>=3.5.0
    - distro <2,>=1.7.0
    - docstring_parser <1,>=0.15
    - httpx <1,>=0.25.0
    - jiter <1,>=0.4.0
    - pydantic <3,>=1.9.0
    - sniffio <2,>=1
    - typing_extensions <5,>=4.14

tests:
  - python:
      imports:
        - anthropic
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/anthropics/anthropic-sdk-python
  license: MIT
  license_file: LICENSE
  summary: The official Python library for the anthropic API
  description: |
    The official Python library for the anthropic API
  repository: https://github.com/anthropics/anthropic-sdk-python

extra:
  recipe-maintainers:
    - jan-janssen
    - mikelambert
    - moritzwilksch
    - siboehm
    - x5a

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: anthropic
  cfe-upstream-registry: pypi
  cfe-upstream-name: anthropic
  cfe-purls:
    - pkg:conda/anthropic@${{ version }}?channel=conda-forge
    - pkg:pypi/anthropic@${{ version }}
  cfe-upstream-repo: https://github.com/anthropics/anthropic-sdk-python
  cfe-upstream-homepage: https://github.com/anthropics/anthropic-sdk-python
  cfe-import-names: [anthropic]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/anthropic-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.122.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T07:51:51Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T07:51:51Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T07:51:51Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
