# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: paperless-ngx
  version: "2.19.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/paperless-ngx/paperless-ngx/archive/v${{ version }}.tar.gz
  sha256: 3cdde3778b3aa664d01d4b817cfab46916cbf8b6fe2835699422707ae4b6f6e5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools <81.0.0
  run:
    - python >=${{ python_min }},<4
    - babel >=2.17
    - bleach >=6.2.0,<6.3.0
    - celery >=5.5.1,<5.6.0
    - channels >=4.2,<5.0
    - channels_redis >=4.2,<5.0
    #- concurrent-log-handler >=0.9.25,<0.10.0  # concurrent-log-handler >=0.9.25,<0.10.dev0, for which no candidates were found.
    - dateparser >=1.2,<2.0
    - django >=5.2.5,<5.3.0
    - django-allauth >=65.4.0,<65.5.0
    - django-auditlog >=3.2.1,<3.3.0
    #- django-cachalot >=2.8.0,<2.9.0  # django-cachalot >=2.8.0,<2.9.0, for which no candidates were found.
    #- django-celery-results >=2.6.0,<2.7.0  # django-celery-results >=2.6.0,<2.7.0, for which no candidates were found.
    #- django-compression-middleware >=0.5.0,<0.6.0  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31296
    - django-cors-headers >=4.9.0,<4.10.0
    - django-extensions >=4.1,<5.0
    - django-filter >=25.1,<26.0
    - django-guardian >=3.2.0,<3.3.0
    #- django-multiselectfield >=1.0.1,<1.1.0  # django-multiselectfield >=1.0.1,<1.1.0, for which no candidates were found.
    #- django-soft-delete >=1.0.18,<1.1.0  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31295
    #- django-treenode >=0.23.2  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31294
    - djangorestframework >=3.16,<4.0
    #- djangorestframework-guardian >=0.4.0,<0.5.0  #  djangorestframework-guardian >=0.4.0,<0.5.0, for which no candidates were found.
    - drf-spectacular >=0.28,<1.0
    - drf-spectacular-sidecar >=2025.9.1,<2025.10.0
    #- drf-writable-nested >=0.7.1,<0.8.0  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31293 - TODO FAILING
    - filelock >=3.20.0,<3.21.0
    - flower >=2.0.1,<2.1.0
    #- gotenberg-client >=0.12.0,<0.13.0  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31292
    - httpx-oauth >=0.16,<1.0
    - imap-tools >=1.11.0,<1.12.0
    #- inotifyrecursive >=0.3,<1.0  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31291 - TODO FAILING
    - jinja2 >=3.1.5,<3.2.0
    - langdetect >=1.0.9,<1.1.0
    - nltk >=3.9.1,<3.10.0
    #- ocrmypdf >=16.11.0,<16.12.0  # ocrmypdf >=16.11.0,<16.12.0, for which no candidates were found.
    - pathvalidate >=3.3.1,<3.4.0
    - pdf2image >=1.17.0,<1.18.0
    - python-dateutil >=2.9.0,<2.10.0
    - python-dotenv >=1.1.0,<1.2.0
    #- python-gnupg >=0.5.4,<0.6.0  #  python-gnupg >=0.5.4,<0.6.0, for which no candidates were found.
    - python-ipware >=3.0.0,<3.1.0
    - python-magic >=0.4.27,<0.5.0
    - pyzbar >=0.1.9,<0.2.0
    - rapidfuzz >=3.14.0,<3.15.0
    - redis-py >=5.2.1,<5.3.0
    - scikit-learn >=1.7.0,<1.8.0
    - setproctitle >=1.3.4,<1.4.0
    #- tika-client >=0.10.0,<0.11.0  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31290
    - tqdm >=4.67.1,<4.68.0
    - watchdog >=6.0,<7.0
    #- whitenoise >=6.9,<7.0  #  whitenoise >=6.9,<7.0, for which no candidates were found.
    #- whoosh-reloaded >=2.7.5  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31289
    #- zxing-cpp >=2.3.0,<2.4.0  # NA Conda-Forge - https://github.com/conda-forge/staged-recipes/pull/31288

tests:
  - python:
      imports:
        - paperless_ngx
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: "A community-supported supercharged document management system: scan, index and archive all your physical documents"
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/paperless-ngx/paperless-ngx
  repository: https://github.com/paperless-ngx/paperless-ngx
  documentation: https://docs.paperless-ngx.com/

extra:
  recipe-maintainers:
    - rxm7706
