# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: shapash
  version: "2.8.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/shapash-${{ version }}.tar.gz
  sha256: 46582c1642fca8452fa34755ecd8e8c0014f00c4c829f8bbb52dfa1ed1186086

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - category_encoders >=2.6.0
    - dash-bootstrap-components >=1.1.0,<2.0.0
    - dash-core-components >=2.0.0
    - dash-daq >=0.5.0
    - dash-html-components >=2.0.0
    - dash-renderer ==1.8.3
    - dash-table >=5.0.0
    - dash >=2.3.1,<3.0.0
    - flask >=1.0.4
    - matplotlib-base >=3.8.4
    - nbformat >5.8.0
    - numba >=0.60.0
    - numpy >=2.0.0
    - pandas >=2.2.2
    - plotly >=5.0.0,<6.0.0
    - scikit-learn >=1.4.2,<1.6.0
    - scipy >=1.13.0
    - shap >=0.46.0
    - shapely >=2.0.0

tests:
  - python:
      imports:
        - shapash
#        - build
#        - catboost_info
#        - data
#        - dist
#        - docs
#        - tutorial
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/MAIF/shapash
  summary: Shapash is a Python library which aims to make machine learning interpretable and understandable by everyone.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
