# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "26.7.1"

package:
  name: appdynamics-bindeps-linux-x64
  version: ${{ version }}

source:
  url: https://pypi.org/packages/cp310/a/appdynamics-bindeps-linux-x64/appdynamics_bindeps_linux_x64-26.7.1-cp310-none-any.whl
  sha256: 0a8f3194921ce277a7cf429a48d318774b3263b999389b3bd1d236edcb6f075e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - appdynamics_bindeps_linux_x64
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: http://www.appdynamics.com
  license: Proprietary
  license_file: LICENSE
  summary: Dependencies for AppDynamics Python agent
  description: |
    Dependencies for AppDynamics Python agent

extra:
  recipe-maintainers:
    - rxm7706

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: appdynamics-bindeps-linux-x64
  cfe-upstream-registry: pypi
  cfe-upstream-name: appdynamics-bindeps-linux-x64
  cfe-purls:
    - pkg:conda/appdynamics-bindeps-linux-x64@${{ version }}?channel=conda-forge
    - pkg:pypi/appdynamics-bindeps-linux-x64@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: http://www.appdynamics.com
  cfe-import-names: [appdynamics_bindeps_linux_x64]
  cfe-source-kind: pypi-wheel
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: pending-submission-to-conda-forge
  cfe-on-conda-forge-feedstock: none
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T07:53:19Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T07:53:19Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-18T07:53:19Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
