# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.15.0"

package:
  name: python-lsp-server
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-lsp-server/python_lsp_server-${{ version }}.tar.gz
  sha256: 85fa090262c3d1aef09b759d98811d6cb9ad5bbc58af15d588608ae8c1925801

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=69.0.0
  run:
    - python >=${{ python_min }}
    - docstring-to-markdown
    - importlib-metadata >=4.8.3
    - jedi <0.21.0,>=0.17.2
    - pluggy >=1.0.0
    - python-lsp-jsonrpc <2.0.0,>=1.1.0
    - ujson >=3.0.0
    - black

tests:
  - python:
      imports:
        - pylsp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/python-lsp/python-lsp-server
  license: MIT
  license_file: LICENSE
  summary: Python Language Server for the Language Server Protocol
  description: |
    Python Language Server for the Language Server Protocol

extra:
  recipe-maintainers:
    - krassowski
    - ccordoba12
    - andfoy
    - steff456
    - dalthviz

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: python-lsp-server
  cfe-upstream-registry: pypi
  cfe-upstream-name: python-lsp-server
  cfe-purls:
    - pkg:conda/python-lsp-server@${{ version }}?channel=conda-forge
    - pkg:pypi/python-lsp-server@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/python-lsp/python-lsp-server
  cfe-import-names: [pylsp]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/python-lsp-server-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-1.15.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T04:28:00Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T04:28:00Z
  cfe-local-build-status: build-clean-test-blocked
  cfe-local-build-datetime: 2026-08-18T04:28:00Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
