# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: py-key-value-shared
  version: "0.2.8"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/py_key_value_shared-${{ version }}.tar.gz
  sha256: 703b4d3c61af124f0d528ba85995c3c8d78f8bd3d2b217377bd3278598070cc1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.8.2,<0.9.0
    - pip
  run:
    - python >=${{ python_min }},<4
    - typing_extensions >=4.15.0
    - beartype >=0.22.2

tests:
  - python:
      imports:
        - py_key_value_shared
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/strawgate/py-key-value
  summary: Shared Key-Value, A pluggable interface for KV Stores
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
