# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-watchfiles
  version: "1.4.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_watchfiles-${{ version }}.tar.gz
  sha256: 88e253e8e8427834eac467923d334c35010279b3e9ceb5bb91014be83975b11b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - pip
  run:
    - python >=${{ python_min }},<4
    - django >=4.2
    - watchfiles

tests:
  - python:
      imports:
        - django_watchfiles
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/adamchainz/django-watchfiles
  summary: Make Django’s autoreloader more efficient by watching for changes with watchfiles.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
