# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: jupyterlab-gallery
  version: "0.6.3"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jupyterlab_gallery-${{ version }}.tar.gz
  sha256: 780a71918e7cd4d7b5cc82ded3c9ff79290fe2447caa6a34abd88b625b093c8d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - jupyterlab-gallery = jupyterlab_gallery:GalleryApp.launch_instance
      - jupyterhub-gallery = jupyterlab_gallery.hub:HubGalleryApp.launch_instance

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - jupyter_server >=2.0.1,<3
    - nbgitpuller >=1.2.1
    - gitpython >=3.1.43
  run_constraints:
    - jupyterhub >4

tests:
  - python:
      imports:
        - jupyterlab_gallery
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - jupyterhub >4
        - python ${{ python_min }}.*
    script:
      - jupyterlab-gallery --help
      - jupyterhub-gallery --help

about:
  summary: A JupyterLab gallery extension for presenting and downloading examples from remote repositories
  license: Apache-2.0 AND BSD-3-Clause
  homepage: https://github.com/nebari-dev/jupyterlab-gallery
  repository: https://github.com/nebari-dev/jupyterlab-gallery
  license_file:
    - LICENSE
    - style/icons/md/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
