# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: nlp-feature-extractors
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/nlp_feature_extractors-${{ version }}.tar.gz
  sha256: a042ecfb2a6d2e890a79e47678f2b1032c393248dd1c6342b185051a0c9aeddf

build:
  number: 1
  noarch: python
  script:
    - if: unix
      then: cp -R ${{ RECIPE_DIR }}/requirements.txt ${{ SRC_DIR }}/requirements.txt
    - if: win
      then: echo f | xcopy /f /y /S %RECIPE_DIR%\requirements.txt %SRC_DIR%\requirements.txt
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - datasets
    - gender-guesser >=0.4.0
    - negspacy >=1.0.0
    - numpy >=1.17.2
    - sentencepiece
    - spacy
    - tqdm
    - raiutils >=0.2.0

tests:
  - python:
      imports:
        - nlp_feature_extractors
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: NLP Feature Extractors
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/microsoft/responsible-ai-widgets

extra:
  recipe-maintainers:
    - rxm7706
