schema_version: 1

context:
  name: firecrawl-py
  version: 1.12.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/firecrawl_py-${{ version }}.tar.gz
  sha256: bbf883f6c774f05a5426121b85978a5f7b5ab11e614aff609f0673b097c3e553

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - python-dotenv
    - websockets
    - nest-asyncio
    - pydantic >=2.10.3
    - pytest
    - asyncio

tests:
  - python:
      imports:
        - firecrawl
      pip_check: true

about:
  summary: Python SDK for Firecrawl API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mendableai/firecrawl
  repository: https://github.com/mendableai/firecrawl

extra:
  recipe-maintainers:
    - rxm7706
