# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: lupa
  version: "2.6"
  python_min: '3.10'
  python_check_max: "3.13"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lupa-${{ version }}.tar.gz
  sha256: 9a770a6e89576be3447668d7ced312cd6fd41d3c13c2462c9dc2c2ab570e45d9

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    #- ${{ stdlib('c') }}
    - ${{ compiler('c') }}
  host:
    - python
    - cython >=3.1.6
    - setuptools
    - wheel
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - lupa
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*


about:
  homepage: https://github.com/scoder/lupa
  summary: Python wrapper around Lua and LuaJIT
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party/lua51/COPYRIGHT
    - third-party/luajit20/COPYRIGHT
    - third-party/luajit21/COPYRIGHT

extra:
  recipe-maintainers:
    - lincrosenbach
    - mv-per
    - brnomendes
    - mediocretech
    - rxm7706
