# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: lupa
  version: "2.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lupa-${{ version }}.tar.gz
  sha256: d8022641b9ec8ecf2c5ecbe9f47e5a70e0b87c4b5ae921b92cb02a638e0acd08

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
    - cmake
    - make
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: linux
      then: gcc
  host:
    - python
    - cython
    - pip
    - setuptools
    - lua
    - luajit
  run:
    - python

tests:
  - python:
      imports:
        - lupa
      pip_check: true

about:
  summary: Python wrapper around Lua and LuaJIT
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/scoder/lupa

extra:
  recipe-maintainers:
    - lincrosenbach
    - mv-per
    - brnomendes
    - mediocretech
