# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.16.4"

package:
  name: python-socketio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-socketio/python_socketio-${{ version }}.tar.gz
  sha256: f7fa4a43cc8e687930b5c6e44d6e2efc2071eca4bef49b8bb3dc0827f7f92235

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.2
  run:
    - python >=${{ python_min }}
    - bidict >=0.21.0
    - python-engineio >=4.13.2
tests:
  - python:
      imports:
        - socketio
        - socketio.base_manager
        - socketio.kombu_manager
        - socketio.middleware
        - socketio.namespace
        - socketio.packet
        - socketio.pubsub_manager
        - socketio.redis_manager
        - socketio.server
      pip_check: true
      python_version: 
        - ${{ python_min }}.*
        - "*"

about:
  license_file: LICENSE
  license: MIT
  summary: Socket.IO server
  homepage: https://github.com/miguelgrinberg/python-socketio/
  repository: https://github.com/miguelgrinberg/python-socketio/
  documentation: https://python-socketio.readthedocs.io/

extra:
  recipe-maintainers:
    - ReimarBauer
    - synapticarbors
