# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: google-colab
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/google-colab-${{ version }}.tar.gz
  sha256: 932fd05e649dba27457ef9959bc5f3b1e6f7c8d9b4451c9fa1b4d2eb0c3fa3ab
  patches:
    - setup.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - google-auth
    - ipykernel
    - ipython
    - notebook
    - pandas
    - portpicker
    - python
    - requests
    - six
    - tornado

tests:
  - python:
      imports:
        - google
        - google.colab
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Python libraries for Google Colaboratory
  description: |
    Colaboratory is a research project created to help disseminate machine
    learning education and research. It’s a Jupyter notebook environment
    that requires no setup to use. For more information, see our FAQ.
  homepage: https://colab.research.google.com/
  repository: https://github.com/googlecolab/colabtools
  documentation: https://colab.research.google.com/

extra:
  recipe-maintainers:
    - jan-janssen
