# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: marshmallow-sqlalchemy
  version: "1.5.0"
  sha256: e51192c204770645a2fab0d72f44f8789272eef75951f84b1608d6b4b0bfe0e6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - flit-core
  run:
    - python >=${{ python_min }}
    - marshmallow >=2.15.2
    - sqlalchemy >=1.2.0

tests:
  - python:
      imports:
        - marshmallow_sqlalchemy
      pip_check: false
      python_version: ${{ python_min }}
  - requirements:
      run:
        - python ${{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  summary: SQLAlchemy integration with marshmallow
  description: |
    SQLAlchemy integration with the marshmallow (de)serialization library.
  homepage: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  repository: https://github.com/marshmallow-code/marshmallow-sqlalchemy
  documentation: http://marshmallow-sqlalchemy.readthedocs.io/

extra:
  recipe-maintainers:
    - frol
    - mediocretech
