schema_version: 1

context:
  name: robotcode-runner
  version: 1.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robotcode_runner-${{ version }}.tar.gz
  sha256: 99ef0a1de3df00516907453503c234bf75f38b27419628a99888afe051ee65d7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - robotframework >=4.1.0
    - robotcode-robot ==1.9.0
    - robotcode-modifiers ==1.9.0
    - robotcode-plugin ==1.9.0
    - robotcode ==1.9.0

tests:
  - python:
      imports:
        - robotcode_runner
      pip_check: true

about:
  summary: RobotCode runner for Robot Framework
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/robotcodedev/robotcode

extra:
  recipe-maintainers:
    - rxm7706
