# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: cucumber-tag-expressions
  version: "11.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: f8304dd16e546517816e62ace6c486575023812f42e8a60526fcec1694016146

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.12.0,<0.13.0
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - cucumber_tag_expressions
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Provides tag-expression parser for cucumber/behave
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/cucumber/tag-expressions

extra:
  recipe-maintainers:
    - thewchan
