{% set name = "wagtail-treemodeladmin" %}
{% set version = "1.11.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 357a619589168ee558a1d96249a46575d973a65c59a7f824ace04c0878e5d7d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=63
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=6.3
    - wagtail-modeladmin >=1.0

test:
  imports:
    - treemodeladmin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: TreeModelAdmin for Wagtail
  home: https://github.com/cfpb/wagtail-treemodeladmin
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
