{% set version = "1.28.0" %}

package:
  name: mailpit
  version: {{ version }}

source:
  url: https://github.com/axllent/mailpit/archive/v{{ version }}.tar.gz
  sha256: 438581a2fd717d12b6259081420b10a8dab5af30b18b73c01db9cf5d83467869

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-cgo') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - go-licenses
    - nodejs >=18

test:
  commands:
    - mailpit --help

about:
  home: https://github.com/axllent/mailpit
  summary: A small, fast, low memory, zero-dependency, multi-platform email testing tool & API for developers
  description: |
    Mailpit is an email testing tool for developers. It acts as an SMTP server,
    captures all sent emails, and displays them in a modern web interface.
    It also provides a REST API for integration testing.

    Key features:
    - Fast, lightweight, and low memory usage
    - Multi-platform support (Linux, macOS, Windows)
    - Modern web UI for viewing emails
    - REST API for automated testing
    - Support for SMTP relay
    - Message tagging and search
    - Real-time web UI updates
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/
  doc_url: https://mailpit.axllent.org/docs/
  dev_url: https://github.com/axllent/mailpit

extra:
  recipe-maintainers:
    - rxm7706
