# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ydata-quality
  version: "0.1.0"
  python_min: '3.7'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ydata-quality-${{ version }}.tar.gz
  sha256: e32bd5074a490d27606b42004d4d7cfbaaeeac21a403d9e40955ac8fb92c12c8

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<3.9
    - dython ==0.6.7
    - matplotlib-base ==3.4.2
    - numpy ==1.20.3
    - pandas >=1.2.0,<1.3.0
    - pydantic ==1.8.2
    - scikit-learn ==0.24.2
    - statsmodels ==0.12.2

tests:
  - python:
      imports:
        - ydata_quality
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: YData open-source tools for Data Quality.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ydataai/ydata-quality

extra:
  recipe-maintainers:
    - rxm7706
