# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "7.2.0"
  python_check_max: "3.14"

package:
  name: docker-py
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/docker/docker-${{ version }}.tar.gz
  sha256: cebb93773d334f778e023a7ee352a8d6e13ab1bd3b863a4d4a59dec897df43ac

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - paramiko >=2.4.3
    - python >=${{ python_min }}
    - pywin32 >=304
    - requests >=2.26.0
    - urllib3 >=1.26.0
    - websocket-client >=1.3.0

tests:
  - python:
      imports:
        - docker
        - docker.api
        - docker.auth
        - docker.tls
        - docker.utils
        - docker.utils.ports
        - docker.transport.unixconn
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  summary: A Python library for the Docker Engine API.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/docker
  repository: https://github.com/docker/docker-py
  documentation: https://docker-py.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
    - scopatz
    - mariusvniekerk
