# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.3.4"
  python_check_max: "3.14"

package:
  name: mistune
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mistune/mistune-${{ version }}.tar.gz
  sha256: 58b5c96d6fcb61190dfe5fae498d2b2065f99cf61e9649418fd54cf1ada86dfe

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - mistune = mistune.__main__:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - typing_extensions

tests:
  - python:
      imports: mistune
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - pyproject.toml
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - mistune --help
      - mistune --version | ${{ "grep -iE" if unix else "findstr" }} "${{ version | replace('.', '\\.') }}"
      - coverage run --source=mistune --branch -m pytest -vv --color=yes --tb=long
      - coverage report --show-missing --skip-covered --fail-under=93

about:
  summary: A sane and fast Markdown parser with useful plugins and renderers
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/mistune
  repository: https://github.com/lepture/mistune
  documentation: https://mistune.lepture.com

extra:
  recipe-maintainers:
    - xylar
    - pelson
    - bollwyvl
    - ocefpaf
