# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-cachalot
  version: "2.8.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_cachalot-${{ version }}.tar.gz
  sha256: 30456720ac9f3fabeb90ce898530fe01130c25a1eca911cd016cfaeab251d627

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    #- cachalot
    - pip
  run:
    - python >=${{ python_min }},<4
    - django >=3.2,<5.3

tests:
  - python:
      imports:
        - cachalot
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: Caches your Django ORM queries and automatically invalidates them.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/noripyt/django-cachalot

extra:
  recipe-maintainers:
    - rxm7706
