schema_version: 1

context:
  name: jupyterlab-nebari-mode
  version: 0.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jupyterlab_nebari_mode-${{ version }}.tar.gz
  sha256: 9686e192b8f66939d6117e274e7f7e6af836810238be9163a238fa399921759f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >=3.8

tests:
  - python:
      imports:
        - jupyterlab_nebari_mode
      pip_check: true

about:
  summary: Nebari customizations for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
