# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-health-check
  version: "3.22.0"
  python_min: '3.10'


package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_health_check-${{ version }}.tar.gz
  sha256: b93897c09d47fcc990fff480f28e72e676aee331808c14f0bdcfb8d64de623b1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2
    - flit-scm
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - psutil

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import health_check"
      - pip check

about:
  summary: Monitor the health of your Django app and its connected services.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/codingjoe/django-health-check

extra:
  recipe-maintainers:
    - rxm7706
