# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: get_pypi_latest_version
  package_name: GetPyPiLatestVersion
  version: "0.1.0"
  python_min: '3.10'

package:
  name: ${{ package_name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/SWHL/GetPyPiLatestVersion/archive/v${{ version }}.tar.gz
  sha256: 0d5e6e24da56b627adaf7aa4051ba2dca77f5c5cd082b119b73002857b4e4bf2

build:
  number: 0
  noarch: python
  #script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  #script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script:
    - SETUPTOOLS_SCM_PRETEND_VERSION="{{ version }}"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - get_pypi_latest_version=get_pypi_latest_version.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    #- get_pypi_latest_version
    - pip #<22.0
    - setuptools
    - setuptools-scm
    - requests
    - packaging
    - wheel
  run:
    - python >=${{ python_min }},<4.0
    - requests >=2.28.1
    - packaging
    - setuptools
    - setuptools-scm

tests:
  - python:
      imports:
        - get_pypi_latest_version
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip #<22.0
    script:
      - get_pypi_latest_version --help

about:
  summary: Get the latest version of the specified python package name in the pypi.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/SWHL/GetPyPiLatestVersion

extra:
  recipe-maintainers:
    - rxm7706
