schema_version: 1

context:
  name: reactpy-select
  version: 0.0.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reactpy_select-${{ version }}.tar.gz
  sha256: 992c6614439d60b251de44b493325de34820f86420512fadb95750d108d6933d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0.0
    - reactpy >=1.0.2,<2.0.0

tests:
  - python:
      imports:
        - reactpy_select
      pip_check: true

about:
  summary:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/stevej2608/reactpy-select/blob/master/README.md

extra:
  recipe-maintainers:
    - rxm7706
