{% set name = "dagster-dataform" %}
{% set version = "0.0.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dagster_dataform-{{ version }}.tar.gz
  sha256: e6beb6046e5e1d0fc26222031cc6d702efc0b4bc392ac04e6eeaf3c04a0729ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }},<4.0
    - dagster-webserver >=1.8.12
    - dagster ==1.11.4
    - google-cloud-dataform >=0.6.2

test:
  imports:
    - dagster_dataform
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Dagster integration for Dataform
  license: 'Apache-2.0'
  license_file: LICENSE
  home: https://github.com/dagster-io/community-integrations

extra:
  recipe-maintainers:
    - rxm7706
