# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.6.3"

package:
  name: jupyter-console
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-console/jupyter_console-${{ version }}.tar.gz
  sha256: 566a4bf31c87adbfadf22cdf846e3069b59a71ed5da71d6ba4d8aaad14a53539

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5
  run:
    - python >=${{ python_min }}
    - ipykernel >=6.14
    - ipython
    - jupyter-client >=7.0.0
    - jupyter-core !=5.0.*,>=4.12
    - prompt-toolkit >=3.0.30
    - pygments
    - pyzmq >=17
    - traitlets >=5.4

tests:
  - python:
      imports:
        - jupyter_console
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter terminal console
  description: |
    Jupyter terminal console

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - blink1073
    - Carreau
    - davidbrochart

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: jupyter_console
  cfe-upstream-registry: pypi
  cfe-upstream-name: jupyter-console
  cfe-purls:
    - pkg:conda/jupyter_console@${{ version }}?channel=conda-forge
    - pkg:pypi/jupyter-console@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://jupyter.org
  cfe-import-names: [jupyter_console]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/jupyter_console-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-6.6.3

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T00:28:39Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T00:28:39Z
  cfe-local-build-status: build-clean-test-blocked
  cfe-local-build-datetime: 2026-08-18T00:28:39Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
