# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: bigframes
  version: "2.27.0"
  python_min: '3.9'
  python_max: '4.0'
  python_test_max: '3.13'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/bigframes-${{ version }}.tar.gz
  sha256: 3b9624658f5030b8bcb8d368185cc17bb66fa408f64e9520d1a9a073c0267f75

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - cloudpickle >=2.0.0
    - fsspec >=2023.3.0
    - gcsfs >=2023.3.0
    - geopandas >=0.12.2
    - google-auth >=2.15.0,<3.0dev
    - google-cloud-bigtable >=2.24.0
    - google-cloud-pubsub >=2.21.4
    - google-cloud-bigquery-core >=3.31.0
    - google-cloud-functions >=1.12.0
    - google-cloud-bigquery-connection >=1.12.0
    - google-cloud-iam >=2.12.1
    - google-cloud-resource-manager >=1.10.3
    - google-cloud-storage >=2.0.0
    - numpy >=1.24.0
    - pandas >=1.5.3
    - pandas-gbq >=0.26.1
    - pyarrow >=15.0.2
    - pydata-google-auth >=1.8.2
    - requests >=2.27.1
    - shapely >=1.8.5
    - sqlglot >=23.6.3
    - tabulate >=0.9
    - ipywidgets >=7.7.1
    - humanize >=4.6.0
    - matplotlib-base >=3.7.1
    - db-dtypes >=1.4.2
    - atpublic >=2.3,<6
    - python-dateutil >=2.8.2,<3
    - pytz >=2022.7
    - toolz >=0.11,<2
    - typing_extensions >=4.5.0,<5
    - rich >=12.4.4,<14

tests:
  - python:
      imports:
        - bigframes
        - bigframes_vendored
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_test_max }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script: pip check

about:
  summary: BigQuery DataFrames -- scalable analytics and machine learning with BigQuery
  repository: https://github.com/googleapis/python-bigquery-dataframes
  homepage: https://cloud.google.com/python/docs/reference/bigframes/latest
  description: |
    BigQuery DataFrames provides a Pythonic DataFrame and machine learning (ML) API powered by the BigQuery engine.
      bigframes.pandas provides a pandas-compatible API for analytics.
      bigframes.ml provides a scikit-learn-like API for ML.
  license: BSD-3-Clause AND MIT AND MPL-2.0 AND BSD-4-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - third_party/bigframes_vendored/ibis/LICENSE.txt
    - third_party/bigframes_vendored/cpython/LICENSE
    - third_party/bigframes_vendored/db_benchmark/LICENSE
    - third_party/bigframes_vendored/pandas/LICENSE
    - third_party/bigframes_vendored/geopandas/LICENSE.txt
    - third_party/bigframes_vendored/tpch/LICENSE
    - third_party/bigframes_vendored/google_cloud_bigquery/LICENSE
    - third_party/bigframes_vendored/xgboost/LICENSE
    - third_party/bigframes_vendored/sklearn/COPYING

extra:
  recipe-maintainers:
    - rxm7706
