{% set name = "bmad-method" %}
{% set version = "6.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: f9dfde8a90233e0bcf4c4bde9c41c1dd48789fccd433dedb7e6634890438aa0b

build:
  number: 0
  # Not noarch: wrapper scripts differ between Unix and Windows
  # Prevent nodejs run_exports from pinning to a specific major version;
  # pure-JS packages work with any nodejs >=20.
  ignore_run_exports_from:
    - nodejs

requirements:
  host:
    - nodejs >=20
  run:
    - nodejs >=20

test:
  commands:
    - bmad --help              # [not win]
    - bmad-method --help       # [not win]
    - bmad.bat --help          # [win]
    - bmad-method.bat --help   # [win]

about:
  home: https://github.com/bmad-code-org/BMAD-METHOD
  license: MIT
  license_file: LICENSE
  summary: AI-powered agile development framework with specialized AI agent personas for the full software development lifecycle
  description: |
    BMAD-METHOD (Breakthrough Method for Agile AI-driven Development) is an
    AI-driven agile development framework providing 12+ specialized AI agent
    personas (architect, developer, product manager, QA, etc.) and structured
    workflows across the full software development lifecycle. It supports
    scale-adaptive intelligence for projects from bug fixes to enterprise systems.
  doc_url: https://bmad.io
  dev_url: https://github.com/bmad-code-org/BMAD-METHOD

extra:
  recipe-maintainers:
    - rxm7706
