# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-mongodb-backend
  version: "5.2.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_mongodb_backend-${{ version }}.tar.gz
  sha256: 2ab1e892fbd936a194c5881aa2a4dce3707ece3c4b2f9744233b8ff785263d46

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-requirements-txt >=0.4.1
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=5.2,<6.0
    - pymongo >=4.7,<5.0

tests:
  - python:
      imports:
        - django_mongodb_backend
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Django MongoDB Backend
  homepage: https://www.mongodb.com/docs/languages/python/django-mongodb/current/
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/mongodb/django-mongodb-backend

extra:
  recipe-maintainers:
    - rxm7706
