# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.25.1"

package:
  name: redisvl
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/redisvl/redisvl-${{ version }}.tar.gz
  sha256: 5a651d4be1136e6e82d00c8e16ec02711992a5cf95079d9c50e6129bd960621c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - jsonpath-ng >=1.5.0
    - ml-dtypes <1.0.0,>=0.4.0
    - numpy <3,>=1.26.0
    - pydantic <3,>=2
    - python-ulid >=3.0.0
    - pyyaml <7.0,>=5.4
    - redis-py <8.0,>=5.0
    - tenacity >=8.2.2

tests:
  - python:
      imports:
        - redisvl
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/redis/redis-vl-python
  license: MIT
  license_file: LICENSE
  summary: Python client library and CLI for using Redis as a vector database
  description: |
    Python client library and CLI for using Redis as a vector database
  repository: https://github.com/redis/redis-vl-python
  documentation: https://docs.redisvl.com

extra:
  recipe-maintainers:
    - beenje

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: redisvl
  cfe-upstream-registry: pypi
  cfe-upstream-name: redisvl
  cfe-purls:
    - pkg:conda/redisvl@${{ version }}?channel=conda-forge
    - pkg:pypi/redisvl@${{ version }}
  cfe-upstream-repo: https://github.com/redis/redis-vl-python
  cfe-upstream-homepage: https://github.com/redis/redis-vl-python
  cfe-import-names: [redisvl]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/redisvl-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T12:01:10Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T12:01:10Z
  cfe-local-build-status: build-clean-test-blocked
  cfe-local-build-datetime: 2026-08-18T12:01:10Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
