schema_version: 1

context:
  name: robotcode-language-server
  version: 1.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robotcode_language_server-${{ version }}.tar.gz
  sha256: f1190b5ddf0b1be533f0ac315bca718ffe7577e1c0f298f3fc8fb91b803610cc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - robotframework >=4.1.0
    - robotcode-jsonrpc2 ==1.9.0
    - robotcode-robot ==1.9.0
    - robotcode-analyze ==1.9.0
    - robotcode ==1.9.0

tests:
  - python:
      imports:
        - robotcode_language_server
      pip_check: true

about:
  summary: RobotCode Language Server for Robot Framework
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/robotcodedev/robotcode

extra:
  recipe-maintainers:
    - rxm7706
