{% set name = "azure-storage-file-datalake" %}
{% set version = "12.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 34813c6f3e9bf1636898cec62529dd2ced189cd2c677160ec69ef88c3b72da7f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - typing_extensions >=4.6.0
    - python >={{ python_min }}
    - azure-core >=1.37.0
    - azure-storage-blob >=12.30.0
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.storage
    - azure.storage.filedatalake

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  doc_url: https://aka.ms/azsdk-python-storage-filedatalake-ref

extra:
  recipe-maintainers:
    - dhirschfeld
