# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-read-only
  version: "1.21.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_read_only-${{ version }}.tar.gz
  sha256: 5ffc75ccc8a9d9b7b587b074681472fd8edc49624cf0f537812d839a993182c4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - pip
  run:
    - python >=${{ python_min }},<4
    - django >=4.2

tests:
  - python:
      imports:
        - django_read_only
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Disable Django database writes.
  homepage: https://github.com/adamchainz/django-read-only
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
