{% set name = "vizro-ai" %}
{% set version = "0.3.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vizro_ai-{{ version }}.tar.gz
  sha256: 8972fec0f00f48307ee185954852fa15851d2ce326580c4e82b5cbc0544bd3f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.14
    - pandas
    - tabulate
    - openai >=1.0.0
    - langchain >=0.3.0
    - langgraph >=0.1.2
    - python-dotenv >=1.0.0
    - vizro >=0.1.32
    - pydantic >=2.7.0
    - langchain-openai
    - black
    - autoflake

test:
  imports:
    - vizro_ai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Vizro-AI is a tool for generating data visualizations
  home: https://vizro.mckinsey.com/
  dev_url: https://github.com/mckinsey/vizro
  doc_url: https://vizro.readthedocs.io/en/stable/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
