{% set name = "writefreely" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/writefreely/writefreely/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 284fbd70908b7461f3ca4067823ee099bffb2098dc6c5958767d9a8dad810e15

build:
  number: 0
  # Windows CGO builds are complex; start with Unix only
  skip: true  # [win]

requirements:
  build:
    # CGO is required for SQLite support
    - {{ compiler('cgo') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - go-licenses
  host:
    - sqlite
  run:
    - sqlite

test:
  commands:
    - writefreely --version
    - writefreely --help

about:
  home: https://writefreely.org
  summary: A clean, Markdown-based publishing platform made for writers
  description: |
    WriteFreely is a clean, minimalist publishing platform made for writers.
    Start a blog, share knowledge within your organization, or build a community
    around the shared act of writing. Features include:
    - Distraction-free writing with auto-save
    - Markdown support
    - ActivityPub federation (connect with Mastodon, etc.)
    - SQLite or MySQL database support
    - Multi-user/community support
    - Customizable themes
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - library_licenses/
  dev_url: https://github.com/writefreely/writefreely
  doc_url: https://writefreely.org/docs

extra:
  recipe-maintainers:
    # Add your GitHub username here
    - YOUR_GITHUB_USERNAME
