{% set name = "reflex" %}
{% set version = "0.8.16" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/reflex-dev/reflex/archive/v{{ version }}.tar.gz
  sha256: 506bb10136d0f5d2bdc918723176f0f5daaa7073079dba1d8d0b0844df4b7dc1

build:
  entry_points:
    - reflex = reflex.reflex:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - alembic >=1.15.2,<2.0
    - click >=8.2
    - granian >=2.5.5
    - httpx >=0.23.3,<1.0
    - packaging >=24.2,<26
    - platformdirs >=4.3.7,<5.0
    - psutil >=7.0.0,<8.0
    - pydantic >=1.10.21,<3.0
    - python-multipart >=0.0.20,<1.0
    - python-socketio >=5.12.0,<6.0
    - redis-py >=5.2.1,<7.0
    - reflex-hosting-cli >=0.1.55
    - rich >=13,<15
    - sqlmodel >=0.0.27,<0.1
    - starlette >=0.47.0
    - typing_extensions >=4.13.0
    - wrapt >=1.17.0,<2.0

test:
  imports:
    - reflex
  commands:
    - pip check
    - reflex --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Web apps in pure Python.
  home: https://reflex.dev/
  dev_url: https://github.com/reflex-dev/reflex
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
