# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: reflex
  version: "0.8.16"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reflex-${{ version }}.tar.gz
  sha256: e5edd163e82359f2aa2aa717bec0bb87b8e1f5843fa57a7f5eaeafceb25b9203

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - reflex = reflex.reflex:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
    - click >=8.2
    - httpx >=0.25.1,<1.0
    - packaging >=24.2
    - platformdirs >=3.10.0,<5.0
    - rich >=13,<15
    - wrapt >=1.17.0,<2.0
    - plotly
    - python-socketio >=5.12.0,<6.0
    - starlette >=0.47.0
    - ruff
  run:
    - python >=${{ python_min }},<4
    - alembic >=1.15.2,<2.0
    - click >=8.2
    - granian >=2.5.5
    - httpx >=0.23.3,<1.0
    - packaging >=24.2,<26
    - platformdirs >=4.3.7,<5.0
    - psutil >=7.0.0,<8.0
    - pydantic >=1.10.21,<3.0
    - python-multipart >=0.0.20,<1.0
    - python-socketio >=5.12.0,<6.0
    - redis-py >=5.2.1,<7.0
    - reflex-hosting-cli >=0.1.55
    - rich >=13,<15
    - sqlmodel >=0.0.27,<0.1
    - starlette >=0.47.0
    - typing_extensions >=4.13.0
    - wrapt >=1.17.0,<2.0

tests:
  - python:
      imports:
        - reflex
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - reflex --help

about:
  homepage: https://reflex.dev/
  repository: https://github.com/reflex-dev/reflex
  summary: Web apps in pure Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
