# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.3.0"

package:
  name: dspy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dspy/dspy-${{ version }}.tar.gz
  sha256: 39aa9531391accda8acd7903b52f3c9d2efe462d4bab0c2256db5352e7392754

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77.0.1
  run:
    - python >=${{ python_min }}
    - openai >=1.66.2
    - regex >=2023.10.3
    - orjson >=3.9.0
    - tqdm >=4.66.1
    - requests >=2.31.0
    - pydantic >=2.0
    - litellm >=1.65.8
    - diskcache >=5.6.0
    - json-repair >=0.54.2
    - tenacity >=8.2.3
    - anyio
    - cachetools >=5.5.0
    - cloudpickle >=3.1.2
    - gepa ==0.1.1
    - if: win
      then:
        - litellm

tests:
  - python:
      imports:
        - dspy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/stanfordnlp/dspy
  license: MIT
  license_file: LICENSE
  summary: DSPy
  description: |
    DSPy: The framework for programming—not prompting—foundation models

extra:
  feedstock-name: dspy
  recipe-maintainers:
    - mukhery


#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: dspy
  cfe-upstream-registry: pypi
  cfe-upstream-name: dspy
  cfe-purls:
    - pkg:conda/dspy@${{ version }}?channel=conda-forge
    - pkg:pypi/dspy@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/stanfordnlp/dspy
  cfe-import-names: [dspy]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: pending-submission-to-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/dspy-ai-feedstock
  cfe-forge-recipe-updates-needed: 
    - version-update-to-3.3.0

  cfe-forge-blocker-list:
    - license-unresolved:REPLACE_LICENSE

  cfe-last-checked: 2026-08-17T01:18:48Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T01:18:48Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-17T01:18:48Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
