{% set name = "sentry-sdk" %}
{% set version = "2.71.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7beb27a22f06396f3a05510c3da6ea10e1c79e02e859993c27ce4ff074e296d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - urllib3 >=1.25.7
    - certifi

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - sentry_sdk
  commands:
    - pip check

about:
  home: https://github.com/getsentry/sentry-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python SDK for Sentry.io
  description: |
    The official Python SDK for Sentry.io 
  doc_url: https://docs.sentry.io/platforms/python/
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - rxm7706
    - alippai
    - dgasmith
    - djsutherland
