{% set name = "mkdocs-jupyter" %}
{% set version = "0.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0e9272ff4947e0ec683c92423a4bfb42a26477c103ab1a6ab8277e2dcc8f7afe

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - hatch >=1
  run:
    - python >={{ python_min }}
    - nbconvert <8,>=7.2.9
    - mkdocs <2,>=1.4.0
    - mkdocs-material >9.0.0
    - jupytext <2,>1.13.8
    - pygments >2.12.0
    - ipykernel <7.0.0,>6.0.0

test:
  imports:
    - mkdocs_jupyter
    - mkdocs_jupyter.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/danielfrg/mkdocs-jupyter
  summary: Use Jupyter Notebooks in mkdocs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cpcloud
    - cwognum
