# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: langchain-text-splitters
  version: "0.3.11"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_text_splitters-${{ version }}.tar.gz
  sha256: 7a50a04ada9a133bbabb80731df7f6ddac51bc9f1b9cab7fa09304d71d38a6cc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - langchain-core <2.0.0,>=0.3.75
  run_constraints:
    - lxml >=4.9.3,<6.0.0
    - beautifulsoup4 >=4.12.3,<5.0.0

tests:
  - python:
      imports:
        - langchain_text_splitters
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/langchain-ai/langchain
  documentation: https://github.com/langchain-ai/langchain/tree/master/libs/text-splitters
  summary: LangChain text splitting utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
    - rxm7706
