schema_version: 1

context:
  name: sqlfluff
  version: "4.0.4"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqlfluff-${{ version }}.tar.gz
  sha256: 3f443e18b49ec7062132ae0ef0e2f6e56fc485a2044e9f09ea12a17872efd987

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sqlfluff = sqlfluff.cli.commands:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - platformdirs
    - chardet
    - click <8.4.0
    - colorama >=0.3
    - diff-cover >=2.5.0
    - jinja2
    - pathspec
    - pytest
    - pyyaml >=5.1
    - regex
    - tblib
    - tomli
    - tqdm

tests:
  - python:
      imports:
        - sqlfluff
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - test
    requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - sqlfluff --help
      - pytest -vvv --capture=tee-sys -k "not test_rules_test_case_has_variable_introspection " test

about:
  summary: The SQL Linter for Humans
  license: MIT
  license_file: LICENSE.md
  description: |
    SQLFluff is a dialect-flexible and configurable SQL linter. Designed
    with ELT applications in mind, SQLFluff also works with Jinja
    templating and dbt. SQLFluff will auto-fix most linting errors,
    allowing you to focus your time on what matters.


  homepage: https://www.sqlfluff.com/
  repository: https://github.com/sqlfluff/sqlfluff
  documentation: https://docs.sqlfluff.com/en/stable/index.html

extra:
  recipe-maintainers:
    - svengiegerich
    - borchero
    - thewchan
    - rxm7706
