# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: robotframework-requests
  version: "0.9.7"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robotframework-requests-${{ version }}.tar.gz
  sha256: c2a2839813e1dc6b299e7d336314c9982c225c5b7e001ec893dc3555c6a95740

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - robotframework
    - requests

tests:
  - python:
      imports:
        - RequestsLibrary
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: RequestsLibrary is a Robot Framework test library that uses the Requests HTTP client.
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/MarketSquare/robotframework-requests

extra:
  recipe-maintainers:
    - daniel88ferreira
    - rxm7706
