# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-http-compression
  version: "1.1.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_http_compression-${{ version }}.tar.gz
  sha256: c146f3c3c6bb122f03914f2c4d3f6cd5db0b452c13f0d7314afc72a821b59d5b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - pip
  run:
    - python >=${{ python_min }},<4
    - asgiref >=3.6
    - backports.zstd >=1
    - django >=4.2
    - typing_extensions >=4.1

tests:
  - python:
      imports:
        - django_http_compression
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/adamchainz/django-http-compression
  summary: Django middleware for compressing HTTP responses with Zstandard, Brotli, or Gzip.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
