{% set name = "drf-spectacular" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drf_spectacular-{{ version }}.tar.gz
  sha256: 53e79e7ba00e240441b63c32273754a5368e4c2ab44a19f2595277cc1cd559c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=2.2
    - djangorestframework >=3.10.3
    - uritemplate >=2.0.0
    - pyyaml >=5.1
    - jsonschema >=2.6.0
    - inflection >=0.3.1
    - typing-extensions

test:
  imports:
    - drf_spectacular
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tfranzel/drf-spectacular
  summary: Sane and flexible OpenAPI 3 schema generation for Django REST framework
  dev_url: https://github.com/tfranzel/drf-spectacular
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - MichelML
