schema_version: 1

context:
  name: nebari-plugin-ray
  version: 0.0.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/nebari_plugin_ray-${{ version }}.tar.gz
  sha256: 0fafb13558c499d323064c041748bfaa1f9d8bbfb573c2871e5fb56d617d68ab

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - nebari

tests:
  - python:
      imports:
        - nebari_plugin_ray
      pip_check: true

about:
  summary: MetroStar Onyx - Ray plugin for Nebari platform
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/MetroStar/nebari-ray

extra:
  recipe-maintainers:
    - rxm7706
