{% set name = "azure-ai-ml" %}
{% set version = "1.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 07445f7336fecbba207a216120d68f2499c25d96f0b1b3b64bf14ac5d2197fda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyyaml >=5.1.0
    - msrest >=0.6.18
    - azure-core >=1.23.0
    - azure-mgmt-core >=1.3.0
    - marshmallow >=3.5
    - jsonschema >=4.0.0
    - tqdm
    - strictyaml
    - colorama
    - pyjwt
    - azure-storage-blob >=12.10.0
    - azure-storage-file-share
    - azure-storage-file-datalake >=12.2.0
    - pydash >=6.0.0
    - isodate
    - azure-common >=1.1
    - typing_extensions
    - azure-monitor-opentelemetry
    # azure-ai-ml 1.16.0 requires opencensus-ext-logging, which is not installed.
    #- opencensus-ext-logging

test:
  imports:
    - azure.ai.ml
    - azure.ai.ml._arm_deployments
  commands:
    #- pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Machine Learning Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-python
  license: Apache-2.0
  license_file: NOTICE.txt

extra:
  recipe-maintainers:
    - rxm7706
