# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: airflow-provider-xlsx
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/airflow-provider-xlsx-${{ version }}.tar.gz
  sha256: 63596c14ceb923fee1cacb1d65df6de7bf3b36b6d0d969dbbf27bdd90a1c7c72

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.0
    - openpyxl
    - pyarrow
    - xlrd

tests:
  - python:
      imports:
        - xlsx_provider
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Airflow operators for reading and writing XLSX files
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/andreax79/airflow-provider-xlsx

extra:
  recipe-maintainers:
    - xylar
    - rxm7706
