# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.3.0"

package:
  name: gmp
  version: ${{ version }}

source:
  url:
    - https://gmplib.org/download/gmp/gmp-${{ version }}.tar.xz
    - https://ftp.gnu.org/gnu/gmp/gmp-${{ version }}.tar.xz
  sha256: a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898

build:
  number: 3
  script: build

requirements:
  build:
    - gnuconfig
    - if: unix
      then:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - m4
        - make
    - if: win
      then:
        - ${{ stdlib('m2w64_c') }}
        - ${{ compiler('m2w64_c') }}
        - m2-m4
        - m2-make
        - m2-base
        - m2-diffutils
        - gendef
  run_exports:
    - ${{ pin_subpackage('gmp') }}
  run_constraints:
    - if: win
      then: mpir <0.0a0

tests:
  - package_contents:
      include:
        - gmp.h
      lib:
        - if: unix
          then:
            - gmp
            - gmpxx
      files:
        exists:
          - if: win
            then:
              - Library/bin/libgmp-10.dll
              - Library/lib/libgmp.dll.a
              - Library/lib/gmp.lib
        not_exists:
          - if: unix
            then:
              - lib/libgmp.a
              - lib/libgmpxx.a
  - if: unix
    then:
      files:
        recipe:
          - test.c
      requirements:
        build:
          - ${{ compiler('c') }}
          - ${{ stdlib('c') }}
      script:
        - $CC -I$PREFIX/include -L$PREFIX/lib test.c -lgmp -Wl,-rpath,$PREFIX/lib -o test.out
        - if: build_platform == target_platform
          then: ./test.out
  - if: win
    then:
      files:
        recipe:
          - test.c
      requirements:
        build:
          - ${{ compiler('c') }}
          - ${{ stdlib('c') }}
      script:
        - cl test.c /I%LIBRARY_INC% %LIBRARY_LIB%\gmp.lib /Fe:test.exe
        - test.exe
        # Give Windows time to release the executable before rattler-build removes the test directory.
        - ping 127.0.0.1 -n 3 > nul
        - del /F /Q test.exe test.obj

about:
  homepage: http://gmplib.org/
  repository: https://gmplib.org/repo/gmp/
  license: GPL-2.0-or-later OR LGPL-3.0-or-later
  license_file: COPYING.LESSERv3
  summary: The GNU multiprecision library.

extra:
  recipe-maintainers:
    - asmeurer
    - isuruf
    - jakirkham
