{% set name = "grpc-google-iam-v1" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grpc_google_iam_v1-{{ version }}.tar.gz
  sha256: 879ac4ef33136c5491a6300e27575a9ec760f6cdf9a2518798c1b8977a5dc389

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - grpcio >=1.44.0,<2.0.0
    - googleapis-common-protos >=1.56.0,<2.0.0
    - googleapis-common-protos-grpc
    - protobuf >=3.20.2,<7.0.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - google.iam.v1
    - google.iam.v1.iam_policy_pb2
    - google.iam.v1.logging
    - google.iam.v1.logging.audit_data_pb2
    - google.iam.v1.policy_pb2
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/grpc-google-iam-v1
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: GRPC library for the google-iam-v1 service
  description: |
    grpc-google-iam-v1 is the IDL-derived library for the
    google-iam v1 service in the googleapis repository.

  doc_url: https://github.com/googleapis/google-cloud-python/blob/main/packages/grpc-google-iam-v1/README.rst
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/grpc-google-iam-v1

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
