# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: agents-at-scale-ark
  version: "0.1.43"
  python_min: '3.12'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mckinsey/agents-at-scale-ark/archive/v${{ version }}.tar.gz
  sha256: 3a06157d62b413adb1a71c4da1973ca5f0925aac0d7b9d6f9e8a940b79b1d906

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ark-evaluator = evaluator.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4
    - fastapi >=0.104.0
    - uvicorn >=0.24.0
    - gunicorn >=21.2.0
    - pydantic >=2.5.0
    - aiohttp >=3.9.0
    - python-kubernetes >=30.1.0
    - langfuse-python >=2.0.0,<3.0.0
    - ragas >=0.3.1
    - openai >=1.0.0
    - langchain-openai >=0.1.0
    - langchain-anthropic >=0.1.0
    - langchain-google-genai >=1.0.0
    - langchain-community >=0.2.0
    - datasets >=2.14.0
    - pandas >=2.0.0
    - nest-asyncio >=1.5.0
    - pillow >=10.0.0
    - ark-sdk

tests:
  - python:
      imports:
        - ark_evaluator
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - ark-evaluator --help

about:
  summary: Evaluator for Ark - AI-powered query evaluation service
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/mckinsey/agents-at-scale-ark

extra:
  recipe-maintainers:
    - rxm7706
