# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.1.0"

package:
  name: flexicon
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flexicon/flexicon-${{ version }}.tar.gz
  sha256: ab096b3c800abfbead6829c9de2f5e5fd7782b3851b14f6703e2013876084c4a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - flexicon
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/bitlang/flexicon
  license: MIT
  license_file: LICENSE
  summary: A lightweight regex-based lexing framework
  description: |
    A lightweight regex-based lexing framework

extra:
  recipe-maintainers:
    - rxm7706

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: flexicon
  cfe-upstream-registry: pypi
  cfe-upstream-name: flexicon
  cfe-purls:
    - pkg:conda/flexicon@${{ version }}?channel=conda-forge
    - pkg:pypi/flexicon@${{ version }}
  cfe-upstream-repo: https://github.com/bitlang/flexicon
  cfe-upstream-homepage: https://github.com/bitlang/flexicon
  cfe-import-names: [flexicon]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: pending-submission-to-conda-forge
  cfe-on-conda-forge-feedstock: none
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-16T17:32:37Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-16T17:32:37Z
  cfe-local-build-status: not-attempted
  cfe-local-build-datetime: none
  cfe-local-build-platform: none
  cfe-local-build-tool: none
####
# CFE comments
# Header:
#    # P4 Create-recipe local-only. flexicon.
####
