{% set name = "pycodestyle" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycodestyle-{{ version }}.tar.gz
  sha256: c4b5b517d278089ff9d0abdec919cd97262a3367449ea1c8b49b91529167b783

build:
  entry_points:
    - pycodestyle = pycodestyle:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pycodestyle
  commands:
    - pip check
    - pycodestyle --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python style guide checker
  doc_url: https://pycodestyle.readthedocs.io/
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jjhelmus
    - pmlandwehr
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf