# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.14.0"

package:
  name: pycodestyle
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pycodestyle/pycodestyle-${{ version }}.tar.gz
  sha256: c4b5b517d278089ff9d0abdec919cd97262a3367449ea1c8b49b91529167b783

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pycodestyle
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pycodestyle.pycqa.org/
  license: MIT
  license_file: LICENSE
  summary: Python style guide checker
  description: |
    Python style guide checker

extra:
  recipe-maintainers:
    - jjhelmus
    - pmlandwehr
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: pycodestyle
  cfe-upstream-registry: pypi
  cfe-upstream-name: pycodestyle
  cfe-purls:
    - pkg:conda/pycodestyle@${{ version }}?channel=conda-forge
    - pkg:pypi/pycodestyle@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://pycodestyle.pycqa.org/
  cfe-import-names: [pycodestyle]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/pycodestyle-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-2.14.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T03:27:22Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T03:27:22Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T03:27:22Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
