# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pygwalker
  version: "0.4.9.15"
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 747b726e8acd35f20aef8ee74652a948575fb70b5fa8f816a692c9870d0ab0cb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pygwalker = bin.pygwalker_command:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - python >=${{ python_min }},<4
    - jinja2
    - ipython
    - astor
    - typing_extensions
    - ipywidgets
    - pydantic
    - psutil
    - python-duckdb >=0.10.1,<2.0.0
    - pyarrow
    - sqlglot >=23.15.8
    - requests
    - arrow
    - sqlalchemy
    - gw-dsl-parser ==0.1.49.1
    - appdirs
    - analytics-python ==2.2.3
    - pandas
    - pytz
    - kanaries-track ==0.0.5
    - cachetools
    - packaging
    - numpy
    - ipylab <=1.0.0
    - python-quickjs
    - traitlets
    - anywidget

tests:
  - python:
      imports:
        - pygwalker
      pip_check: false  # Disabled: wasmtime-py package name mismatch with PyPI
      # gw-dsl-parser 0.1.49.1 has requirement wasmtime>=12.0.0, but you have wasmtime 0.0.0.
  - requirements:
      run:
        - pip
    script:
      - pygwalker --help

about:
  homepage: https://kanaries.net/pygwalker
  repository: https://github.com/Kanaries/pygwalker
  summary: 'pygwalker: turn your data into an interactive UI for data exploration and visualization'
  description: |
    PyGWalker is a Python library that converts pandas DataFrames into interactive
    visual analysis interfaces. It integrates Jupyter Notebooks with Graphic Walker,
    an open-source alternative to Tableau.

    Features:
    - Interactive visualization through drag-and-drop operations
    - Data exploration tools with filtering, zooming, and panning
    - Multiple chart types (bar, line, scatter, etc.)
    - Visual data transformation tools
    - Seamless integration with Jupyter, Colab, Kaggle, and Streamlit
    - Export functionality for charts (PNG, SVG)
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://docs.kanaries.net/pygwalker

extra:
  recipe-maintainers:
    - gabrielcnr
    - Asm-Def
    - longxiaofei
    - rxm7706
