# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: reflex-hosting-cli
  version: "0.1.58"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reflex_hosting_cli-${{ version }}.tar.gz
  sha256: c903aa44944a724fbdd0a6cc66bd174f9be32967daaf6092b7204a1ab3a9272f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4
    - click >=8.2
    - httpx >=0.25.1,<1.0
    - packaging >=24.2
    - platformdirs >=3.10.0,<5.0
    - rich >=13,<15

tests:
  - python:
      imports:
        - rich
      pip_check: true

about:
  homepage: https://github.com/reflex-dev/reflex
  summary: Reflex Hosting CLI
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
