# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: codefind
  version: "0.1.7"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/codefind-${{ version }}.tar.gz
  sha256: a2ec8a2c0180399ea838dfcdcc344ca89f97b8aa293bc17b22b2c023aba06fbc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - codefind
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Find code objects and their referents
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/breuleux/jurigged

extra:
  recipe-maintainers:
    - rxm7706
