{% set name = "dagster-gemini" %}
{% set version = "0.0.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dagster_gemini-{{ version }}.tar.gz
  sha256: e7517bfd3085079ec0d207d43c31add58c8630e398411b75f002ee635170d590

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }},<4.0
    - dagster >=1.8.0
    - google-generativeai >=0.8.3

test:
  imports:
    - dagster_gemini
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Dagster integration with Gemini
  license: 'Apache-2.0'
  license_file: LICENSE
  home: https://github.com/dagster-io/community-integrations

extra:
  recipe-maintainers:
    - rxm7706
