# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: reactpy
  version: "1.1.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reactpy-${{ version }}.tar.gz
  sha256: 16eaf8cca9d05f9947770e00f6cc1e19ea8079a43284a8933b283bcc495eb5db
  target_directory: src/py/reactpy

build:
  number: 0
  noarch: python
  script:
#    - cd src/py/reactpy
#    - cd ..
#    - cd ..
    - ${{ PYTHON }} -m pip install src/py/reactpy -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-build-scripts >=0.0.4
    - pip
    - nodejs >18.0,<19.0
  run:
    - python >=${{ python_min }},<4.0
    - exceptiongroup >=1.0
    - typing_extensions >=3.10
    - mypy_extensions >=0.4.3
    - anyio >=3
    - jsonpatch >=1.32
    - python-fastjsonschema >=2.14.5
    - requests >=2
    - colorlog >=6
    - asgiref >=3
    - lxml >=4

tests:
  - python:
      imports:
        - reactpy
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - LICENSE
        - pyproject.toml
        - README.md
        - src
    requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - pip list | grep -i {{ name }} | grep {{ version }}
      - echo $PWD

about:
  summary: Reactive user interfaces with pure Python
  license: MIT
  license_file: LICENSE
  repository: https://github.com/reactive-python/reactpy

extra:
  recipe-maintainers:
    - rxm7706
