{% set name = "django-countries" %}
{% set version = "7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b8413065160bc93efe1293d746bbde32951d9a1fe7e44f1fe2add1bebbb6962f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=48,<81.0.0
    - wheel >=0.29.0
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }}
    - django >=3.2,<5.0
    - asgiref
    - typing-extensions

test:
  imports:
    - django_countries
    - django_countries.graphql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SmileyChris/django-countries/
  summary: Provides a country field for Django models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rxm7706
