# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: guidance-stitch
  version: "0.1.5"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/guidance_stitch-${{ version }}.tar.gz
  sha256: 2a0d0ede865db387857d494a7bcb1a903621c13f571869cde1109c2c5569cd95

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.21.1
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.8.3
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - ipywidgets >=8.0.0

tests:
  - python:
      imports:
        - stitch
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Bidirectional comms for Jupyter and JavaScript.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/guidance-ai/guidance

extra:
  recipe-maintainers:
    - rxm7706
