{% set python_min = "3.12" %}
{% set name = "pyasyncore" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyasyncore-{{ version }}.tar.gz
  sha256: dd483d5103a6d59b66b86e0ca2334ad43dca732ff23a0ac5d63c88c52510542e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13

test:
  imports:
    - asyncore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonrob/pyasyncore
  summary: Make asyncore available for Python 3.12 onwards
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
