{% set name = "misata" %}
{% set version = "0.1.0b0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/misata-{{ version }}.tar.gz
  sha256: 23633bbf28e9920a7ea211c310280b3f77aba8fbad8f770fc2800f16b5aa422d

build:
  entry_points:
    - misata = misata.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.0.0
    - numpy >=1.24.0
    - pydantic >=2.0.0
    - click >=8.1.0
    - pyyaml >=6.0
    - rich >=13.0.0
    - groq >=0.4.0
    - fastapi >=0.109.0
    - uvicorn >=0.27.0
    - python-multipart >=0.0.6
    - simpleeval >=0.9.0
    - scipy >=1.10.0

test:
  imports:
    - misata
  commands:
    - pip check
    - misata --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: AI-Powered Synthetic Data Engine - Generate realistic multi-table datasets from natural language
  license: MIT
  license_file: LICENSE
  home: https://github.com/rasinmuhammed/misata

extra:
  recipe-maintainers:
    - rxm7706
