# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ai-storyteller-cli
  version: "0.3.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ai_storyteller_cli-${{ version }}.tar.gz
  sha256: 841ba91d6f81d088f77c663433912c2cfdd61cdaf52f0a8d9fdd49231023d967

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - storyteller = storyteller.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - typer >=0.9.0
    - rich >=13.0.0
    - python-dotenv >=1.0.0
    - google-generativeai >=0.3.0
    - openai >=1.0.0
    - anthropic >=0.3.0
    - mcp >=0.1.0
    - pydantic >=2.0.0
    - textual

tests:
  - python:
      imports:
        - storyteller
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - storyteller --help

about:
  summary: AI Storyteller and DM Assistant
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/ai-storyteller-cli/


extra:
  recipe-maintainers:
    - rxm7706
