{% set name = "fastmcp" %}
{% set version = "2.14.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastmcp-{{ version }}.tar.gz
  sha256: bd23d1b808b6f446444f10114dac468b11bfb9153ed78628f5619763d0cf573e

build:
  entry_points:
    - fastmcp = fastmcp.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - uv-dynamic-versioning >=0.7.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - python-dotenv >=1.1.0
    - exceptiongroup >=1.2.2
    - httpx >=0.28.1
    - mcp >=1.24
    - openapi-pydantic >=0.5.1
    - platformdirs >=4.0.0
    - pydocket >=0.15.5
    - rich >=13.9.4
    - cyclopts >=4.0.0
    - authlib >=1.6.5
    - pydantic >=2.11.7
    - pyperclip >=1.9.0
    - py-key-value-aio >=0.3.0,<0.4.0
    - uvicorn >=0.35
    - websockets >=15.0.1
    - jsonschema-path >=0.3.4
    # py-key-value-aio[disk]
    - diskcache >=5.6.0
    - pathvalidate >=3.3.1
    # py-key-value-aio[memory]
    - cachetools >=6.0.0
    # py-key-value-aio[keyring]
    - keyring >=25.6.0
  run_constraints:
    - openai >=1.102.0

test:
  imports:
    - fastmcp
  commands:
    - pip check
    - fastmcp --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: The fast, Pythonic way to build MCP servers and clients.
  home: https://github.com/jlowin/fastmcp
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
