# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: fastmcp
  version: "2.13.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fastmcp-${{ version }}.tar.gz
  sha256: 57f7b7503363e1babc0d1a13af18252b80366a409e1de85f1256cce66a4bee35

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fastmcp = fastmcp.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning >=0.7.0
    - pip
  run:
    - python >=${{ python_min }},<4
    - python-dotenv >=1.1.0
    - exceptiongroup >=1.2.2
    - httpx >=0.28.1
    - mcp >=1.17.0,<2.0.0
    - openapi-pydantic >=0.5.1
    - platformdirs >=4.0.0
    - rich >=13.9.4
    - cyclopts >=3.0.0
    - authlib >=1.5.2
    - pydantic >=2.11.7
    # "pydantic[email]>=2.11.7",
    # https://github.com/jlowin/fastmcp/blob/v2.13.0/pyproject.toml#L16
    # https://github.com/pydantic/pydantic/blob/main/pyproject.toml#L56
    - email-validator >=2.0.0
    - pyperclip >=1.9.0
    - openapi-core >=0.19.5
    - py-key-value-aio >=0.2.6,<0.3.0
    # "py-key-value-aio[disk,keyring,memory]>=0.2.6,<0.3.0",
    # https://github.com/jlowin/fastmcp/blob/v2.13.0/pyproject.toml#L19
    # py-key-value-aio[disk]
    # https://github.com/strawgate/py-key-value/blob/main/key-value/key-value-aio/pyproject.toml#L36
    - diskcache >=5.6.0
    - pathvalidate >=3.3.1
    # py-key-value-aio[memory]
    # https://github.com/strawgate/py-key-value/blob/main/key-value/key-value-aio/pyproject.toml#L35
    - cachetools >=6.0.0
    # py-key-value-aio[keyring]
    # https://github.com/strawgate/py-key-value/blob/main/key-value/key-value-aio/pyproject.toml#L44
    - keyring >=25.6.0
    - websockets >=15.0.1

tests:
  - python:
      imports:
        - fastmcp
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - fastmcp --help

about:
  summary: The fast, Pythonic way to build MCP servers and clients.
  homepage: https://github.com/jlowin/fastmcp
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
