# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: fastmcp
  version: "2.12.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fastmcp-${{ version }}.tar.gz
  sha256: c7d6ec0fe3fa8d10061d08b40ebf6a4f916034a47ff3188dfd81c25e143ac18e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fastmcp = fastmcp.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning >=0.7.0
    - pip
  run:
    - python >=${{ python_min }},<4
    - python-dotenv >=1.1.0
    - exceptiongroup >=1.2.2
    - httpx >=0.28.1
    - mcp >=1.12.4,<2.0.0
    - openapi-pydantic >=0.5.1
    - rich >=13.9.4
    #- typer >=0.15.2
    #- websockets >=14.0
    - cyclopts >=3.0.0
    - authlib >=1.5.2
    - pydantic >=2.11.7
    - pyperclip >=1.9.0
    - openapi-core >=0.19.5
    - openai >=1.95.1

tests:
  - python:
      imports:
        - fastmcp
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - fastmcp --help

about:
  summary: The fast, Pythonic way to build MCP servers.
  homepage: https://github.com/jlowin/fastmcp
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
