# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: opentelemetry-instrumentation-aiohttp-client
  version: 0.65b0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_aiohttp_client-${{ version }}.tar.gz
  sha256: 85906a2806ee5641756b5c33274e9aa75c3cc2441e3b830aa5804cf0e1fa9dd1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - aiohttp ~=3.0
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.65b0
    - opentelemetry-semantic-conventions ==0.65b0
    - opentelemetry-util-http ==0.65b0
    - wrapt <3.0.0,>=1.0.0
    # - opentelemetry-instrumentation-aiohttp-client
    # - opentelemetry-instrumentation-aiohttp-client
    # - opentelemetry-instrumentation-aiohttp-client
    # - opentelemetry-instrumentation-aiohttp-client
    # - http-server-mock
    # - opentelemetry-instrumentation-aiohttp-client
    # - http-server-mock
    # - opentelemetry-instrumentation-aiohttp-client
    # - http-server-mock
    # - opentelemetry-instrumentation-aiohttp-client
    # - http-server-mock
    # - opentelemetry-instrumentation-aiohttp-client
    # - http-server-mock

tests:
  - python:
      imports:
        - opentelemetry.instrumentation.aiohttp_client
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: OpenTelemetry aiohttp client instrumentation
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiohttp-client

extra:
  recipe-maintainers:
    - twoodwark
    - mariusvniekerk
