# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.9.0"

package:
  name: haversine
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/h/haversine/haversine-${{ version }}.tar.gz
  sha256: 1103d7e1f0f108c25b31b63452c54d9d6f29389a70de7dd75fd4b908329b6fcf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - haversine
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/mapado/haversine
  license: MIT
  license_file: LICENSE
  summary: Calculate the distance between 2 points on Earth.
  description: |
    Calculate the distance between 2 points on Earth.

extra:
  recipe-maintainers:
    - ocefpaf

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: haversine
  cfe-upstream-registry: pypi
  cfe-upstream-name: haversine
  cfe-purls:
    - pkg:conda/haversine@${{ version }}?channel=conda-forge
    - pkg:pypi/haversine@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/mapado/haversine
  cfe-import-names: [haversine]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/haversine-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-2.9.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T10:56:41Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T10:56:41Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-17T10:56:41Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
