{% set name = "interpret-community" %}
{% set version = "0.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/interpret_community-{{ version }}.tar.gz
  sha256: 23fc09bc17f23da786927f178f999c221299d89303a8186acdfb7cadc90ab41b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scipy
    - ml-wrappers >=0.6.0,<0.7.dev0
    - scikit-learn
    - packaging
    - interpret-core >=0.1.20,<=0.6.9
    - shap >=0.20.0,<=0.46.0
    - raiutils ~=0.4.0
    # - tensorflow 
    # - pyyaml 
    # - lime >=0.2.0.0
    # - lightgbm 
    # - keras 
    # - hdbscan 

test:
  imports:
    - interpret_community
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/interpretml/interpret-community
  summary: Microsoft Interpret Extensions SDK for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
