# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: langsmith
  version: "0.4.31"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langsmith-${{ version }}.tar.gz
  sha256: 5fb3729e22bd9a225391936cb9d1080322e6c375bb776514af06b56d6c46ed3e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - pydantic >=1,<3
    # The following is only for py>=312, but we require it always to stay noarch
    - pydantic >=2.7.4,<3.0.0
    - requests >=2.0.0
    - orjson >=3.9.14
    - httpx >=0.23.0,<1
    - requests-toolbelt >=1.0.0
    - zstandard >=0.23.0
    - packaging >=23.2
  run_constraints:
    - langsmith-pyo3 >=0.1.0rc2,<0.2.0
    - rich >=13.9.4
    - pytest >=7.0.0
    - openai-agents >=0.0.3,<0.1
    - opentelemetry-sdk >=1.30.0,<2.0.0
    - opentelemetry-api >=1.30.0,<2.0.0
    - opentelemetry-exporter-otlp-proto-http >=1.30.0,<2.0.0

tests:
  - python:
      imports:
        - langsmith
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://smith.langchain.com/
  summary: Client library to connect to the LangSmith LLM Tracing and Evaluation Platform.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_file: LICENSE
  documentation: https://docs.smith.langchain.com/docs/
  repository: https://github.com/langchain-ai/langchainplus-sdk

extra:
  recipe-maintainers:
    - hinthornw
    - jan-janssen
    - pavelzw
    - rxm7706
    - vowelparrot

