schema_version: 1

context:
  name: robotcode-analyze
  version: 1.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robotcode_analyze-${{ version }}.tar.gz
  sha256: 0e70d6281958342fc71b15ab4d9228cfe4587196cfe25a5747d9fbf19ac6cc68

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - robotframework >=4.1.0
    - robotcode-plugin ==1.9.0
    - robotcode-robot ==1.9.0
    - robotcode ==1.9.0

tests:
  - python:
      imports:
        - robotcode_analyze
      pip_check: true

about:
  summary: RobotCode analyze plugin for Robot Framework
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/robotcodedev/robotcode

extra:
  recipe-maintainers:
    - rxm7706
