#!/usr/bin/env python3
"""
npm Registry Autotick Bot.

Mirrors recipe_updater.py (PyPI) and github_updater.py (GitHub releases)
but fetches the latest version from the npm registry. Intended for recipes
generated by ``recipe-generator.py npm`` whose canonical release channel is
the npm registry.

Workflow:
  1. Parse the recipe's context for current name/version.
  2. Auto-detect the npm package name from ``source.url`` (
     ``https://registry.npmjs.org/<scoped-or-bare>/-/<basename>-<version>.tgz``)
     — or accept ``--package`` to override.
  3. Fetch the latest version from ``https://registry.npmjs.org/<name>``.
  4. Compare using PEP 440 semantics; fall back to string equality.
  5. If newer: build an action plan to update ``context.version``,
     reset ``build.number`` to 0, and recalculate the source SHA256 — then
     apply via ``recipe_editor.py``.

Pre-releases are skipped by default (pass ``--pre`` to include them).

Usage:
    python npm_updater.py recipes/husky/recipe.yaml
    python npm_updater.py --package @openai/codex recipes/codex
    python npm_updater.py --dry-run recipes/husky
    python npm_updater.py --pre  recipes/husky
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    from ruamel.yaml import YAML
    RUAMEL_AVAILABLE = True
except ImportError:
    YAML = None  # type: ignore[assignment,misc]
    RUAMEL_AVAILABLE = False

try:
    import requests
    REQUESTS_AVAILABLE = True
except ImportError:
    requests = None  # type: ignore[assignment]
    REQUESTS_AVAILABLE = False

try:
    from packaging.version import Version as PkgVersion
    PACKAGING_AVAILABLE = True
except ImportError:
    PkgVersion = None  # type: ignore[assignment,misc]
    PACKAGING_AVAILABLE = False


_SCRIPTS_DIR = Path(__file__).parent
RECIPE_EDITOR_SCRIPT = _SCRIPTS_DIR / "recipe_editor.py"

# Match `https://registry.npmjs.org/<scoped-or-bare>/-/<basename>-<version>.tgz`.
# Scoped form: ``https://registry.npmjs.org/@openai/codex/-/codex-1.2.3.tgz``
_NPM_URL_RE = re.compile(
    r"registry\.npmjs\.org/(?P<name>(?:@[^/]+/)?[^/]+)/-/[^/]+\.tgz",
    re.IGNORECASE,
)


# ── Recipe helpers ────────────────────────────────────────────────────────────

def _normalize_recipe_path(p: Path) -> Path:
    """Accept either a recipe file or a recipe directory."""
    if p.is_dir():
        for name in ("recipe.yaml", "meta.yaml"):
            candidate = p / name
            if candidate.exists():
                return candidate
        raise FileNotFoundError(f"No recipe.yaml or meta.yaml under {p}")
    return p


def _load_recipe(recipe_path: Path) -> dict[str, Any]:
    if not RUAMEL_AVAILABLE:
        raise ImportError("ruamel.yaml is required to parse the recipe.")
    assert YAML is not None
    yaml_parser = YAML()
    with open(recipe_path) as f:
        return yaml_parser.load(f)


def _extract_npm_name(recipe: dict[str, Any]) -> str | None:
    """Pull the npm package name out of ``source.url``.

    Returns None when the recipe doesn't reference the npm registry (e.g. a
    GitHub-source recipe — should be handled by ``github_updater.py``).
    """
    source = recipe.get("source")
    candidates: list[str] = []
    if isinstance(source, dict):
        url = source.get("url")
        if isinstance(url, str):
            candidates.append(url)
        elif isinstance(url, list):
            candidates.extend(u for u in url if isinstance(u, str))
    elif isinstance(source, list):
        for item in source:
            if isinstance(item, dict):
                url = item.get("url")
                if isinstance(url, str):
                    candidates.append(url)
                elif isinstance(url, list):
                    candidates.extend(u for u in url if isinstance(u, str))

    for url in candidates:
        match = _NPM_URL_RE.search(url)
        if match:
            return match.group("name")
    return None


def _detect_source_path(recipe: dict[str, Any]) -> str:
    """Return 'source' (dict) or 'source.0' (list) for recipe_editor's path arg."""
    return "source" if isinstance(recipe.get("source"), dict) else "source.0"


# ── Version helpers ───────────────────────────────────────────────────────────

def _is_newer(latest: str, current: str) -> bool:
    if PACKAGING_AVAILABLE:
        assert PkgVersion is not None
        try:
            return PkgVersion(latest) > PkgVersion(current)
        except Exception:
            pass
    return latest != current


def _is_prerelease(version: str) -> bool:
    """Detect npm-style pre-release tags (alpha / beta / rc / next / pre)."""
    return bool(re.search(
        r"-(alpha|beta|rc|pre|next|dev|canary|nightly)\b", version, re.IGNORECASE,
    ))


# ── npm registry ──────────────────────────────────────────────────────────────

def get_latest_npm_version(package_name: str, *, allow_prerelease: bool = False) -> dict[str, Any]:
    """Query the npm registry for the latest published version.

    Returns ``{"version": "...", "tarball_url": "...", "prerelease": bool}``.
    Raises ``RuntimeError`` on transport failure.
    """
    if not REQUESTS_AVAILABLE:
        raise RuntimeError("requests library is required for npm registry access.")
    assert requests is not None

    url = f"https://registry.npmjs.org/{package_name}"
    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
    except requests.RequestException as exc:
        raise RuntimeError(f"npm registry request failed: {exc}") from exc

    data = response.json()
    dist_tags = data.get("dist-tags") or {}
    latest_tag = dist_tags.get("latest")
    if not latest_tag:
        raise RuntimeError(f"npm registry returned no 'latest' tag for {package_name!r}.")

    # Optionally pick the highest *non-prerelease* version when latest IS a pre-release
    chosen = latest_tag
    if not allow_prerelease and _is_prerelease(latest_tag):
        # Look for the most recent stable in the versions table
        versions = list(data.get("versions") or {})
        stable = [v for v in versions if not _is_prerelease(v)]
        if stable and PACKAGING_AVAILABLE:
            assert PkgVersion is not None
            try:
                stable.sort(key=PkgVersion, reverse=True)
                chosen = stable[0]
            except Exception:
                chosen = stable[-1]
        elif stable:
            chosen = stable[-1]

    version_info = (data.get("versions") or {}).get(chosen, {})
    tarball_url = (version_info.get("dist") or {}).get("tarball", "")
    return {
        "version": chosen,
        "tarball_url": tarball_url,
        "prerelease": _is_prerelease(chosen),
        "latest_dist_tag": latest_tag,
    }


# ── Core update logic ─────────────────────────────────────────────────────────

def update_recipe(
    recipe_path: Path,
    npm_package: str | None = None,
    dry_run: bool = False,
    allow_prerelease: bool = False,
) -> dict[str, Any]:
    try:
        recipe = _load_recipe(recipe_path)
    except (ImportError, FileNotFoundError, Exception) as exc:
        return {"success": False, "error": str(exc)}

    ctx = recipe.get("context") or {}
    current_version = str(ctx.get("version", "")) if ctx.get("version") else None
    package_name = str(
        (recipe.get("package") or {}).get("name")
        or ctx.get("name")
        or recipe_path.parent.name
    )

    if not current_version:
        return {"success": False, "error": "Cannot read context.version from recipe."}

    # 1. Resolve the npm package name
    if npm_package:
        npm_name = npm_package
    else:
        detected = _extract_npm_name(recipe)
        if detected is None:
            return {
                "success": False,
                "error": (
                    "No npm registry URL detected in this recipe's source. "
                    "Pass --package <name> to specify it manually, "
                    "or use github_updater for GitHub-sourced recipes."
                ),
                "recipe": str(recipe_path),
            }
        npm_name = detected

    print(
        f"Checking npm registry for {npm_name} "
        f"(current: {package_name} {current_version})…",
        file=sys.stderr,
    )

    # 2. Fetch latest
    try:
        latest_info = get_latest_npm_version(
            npm_name, allow_prerelease=allow_prerelease,
        )
    except RuntimeError as exc:
        return {"success": False, "error": str(exc), "package": npm_name}

    latest_version = latest_info["version"]

    if latest_info["prerelease"] and not allow_prerelease:
        return {
            "success": True,
            "updated": False,
            "current_version": current_version,
            "latest_version": latest_version,
            "message": (
                f"Latest npm release {latest_version} is a pre-release — skipping. "
                "Pass --pre to include pre-releases."
            ),
        }

    # 3. Compare
    if not _is_newer(latest_version, current_version):
        return {
            "success": True,
            "updated": False,
            "current_version": current_version,
            "latest_version": latest_version,
            "message": f"Already up-to-date ({current_version}).",
        }

    print(
        f"New npm version found: {current_version} → {latest_version}",
        file=sys.stderr,
    )

    # 4. Build action plan
    source_path = _detect_source_path(recipe)
    actions: list[dict[str, Any]] = [
        {"action": "update", "path": "context.version", "value": latest_version},
        {"action": "update", "path": "build.number", "value": 0},
        {"action": "calculate_hash", "path": source_path},
    ]

    if dry_run:
        return {
            "success": True,
            "updated": True,
            "dry_run": True,
            "current_version": current_version,
            "latest_version": latest_version,
            "tarball_url": latest_info.get("tarball_url"),
            "npm_package": npm_name,
            "actions": actions,
            "message": (
                f"Dry run: would update {package_name} {current_version} "
                f"→ {latest_version}."
            ),
        }

    # 5. Apply via recipe_editor.py
    python = os.environ.get("CONDA_PYTHON_EXE") or sys.executable
    cmd = [
        python, str(RECIPE_EDITOR_SCRIPT), str(recipe_path), json.dumps(actions),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)

    if proc.returncode != 0:
        raw = proc.stderr or proc.stdout
        try:
            detail = json.loads(proc.stdout).get("error", raw)
        except Exception:
            detail = raw
        return {"success": False, "error": f"recipe_editor failed: {detail}"}

    return {
        "success": True,
        "updated": True,
        "current_version": current_version,
        "new_version": latest_version,
        "tarball_url": latest_info.get("tarball_url"),
        "npm_package": npm_name,
        "message": f"Updated {package_name} {current_version} → {latest_version}.",
    }


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Autotick bot: update a conda recipe to the latest npm release.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Auto-detects the npm package name from the recipe's source URL.\n"
            "Pass --package to override (useful for scoped packages whose URL\n"
            "doesn't quite match the standard pattern).\n\n"
            "Exit: 0 = success (updated or already current), 1 = error."
        ),
    )
    parser.add_argument("recipe_path", type=Path, help="Recipe file or directory.")
    parser.add_argument(
        "--package", default=None,
        help="npm package name (e.g. husky, @openai/codex) — overrides auto-detect.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Check for updates but do not write the file.",
    )
    parser.add_argument(
        "--pre", action="store_true",
        help="Include pre-release versions (alpha/beta/rc/next/dev).",
    )
    args = parser.parse_args()

    try:
        recipe_path = _normalize_recipe_path(args.recipe_path)
    except FileNotFoundError as exc:
        print(json.dumps({"success": False, "error": str(exc)}, indent=2))
        sys.exit(1)

    result = update_recipe(
        recipe_path,
        npm_package=args.package,
        dry_run=args.dry_run,
        allow_prerelease=args.pre,
    )
    print(json.dumps(result, indent=2))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
