{% set name = "kedro-viz" %}
{% set version = "12.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kedro-org/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 65bee866ed45860372bd39e8ca701cfc690fdb66e820fbfe504f819012b7186d

build:
  noarch: python
  script:
    - echo {" --------------------------------------------------------Cleans out any and all existing build --------------------------------------------------------------------------"}
    - rm -rf build package/build package/dist package/kedro_viz/html pip-wheel-metadata package/kedro_viz.egg-info

    - echo {" --------------------------------------------------------this replaces the metadata-code-themes.scss in the /src/components/metadata/styles/ to source locally ----------"}
    - cp {{ RECIPE_DIR }}/metadata-code-themes.scss {{ SRC_DIR }}/src/components/metadata/styles/metadata-code-themes.scss
    - echo {" --------------------------------------------------------this adds the local a11y-light.css in the metadata/styles dir---------------------------------------------------"}
    - cp {{ RECIPE_DIR }}/a11y-light.css {{ SRC_DIR }}/src/components/metadata/styles/a11y-light.css
    - echo {" --------------------------------------------------------this adds the local a11y-dark.css in the metadata/styles dir where metadata-code-themes.scss was replaced-------"}
    - cp {{ RECIPE_DIR }}/a11y-dark.css {{ SRC_DIR }}/src/components/metadata/styles/a11y-dark.css

    - echo {" --------------------------------------------------------npm install sass react-scripts ---------------------------------------------------------------------------------"}
    - npm install --save react@18.2.0 react-dom@18.2.0 sass@1.69.5 react-scripts@5.0.1 cypress@13.6.0 eslint-plugin-cypress@2.15.1 jest@27.5.1

    - echo {" --------------------------------------------------------NODE_OPTIONS=--openssl-legacy-provider npm run build ------------------------------------------------------------"}
    - NODE_OPTIONS=--openssl-legacy-provider npm run build

    - echo {" --------------------------------------------------------if [ -d dist ]; then cp -R dist {{ SRC_DIR }}/package/kedro_viz/html; else cp -R build {{ SRC_DIR }}/package/kedro_viz/html; fi ----------------------------------------------------------------"}
    - if [ -d dist ]; then cp -R dist {{ SRC_DIR }}/package/kedro_viz/html; else cp -R build {{ SRC_DIR }}/package/kedro_viz/html; fi

    - {{ PYTHON }} -m pip install ./package -vv --no-deps --no-build-isolation

  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-requirements-txt
    - pip
    - nodejs >16.0,<21.0
  run:
    - python >={{ python_min }}
    - aiofiles >=22.1.0
    - click-default-group
    - fastapi >=0.100.0,<0.200.0
    - fsspec >=2021.4
    - ipython >=7.0.0,<9.0
    - kedro >=0.18.0
    #- kedro-telemetry>=0.6.0
    - networkx >=2.5
    - orjson >=3.9,<4.0
    - packaging >=23.0
    - pandas >=1.3
    - plotly >=4.0
    - pydantic >=2.0.0
    - secure >=0.3.0
    - sqlalchemy >=1.4,<3
    - strawberry-graphql >=0.192.0,<1.0
    - uvicorn-standard >=0.30.0,<1.0
    - watchfiles >=0.24.0
    - pathspec >=0.12.1
    # Added Manually
    - s3fs >=2021.4

test:
  imports:
    - kedro_viz
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kedro-org/kedro-viz
  summary: Kedro-Viz helps visualise Kedro data and analytics pipelines
  doc_url: https://demo.kedro.org
  dev_url: https://github.com/kedro-org/kedro-viz
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE.md
    - COPYING.txt

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
    - millsks
    - zaigner
    - elanqo
