# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: kedro-viz
  version: "12.2.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/kedro_viz-${{ version }}.tar.gz
  sha256: 01a425a403b85100aed843cba9cca09db824f059baf36b7addbe4527050cf8de

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-requirements-txt
    - pip
  run:
    - python >=${{ python_min }},<4
    - aiofiles >=22.1.0
    - click-default-group
    - fastapi >=0.100.0,<0.200.0
    - fsspec >=2021.4
    - ipython >=7.0.0,<9.0
    - kedro-telemetry >=0.6.0
    - kedro >=1.0.0
    - networkx >=2.4
    - orjson >=3.9,<4.0
    - packaging >=23.0
    - pandas >=1.3
    - pathspec >=0.12.1
    - plotly >=4.0
    - pydantic >=2.0.0
    - secure >=0.3.0
    - uvicorn >=0.30.0,<1.0
    - watchfiles >=0.24.0
    - werkzeug >=3.0.0

tests:
  - python:
      imports:
        - kedro_viz
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/kedro-org/kedro-viz
  summary: Kedro-Viz helps visualise Kedro data and analytics pipelines
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE.md
    - COPYING.txt
  documentation: https://demo.kedro.org
  repository: https://github.com/kedro-org/kedro-viz

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
    - millsks
    - zaigner
    - elanqo
