# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-components
  version: "0.146.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_components-${{ version }}.tar.gz
  sha256: 8906d5adeb7ea87371a852989228ed309f10261afa2d4e6ce750c9d00af73d3e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - djc-core >=1.2.2
    - typing_extensions >=4.12.2

tests:
  - python:
      imports:
        - django_components
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A way to create simple reusable template components in Django.
  homepage: https://django-components.github.io/django-components/latest/overview/welcome/
  description: |
       Create simple reusable template components in Django.
  repository: https://github.com/django-components/django-components
  documentation: https://django-components.github.io/django-components/latest/reference/api/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
