# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.0.0"

package:
  name: gspread-dataframe
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gspread-dataframe/gspread-dataframe-${{ version }}.tar.gz
  sha256: 5ca5493478ecae49b833664a06bac8e17b5b4ed0bdf77f551c948f30545860e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - gspread >=3.0.0
    - pandas >=0.24.0
    - six >=1.12.0

tests:
  - python:
      imports:
        - gspread_dataframe
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/robin900/gspread-dataframe
  license: MIT
  license_file: LICENSE
  summary: Read/write gspread worksheets using pandas DataFrames
  description: |
    Read/write gspread worksheets using pandas DataFrames

extra:
  recipe-maintainers:
    - maresb

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: gspread-dataframe
  cfe-upstream-registry: pypi
  cfe-upstream-name: gspread-dataframe
  cfe-purls:
    - pkg:conda/gspread-dataframe@${{ version }}?channel=conda-forge
    - pkg:pypi/gspread-dataframe@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/robin900/gspread-dataframe
  cfe-import-names: [gspread_dataframe]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/gspread-dataframe-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-4.0.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T10:54:55Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T10:54:55Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-17T10:54:55Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
