# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: "gibr"
  python_min: '3.11'
  version: "0.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gibr-${{ version }}.tar.gz
  sha256: 6c949e21493ef5c2a86e0a4b305c0e1af67fda40a3504d977dae75fceff803a2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gibr = gibr.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }},<4
    - gitpython >=3.1.43
    - click >=8.3.0
    - python-dotenv >=1.2.1
    - python-slugify >=8.0.4
    - tabulate >=0.9.0
    - requests >=2.32.5
    #- pygithub >=2.8.1
    #- python-gitlab >=6.5.0
    #- jira >=3.9.2

tests:
  - python:
      imports:
        - gibr
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - gibr --help

about:
  summary: A Git CLI tool for intelligently creating branch names
  license: MIT
  license_file: LICENSE
  repository: https://github.com/ytreister/gibr
  homepage: https://github.com/ytreister/gibr

extra:
  recipe-maintainers:
    - rxm7706
