# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-soft-delete
  version: "1.0.22"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_soft_delete-${{ version }}.tar.gz
  sha256: 32d0bb95f180c28a40163e78a558acc18901fd56011f91f8ee735c171a6d4244

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.24.0
    - pip
  run:
    - python >=${{ python_min }},<4
    - django

tests:
  - python:
      imports:
        - django_soft_delete
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Soft delete models, managers, queryset for Django
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/san4ezy/django_softdelete

extra:
  recipe-maintainers:
    - rxm7706
