{% set name = "rocksdict" %}
{% set version = "0.3.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Congyuwang/RocksDict/archive/v{{ version }}.tar.gz
  sha256: 79441cd6668b337649027df4612382d1f28fd8cf5d41edc11e99cc8f3f5eb9cb

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  script_env:
    - LIBCLANG_PATH=$BUILD_PREFIX/lib  # [not win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - clangdev
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - rocksdict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Congyuwang/RocksDict
  doc_url: https://congyuwang.github.io/RocksDict/rocksdict.html
  summary: Python fast on-disk dictionary; RocksDB & SpeeDB Python binding
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
