# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.5.1"

package:
  name: wsgiproxy2
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/W/WSGIProxy2/WSGIProxy2-${{ version }}.tar.gz
  sha256: 0d9ecb141de720e2fd4f7a275a4a83a961ffeb6717483d940021ffa1c46f665c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - setuptools
    - webob
    - six

tests:
  - python:
      imports:
        - wsgiproxy
      pip_check: false
      python_version: ${{ python_min }}
  - requirements:
      run:
        - python ${{ python_min }}

about:
  license: MIT
  license_file: COPYING
  summary: A WSGI Proxy with various http client backends
  homepage: https://github.com/gawel/WSGIProxy2
  repository: https://github.com/gawel/WSGIProxy2
  documentation: https://wsgiproxy2.readthedocs.org

extra:
  recipe-maintainers:
    - nehaljwani
