# Generated by Django 5.2.15 on 2026-08-13 01:32
#
# Story 9.3 — the initial migration for `AuditEntry` (CAP-4's durable store).
# `id` resolves to `BigAutoField` because `apps.py`'s `DashboardConfig.
# default_auto_field` is set (AD-13) -- without it this migration would have
# taken whatever `DEFAULT_AUTO_FIELD` the adopter's own project happens to
# set, and shifted if that setting ever changed.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.CharField(db_index=True, max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("load", "Load"),
                            ("filter", "Filter"),
                            ("navigate", "Navigate"),
                            ("export", "Export"),
                            ("audit_read", "Audit read"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target", models.CharField(blank=True, default="", max_length=255)),
                ("row_count", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
