# Generated by Django for WorkPassport model (Story 63.5 / Epic 61)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pyforge_steward_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkPassport",
            fields=[
                (
                    "passport_id",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("story_id", models.CharField(db_index=True, max_length=64)),
                ("station", models.CharField(db_index=True, max_length=64)),
                ("epic_id", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(max_length=512)),
                ("status", models.CharField(db_index=True, default="backlog", max_length=32)),
                ("jira_key", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("github_item_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("effort", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Passport",
                "verbose_name_plural": "Work Passports",
                "ordering": ["station", "story_id"],
            },
        ),
    ]
