# Generated by Django 5.2.17 on 2026-09-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyforge_steward_dashboard', '0002_workpassport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridorLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, max_length=8)),
                ('batch_sha', models.CharField(db_index=True, max_length=64)),
                ('waybill', models.CharField(db_index=True, max_length=128)),
                ('transport', models.CharField(max_length=32)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Corridor Load',
                'verbose_name_plural': 'Corridor Loads',
                'ordering': ['-loaded_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('direction', 'batch_sha', 'waybill'), name='corridorload_unique_direction_batch_sha_waybill')],
            },
        ),
    ]
