# Generated by Django 5.2.17 on 2026-09-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyforge_steward_dashboard', '0003_corridorload'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassport',
            name='vendor_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
