# Generated by Django 5.2.17 on 2026-09-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyforge_steward_dashboard', '0004_workpassport_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridorload',
            name='signer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='corridorload',
            name='slice_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
