# Generated by Django 5.2 on 2026-10-03 (Story 84.2)

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyforge_steward_dashboard", "0006_auditaction_purge"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentry",
            name="scope",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "For AUDIT_READ rows: the validated filter lookups that scoped "
                    "the read, as sorted string keys to string values (Story 84.2)."
                ),
            ),
        ),
    ]
