# Generated by Django 5.2 for Story 61.5.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyforge_steward_dashboard", "0007_auditentry_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarantineShelfRow",
            fields=[
                ("row_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("vendor_id", models.CharField(db_index=True, max_length=64)),
                ("jira_key", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("github_item_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("passport_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("arrived_at", models.DateTimeField(db_index=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Quarantine shelf row",
                "verbose_name_plural": "Quarantine shelf rows",
                "ordering": ["-arrived_at", "-row_id"],
            },
        ),
    ]
