schema_version: 1

context:
  name: ovld
  version: 0.5.12

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ovld-${{ version }}.tar.gz
  sha256: 60cdc9a73fe149d658231afe7db58d666bffb4e2d923598ffeebcd3b0ee35bee

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9

tests:
  - python:
      imports:
        - ovld
      pip_check: true

about:
  summary: Overloading Python functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
