# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ovld
  version: "0.5.12"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ovld-${{ version }}.tar.gz
  sha256: 60cdc9a73fe149d658231afe7db58d666bffb4e2d923598ffeebcd3b0ee35bee

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - ovld
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Overloading Python functions
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/breuleux/ovld

extra:
  recipe-maintainers:
    - rxm7706
