# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-compression-middleware
  version: "0.5.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django-compression-middleware-${{ version }}.tar.gz
  sha256: 0df50f12d774659abc8bbc88e4c794f2785a8f11f30b5bb267c314b85d941b73

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools <81.0.0
  run:
    - python >=${{ python_min }},<4
    - django
    - zstandard
    - brotli

tests:
  - python:
      imports:
        - compression_middleware
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Django middleware to compress responses using several algorithms.
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/friedelwolff/django-compression-middleware

extra:
  recipe-maintainers:
    - rxm7706
