"""``core`` pipeline — GENERATED stub mirror of pyforge-atlas.

Auto-generated by tools/regenerate_from_atlas.py from
src/shared/packages/pyforge-atlas/.../pipelines/core/. Do not edit by hand;
re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.
"""
from kedro.pipeline import Pipeline, node, pipeline

from pyforge.atlas_kedro_viz.nodes import stub


def create_pipeline() -> Pipeline:
    return pipeline(
        [
            node(stub("extract_core_anaconda_downloads_raw"), None, 'core_anaconda_downloads_raw', name="extract_core_anaconda_downloads_raw"),
            node(stub("extract_core_cf_graph_raw"), None, 'core_cf_graph_raw', name="extract_core_cf_graph_raw"),
            node(stub("extract_core_channeldata_raw"), None, 'core_channeldata_raw', name="extract_core_channeldata_raw"),
            node(stub("extract_core_feedstock_outputs_raw"), None, 'core_feedstock_outputs_raw', name="extract_core_feedstock_outputs_raw"),
            node(stub("extract_core_repodata_raw"), None, 'core_repodata_raw', name="extract_core_repodata_raw"),
            node(stub("extract_core_s3_download_stats_raw"), None, 'core_s3_download_stats_raw', name="extract_core_s3_download_stats_raw"),
            node(stub("enumerate_conda_packages"), ['core_repodata_raw', 'core_channeldata_raw'], 'core_packages_enumerated', name="enumerate_conda_packages"),
            node(stub("attribute_feedstocks"), 'core_feedstock_outputs_raw', 'core_feedstock_attribution', name="attribute_feedstocks"),
            node(stub("detect_latest_status"), ['core_repodata_raw', 'core_channeldata_raw'], 'core_latest_status', name="detect_latest_status"),
            node(stub("compute_downloads", n_outputs=4), ['core_anaconda_downloads_raw', 'core_s3_download_stats_raw'], ['core_downloads', 'core_downloads_platform_breakdown', 'core_downloads_pyver_breakdown', 'core_downloads_channel_breakdown'], name="compute_downloads"),
            node(stub("compute_version_download_history"), 'core_anaconda_downloads_raw', 'core_version_download_history', name="compute_version_download_history"),
            node(stub("build_dependency_graph"), 'core_cf_graph_raw', 'core_dependencies', name="build_dependency_graph"),
            node(stub("compute_feedstock_health"), 'core_cf_graph_raw', 'core_feedstock_health', name="compute_feedstock_health"),
        ]
    )
