"""``derived_artifacts`` pipeline — GENERATED stub mirror of pyforge-atlas.

Auto-generated by tools/regenerate_from_atlas.py from
src/shared/packages/pyforge-atlas/.../pipelines/derived_artifacts/. Do not edit by hand;
re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.
"""
from kedro.pipeline import Pipeline, node, pipeline

from pyforge.atlas_kedro_viz.nodes import stub


def create_pipeline() -> Pipeline:
    return pipeline(
        [
            node(stub("build_universe_sbom"), ['core_packages_enumerated', 'pypi_conda_mapping', 'parameters'], 'derived_universe_sbom', name="build_universe_sbom"),
        ]
    )
