"""``pypi_intelligence`` pipeline — GENERATED stub mirror of pyforge-atlas.

Auto-generated by tools/regenerate_from_atlas.py from
src/shared/packages/pyforge-atlas/.../pipelines/pypi_intelligence/. Do not edit by hand;
re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.
"""
from kedro.pipeline import Pipeline, node, pipeline

from pyforge.atlas_kedro_viz.nodes import stub


def create_pipeline() -> Pipeline:
    return pipeline(
        [
            node(stub("extract_pypi_bigquery_downloads_raw"), None, 'pypi_bigquery_downloads_raw', name="extract_pypi_bigquery_downloads_raw"),
            node(stub("extract_pypi_cross_channel_repodata_raw"), None, 'pypi_cross_channel_repodata_raw', name="extract_pypi_cross_channel_repodata_raw"),
            node(stub("extract_pypi_json_raw"), None, 'pypi_json_raw', name="extract_pypi_json_raw"),
            node(stub("extract_pypi_parselmouth_mapping_raw"), None, 'pypi_parselmouth_mapping_raw', name="extract_pypi_parselmouth_mapping_raw"),
            node(stub("extract_pypi_simple_index_raw"), None, 'pypi_simple_index_raw', name="extract_pypi_simple_index_raw"),
            node(stub("map_pypi_conda"), ['pypi_parselmouth_mapping_raw', 'core_packages_enumerated'], 'pypi_conda_mapping_base', name="map_pypi_conda"),
            node(stub("match_source_urls"), ['pypi_conda_mapping_base', 'pypi_json_raw'], 'pypi_conda_mapping', name="match_source_urls"),
            node(stub("enumerate_pypi_universe"), 'pypi_simple_index_raw', 'pypi_universe', name="enumerate_pypi_universe"),
            node(stub("fetch_pypi_current_versions"), ['pypi_json_raw', 'pypi_universe'], 'pypi_current_versions', name="fetch_pypi_current_versions"),
            node(stub("snapshot_pypi_serials"), 'pypi_simple_index_raw', 'pypi_universe_serial_snapshots', name="snapshot_pypi_serials"),
            node(stub("fetch_pypi_downloads"), 'pypi_bigquery_downloads_raw', 'pypi_downloads_monthly', name="fetch_pypi_downloads"),
            node(stub("flag_cross_channel"), 'pypi_cross_channel_repodata_raw', 'pypi_cross_channel_flags', name="flag_cross_channel"),
            node(stub("enrich_pypi_intelligence"), 'pypi_json_raw', 'pypi_intelligence_enriched', name="enrich_pypi_intelligence"),
            node(stub("score_pypi_readiness"), 'pypi_intelligence_enriched', 'pypi_intelligence_scored', name="score_pypi_readiness"),
            node(stub("export_pypi_conda_map"), 'pypi_conda_mapping', 'pypi_conda_map_store', name="export_pypi_conda_map"),
        ]
    )
