"""``seed_gaps`` pipeline — GENERATED stub mirror of pyforge-atlas.

Auto-generated by tools/regenerate_from_atlas.py from
src/shared/packages/pyforge-atlas/.../pipelines/seed_gaps/. Do not edit by hand;
re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.
"""
from kedro.pipeline import Pipeline, node, pipeline

from pyforge.atlas_kedro_viz.nodes import stub


def create_pipeline() -> Pipeline:
    return pipeline(
        [
            node(stub("extract_pypi_endoflife_raw"), None, 'pypi_endoflife_raw', name="extract_pypi_endoflife_raw"),
            node(stub("extract_seed_cwe_categories"), None, 'seed_cwe_categories', name="extract_seed_cwe_categories"),
            node(stub("extract_seed_lts_registry"), None, 'seed_lts_registry', name="extract_seed_lts_registry"),
            node(stub("extract_seed_spdx_schema"), None, 'seed_spdx_schema', name="extract_seed_spdx_schema"),
            node(stub("extract_seed_spdx_upstream_list_raw"), None, 'seed_spdx_upstream_list_raw', name="extract_seed_spdx_upstream_list_raw"),
            node(stub("report_lts_registry_gap"), ['seed_lts_registry', 'pypi_endoflife_raw', 'core_packages_enumerated', 'pypi_conda_mapping'], 'seed_gaps_lts_registry_report', name="report_lts_registry_gap"),
            node(stub("report_cwe_seed_gap"), ['seed_cwe_categories', 'vulnerability_cwe_categories'], 'seed_gaps_cwe_report', name="report_cwe_seed_gap"),
            node(stub("report_spdx_schema_gap"), ['seed_spdx_schema', 'seed_spdx_upstream_list_raw', 'core_packages_enumerated'], 'seed_gaps_spdx_report', name="report_spdx_schema_gap"),
            node(stub("report_license_map_gap"), ['seed_spdx_schema', 'pypi_intelligence_enriched'], 'seed_gaps_license_map_report', name="report_license_map_gap"),
        ]
    )
