"""``universal_sbom`` pipeline — GENERATED stub mirror of pyforge-atlas.

Auto-generated by tools/regenerate_from_atlas.py from
src/shared/packages/pyforge-atlas/.../pipelines/universal_sbom/. Do not edit by hand;
re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.
"""
from kedro.pipeline import Pipeline, node, pipeline

from pyforge.atlas_kedro_viz.nodes import stub


def create_pipeline() -> Pipeline:
    return pipeline(
        [
            node(stub("extract_sbom_intake_entry"), None, 'sbom_intake_entry', name="extract_sbom_intake_entry"),
            node(stub("extract_sbom_resolution_entry"), None, 'sbom_resolution_entry', name="extract_sbom_resolution_entry"),
            node(stub("normalize_intake_to_cyclonedx"), ['sbom_intake_entry', 'sbom_resolution_entry', 'parameters'], 'sbom_normalized_bom_entry', name="normalize_intake_to_cyclonedx"),
            node(stub("match_against_universe"), ['sbom_normalized_bom_entry', 'core_packages_enumerated', 'pypi_conda_mapping', 'derived_universe_sbom', 'pypi_universe', 'parameters'], 'sbom_match_report_entry', name="match_against_universe"),
            node(stub("run_dependency_hygiene"), ['sbom_intake_entry', 'parameters'], 'sbom_hygiene_entry', name="run_dependency_hygiene"),
            node(stub("assemble_and_gate"), ['sbom_hygiene_entry', 'sbom_match_report_entry', 'parameters'], 'sbom_compliance_report_entry', name="assemble_and_gate"),
        ]
    )
