"""``vcs_health`` pipeline — GENERATED stub mirror of pyforge-atlas.

Auto-generated by tools/regenerate_from_atlas.py from
src/shared/packages/pyforge-atlas/.../pipelines/vcs_health/. Do not edit by hand;
re-run `pixi run -e local-recipes regenerate-kedro-viz-proto`.
"""
from kedro.pipeline import Pipeline, node, pipeline

from pyforge.atlas_kedro_viz.nodes import stub


def create_pipeline() -> Pipeline:
    return pipeline(
        [
            node(stub("extract_vcs_codeberg_api_raw"), None, 'vcs_codeberg_api_raw', name="extract_vcs_codeberg_api_raw"),
            node(stub("extract_vcs_github_api_raw"), None, 'vcs_github_api_raw', name="extract_vcs_github_api_raw"),
            node(stub("extract_vcs_gitlab_api_raw"), None, 'vcs_gitlab_api_raw', name="extract_vcs_gitlab_api_raw"),
            node(stub("extract_vcs_migration_detail_raw"), None, 'vcs_migration_detail_raw', name="extract_vcs_migration_detail_raw"),
            node(stub("extract_vcs_registry_cpan_raw"), None, 'vcs_registry_cpan_raw', name="extract_vcs_registry_cpan_raw"),
            node(stub("extract_vcs_registry_cran_raw"), None, 'vcs_registry_cran_raw', name="extract_vcs_registry_cran_raw"),
            node(stub("extract_vcs_registry_crates_raw"), None, 'vcs_registry_crates_raw', name="extract_vcs_registry_crates_raw"),
            node(stub("extract_vcs_registry_luarocks_raw"), None, 'vcs_registry_luarocks_raw', name="extract_vcs_registry_luarocks_raw"),
            node(stub("extract_vcs_registry_maven_raw"), None, 'vcs_registry_maven_raw', name="extract_vcs_registry_maven_raw"),
            node(stub("extract_vcs_registry_npm_raw"), None, 'vcs_registry_npm_raw', name="extract_vcs_registry_npm_raw"),
            node(stub("extract_vcs_registry_nuget_raw"), None, 'vcs_registry_nuget_raw', name="extract_vcs_registry_nuget_raw"),
            node(stub("extract_vcs_registry_rubygems_raw"), None, 'vcs_registry_rubygems_raw', name="extract_vcs_registry_rubygems_raw"),
            node(stub("enrich_maintainers", n_outputs=2), 'core_cf_graph_raw', ['vcs_maintainers', 'vcs_package_maintainers'], name="enrich_maintainers"),
            node(stub("detect_archived_feedstocks"), 'vcs_github_api_raw', 'vcs_archived_feedstocks', name="detect_archived_feedstocks"),
            node(stub("track_upstream_versions"), ['vcs_github_api_raw', 'vcs_gitlab_api_raw', 'vcs_codeberg_api_raw'], 'vcs_upstream_versions', name="track_upstream_versions"),
            node(stub("track_registry_versions"), ['vcs_registry_npm_raw', 'vcs_registry_cran_raw', 'vcs_registry_cpan_raw', 'vcs_registry_luarocks_raw', 'vcs_registry_crates_raw', 'vcs_registry_rubygems_raw', 'vcs_registry_maven_raw', 'vcs_registry_nuget_raw'], 'vcs_registry_versions', name="track_registry_versions"),
            node(stub("fetch_live_health"), 'vcs_github_api_raw', 'vcs_live_health', name="fetch_live_health"),
            node(stub("derive_release_velocity"), ['pypi_current_versions', 'core_repodata_raw', 'pypi_conda_mapping'], 'vcs_release_velocity', name="derive_release_velocity"),
            node(stub("classify_migration_readiness"), ['vcs_migration_detail_raw', 'core_packages_enumerated', 'core_downloads'], 'vcs_migration_readiness', name="classify_migration_readiness"),
        ]
    )
