{% set name = "StringZilla" %}
{% set version = "4.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ashvardanian/StringZilla/archive/v{{ version }}.tar.gz
  sha256: 5c49782bc7f5a7392c8b960248d3cc9ba87b3a9629b665f731a2d407fefe425b
  #patches:
  #  - patches/0001-fix-build-option.patch

build:
  entry_points:
    - sz_split=cli.split:main
    - sz_wc=cli.wc:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - cli
  commands:
    - pip check
    - sz_split --help
    - sz_wc --help
  requires:
    - pip

about:
  home: https://github.com/ashvardanian/stringzilla
  summary: Search, hash, sort, fingerprint, and fuzzy-match strings faster via SWAR, SIMD, and GPGPU
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
