# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: langchain-core
  version: "0.3.76"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_core-${{ version }}.tar.gz
  sha256: 71136a122dd1abae2c289c5809d035cf12b5f2bb682d8a4c1078cd94feae7419

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - langsmith >=0.3.45
    - tenacity !=8.4.0,<10.0.0,>=8.1.0
    - jsonpatch <2.0,>=1.33
    - pyyaml >=5.3
    - typing_extensions >=4.7
    - packaging >=23.2
    - pydantic >=2.7.4
  run_constraints:
    - jinja2 >=3.0.0,<4.0.0

tests:
  - python:
      imports:
        - langchain_core
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/langchain-ai/langchain
  documentation: https://api.python.langchain.com/en/stable/core_api_reference.html
  repository: https://github.com/langchain-ai/langchain/tree/master/libs/core
  summary: Core APIs for LangChain, the LLM framework for buildilng applications through composability
  description: LangChain Core contains the core abstractions powering LangChain, including LangChain Expression Language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agola11
    - baskaryan
    - ccurme
    - dlqqq
    - hinthornw
    - hwchase17
    - jan-janssen
    - pavelzw
    - rxm7706
    - sydney-runkle
