schema_version: 1

context:
  name: nebari-plugin-airflow
  version: 0.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/nebari_plugin_airflow-${{ version }}.tar.gz
  sha256: ae8eca82050c3eb01dcc5fff2fd82286d967e92d2009bd57d831724fbb765079

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - nebari

tests:
  - python:
      imports:
        - nebari_plugin_airflow
      pip_check: true

about:
  summary: MetroStar Onyx - Airflow plugin for Nebari platform
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/MetroStar/nebari-airflow

extra:
  recipe-maintainers:
    - rxm7706
