# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ag-ui-protocol
  version: "0.1.13"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ag_ui_protocol-${{ version }}.tar.gz
  sha256: 811d7d7dcce4783dec252918f40b717ebfa559399bf6b071c4ba47c0c1e21bcb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.8.0,<0.9
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - pydantic >=2.11.2

tests:
  - python:
      imports:
        - ag_ui.core
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: 'AG-UI: the Agent-User Interaction Protocol. Bring Agents into Frontend Applications.'
  license: MIT
  homepage: https://github.com/ag-ui-protocol/ag-ui
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
