# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: utilsforecast
  version: "0.2.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/utilsforecast-${{ version }}.tar.gz
  sha256: dca406231d002279562ae897dbcb9e419c2fc5bf48908be02834b3187ce5a52b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - packaging
    - pandas >=1.1.1
    - narwhals >=2.0

tests:
  - python:
      imports:
        - utilsforecast
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Forecasting utilities
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/Nixtla/utilsforecast

extra:
  recipe-maintainers:
    - AzulGarza
    - jmoralez
    - cchallu
    - mergenthaler
    - marcopeix
    - elephaint
    - JQGoh
    - nasaul
    - MMenchero
    - goodwanghan
