# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.3"

package:
  name: anyascii
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/anyascii/anyascii-${{ version }}.tar.gz
  sha256: c94e9dd9d47b3d9494eca305fef9447d00b4bf1a32aff85aa746fa3ec7fb95c3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - anyascii
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/anyascii/anyascii
  license: ISC
  license_file: LICENSE
  summary: Unicode to ASCII transliteration
  description: |
    Unicode to ASCII transliteration

extra:
  recipe-maintainers:
    - thewchan

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: anyascii
  cfe-upstream-registry: pypi
  cfe-upstream-name: anyascii
  cfe-purls:
    - pkg:conda/anyascii@${{ version }}?channel=conda-forge
    - pkg:pypi/anyascii@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/anyascii/anyascii
  cfe-import-names: [anyascii]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/anyascii-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T05:55:48Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T05:55:48Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-17T05:55:48Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
