{% set name = "mcp-ui-server" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcp_ui_server-{{ version }}.tar.gz
  sha256: 5ab8f17b93bf794966af7c35e9a575e4f21a9ba2bab3d316cfc107a15f88a3c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - mcp >=1.0.0
    - pydantic >=2.0.0
    - typing_extensions >=4.0.0

test:
  imports:
    - mcp_ui_server
  commands:
    - pip check
  requires:
    - pip

about:
  summary: mcp-ui Server SDK for Python
  license: Apache-2.0
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - rxm7706
