# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.0"

package:
  name: colorlover
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/colorlover/colorlover-${{ version }}.tar.gz
  sha256: b8fb7246ab46e1f5e6715649453c1762e245a515de5ff2d2b4aab7a6e67fa4e2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - colorlover
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/jackparmer/colorlover
  license: REPLACE_LICENSE
  license_file: LICENSE
  summary: Color scales for IPython notebook
  description: |
    Color scales for IPython notebook

extra:
  recipe-maintainers:
    - cshaley
    - sannykr

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: colorlover
  cfe-upstream-registry: pypi
  cfe-upstream-name: colorlover
  cfe-purls:
    - pkg:conda/colorlover@${{ version }}?channel=conda-forge
    - pkg:pypi/colorlover@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/jackparmer/colorlover
  cfe-import-names: [colorlover]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/colorlover-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.3.0

  cfe-forge-blocker-list:
    - license-unresolved:REPLACE_LICENSE

  cfe-last-checked: 2026-08-17T07:08:39Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T07:08:39Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-17T07:08:39Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
#    # license:REPLACE_LICENSE
#    # blocker: license-unresolved:REPLACE_LICENSE
####
