# Generated by Django 5.2.17 on 2026-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeckExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=64)),
                ('export_date', models.DateField()),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('source_commit', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('slug', 'kind', '-export_date'),
            },
        ),
    ]
