# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ocrmypdf
  version: "16.11.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ocrmypdf-${{ version }}.tar.gz
  sha256: 838ab69e0ee0f04feea0d5861a17badecab6d3beaed0e29a97058eadda58cbb1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ocrmypdf = ocrmypdf.__main__:run

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }},<4
    - deprecation >=2.1.0
    - img2pdf >=0.5
    - packaging >=20
    - pdfminer.six >=20220319
    #- pi-heif
    - pillow-heif
    - pikepdf >=8.10.1,!=9.8.0
    - pillow >=10.0.1
    - pluggy >=1
    - rich >=13
    - pdfminer-six >=20220319

tests:
  - python:
      imports:
        - ocrmypdf
        - ocrmypdf._exec
      pip_check: false
      #│ │ ocrmypdf 16.11.1 requires pi-heif, which is not installed. # Note conda package is pillow-heif
      #│ │ ocrmypdf 16.11.1 has requirement pdfminer-six>=20220319, but you have pdfminer-six 0.0.0. # Note conda package pdfminer-six is returning version 0.0.0
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - ocrmypdf --help

about:
  summary: OCRmyPDF adds an OCR text layer to scanned PDF files, allowing them to be searched
  license: MPL-2.0
  license_file: LICENSE
  repository: https://github.com/ocrmypdf/OCRmyPDF
  homepage: https://github.com/jbarlow83/OCRmyPDF

extra:
  recipe-maintainers:
    - izahn
    - rxm7706
