# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ydata-core
  version: "0.7.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ydataai/python-core/archive/${{ version }}.tar.gz
  sha256: 8655a78b478139dc7c8cf6e0ab29cd9bd1ab74e684502ab1422147d5002ae459

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - core
        - datascience
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ydataai/python-core
  summary: Core functionality for all python packages at YData

extra:
  recipe-maintainers:
    - rxm7706
