# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: python-gnupg
  version: "0.5.5"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python-gnupg-${{ version }}.tar.gz
  sha256: 3fdcaf76f60a1b948ff8e37dc398d03cf9ce7427065d583082b92da7a4ff5a63

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=44,<81.0.0
    - wheel >=0.29.0
    - pip
  run:
    - python >=${{ python_min }},<4

tests:
  - python:
      imports:
        - gnupg
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A wrapper for the Gnu Privacy Guard (GPG or GnuPG)
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/vsajip/python-gnupg
  repository: https://github.com/vsajip/python-gnupg
  documentation: https://pythonhosted.org/python-gnupg/

extra:
  recipe-maintainers:
    - rxm7706
    - vamega
