# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: python-keystoneclient
  version: "5.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 3ca87c67c404298ce862310b569f545a58acf75cd5685094c82f35320b3a355d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python ${{ python_min }}
    - setuptools
  run:
    - debtcollector
    - keystoneauth1
    - oslo.config
    - oslo.i18n
    - oslo.serialization
    - oslo.utils
    - packaging
    - python >=${{ python_min }}
    - requests
    - stevedore

tests:
  - python:
      imports:
        - keystoneclient
      pip_check: false
      python_version: ${{ python_min }}
  - requirements:
      run:
        - python ${{ python_min }}

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Client Library for OpenStack Identity
  homepage: https://github.com/openstack/python-keystoneclient
  repository: https://opendev.org/openstack/python-keystoneclient
  documentation: https://docs.openstack.org/python-keystoneclient/latest/

extra:
  recipe-maintainers:
    - tschoonj
