# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "19.1.1"

package:
  name: approval-utilities
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/approval-utilities/approval_utilities-${{ version }}.tar.gz
  sha256: 33bd42b568bddae052f97e4d2b2061835b2ddba2262b857dedd895bde975f450

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=69.0.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.12.0

tests:
  - python:
      imports:
        - approval_utilities
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Utilities for your production code that work well with approvaltests
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/approvals/ApprovalTests.Python

extra:
  recipe-maintainers:
    - apmorton
    - mgorny
