# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.17.0"

package:
  name: kfp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/kfp/kfp-${{ version }}.tar.gz
  sha256: 92dd2fc0cca5b073f14860253e936cc9e6901f871dfae355be6a9f8ea9d580c5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click >=8.1.8
    - click-option-group ==0.5.7
    - docstring_parser <1,>=0.7.3
    - google-api-core !=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
    - google-auth <3,>=1.6.1
    - google-cloud-storage <4,>=2.2.1
    - kfp-pipeline-spec <3,>=2.17.0
    - kfp-server-api <3,>=2.17.0
    - kubernetes <31,>=8.0.0
    - protobuf <7.0,>=6.31.1
    - pyyaml <7,>=5.3
    - requests ==2.32.5
    - requests-toolbelt <2,>=0.8.0
    - tabulate <1,>=0.8.6
    - urllib3 ==2.6.3
    - typing_extensions <5,>=3.7.4

tests:
  - python:
      imports:
        - kfp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/kubeflow/pipelines
  license: Apache-2.0
  license_file: LICENSE
  summary: Kubeflow Pipelines SDK
  description: |
    Kubeflow Pipelines SDK
  repository: https://github.com/kubeflow/pipelines/tree/master/sdk
  documentation: https://kubeflow-pipelines.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - tanguycdls
    - radcheb
    - ckadner
    - manuelwalserqc
    - tarrade
    - alanhdu

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: kfp
  cfe-upstream-registry: pypi
  cfe-upstream-name: kfp
  cfe-purls:
    - pkg:conda/kfp@${{ version }}?channel=conda-forge
    - pkg:pypi/kfp@${{ version }}
  cfe-upstream-repo: https://github.com/kubeflow/pipelines/tree/master/sdk
  cfe-upstream-homepage: https://github.com/kubeflow/pipelines
  cfe-import-names: [kfp]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/kfp-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-2.17.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T09:57:50Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T09:57:50Z
  cfe-local-build-status: build-clean-test-blocked
  cfe-local-build-datetime: 2026-08-18T09:57:50Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
