# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: tika-client
  version: "0.10.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tika_client-${{ version }}.tar.gz
  sha256: 3101e8b2482ae4cb7f87be13ada970ff691bdc3404d94cd52f5e57a09c99370c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4
    - anyio >=4.8
    - httpx >=0.27
    - typing_extensions

tests:
  - python:
      imports:
        - tika_client
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A modern REST client for Apache Tika server
  license: MPL-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/stumpylog/tika-client

extra:
  recipe-maintainers:
    - rxm7706
