
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: universal-mcp-markitdown
  version: "0.1.2"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/universal_mcp_markitdown-${{ version }}.tar.gz
  sha256: 3ded1af70b14b855549fb17cc2d15a19e54bc5b6a6b94eed827cf759c8c600f6

build:
  number: 0
  noarch: python
  script: 
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cp ${{ RECIPE_DIR }}/patch-files/universal_mcp_markitdown__init__.py ${{ SP_DIR }}/universal_mcp_markitdown/__init__.py
  python:
    entry_points:
      - universal_mcp_markitdown = universal_mcp_markitdown:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - markitdown >=0.1.1
    - universal-mcp >=0.1.22

tests:
  - python:
      imports:
        - universal_mcp_markitdown
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - universal_mcp_markitdown --help

about:
  summary: 'A Universal MCP Application: universal_mcp_markitdown'
  license: MIT
  license_file: LICENSE
  repository: https://github.com/universal-mcp/markitdown
  homepage: https://pypi.org/project/universal-mcp-markitdown/

extra:
  recipe-maintainers:
    - rxm7706

