c_stdlib_version:       # [osx and x86]
  - '10.15'             # [osx and x86]
MACOSX_SDK_VERSION:     # [osx and x86]
  - '10.15'             # [osx and x86]
channel_sources:
- conda-forge/label/rust_dev,conda-forge
