{% set name = "daft" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daft-{{ version }}.tar.gz
  sha256: 468fb0bc7c6d70f3cf4a4df2caa657263517a01aa22e23bf6987e3a613db0283

build:
  entry_points:
    - daft = daft.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - maturin >=1.5.0,<2.0.0
    - pip
  run:
    - python >=3.9
    - pyarrow >=8.0.0
    - fsspec
    - tqdm
    - typing_extensions >=4.0.0
    - packaging
    - mkdocs >=1.4

test:
  imports:
    - nav_hide_children
  commands:
    - pip check
    - daft --help
  requires:
    - pip

about:
  summary: Distributed Dataframes for Multimodal Data
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - src/parquet-format-safe/LICENSE-MIT
    - src/parquet-format-safe/LICENSE-APACHE
    - src/parquet-format-safe/src/thrift/varint/LICENSE
    - src/arrow2/LICENSE
    - src/parquet2/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
