# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: "getdaft"
  version: "0.6.7"
  python_min: '3.10'

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://github.com/Eventual-Inc/Daft/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6db23da58825e1418666313dae5cafb8a1dc97d8390ca527f512bb996a2771b6

build:
  number: 0

requirements:
  build:
    #- ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - pkg-config
    - make
    - cargo-bundle-licenses
    - if: unix
      then: unzip
    - nodejs
  host:
    - python
    - maturin >=1.5.0,<2.0.0
    - pip
    - openssl
    - xz-tools
  run:
    - python
    - pyarrow >=8.0.0
    - fsspec
    - tqdm
    - typing_extensions >=4.0.0

tests:
  - python:
      imports:
        - daft
  - script:
      - pip check
    requirements:
      run:
        - pip

about:
  license: Apache-2.0
  summary: Distributed Dataframes for Multimodal Data
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://www.getdaft.io/
  repository: https://github.com/Eventual-Inc/Daft
  documentation: https://www.getdaft.io/projects/docs/

extra:
  recipe-maintainers:
    - thewchan
    - rxm7706
    - whophil
