{% set name = "coderedcms" %}
{% set version = "6.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coderedcms-{{ version }}.tar.gz
  sha256: 5ee2fe9a1210cf63db4fdffa802311b233a394562a40d6bdc37c6ea2de273110

build:
  entry_points:
    - coderedcms = coderedcms.bin.coderedcms:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=78.0
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.8,<5  # should be the same as wagtail
    - django-eventtools ==1.0.*
    - django-bootstrap5 ==25.2
    - django >=4.2,<6.0
    - geocoder ==1.38.*
    - icalendar ==6.3.*
    # icalendar 6.0.1 requires tzdata, which is not installed
    - python-tzdata
    - wagtail >=7.0,<8.0
    - wagtail-cache ==3.*
    - wagtail-flexible-forms >=2.1,<3.0
    - wagtail-seo >=3.1,<4.0

test:
  imports:
    - coderedcms
  commands:
    - pip check
    - coderedcms --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/coderedcorp/coderedcms
  summary: Wagtail + CodeRed Extensions enabling rapid development of marketing-focused websites.
  dev_url: https://github.com/coderedcorp/coderedcms
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - coderedcms/static/coderedcms/vendor/bootstrap/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
