# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: coderedcms
  version: "6.0.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/coderedcms-${{ version }}.tar.gz
  sha256: 5ee2fe9a1210cf63db4fdffa802311b233a394562a40d6bdc37c6ea2de273110

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - coderedcms = coderedcms.bin.coderedcms:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=78.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - beautifulsoup4 >=4.8,<5  # should be the same as wagtail
    - django-eventtools ==1.0
    - django-bootstrap5 ==25.2
    - django >=4.2,<6.0
    - geocoder ==1.38
    - icalendar ==6.3
    # icalendar 6.0.1 requires tzdata, which is not installed
    - python-tzdata
    - wagtail >=7.0,<8.0
    - wagtail-cache ==3.*
    - wagtail-flexible-forms >=2.1,<3.0
    - wagtail-seo >=3.1,<4.0

tests:
  - python:
      imports:
        - coderedcms
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - coderedcms help
      - pip check

about:
  homepage: https://github.com/coderedcorp/coderedcms
  summary: Wagtail + CodeRed Extensions enabling rapid development of marketing-focused websites.
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - coderedcms/static/coderedcms/vendor/bootstrap/LICENSE
  repository: https://github.com/coderedcorp/coderedcms

extra:
  recipe-maintainers:
    - rxm7706
