--liquibase formatted sql
--changeset django-herald:1
--comment sqlmigrate herald_portal.0001_initial
--
-- Create model DeckExport
--
CREATE TABLE "herald_portal_deckexport" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "slug" varchar(255) NOT NULL, "topic" varchar(255) NOT NULL, "kind" varchar(64) NOT NULL, "export_date" date NOT NULL, "size" bigint NOT NULL CHECK ("size" >= 0), "content_type" varchar(255) NOT NULL, "sha256" varchar(64) NOT NULL UNIQUE, "source_commit" varchar(64) NOT NULL, "published_at" timestamp with time zone NOT NULL);
CREATE INDEX "herald_portal_deckexport_slug_ff7886bf" ON "herald_portal_deckexport" ("slug");
CREATE INDEX "herald_portal_deckexport_slug_ff7886bf_like" ON "herald_portal_deckexport" ("slug" varchar_pattern_ops);
CREATE INDEX "herald_portal_deckexport_sha256_d923d62f_like" ON "herald_portal_deckexport" ("sha256" varchar_pattern_ops);
--rollback DROP TABLE IF EXISTS "herald_portal_deckexport";
