--liquibase formatted sql
--changeset python-agent-platform:10
--comment sqlmigrate sites.0001_initial
--
-- Create model Site
--
CREATE TABLE "django_site" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "domain" varchar(100) NOT NULL, "name" varchar(50) NOT NULL);
