--liquibase formatted sql
--changeset python-agent-platform:22
--comment sqlmigrate warden_fabric.0002_fleet_run — Story 16.2 fleet run tables.

--
-- Create model FleetRepo
--
CREATE TABLE "warden_fabric_fleetrepo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "organisation" varchar(255) NOT NULL, "full_name" varchar(512) NOT NULL, "default_branch" varchar(255) NOT NULL, "clone_url" varchar(1024) NOT NULL, "archived" boolean NOT NULL, "last_seen_at" timestamp with time zone NOT NULL);
CREATE INDEX "warden_fabric_fleetrepo_organisation_8a0b0d0a" ON "warden_fabric_fleetrepo" ("organisation");
ALTER TABLE "warden_fabric_fleetrepo" ADD CONSTRAINT "warden_fabric_fleetrepo_org_name_uniq" UNIQUE ("organisation", "full_name");
--
-- Create model FleetRun
--
CREATE TABLE "warden_fabric_fleetrun" ("id" uuid NOT NULL PRIMARY KEY, "organisation" varchar(255) NOT NULL, "status" varchar(16) NOT NULL, "phase_index" smallint NOT NULL CHECK ("phase_index" >= 0), "error" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE INDEX "warden_fabric_fleetrun_organisation_6d0e0f0a" ON "warden_fabric_fleetrun" ("organisation");
--
-- Create model FleetRepoScan
--
CREATE TABLE "warden_fabric_fleetreposcan" ("id" uuid NOT NULL PRIMARY KEY, "commit_sha" varchar(64) NOT NULL, "report_json" text NOT NULL, "scan_exit_code" integer NULL, "status" varchar(16) NOT NULL, "error" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "fleet_repo_id" bigint NOT NULL, "fleet_run_id" uuid NOT NULL);
ALTER TABLE "warden_fabric_fleetreposcan" ADD CONSTRAINT "warden_fabric_fleetreposcan_fleet_repo_id_fk" FOREIGN KEY ("fleet_repo_id") REFERENCES "warden_fabric_fleetrepo" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "warden_fabric_fleetreposcan" ADD CONSTRAINT "warden_fabric_fleetreposcan_fleet_run_id_fk" FOREIGN KEY ("fleet_run_id") REFERENCES "warden_fabric_fleetrun" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "warden_fabric_fleetreposcan_fleet_repo_id_0a0b0c0d" ON "warden_fabric_fleetreposcan" ("fleet_repo_id");
CREATE INDEX "warden_fabric_fleetreposcan_fleet_run_id_1b1c1d1e" ON "warden_fabric_fleetreposcan" ("fleet_run_id");
ALTER TABLE "warden_fabric_fleetreposcan" ADD CONSTRAINT "warden_fabric_fleetreposcan_run_repo_uniq" UNIQUE ("fleet_run_id", "fleet_repo_id");
