--liquibase formatted sql
--changeset python-agent-platform:9
--comment sqlmigrate front_door.0002_console_parity
--
-- Create model ConsoleEditorialPage
--
CREATE TABLE "front_door_consoleeditorialpage" ("page_ptr_id" integer NOT NULL PRIMARY KEY, "surface_id" varchar(64) NOT NULL, "body" text NOT NULL);
--
-- Create model DetectorVerdict
--
CREATE TABLE "detector_verdict" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "detector" varchar(64) NOT NULL UNIQUE, "state" varchar(32) NOT NULL, "findings" integer NOT NULL CHECK ("findings" >= 0), "verdict" text NOT NULL, "captured_at" timestamp with time zone NOT NULL);
ALTER TABLE "front_door_consoleeditorialpage" ADD CONSTRAINT "front_door_consoleed_page_ptr_id_7bdc4422_fk_wagtailco" FOREIGN KEY ("page_ptr_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "detector_verdict_detector_2946e38d_like" ON "detector_verdict" ("detector" varchar_pattern_ops);
