--liquibase formatted sql
--changeset python-agent-platform:3
--comment sqlmigrate django_pyforge.0001_supervisor_tables
--
-- Create model RunState
--
CREATE TABLE "run_state" ("id" uuid NOT NULL PRIMARY KEY, "status" varchar(16) NOT NULL, CONSTRAINT "run_state_status_valid" CHECK ("status" IN ('pending', 'running', 'succeeded', 'failed')));
--
-- Create model McpHandle
--
CREATE TABLE "mcp_handles" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "handle" varchar(128) NOT NULL UNIQUE, "expires_at" timestamp with time zone NOT NULL, "run_id" uuid NOT NULL);
ALTER TABLE "mcp_handles" ADD CONSTRAINT "mcp_handles_run_id_0e0f2a1b_fk_run_state_id" FOREIGN KEY ("run_id") REFERENCES "run_state" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "mcp_handles_handle_9e462dc2_like" ON "mcp_handles" ("handle" varchar_pattern_ops);
CREATE INDEX "mcp_handles_run_id_0e0f2a1b" ON "mcp_handles" ("run_id");
