--liquibase formatted sql
--changeset python-agent-platform:16
--comment Wagtail core initial tables (wagtailcore_page) required by front_door.0001. Not in sqlmigrate-map.yaml -- 27.3 first-party only. sqlmigrate wagtailcore.0001_squashed against PostgreSQL (CRC 12.7). Later Wagtail migrations are not replayed here (isolated sqlmigrate emits unsafe ALTERs).
-- sqlmigrate wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field
--
-- Create model Page
--
CREATE TABLE "wagtailcore_page" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "path" varchar(255) NOT NULL UNIQUE, "depth" integer NOT NULL CHECK ("depth" >= 0), "numchild" integer NOT NULL CHECK ("numchild" >= 0), "title" varchar(255) NOT NULL, "slug" varchar(255) NOT NULL, "live" boolean NOT NULL, "has_unpublished_changes" boolean NOT NULL, "url_path" text NOT NULL, "seo_title" varchar(255) NOT NULL, "show_in_menus" boolean NOT NULL, "search_description" text NOT NULL, "go_live_at" timestamp with time zone NULL, "expire_at" timestamp with time zone NULL, "expired" boolean NOT NULL, "content_type_id" integer NOT NULL, "owner_id" bigint NULL, "locked" boolean NOT NULL, "latest_revision_created_at" timestamp with time zone NULL, "first_published_at" timestamp with time zone NULL);
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Create model GroupPagePermission
--
CREATE TABLE "wagtailcore_grouppagepermission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "permission_type" varchar(20) NOT NULL, "group_id" integer NOT NULL, "page_id" integer NOT NULL);
--
-- Alter unique_together for grouppagepermission (1 constraint(s))
--
ALTER TABLE "wagtailcore_grouppagepermission" ADD CONSTRAINT "wagtailcore_grouppageper_group_id_page_id_permiss_0898bdf8_uniq" UNIQUE ("group_id", "page_id", "permission_type");
--
-- Change Meta options on grouppagepermission
--
-- (no-op)
--
-- Create model PageRevision
--
CREATE TABLE "wagtailcore_pagerevision" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "submitted_for_moderation" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "content_json" text NOT NULL, "approved_go_live_at" timestamp with time zone NULL, "page_id" integer NOT NULL, "user_id" bigint NULL);
--
-- Change Meta options on pagerevision
--
-- (no-op)
--
-- Create model PageViewRestriction
--
CREATE TABLE "wagtailcore_pageviewrestriction" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(255) NOT NULL, "page_id" integer NOT NULL);
--
-- Change Meta options on pageviewrestriction
--
-- (no-op)
--
-- Create model Site
--
CREATE TABLE "wagtailcore_site" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "hostname" varchar(255) NOT NULL, "port" integer NOT NULL, "is_default_site" boolean NOT NULL, "root_page_id" integer NOT NULL);
--
-- Alter unique_together for site (1 constraint(s))
--
ALTER TABLE "wagtailcore_site" ADD CONSTRAINT "wagtailcore_site_hostname_port_2c626d70_uniq" UNIQUE ("hostname", "port");
--
-- Change Meta options on site
--
-- (no-op)
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
ALTER TABLE "wagtailcore_page" ADD CONSTRAINT "wagtailcore_page_content_type_id_c28424df_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "wagtailcore_page" ADD CONSTRAINT "wagtailcore_page_owner_id_fbf7c332_fk_users_user_id" FOREIGN KEY ("owner_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailcore_page_path_98eba2c8_like" ON "wagtailcore_page" ("path" varchar_pattern_ops);
CREATE INDEX "wagtailcore_page_slug_e7c11b8f" ON "wagtailcore_page" ("slug");
CREATE INDEX "wagtailcore_page_slug_e7c11b8f_like" ON "wagtailcore_page" ("slug" varchar_pattern_ops);
CREATE INDEX "wagtailcore_page_content_type_id_c28424df" ON "wagtailcore_page" ("content_type_id");
CREATE INDEX "wagtailcore_page_owner_id_fbf7c332" ON "wagtailcore_page" ("owner_id");
ALTER TABLE "wagtailcore_grouppagepermission" ADD CONSTRAINT "wagtailcore_grouppag_group_id_fc07e671_fk_auth_grou" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "wagtailcore_grouppagepermission" ADD CONSTRAINT "wagtailcore_grouppag_page_id_710b114a_fk_wagtailco" FOREIGN KEY ("page_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailcore_grouppagepermission_group_id_fc07e671" ON "wagtailcore_grouppagepermission" ("group_id");
CREATE INDEX "wagtailcore_grouppagepermission_page_id_710b114a" ON "wagtailcore_grouppagepermission" ("page_id");
ALTER TABLE "wagtailcore_pagerevision" ADD CONSTRAINT "wagtailcore_pagerevi_page_id_d421cc1d_fk_wagtailco" FOREIGN KEY ("page_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "wagtailcore_pagerevision" ADD CONSTRAINT "wagtailcore_pagerevision_user_id_2409d2f4_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailcore_pagerevision_page_id_d421cc1d" ON "wagtailcore_pagerevision" ("page_id");
CREATE INDEX "wagtailcore_pagerevision_user_id_2409d2f4" ON "wagtailcore_pagerevision" ("user_id");
ALTER TABLE "wagtailcore_pageviewrestriction" ADD CONSTRAINT "wagtailcore_pageview_page_id_15a8bea6_fk_wagtailco" FOREIGN KEY ("page_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailcore_pageviewrestriction_page_id_15a8bea6" ON "wagtailcore_pageviewrestriction" ("page_id");
ALTER TABLE "wagtailcore_site" ADD CONSTRAINT "wagtailcore_site_root_page_id_e02fb95c_fk_wagtailcore_page_id" FOREIGN KEY ("root_page_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailcore_site_hostname_96b20b46" ON "wagtailcore_site" ("hostname");
CREATE INDEX "wagtailcore_site_hostname_96b20b46_like" ON "wagtailcore_site" ("hostname" varchar_pattern_ops);
CREATE INDEX "wagtailcore_site_root_page_id_e02fb95c" ON "wagtailcore_site" ("root_page_id");

