--liquibase formatted sql
--changeset python-agent-platform:17
--comment django_celery_beat tables (CRC 12.7 leftover). Not in sqlmigrate-map.yaml — 27.3 first-party only. sqlmigrate all django_celery_beat migrations against PostgreSQL; BEGIN/COMMIT stripped. ALTER COLUMN TYPE lines are varchar widenings.
-- sqlmigrate django_celery_beat.0001_initial

--
-- Create model CrontabSchedule
--
CREATE TABLE "django_celery_beat_crontabschedule" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "minute" varchar(64) NOT NULL, "hour" varchar(64) NOT NULL, "day_of_week" varchar(64) NOT NULL, "day_of_month" varchar(64) NOT NULL, "month_of_year" varchar(64) NOT NULL);
--
-- Create model IntervalSchedule
--
CREATE TABLE "django_celery_beat_intervalschedule" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "every" integer NOT NULL, "period" varchar(24) NOT NULL);
--
-- Create model PeriodicTask
--
CREATE TABLE "django_celery_beat_periodictask" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL UNIQUE, "task" varchar(200) NOT NULL, "args" text NOT NULL, "kwargs" text NOT NULL, "queue" varchar(200) NULL, "exchange" varchar(200) NULL, "routing_key" varchar(200) NULL, "expires" timestamp with time zone NULL, "enabled" boolean NOT NULL, "last_run_at" timestamp with time zone NULL, "total_run_count" integer NOT NULL CHECK ("total_run_count" >= 0), "date_changed" timestamp with time zone NOT NULL, "description" text NOT NULL, "crontab_id" integer NULL, "interval_id" integer NULL);
--
-- Create model PeriodicTasks
--
CREATE TABLE "django_celery_beat_periodictasks" ("ident" smallint NOT NULL PRIMARY KEY, "last_update" timestamp with time zone NOT NULL);
ALTER TABLE "django_celery_beat_periodictask" ADD CONSTRAINT "django_celery_beat_p_crontab_id_d3cba168_fk_django_ce" FOREIGN KEY ("crontab_id") REFERENCES "django_celery_beat_crontabschedule" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_celery_beat_periodictask" ADD CONSTRAINT "django_celery_beat_p_interval_id_a8ca27da_fk_django_ce" FOREIGN KEY ("interval_id") REFERENCES "django_celery_beat_intervalschedule" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_celery_beat_periodictask_name_265a36b7_like" ON "django_celery_beat_periodictask" ("name" varchar_pattern_ops);
CREATE INDEX "django_celery_beat_periodictask_crontab_id_d3cba168" ON "django_celery_beat_periodictask" ("crontab_id");
CREATE INDEX "django_celery_beat_periodictask_interval_id_a8ca27da" ON "django_celery_beat_periodictask" ("interval_id");

-- sqlmigrate django_celery_beat.0002_auto_20161118_0346

--
-- Create model SolarSchedule
--
CREATE TABLE "django_celery_beat_solarschedule" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event" varchar(24) NOT NULL, "latitude" numeric(9, 6) NOT NULL, "longitude" numeric(9, 6) NOT NULL);
--
-- Add field solar to periodictask
--
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" integer NULL CONSTRAINT "django_celery_beat_p_solar_id_a87ce72c_fk_django_ce" REFERENCES "django_celery_beat_solarschedule"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "django_celery_beat_p_solar_id_a87ce72c_fk_django_ce" IMMEDIATE;
CREATE INDEX "django_celery_beat_periodictask_solar_id_a87ce72c" ON "django_celery_beat_periodictask" ("solar_id");

-- sqlmigrate django_celery_beat.0003_auto_20161209_0049

--
-- Change Meta options on solarschedule
--
-- (no-op)
--
-- Alter unique_together for solarschedule (1 constraint(s))
--
ALTER TABLE "django_celery_beat_solarschedule" ADD CONSTRAINT "django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq" UNIQUE ("event", "latitude", "longitude");

-- sqlmigrate django_celery_beat.0004_auto_20170221_0000

--
-- Alter field longitude on solarschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0005_add_solarschedule_events_choices

--
-- Alter field event on solarschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0006_auto_20180210_1226

--
-- Alter field day_of_month on crontabschedule
--
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "day_of_month" TYPE varchar(124);
--
-- Alter field hour on crontabschedule
--
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "hour" TYPE varchar(96);
--
-- Alter field minute on crontabschedule
--
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "minute" TYPE varchar(240);

-- sqlmigrate django_celery_beat.0006_auto_20180322_0932

--
-- Change Meta options on crontabschedule
--
-- (no-op)
--
-- Add field timezone to crontabschedule
--
ALTER TABLE "django_celery_beat_crontabschedule" ADD COLUMN "timezone" varchar(63) DEFAULT 'UTC' NOT NULL;
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "timezone" DROP DEFAULT;
--
-- Alter field day_of_month on crontabschedule
--
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "day_of_month" TYPE varchar(124);
--
-- Alter field hour on crontabschedule
--
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "hour" TYPE varchar(96);
--
-- Alter field minute on crontabschedule
--
ALTER TABLE "django_celery_beat_crontabschedule" ALTER COLUMN "minute" TYPE varchar(240);

-- sqlmigrate django_celery_beat.0006_periodictask_priority

--
-- Add field priority to periodictask
--
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "priority" integer NULL CHECK ("priority" >= 0);

-- sqlmigrate django_celery_beat.0007_auto_20180521_0826

--
-- Add field one_off to periodictask
--
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "one_off" boolean DEFAULT false NOT NULL;
ALTER TABLE "django_celery_beat_periodictask" ALTER COLUMN "one_off" DROP DEFAULT;
--
-- Add field start_time to periodictask
--
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "start_time" timestamp with time zone NULL;

-- sqlmigrate django_celery_beat.0008_auto_20180914_1922

--
-- Alter field day_of_month on crontabschedule
--
-- (no-op)
--
-- Alter field day_of_week on crontabschedule
--
-- (no-op)
--
-- Alter field hour on crontabschedule
--
-- (no-op)
--
-- Alter field minute on crontabschedule
--
-- (no-op)
--
-- Alter field month_of_year on crontabschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0009_periodictask_headers

--
-- Add field headers to periodictask
--
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "headers" text DEFAULT '{}' NOT NULL;
ALTER TABLE "django_celery_beat_periodictask" ALTER COLUMN "headers" DROP DEFAULT;

-- sqlmigrate django_celery_beat.0010_auto_20190429_0326

--
-- Alter field day_of_month on crontabschedule
--
-- (no-op)
--
-- Alter field day_of_week on crontabschedule
--
-- (no-op)
--
-- Alter field hour on crontabschedule
--
-- (no-op)
--
-- Alter field minute on crontabschedule
--
-- (no-op)
--
-- Alter field month_of_year on crontabschedule
--
-- (no-op)
--
-- Alter field timezone on crontabschedule
--
-- (no-op)
--
-- Alter field every on intervalschedule
--
-- (no-op)
--
-- Alter field period on intervalschedule
--
-- (no-op)
--
-- Alter field args on periodictask
--
-- (no-op)
--
-- Alter field crontab on periodictask
--
-- (no-op)
--
-- Alter field date_changed on periodictask
--
-- (no-op)
--
-- Alter field description on periodictask
--
-- (no-op)
--
-- Alter field enabled on periodictask
--
-- (no-op)
--
-- Alter field exchange on periodictask
--
-- (no-op)
--
-- Alter field expires on periodictask
--
-- (no-op)
--
-- Alter field headers on periodictask
--
-- (no-op)
--
-- Alter field interval on periodictask
--
-- (no-op)
--
-- Alter field kwargs on periodictask
--
-- (no-op)
--
-- Alter field last_run_at on periodictask
--
-- (no-op)
--
-- Alter field name on periodictask
--
-- (no-op)
--
-- Alter field one_off on periodictask
--
-- (no-op)
--
-- Alter field priority on periodictask
--
-- (no-op)
--
-- Alter field queue on periodictask
--
-- (no-op)
--
-- Alter field routing_key on periodictask
--
-- (no-op)
--
-- Alter field solar on periodictask
--
-- (no-op)
--
-- Alter field start_time on periodictask
--
-- (no-op)
--
-- Alter field task on periodictask
--
-- (no-op)
--
-- Alter field total_run_count on periodictask
--
-- (no-op)
--
-- Alter field event on solarschedule
--
-- (no-op)
--
-- Alter field latitude on solarschedule
--
-- (no-op)
--
-- Alter field longitude on solarschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0011_auto_20190508_0153

--
-- Create model ClockedSchedule
--
CREATE TABLE "django_celery_beat_clockedschedule" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "clocked_time" timestamp with time zone NOT NULL, "enabled" boolean NOT NULL);
--
-- Add field clocked to periodictask
--
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "clocked_id" integer NULL CONSTRAINT "django_celery_beat_p_clocked_id_47a69f82_fk_django_ce" REFERENCES "django_celery_beat_clockedschedule"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "django_celery_beat_p_clocked_id_47a69f82_fk_django_ce" IMMEDIATE;
CREATE INDEX "django_celery_beat_periodictask_clocked_id_47a69f82" ON "django_celery_beat_periodictask" ("clocked_id");

-- sqlmigrate django_celery_beat.0012_periodictask_expire_seconds

--
-- Add field expire_seconds to periodictask
--
ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "expire_seconds" integer NULL CHECK ("expire_seconds" >= 0);

-- sqlmigrate django_celery_beat.0013_auto_20200609_0727

--
-- Alter field timezone on crontabschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0014_remove_clockedschedule_enabled

--
-- Remove field enabled from clockedschedule
--
ALTER TABLE "django_celery_beat_clockedschedule" DROP COLUMN "enabled" CASCADE;

-- sqlmigrate django_celery_beat.0015_edit_solarschedule_events_choices

--
-- Alter field event on solarschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0016_alter_crontabschedule_timezone

--
-- Alter field timezone on crontabschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0017_alter_crontabschedule_month_of_year

--
-- Alter field month_of_year on crontabschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0018_improve_crontab_helptext

--
-- Alter field day_of_week on crontabschedule
--
-- (no-op)

-- sqlmigrate django_celery_beat.0019_alter_periodictasks_options

--
-- Change Meta options on periodictasks
--
-- (no-op)
