--liquibase formatted sql
--changeset python-agent-platform:18
--comment Third-party 0001 tables (admin, taggit, Wagtail satellites) plus allauth account+socialaccount chains. Not in sqlmigrate-map.yaml. Isolated mfa sqlmigrate fails (constraint count); MFA tables remain migrate --fake. Later Wagtailcore migrations still not replayed (unsafe ALTERs, same as :16).
-- sqlmigrate admin.0001_initial

--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");

-- sqlmigrate taggit.0001_initial

--
-- Create model Tag
--
CREATE TABLE "taggit_tag" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL UNIQUE, "slug" varchar(100) NOT NULL UNIQUE);
--
-- Create model TaggedItem
--
CREATE TABLE "taggit_taggeditem" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "object_id" integer NOT NULL, "content_type_id" integer NOT NULL, "tag_id" integer NOT NULL);
CREATE INDEX "taggit_tag_name_58eb2ed9_like" ON "taggit_tag" ("name" varchar_pattern_ops);
CREATE INDEX "taggit_tag_slug_6be58b2c_like" ON "taggit_tag" ("slug" varchar_pattern_ops);
ALTER TABLE "taggit_taggeditem" ADD CONSTRAINT "taggit_taggeditem_content_type_id_9957a03c_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "taggit_taggeditem" ADD CONSTRAINT "taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id" FOREIGN KEY ("tag_id") REFERENCES "taggit_tag" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "taggit_taggeditem_object_id_e2d7d1df" ON "taggit_taggeditem" ("object_id");
CREATE INDEX "taggit_taggeditem_content_type_id_9957a03c" ON "taggit_taggeditem" ("content_type_id");
CREATE INDEX "taggit_taggeditem_tag_id_f4f5b767" ON "taggit_taggeditem" ("tag_id");

-- sqlmigrate wagtailimages.0001_initial

--
-- Create model Filter
--
CREATE TABLE "wagtailimages_filter" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "spec" varchar(255) NOT NULL);
--
-- Create model Image
--
CREATE TABLE "wagtailimages_image" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "file" varchar(100) NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "created_at" timestamp with time zone NOT NULL, "focal_point_x" integer NULL CHECK ("focal_point_x" >= 0), "focal_point_y" integer NULL CHECK ("focal_point_y" >= 0), "focal_point_width" integer NULL CHECK ("focal_point_width" >= 0), "focal_point_height" integer NULL CHECK ("focal_point_height" >= 0), "uploaded_by_user_id" bigint NULL);
--
-- Create model Rendition
--
CREATE TABLE "wagtailimages_rendition" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "file" varchar(100) NOT NULL, "width" integer NOT NULL, "height" integer NOT NULL, "focal_point_key" varchar(18) NULL, "filter_id" integer NOT NULL, "image_id" integer NOT NULL);
--
-- Alter unique_together for rendition (1 constraint(s))
--
ALTER TABLE "wagtailimages_rendition" ADD CONSTRAINT "wagtailimages_rendition_image_id_filter_id_focal_03110280_uniq" UNIQUE ("image_id", "filter_id", "focal_point_key");
CREATE INDEX "wagtailimages_filter_spec_42ad6e02" ON "wagtailimages_filter" ("spec");
CREATE INDEX "wagtailimages_filter_spec_42ad6e02_like" ON "wagtailimages_filter" ("spec" varchar_pattern_ops);
ALTER TABLE "wagtailimages_image" ADD CONSTRAINT "wagtailimages_image_uploaded_by_user_id_5d73dc75_fk_users_use" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailimages_image_uploaded_by_user_id_5d73dc75" ON "wagtailimages_image" ("uploaded_by_user_id");
ALTER TABLE "wagtailimages_rendition" ADD CONSTRAINT "wagtailimages_rendit_filter_id_7fc52567_fk_wagtailim" FOREIGN KEY ("filter_id") REFERENCES "wagtailimages_filter" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "wagtailimages_rendition" ADD CONSTRAINT "wagtailimages_rendit_image_id_3e1fd774_fk_wagtailim" FOREIGN KEY ("image_id") REFERENCES "wagtailimages_image" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailimages_rendition_filter_id_7fc52567" ON "wagtailimages_rendition" ("filter_id");
CREATE INDEX "wagtailimages_rendition_image_id_3e1fd774" ON "wagtailimages_rendition" ("image_id");

-- sqlmigrate wagtaildocs.0001_initial

--
-- Create model Document
--
CREATE TABLE "wagtaildocs_document" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "file" varchar(100) NOT NULL, "created_at" timestamp with time zone NOT NULL, "uploaded_by_user_id" bigint NULL);
ALTER TABLE "wagtaildocs_document" ADD CONSTRAINT "wagtaildocs_document_uploaded_by_user_id_17258b41_fk_users_use" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtaildocs_document_uploaded_by_user_id_17258b41" ON "wagtaildocs_document" ("uploaded_by_user_id");

-- sqlmigrate wagtailusers.0001_initial

--
-- Create model UserProfile
--
CREATE TABLE "wagtailusers_userprofile" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "submitted_notifications" boolean NOT NULL, "approved_notifications" boolean NOT NULL, "rejected_notifications" boolean NOT NULL, "user_id" bigint NOT NULL UNIQUE);
ALTER TABLE "wagtailusers_userprofile" ADD CONSTRAINT "wagtailusers_userprofile_user_id_59c92331_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;

-- sqlmigrate wagtailredirects.0001_initial

--
-- Create model Redirect
--
CREATE TABLE "wagtailredirects_redirect" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "old_path" varchar(255) NOT NULL UNIQUE, "is_permanent" boolean NOT NULL, "redirect_link" varchar(200) NOT NULL, "redirect_page_id" integer NULL, "site_id" integer NULL);
ALTER TABLE "wagtailredirects_redirect" ADD CONSTRAINT "wagtailredirects_red_redirect_page_id_b5728a8f_fk_wagtailco" FOREIGN KEY ("redirect_page_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "wagtailredirects_redirect" ADD CONSTRAINT "wagtailredirects_red_site_id_780a0e1e_fk_wagtailco" FOREIGN KEY ("site_id") REFERENCES "wagtailcore_site" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailredirects_redirect_old_path_bb35247b_like" ON "wagtailredirects_redirect" ("old_path" varchar_pattern_ops);
CREATE INDEX "wagtailredirects_redirect_redirect_page_id_b5728a8f" ON "wagtailredirects_redirect" ("redirect_page_id");
CREATE INDEX "wagtailredirects_redirect_site_id_780a0e1e" ON "wagtailredirects_redirect" ("site_id");

-- sqlmigrate wagtailembeds.0001_initial

--
-- Create model Embed
--
CREATE TABLE "wagtailembeds_embed" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "url" varchar(200) NOT NULL, "max_width" smallint NULL, "type" varchar(10) NOT NULL, "html" text NOT NULL, "title" text NOT NULL, "author_name" text NOT NULL, "provider_name" text NOT NULL, "thumbnail_url" varchar(200) NULL, "width" integer NULL, "height" integer NULL, "last_updated" timestamp with time zone NOT NULL);
--
-- Alter unique_together for embed (1 constraint(s))
--
ALTER TABLE "wagtailembeds_embed" ADD CONSTRAINT "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE ("url", "max_width");

-- sqlmigrate wagtailforms.0001_initial

--
-- Create model FormSubmission
--
CREATE TABLE "wagtailforms_formsubmission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "form_data" text NOT NULL, "submit_time" timestamp with time zone NOT NULL, "page_id" integer NOT NULL);
ALTER TABLE "wagtailforms_formsubmission" ADD CONSTRAINT "wagtailforms_formsub_page_id_e48e93e7_fk_wagtailco" FOREIGN KEY ("page_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailforms_formsubmission_page_id_e48e93e7" ON "wagtailforms_formsubmission" ("page_id");

-- sqlmigrate wagtailsearch.0001_initial

--
-- Create model EditorsPick
--
CREATE TABLE "wagtailsearch_editorspick" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "sort_order" integer NULL, "description" text NOT NULL, "page_id" integer NOT NULL);
--
-- Create model Query
--
CREATE TABLE "wagtailsearch_query" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "query_string" varchar(255) NOT NULL UNIQUE);
--
-- Create model QueryDailyHits
--
CREATE TABLE "wagtailsearch_querydailyhits" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "hits" integer NOT NULL, "query_id" integer NOT NULL);
--
-- Alter unique_together for querydailyhits (1 constraint(s))
--
ALTER TABLE "wagtailsearch_querydailyhits" ADD CONSTRAINT "wagtailsearch_querydailyhits_query_id_date_1dd232e6_uniq" UNIQUE ("query_id", "date");
--
-- Add field query to editorspick
--
ALTER TABLE "wagtailsearch_editorspick" ADD COLUMN "query_id" integer NOT NULL CONSTRAINT "wagtailsearch_editor_query_id_c6eee4a0_fk_wagtailse" REFERENCES "wagtailsearch_query"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "wagtailsearch_editor_query_id_c6eee4a0_fk_wagtailse" IMMEDIATE;
ALTER TABLE "wagtailsearch_editorspick" ADD CONSTRAINT "wagtailsearch_editor_page_id_28cbc274_fk_wagtailco" FOREIGN KEY ("page_id") REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailsearch_editorspick_page_id_28cbc274" ON "wagtailsearch_editorspick" ("page_id");
CREATE INDEX "wagtailsearch_query_query_string_e785ea07_like" ON "wagtailsearch_query" ("query_string" varchar_pattern_ops);
ALTER TABLE "wagtailsearch_querydailyhits" ADD CONSTRAINT "wagtailsearch_queryd_query_id_2185994b_fk_wagtailse" FOREIGN KEY ("query_id") REFERENCES "wagtailsearch_query" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "wagtailsearch_querydailyhits_query_id_2185994b" ON "wagtailsearch_querydailyhits" ("query_id");
CREATE INDEX "wagtailsearch_editorspick_query_id_c6eee4a0" ON "wagtailsearch_editorspick" ("query_id");

-- SKIP wagtailadmin.0001_initial: Cannot find a migration matching '0001_initial' from app 'wagtailadmin'. Is it in INSTALLED_APPS?

-- sqlmigrate account.0001_initial

--
-- Create model EmailAddress
--
CREATE TABLE "account_emailaddress" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "email" varchar(75) NOT NULL UNIQUE, "verified" boolean NOT NULL, "primary" boolean NOT NULL, "user_id" bigint NOT NULL);
--
-- Create model EmailConfirmation
--
CREATE TABLE "account_emailconfirmation" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created" timestamp with time zone NOT NULL, "sent" timestamp with time zone NULL, "key" varchar(64) NOT NULL UNIQUE, "email_address_id" integer NOT NULL);
ALTER TABLE "account_emailaddress" ADD CONSTRAINT "account_emailaddress_user_id_2c513194_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "account_emailaddress_email_03be32b2_like" ON "account_emailaddress" ("email" varchar_pattern_ops);
CREATE INDEX "account_emailaddress_user_id_2c513194" ON "account_emailaddress" ("user_id");
ALTER TABLE "account_emailconfirmation" ADD CONSTRAINT "account_emailconfirm_email_address_id_5b7f8c58_fk_account_e" FOREIGN KEY ("email_address_id") REFERENCES "account_emailaddress" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "account_emailconfirmation_key_f43612bd_like" ON "account_emailconfirmation" ("key" varchar_pattern_ops);
CREATE INDEX "account_emailconfirmation_email_address_id_5b7f8c58" ON "account_emailconfirmation" ("email_address_id");

-- sqlmigrate account.0002_email_max_length

--
-- Alter field email on emailaddress
--
ALTER TABLE "account_emailaddress" ALTER COLUMN "email" TYPE varchar(254);

-- sqlmigrate account.0003_alter_emailaddress_create_unique_verified_email

--
-- Alter unique_together for emailaddress (1 constraint(s))
--
ALTER TABLE "account_emailaddress" ADD CONSTRAINT "account_emailaddress_user_id_email_987c8728_uniq" UNIQUE ("user_id", "email");
--
-- Create constraint unique_verified_email on model emailaddress
--
CREATE UNIQUE INDEX "unique_verified_email" ON "account_emailaddress" ("email") WHERE "verified";

-- sqlmigrate account.0004_alter_emailaddress_drop_unique_email

--
-- Alter field email on emailaddress
--
DROP INDEX IF EXISTS "account_emailaddress_email_03be32b2_like";

-- sqlmigrate account.0005_emailaddress_idx_upper_email

--
-- Create index account_emailaddress_upper on Upper(F(email)) on model emailaddress
--
CREATE INDEX "account_emailaddress_upper" ON "account_emailaddress" ((UPPER("email")));

-- sqlmigrate account.0006_emailaddress_lower

--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL

-- sqlmigrate account.0007_emailaddress_idx_email

--
-- Remove index account_emailaddress_upper from emailaddress
--
DROP INDEX IF EXISTS "account_emailaddress_upper";
--
-- Alter field email on emailaddress
--
CREATE INDEX "account_emailaddress_email_03be32b2" ON "account_emailaddress" ("email");
CREATE INDEX "account_emailaddress_email_03be32b2_like" ON "account_emailaddress" ("email" varchar_pattern_ops);

-- sqlmigrate account.0008_emailaddress_unique_primary_email_fixup

--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL

-- sqlmigrate account.0009_emailaddress_unique_primary_email

--
-- Create constraint unique_primary_email on model emailaddress
--
CREATE UNIQUE INDEX "unique_primary_email" ON "account_emailaddress" ("user_id", "primary") WHERE "primary";

-- sqlmigrate socialaccount.0001_initial

--
-- Create model SocialAccount
--
CREATE TABLE "socialaccount_socialaccount" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "provider" varchar(30) NOT NULL, "uid" varchar(191) NOT NULL, "last_login" timestamp with time zone NOT NULL, "date_joined" timestamp with time zone NOT NULL, "extra_data" text NOT NULL, "user_id" bigint NOT NULL);
--
-- Create model SocialApp
--
CREATE TABLE "socialaccount_socialapp" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "provider" varchar(30) NOT NULL, "name" varchar(40) NOT NULL, "client_id" varchar(100) NOT NULL, "secret" varchar(100) NOT NULL, "key" varchar(100) NOT NULL);
CREATE TABLE "socialaccount_socialapp_sites" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "socialapp_id" integer NOT NULL, "site_id" integer NOT NULL);
--
-- Create model SocialToken
--
CREATE TABLE "socialaccount_socialtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" text NOT NULL, "token_secret" text NOT NULL, "expires_at" timestamp with time zone NULL, "account_id" integer NOT NULL, "app_id" integer NOT NULL);
--
-- Alter unique_together for socialtoken (1 constraint(s))
--
ALTER TABLE "socialaccount_socialtoken" ADD CONSTRAINT "socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq" UNIQUE ("app_id", "account_id");
--
-- Alter unique_together for socialaccount (1 constraint(s))
--
ALTER TABLE "socialaccount_socialaccount" ADD CONSTRAINT "socialaccount_socialaccount_provider_uid_fc810c6e_uniq" UNIQUE ("provider", "uid");
ALTER TABLE "socialaccount_socialaccount" ADD CONSTRAINT "socialaccount_socialaccount_user_id_8146e70c_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "socialaccount_socialaccount_user_id_8146e70c" ON "socialaccount_socialaccount" ("user_id");
ALTER TABLE "socialaccount_socialapp_sites" ADD CONSTRAINT "socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq" UNIQUE ("socialapp_id", "site_id");
ALTER TABLE "socialaccount_socialapp_sites" ADD CONSTRAINT "socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc" FOREIGN KEY ("socialapp_id") REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "socialaccount_socialapp_sites" ADD CONSTRAINT "socialaccount_social_site_id_2579dee5_fk_django_si" FOREIGN KEY ("site_id") REFERENCES "django_site" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "socialaccount_socialapp_sites_socialapp_id_97fb6e7d" ON "socialaccount_socialapp_sites" ("socialapp_id");
CREATE INDEX "socialaccount_socialapp_sites_site_id_2579dee5" ON "socialaccount_socialapp_sites" ("site_id");
ALTER TABLE "socialaccount_socialtoken" ADD CONSTRAINT "socialaccount_social_account_id_951f210e_fk_socialacc" FOREIGN KEY ("account_id") REFERENCES "socialaccount_socialaccount" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "socialaccount_socialtoken" ADD CONSTRAINT "socialaccount_social_app_id_636a42d7_fk_socialacc" FOREIGN KEY ("app_id") REFERENCES "socialaccount_socialapp" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "socialaccount_socialtoken_account_id_951f210e" ON "socialaccount_socialtoken" ("account_id");
CREATE INDEX "socialaccount_socialtoken_app_id_636a42d7" ON "socialaccount_socialtoken" ("app_id");

-- sqlmigrate socialaccount.0002_token_max_lengths

--
-- Alter field uid on socialaccount
--
-- (no-op)
--
-- Alter field client_id on socialapp
--
ALTER TABLE "socialaccount_socialapp" ALTER COLUMN "client_id" TYPE varchar(191);
--
-- Alter field key on socialapp
--
ALTER TABLE "socialaccount_socialapp" ALTER COLUMN "key" TYPE varchar(191);
--
-- Alter field secret on socialapp
--
ALTER TABLE "socialaccount_socialapp" ALTER COLUMN "secret" TYPE varchar(191);

-- sqlmigrate socialaccount.0003_extra_data_default_dict

--
-- Alter field extra_data on socialaccount
--
-- (no-op)

-- sqlmigrate socialaccount.0004_app_provider_id_settings

--
-- Add field provider_id to socialapp
--
ALTER TABLE "socialaccount_socialapp" ADD COLUMN "provider_id" varchar(200) DEFAULT '' NOT NULL;
ALTER TABLE "socialaccount_socialapp" ALTER COLUMN "provider_id" DROP DEFAULT;
--
-- Add field settings to socialapp
--
ALTER TABLE "socialaccount_socialapp" ADD COLUMN "settings" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "socialaccount_socialapp" ALTER COLUMN "settings" DROP DEFAULT;
--
-- Alter field provider on socialaccount
--
ALTER TABLE "socialaccount_socialaccount" ALTER COLUMN "provider" TYPE varchar(200);

-- sqlmigrate socialaccount.0005_socialtoken_nullable_app

--
-- Alter field app on socialtoken
--
ALTER TABLE "socialaccount_socialtoken" ALTER COLUMN "app_id" DROP NOT NULL;

-- sqlmigrate socialaccount.0006_alter_socialaccount_extra_data

--
-- Alter field extra_data on socialaccount
--
ALTER TABLE "socialaccount_socialaccount" ALTER COLUMN "extra_data" TYPE jsonb USING "extra_data"::jsonb;
