# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: shareplum
  version: "0.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/SharePlum-${{ version }}.tar.gz
  sha256: 07a45d48920450092e56c33846fe17768d4611dc83a7314ef0140e57dee52966

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - requests
    - requests_ntlm
    - requests-toolbelt
    - lxml

tests:
  - python:
      imports:
        - shareplum
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Python SharePoint API
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/mdowds/shareplum

extra:
  recipe-maintainers:
    - ajaypnair09
