# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: FormEncode
  version: "2.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | lower }}-${{ version }}.tar.gz
  sha256: e17f16199d232e54f67912004f3ad333cdbbb81a1a1a10238acf09bab99f9199

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=7
  run:
    - python >=${{ python_min }}
    - setuptools

tests:
  - python:
      imports:
        - formencode
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: MIT
  license_file: LICENSE.txt
  summary: HTML form validation, generation, and conversion package
  homepage: http://formencode.org
  repository: https://github.com/formencode/formencode

extra:
  recipe-maintainers:
    - windelbouwman
    - synapticarbors
