# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.23.2"

package:
  name: prometheus-flask-exporter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/prometheus-flask-exporter/prometheus_flask_exporter-${{ version }}.tar.gz
  sha256: 41fc9bbd7d48cc958ed8384aacf60c3621d9e903768be61c4e7f0c63872eaf1a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - prometheus_client
    - flask

tests:
  - python:
      imports:
        - prometheus_flask_exporter
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/rycus86/prometheus_flask_exporter
  license: MIT
  license_file: LICENSE
  summary: Prometheus metrics exporter for Flask
  description: |
    Prometheus metrics exporter for Flask

extra:
  recipe-maintainers:
    - xhochy

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: prometheus_flask_exporter
  cfe-upstream-registry: pypi
  cfe-upstream-name: prometheus-flask-exporter
  cfe-purls:
    - pkg:conda/prometheus_flask_exporter@${{ version }}?channel=conda-forge
    - pkg:pypi/prometheus-flask-exporter@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/rycus86/prometheus_flask_exporter
  cfe-import-names: [prometheus_flask_exporter]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/prometheus_flask_exporter-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.23.2

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T03:16:52Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T03:16:52Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T03:16:52Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
