{% set name = "pydocket" %}
{% set version = "0.15.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydocket-{{ version }}.tar.gz
  sha256: b3af47702a293dd1da2e5e0f8f73f27fd3b3c95e36de72a2f71026d16908d5ba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - docket = docket.__main__:app

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - cachetools >=5.0.0
    - cloudpickle >=3.1.1
    - exceptiongroup >=1.2.0
    - fakeredis >=2.32.1
    - opentelemetry-api >=1.33.0
    - opentelemetry-exporter-prometheus >=0.60b0
    - opentelemetry-instrumentation >=0.60b0
    # prometheus_client is conda-forge package name for prometheus-client pip package
    - prometheus_client >=0.21.1
    - py-key-value-aio >=0.3.0
    - python-json-logger >=2.0.7
    - redis-py >=5
    - rich >=13.9.4
    - typer >=0.15.1
    # typing_extensions is conda-forge package name for typing-extensions pip package
    - typing-extensions >=4.12.0

test:
  imports:
    - docket
  commands:
    - pip check
    - docket --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chrisguidry/docket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A distributed background task system for Python functions
  description: |
    Docket is a distributed background task system for Python functions with a
    focus on scheduling future work. It requires a Redis server with Streams
    support (Redis 5.0.0+).
  dev_url: https://github.com/chrisguidry/docket
  doc_url: https://github.com/chrisguidry/docket

extra:
  recipe-maintainers:
    - chrisguidry
    - zzstoatzz
