# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: toolbox-core
  version: "0.5.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/toolbox_core-${{ version }}.tar.gz
  sha256: a6bd7c4ae613b8603b31988483b4c53a0dc7b88b640978d6cff0d0004f8001c0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - pydantic >=2.7.0,<3.0.0
    - aiohttp >=3.8.6,<4.0.0
    - deprecated >=1.2.15,<2.0.0
    - google-auth >=2.0.0,<3.0.0
    - requests >=2.19.0,<3.0.0

tests:
  - python:
      imports:
        - toolbox_core
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python Base SDK for interacting with the Toolbox service
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/mcp-toolbox-sdk-python/tree/main/packages/toolbox-core
  repository: https://github.com/googleapis/mcp-toolbox-sdk-python

extra:
  recipe-maintainers:
    - rxm7706
