{% set name = "splunk-opentelemetry" %}
{% set version = "2.8.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/splunk_opentelemetry-{{ version }}.tar.gz
  sha256: 901a430e1500ac3bdc5158dfd5ced923597fae9f138bed89e8cac5973123de2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api ==1.38.0
    - opentelemetry-sdk ==1.38.0
    - opentelemetry-propagator-b3 ==1.38.0
    - opentelemetry-exporter-otlp-proto-grpc ==1.38.0
    - opentelemetry-exporter-otlp-proto-http ==1.38.0
    - opentelemetry-instrumentation ==0.59b0
    - opentelemetry-instrumentation-system-metrics ==0.59b0
    - opentelemetry-semantic-conventions ==0.59b0
    - protobuf >=6.31.1

test:
  imports:
    - splunk_otel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/signalfx/splunk-otel-python
  summary: The Splunk distribution of OpenTelemetry Python Instrumentation provides a Python agent that automatically instruments your Python application to capture and report distributed traces to SignalFx APM.
  license: Apache-2.0
  license_file: LICENSE.txt
  #license_file: LICENSE
  license_family: Apache
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  doc_url: https://github.com/signalfx/splunk-otel-python
  dev_url: https://github.com/signalfx/splunk-otel-python
  license: Apache-2.0
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
