# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: splunk-opentelemetry
  version: "2.9.0"
  python_min: '3.10'
  python_max: '4.0'
  python_test_max: '3.14'
  opentelemetry_api_version: '1.39.1'
  opentelemetry_instrumentation_version: '0.60b1'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/splunk_opentelemetry-${{ version }}.tar.gz
  sha256: 37c965e328ba164febf4e84c6af933b3908923b6007ac76221213af2f7062f07

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - opentelemetry-api ==${{ opentelemetry_api_version }}
    - opentelemetry-sdk ==${{ opentelemetry_api_version }}
    - opentelemetry-propagator-b3 ==${{ opentelemetry_api_version }}
    - opentelemetry-exporter-otlp-proto-grpc ==${{ opentelemetry_api_version }}
    - opentelemetry-exporter-otlp-proto-http ==${{ opentelemetry_api_version }}
    - opentelemetry-instrumentation ==${{ opentelemetry_instrumentation_version }}
    - opentelemetry-instrumentation-system-metrics ==${{ opentelemetry_instrumentation_version }}
    - opentelemetry-semantic-conventions ==${{ opentelemetry_instrumentation_version }}
    - protobuf >=6.31.1

tests:
  - python:
      imports:
        - splunk_otel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_test_max }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: The Splunk distribution of OpenTelemetry Python Instrumentation provides a Python agent that automatically instruments your Python application to capture and report distributed traces to SignalFx APM.
  homepage: https://github.com/signalfx/splunk-otel-python
  license: Apache-2.0
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  repository: https://github.com/signalfx/splunk-otel-python
  documentation: https://docs.splunk.com/observability/en/gdi/get-data-in/application/python/get-started.html

extra:
  recipe-maintainers:
    - rxm7706
