"""CAP-1 template-parse-then-fill (Story 15.1): a second, parallel
PPTX-generation module producing genuinely editable ``.pptx`` decks --
coexisting with, never replacing, the existing Marp/bridge pipeline
(``deck_pipeline.py``, ``cli.py``'s ``marp-*`` pull targets).

Herald's Marp/HTML pipeline exports ``.pptx`` files that are proven
non-editable (2026-08-22 inspection: shipped exports are background-image
slides with zero text runs). This module is the fix, for the one artifact
the HTML/Marp pipeline structurally cannot produce: it parses a
``.potx``/``.pptx`` template once into a machine-readable ``spec.json``
contract (:func:`extract_spec`), then fills an agent-authored
``content_plan.json`` into that template mechanically
(:func:`fill_template`) via python-pptx's high-level object model only --
``text_frame``/``placeholders[idx]``/``add_paragraph()`` -- never
hand-written or hand-edited OOXML/XML strings (Boundaries & Constraints).

**Own-template decision (2026-08-22, spec Design Notes).** No
operator-supplied ``.potx`` exists and this is an unattended run, so
PyForge's interim "own template" is python-pptx's own bundled default
Office-theme template, committed verbatim as
``templates/pyforge-deck-template.pptx`` (regenerated by
``scripts/generate_default_template.py``, never hand-edited) -- 11 real
stock layouts with genuinely inheriting placeholders, requiring zero
hand-written OOXML. :func:`extract_spec` derives ``spec.json`` generically
from whatever template path it is given, so swapping in a future
PyForge-branded ``.potx`` needs zero pipeline code changes, only a new
template file and a ``--template`` flag pointing at it.

``run_spec``/``run_fill`` are the file-path orchestration wrappers
``cli.py`` calls, mirroring ``deck_qa.py``'s ``run()``/``to_dict()`` shape:
they resolve real paths on disk (a template, a ``content_plan.json``, an
output ``spec.json``/``.pptx``) around the pure-computation
``extract_spec``/``fill_template`` functions, which take/return in-memory
objects only.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import asdict, dataclass, field
from importlib import resources
from pathlib import Path
from typing import TYPE_CHECKING, Any

from pptx import Presentation

from pyforge.core.atomic_write import atomic_write, atomic_write_text

from . import errors

if TYPE_CHECKING:
    from pptx.presentation import Presentation as PptxPresentation
    from pptx.slide import SlideLayout


@dataclass(frozen=True)
class TemplatePlaceholder:
    """One placeholder on one template layout: enough to both describe it
    (``spec.json``'s contract) and address it from a ``content_plan.json``
    entry (``idx`` is the key :func:`fill_template` matches against)."""

    idx: int
    type: str
    name: str
    left: int
    top: int
    width: int
    height: int


@dataclass(frozen=True)
class TemplateLayout:
    """One slide layout: its index/name (either one is a valid
    ``content_plan.json`` ``"layout"`` reference, see
    :func:`_resolve_layout`) plus every placeholder it declares."""

    index: int
    name: str
    placeholders: list[TemplatePlaceholder] = field(default_factory=list)


@dataclass(frozen=True)
class TemplateSpec:
    """The whole ``spec.json`` contract for one template: every layout, in
    template order."""

    layouts: list[TemplateLayout] = field(default_factory=list)


def default_template_path() -> Path:
    """PyForge's bundled interim template (Design Notes' own-template
    decision) -- resolved via ``importlib.resources``, never a
    source-tree-relative path, so this resolves identically from an
    installed wheel or conda package (Code Map)."""
    return Path(
        resources.files("pyforge.herald") / "templates" / "pyforge-deck-template.pptx"
    )


def _open_template(template_path: Path) -> PptxPresentation:
    template_path = Path(template_path)
    if not template_path.is_file():
        raise errors.PptxTemplateError(f"template not found: {template_path}")
    try:
        return Presentation(str(template_path))
    except Exception as exc:  # noqa: BLE001 -- any python-pptx open failure
        # (corrupt zip, not a .pptx/.potx at all, ...) is "bad template" for
        # this module's purposes.
        raise errors.PptxTemplateError(
            f"cannot open template {template_path}: {exc}"
        ) from exc


def _emu(value: int | None) -> int:
    """A placeholder's geometry can inherit from the slide master with no
    explicit EMU value of its own (``None``) -- normalized to ``0`` rather
    than surfaced as null, keeping ``spec.json``'s geometry fields uniformly
    integers."""
    return int(value) if value is not None else 0


def extract_spec(template_path: Path) -> TemplateSpec:
    """Parse ``template_path`` once into a :class:`TemplateSpec` -- every
    stock layout's index/name, and each of its placeholders'
    idx/type/name/geometry (EMU). Derived generically from whatever
    template is given (Boundaries & Constraints): swapping in a future
    branded ``.potx`` needs no change here, only a different path.

    Raises :class:`errors.PptxTemplateError` when ``template_path`` does
    not exist or python-pptx cannot open it."""
    prs = _open_template(template_path)
    layouts = [
        TemplateLayout(
            index=index,
            name=layout.name,
            placeholders=[
                TemplatePlaceholder(
                    idx=ph.placeholder_format.idx,
                    type=(
                        ph.placeholder_format.type.name
                        if ph.placeholder_format.type is not None
                        else "UNKNOWN"
                    ),
                    name=ph.name,
                    left=_emu(ph.left),
                    top=_emu(ph.top),
                    width=_emu(ph.width),
                    height=_emu(ph.height),
                )
                for ph in layout.placeholders
            ],
        )
        for index, layout in enumerate(prs.slide_layouts)
    ]
    return TemplateSpec(layouts=layouts)


def spec_to_dict(spec: TemplateSpec) -> dict[str, Any]:
    """``spec`` as a JSON-serializable dict -- mirrors ``deck_qa.to_dict``'s
    ``dataclasses.asdict`` delegation: every field here is itself a
    dataclass, primitive, or plain list of those, so the recursive default
    handles the whole tree with no manual field-by-field walk."""
    return asdict(spec)


def _resolve_layout(
    prs: PptxPresentation, layout_ref: object, slide_index: int
) -> SlideLayout:
    """A ``content_plan.json`` slide entry's ``"layout"`` field -> the
    template's matching ``SlideLayout``. Accepts either an ``int`` index or
    a ``str`` name (spec: "real layout indices/names"); ``bool`` is
    rejected explicitly even though Python's ``bool`` is an ``int``
    subclass -- ``true``/``false`` in a plan is never a meaningful layout
    reference."""
    layouts = list(prs.slide_layouts)
    if isinstance(layout_ref, bool) or not isinstance(layout_ref, (int, str)):
        raise errors.InvalidContentPlanError(
            f"slide #{slide_index}: 'layout' must be an int index or "
            f"string name, got {layout_ref!r}"
        )
    if isinstance(layout_ref, int):
        if 0 <= layout_ref < len(layouts):
            return layouts[layout_ref]
        raise errors.InvalidContentPlanError(
            f"slide #{slide_index}: layout index {layout_ref} out of range "
            f"(template has {len(layouts)} layouts)"
        )
    for layout in layouts:
        if layout.name == layout_ref:
            return layout
    raise errors.InvalidContentPlanError(
        f"slide #{slide_index}: no layout named {layout_ref!r} in template"
    )


def _resolve_placeholder_values(
    layout: SlideLayout, raw_values: object, slide_index: int
) -> dict[int, str | list[str]]:
    """A slide entry's ``"placeholders"`` mapping -> validated
    ``{idx: value}``, checked against ``layout``'s own placeholder idxs and
    each one's ``has_text_frame`` (a placeholder that cannot hold text --
    e.g. a picture placeholder already carrying an image -- is rejected
    here rather than crashing :func:`_set_placeholder_text` later). Every
    failure here raises :class:`errors.InvalidContentPlanError` before
    :func:`fill_template` materializes anything (I/O matrix: "No file
    written")."""
    if not isinstance(raw_values, Mapping):
        raise errors.InvalidContentPlanError(
            f"slide #{slide_index}: 'placeholders' must be a JSON object"
        )
    layout_by_idx = {ph.placeholder_format.idx: ph for ph in layout.placeholders}
    resolved: dict[int, str | list[str]] = {}
    for raw_idx, value in raw_values.items():
        try:
            idx = int(raw_idx)
        except (TypeError, ValueError):
            raise errors.InvalidContentPlanError(
                f"slide #{slide_index}: placeholder key {raw_idx!r} is not "
                f"an integer idx"
            ) from None
        if idx not in layout_by_idx:
            raise errors.InvalidContentPlanError(
                f"slide #{slide_index}: layout {layout.name!r} has no "
                f"placeholder idx {idx}"
            )
        if not layout_by_idx[idx].has_text_frame:
            raise errors.InvalidContentPlanError(
                f"slide #{slide_index}: layout {layout.name!r} placeholder "
                f"idx {idx} does not support text (type "
                f"{layout_by_idx[idx].placeholder_format.type})"
            )
        if isinstance(value, str):
            resolved[idx] = value
        elif (
            isinstance(value, list)
            and value
            and all(isinstance(item, str) for item in value)
        ):
            resolved[idx] = value
        else:
            raise errors.InvalidContentPlanError(
                f"slide #{slide_index}: placeholder idx {idx} value must "
                f"be a string or a non-empty list of strings, got {value!r}"
            )
    return resolved


def _set_placeholder_text(placeholder: Any, value: str | list[str]) -> None:
    """Fill one placeholder's text, preserving inherited formatting
    (Design Notes). Setting ``.text_frame.text`` (rather than touching XML)
    lets the run inherit font/size/color from the slide layout/master --
    this is exactly the mechanism that makes the output editable, and it's
    the same regression the old Marp pipeline's ``<a:blip>``-based export
    failed."""
    lines = value if isinstance(value, list) else [value]
    placeholder.text_frame.text = lines[0]
    for line in lines[1:]:
        placeholder.text_frame.add_paragraph().text = line


def fill_template(template_path: Path, content_plan: object) -> PptxPresentation:
    """Fill ``content_plan`` into ``template_path``, mechanically, via
    python-pptx's high-level object model only (Boundaries & Constraints --
    never hand-written OOXML): one slide per plan entry, each named
    placeholder's text set through :func:`_set_placeholder_text`.

    Every slide entry is resolved and validated BEFORE any slide is
    materialized, so a plan with one bad entry (unknown layout, unknown
    placeholder idx, malformed value) raises with the in-memory
    ``Presentation`` never having gained a single slide -- ``run_fill``
    only writes a file once this function returns successfully (I/O
    matrix's "No file written" rows).

    Raises :class:`errors.PptxTemplateError` on a bad template path, and
    :class:`errors.InvalidContentPlanError` on any malformed/unresolvable
    plan content."""
    prs = _open_template(template_path)
    if not isinstance(content_plan, Mapping):
        raise errors.InvalidContentPlanError("content plan must be a JSON object")
    slides = content_plan.get("slides")
    if not isinstance(slides, list):
        raise errors.InvalidContentPlanError("content plan must have a 'slides' list")

    resolved_slides: list[tuple[SlideLayout, dict[int, str | list[str]]]] = []
    for index, entry in enumerate(slides):
        if not isinstance(entry, Mapping):
            raise errors.InvalidContentPlanError(f"slide #{index} is not a JSON object")
        if "layout" not in entry:
            raise errors.InvalidContentPlanError(f"slide #{index} is missing 'layout'")
        layout = _resolve_layout(prs, entry["layout"], index)
        placeholder_values = _resolve_placeholder_values(
            layout, entry.get("placeholders", {}), index
        )
        resolved_slides.append((layout, placeholder_values))

    for layout, placeholder_values in resolved_slides:
        slide = prs.slides.add_slide(layout)
        for idx, value in placeholder_values.items():
            _set_placeholder_text(slide.placeholders[idx], value)
    return prs


def run_spec(template_path: Path, out_path: Path | None = None) -> TemplateSpec:
    """``herald deck pptx-spec``'s file-path orchestration: extract
    ``template_path``'s :class:`TemplateSpec`, and -- when ``out_path`` is
    given -- atomically write it as ``spec.json`` there. Always returns the
    spec so a caller printing to stdout (``out_path=None``) needs no second
    read."""
    spec = extract_spec(template_path)
    if out_path is not None:
        atomic_write_text(Path(out_path), json.dumps(spec_to_dict(spec)))
    return spec


def run_fill(template_path: Path, content_plan_path: Path, out_path: Path) -> None:
    """``herald deck pptx-fill``'s file-path orchestration: read + parse
    ``content_plan_path``, fill it into ``template_path``
    (:func:`fill_template`), and atomically write the result to
    ``out_path`` only once every prior step has succeeded -- the I/O
    matrix's "No file written" rows hold by construction, since
    ``atomic_write`` runs last.

    Raises :class:`errors.InvalidContentPlanError` when
    ``content_plan_path`` cannot be read (``OSError``), is not valid UTF-8
    (``UnicodeDecodeError`` -- a ``ValueError`` subclass, not an
    ``OSError`` one, so caught separately), or is not valid JSON (in
    addition to every case :func:`fill_template` itself raises), and
    :class:`errors.PptxTemplateError` on a bad template path."""
    content_plan_path = Path(content_plan_path)
    try:
        raw = content_plan_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise errors.InvalidContentPlanError(
            f"cannot read content plan {content_plan_path}: {exc}"
        ) from exc
    try:
        content_plan = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise errors.InvalidContentPlanError(
            f"content plan {content_plan_path} is not valid JSON: {exc}"
        ) from exc
    presentation = fill_template(template_path, content_plan)
    atomic_write(Path(out_path), lambda tmp: presentation.save(str(tmp)))
