# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: cucumber-expressions
  version: "18.1.0"
  python_min: '3.10'


package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cucumber_expressions-${{ version }}.tar.gz
  sha256: b6f31c15def3821ed8313d7c59c3ccd6e5b607ee65b86ad33140a43e8858d1f2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.9.0,<0.10.0
    - pip
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - cucumber_expressions
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Cucumber Expressions - a simpler alternative to Regular Expressions
  homepage: https://github.com/cucumber/cucumber-expressions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
