# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: sqlfluff-templater-dbt
  version: "4.0.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqlfluff_templater_dbt-${{ version }}.tar.gz
  sha256: afc34eb926b6e54c2daa3495533b7197db8455db1a1e254c77e5e317537b673d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools <81.0.0
  run:
    - python >=${{ python_min }},<4
    - sqlfluff ==4.0.0
    - dbt-core >=1.4.1
    - jinja2-simple-tags >=0.3.1

tests:
  - python:
      imports:
        - sqlfluff_templater_dbt
      pip_check: true
      python_version:
        - ${{ python_min }}.*

about:
  summary: Lint your dbt project SQL
  license: MIT
  license_file: LICENSE.md
  repository: https://github.com/sqlfluff/sqlfluff
  homepage: https://github.com/sqlfluff/sqlfluff

extra:
  recipe-maintainers:
    - rxm7706
