# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: strictyaml
  version: "1.7.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 22f854a5fcab42b5ddba8030a0e4be51ca89af0267961c8d6cfa86395586c407

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - python-dateutil >=2.6.0
    - ruamel.yaml >=0.17

tests:
  - python:
      imports:
        - strictyaml
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Type-safe YAML parser and validator.
  homepage: http://hitchdev.com/strictyaml/
  repository: https://github.com/crdoconnor/strictyaml

extra:
  recipe-maintainers:
    - mcs07
    - chrisburr
