# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: google-generativeai
  version: 0.8.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/google-gemini/generative-ai-python/archive/v${{ version }}.tar.gz
  sha256: e58365ea1c36da40e07c8917cd50b647f6eaf4189f6682728d79327c84ab7e70

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - typing_extensions
    - python >=${{ python_min }}
    - google-ai-generativelanguage ==0.6.15
    - google-api-core
    - google-api-python-client
    - google-auth >=2.15.0
    - protobuf
    - pydantic
    - tqdm
    - grpcio

tests:
  - python:
      imports:
        - google
        - google.generativeai
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: The Gemini API Python SDK enables developers to use Google's state-of-the-art generative AI models to build AI-powered features and applications.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/google/generative-ai-python

extra:
  recipe-maintainers:
    - jan-janssen
    - moritzwilksch
