# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: azure-core-tracing-opentelemetry
  version: 1.0.0b13

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_core_tracing_opentelemetry-${{ version }}.tar.gz
  sha256: 6cb2f8dfd5dee6c11843db0205fc92e2434e1a272c169c953afe92483aafc7eb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - opentelemetry-api <2.0.0,>=1.12.0
    - azure-core <2.0.0,>=1.24.0

tests:
  - python:
      imports:
        - azure.core.tracing.ext.opentelemetry_span
        - azure.core.tracing
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Microsoft Azure Azure Core OpenTelemetry plugin Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core-tracing-opentelemetry

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-api
