schema_version: 1

context:
  name: nebari-plugin-cert-manager-chart
  version: 0.0.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/nebari_plugin_cert_manager_chart-${{ version }}.tar.gz
  sha256: b41035724e3bb0e81a1719eba1eaf98c6a10a615526a7eb9ac855e123b30b01d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - nebari

tests:
  - python:
      imports:
        - nebari_plugin_cert_manager_chart
      pip_check: true

about:
  summary: MetroStar Onyx - cert-manager plugin for Nebari platform
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/MetroStar/nebari-cert-manager

extra:
  recipe-maintainers:
    - rxm7706
