# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: python-socks
  version: "3.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: c20ddf978b5c90467bf242757a11dcd00d7c8bd339901de1839b492d5571ab7f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77.0
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - python_socks
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Core proxy (SOCKS4, SOCKS5, HTTP tunneling) functionality for Python
  license: Apache-2.0
  license_file:
    - LICENSE.txt
  homepage: https://github.com/romis2012/python-socks

extra:
  recipe-maintainers:
    - thewchan
