{% set name = "dlt-pendulum" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dlt-hub/pendulum/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9a0225a8e97399ad7c3930856d581093b65e36bb27c85c0da5a2575ddbaa9248
  patches:
    - 0001-remove-tzdata-dep-for-pip-check.patch
build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - python                                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}         # [build_platform != target_platform]
    - crossenv                                   # [build_platform != target_platform]
    - maturin >=1.0,<2.0                         # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - python-dateutil >=2.6
    # Source uses tzdata>=2020.1, python-tzdata and tzdata are available on conda-forge, python-tzdata is the correct conda package to use
    - python-tzdata >=2020.1
    - cffi >=1.17

test:
  imports:
    - pendulum
  commands:
    - pip check
    # make sure the extensions actually built (this might be fragile since these modules are private)
    - python -c "from pendulum._pendulum import parse_iso8601"  # [python_impl == 'cpython']
    - python -c "from pendulum._helpers import days_in_year"  # [python_impl == 'cpython']
  requires:
    - pip

about:
  home: https://github.com/dlt-hub/pendulum
  summary: Python datetimes made easy
  description: |
    Pendulum is a Python library that simplifies datetime operations,
    providing a cleaner API built on Python's standard datetime library.
    This is a fork maintained by dlt-hub to support Python 3.9-3.13.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/dlt-hub/pendulum
  doc_url: https://pendulum.eustace.io

extra:
  recipe-maintainers:
    - rxm7706
