# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "6.12.0"

package:
  name: colorlog
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/colorlog/colorlog-${{ version }}.tar.gz
  sha256: 2a7924c1dadf18b22a0eb8b06d1c7b01d5341707ec1641eb6fcc4fde0c3e8e5f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - if: win
      then:
        - colorama

tests:
  - python:
      imports:
        - colorlog
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/borntyping/python-colorlog
  license: MIT
  license_file: LICENSE
  summary: Add colours to the output of Python's logging module.
  description: |
    Add colours to the output of Python's logging module.

extra:
  recipe-maintainers:
    - xylar
    - frol
    - forrestwaters

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: colorlog
  cfe-upstream-registry: pypi
  cfe-upstream-name: colorlog
  cfe-purls:
    - pkg:conda/colorlog@${{ version }}?channel=conda-forge
    - pkg:pypi/colorlog@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/borntyping/python-colorlog
  cfe-import-names: [colorlog]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/colorlog-feedstock
  cfe-forge-recipe-updates-needed: 
    - version-update-to-6.12.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T07:08:35Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T07:08:35Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-17T07:08:35Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
