# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: blessed
  version: "1.21.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/blessed-${{ version }}.tar.gz
  sha256: ece8bbc4758ab9176452f4e3a719d70088eb5739798cd5582c9e05f2a28337ec

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - __${{ noarch_platform }}
    - python >=${{ python_min }},<4.0
    - if: noarch_platform != "win"
      then:
        - wcwidth >=0.1.4
      else:
        - wcwidth >=0.1.4
        - jinxed >=1.1.0

tests:
  - python:
      imports:
        - blessed
        - ${{ "jinxed" if noarch_platform == "win" }}
        - ${{ "wcwidth" if noarch_platform == "osx" or noarch_platform == "linux" or noarch_platform == "win" }}
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - echo "Test Script Imports for unix and windows Started"
      - if: noarch_platform  != "win"
        then:
          - echo "Test Script Importing blessed and terminal for unix and windows"
          - python -c "from blessed import Terminal; assert Terminal"
          - python -c "assert __import__('blessed').__version__ == '${{ version }}'"
        else:
          - echo "Test Script Importing jinxed, blessed and terminal for windows"
          - python -c "from jinxed import setupterm; assert setupterm"
          - python -c "from blessed import Terminal; assert Terminal"
          - python -c "assert __import__('blessed').__version__ == '${{ version }}'"
      - echo "Test Script Imports for unix and windows Completed"

about:
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jquast/blessed

extra:
  recipe-maintainers:
    - mattip
    - hadim
