"""Single source for identity complete export and gist column contracts (Story 27.1).

The Kedro ``identity_complete_export`` node, ``identity_gist`` dashboard renderer,
and ``conda-forge-packaging-inventory-operations_openteams_identity.py`` must stay
aligned — tests import this module directly.
"""

from __future__ import annotations

IDENTITY_COMPLETE_EXPORT_COLUMNS: tuple[str, ...] = (
    "P",
    "Rank",
    "Score",
    "Package",
    "Work",
    "Platforms",
    "Apps",
    "Downloads",
    "Versions",
    "Vuln",
    "Core_Python_Package_Name",
    "OpenTeams_Title",
    "identity_source",
    "associator_key",
    "associator_status",
    "primary_purl",
    "primary_type",
    "alternative_purls",
    "cpes",
    "conda_purl",
    "source_repository_url",
    "OpenTeams_Issue_URL",
    "Conda-Forge_FeedStock_URL",
    "Conda-Forge_Metadata_URL",
    "Staged_Recipes_PR_URL",
    "Local_Recipes_URL",
    "Local_Build_Status",
    "Verification_Timestamp_UTC",
    "Priority_Bucket_Description",
    "Priority_Source",
    "Priority_Reason",
    "JFROG_risk_level",
    "JFROG_latest_vuln_count",
    "internal_component_count",
    "internal_lob_count",
    "platform_env_count",
    "internal_app_count",
    "artifactory_downloads",
    "artifactory_version_count",
    "JFROG_vuln_status",
    "OpenTeams_Cohort",
    "OpenTeams_Batch",
    "OpenTeams_Coverage",
    "Repository_Source",
    "Role",
    "PyPI_Verified",
    "CondaForge_Verified",
    "Packaging_Candidate_Status",
    "in_basilisk",
    "in_aoss_free",
    "in_aoss_premium",
    "in_anaconda_main",
    "in_anaconda_dist",
    "in_selfexplainml",
    "in_bioconda",
    "in_pytorch",
    "in_nvidia",
    "in_robostack",
    "in_homebrew",
    "in_nixpkgs",
    "in_spack",
    "in_debian",
    "in_fedora",
)

GIST_SCHEMA: tuple[tuple[str, str, str, str], ...] = (
    ("P", "enum", "yes", "Proposed priority `P1`–`P10`."),
    ("Rank", "int", "yes", "1-based rank across the snapshot (P1 first)."),
    ("Score", "int", "yes", "Use-score percentile 1–100."),
    ("Package", "string", "yes", "Display name (same identity as Core_Python_Package_Name)."),
    (
        "Work",
        "enum",
        "yes",
        "`Fix vulnerability` | `Create recipe` | `File OpenTeams tracking issue [Conda-Forge Packaging]` | `Already tracked`.",
    ),
    ("Platforms", "int", "no", "JFROG `platform_env_count`."),
    ("Apps", "int", "no", "JFROG `internal_app_count`."),
    ("Downloads", "int", "no", "JFROG `artifactory_downloads`."),
    ("Versions", "int", "no", "JFROG `artifactory_version_count`."),
    ("Vuln", "enum", "no", "JFROG `vuln_status` (`affected_latest`, `clean`, …)."),
    (
        "Core_Python_Package_Name",
        "string",
        "yes",
        "Primary key. Conda/PyPI package identity as stored (unique).",
    ),
    ("OpenTeams_Title", "string", "yes", "Issue title `[Conda-Forge Packaging] {name}`."),
    (
        "identity_source",
        "enum",
        "yes",
        "`purl-associator` | `inventory` | `none` | `openteams-board`.",
    ),
    (
        "associator_key",
        "string",
        "no",
        "Key matched in prefix-dev/purl-associator mappings-index. Blank if unused.",
    ),
    (
        "associator_status",
        "string",
        "no",
        "Associator status, or `inventory-derived` / `unmapped`.",
    ),
    ("primary_purl", "purl", "no", "Upstream PURL (`pkg:pypi/…` or `pkg:github/…`). Not a conda PURL."),
    ("primary_type", "enum", "no", "`pypi` | `github` | `git` | blank."),
    ("alternative_purls", "purl[]", "no", "`; `-joined extra PURLs."),
    ("cpes", "string[]", "no", "`; `-joined CPEs from the associator."),
    ("conda_purl", "purl", "no", "`pkg:conda/{name}?channel=conda-forge` only when on conda-forge."),
    ("source_repository_url", "url", "no", "Upstream VCS URL. Not a feedstock and not PyPI/anaconda."),
    (
        "OpenTeams_Issue_URL",
        "url",
        "no",
        "GitHub issue on OpenTeams-WFT-CDO/mgmt-wf-python-modernization.",
    ),
    (
        "Conda-Forge_FeedStock_URL",
        "url[]",
        "no",
        "`; `-joined github.com/conda-forge/{repo}-feedstock from conda-forge.org/packages.",
    ),
    (
        "Conda-Forge_Metadata_URL",
        "url",
        "no",
        "Packages-page Browse link: conda-metadata-app.streamlit.app/?q=conda-forge/{pkg}.",
    ),
    (
        "Staged_Recipes_PR_URL",
        "url",
        "no",
        "Best conda-forge/staged-recipes PR (open file path, else title; prefer open then merged).",
    ),
    (
        "Local_Recipes_URL",
        "url[]",
        "no",
        "`; `-joined github.com/rxm7706/local-recipes/tree/main/recipes/{dir}.",
    ),
    (
        "Local_Build_Status",
        "enum",
        "no",
        "`success` | `failed` | `build-clean-test-blocked` | `not-attempted`. From the local `recipe.yaml` CFE stamp. Blank if no stamp.",
    ),
    ("Verification_Timestamp_UTC", "datetime", "yes", "ISO 8601 UTC generation time for this snapshot."),
    ("Priority_Bucket_Description", "string", "yes", "Human description of `P`."),
    (
        "Priority_Source",
        "string",
        "no",
        "Assignment source (`current-version-vuln`, `platform`, `work-create-recipe`, …).",
    ),
    ("Priority_Reason", "string", "no", "Short reason for this `P`."),
    ("JFROG_risk_level", "enum", "no", "`HIGH` | `MEDIUM` | `LOW` | `NO_DATA`."),
    ("JFROG_latest_vuln_count", "int", "no", "Basilisk latest-version known vulnerability count."),
    ("internal_component_count", "int", "no", "JFROG internal component count."),
    ("internal_lob_count", "int", "no", "JFROG internal LOB count."),
)

GIST_COLUMNS: tuple[str, ...] = tuple(name for name, _typ, _req, _meaning in GIST_SCHEMA)

RANKING_COLUMNS: tuple[str, ...] = ("P", "Rank", "Score", "Work")
