# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pyotp
  version: "2.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d01e9703443616b03c57c700b5cbffd56a1f929c1b0f8f03131bc78c1fca9d3f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pyotp
      pip_check: false
      python_version: ${{ python_min }}
  - requirements:
      run:
        - python ${{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  summary: Python One Time Password Library
  description: PyOTP - The Python One-Time Password Library. PyOTP is a Python library for generating and verifying one-time passwords. It can be used to implement two-factor (2FA) or multi-factor (MFA) authentication methods in web applications and in other systems that require users to log in.
  homepage: https://github.com/pyauth/pyotp
  repository: https://github.com/pyauth/pyotp
  documentation: https://pyotp.readthedocs.io/

extra:
  recipe-maintainers:
    - kalling
    - smithsp
    - jan-janssen
