{% set name = "datasketches-python" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/datasketches-python/archive/{{ version }}.tar.gz
  sha256: 9bbc4f33261a0ef8c3dc8789a6e7eb6d66d3d742b10648a25bb679faf30fdd93

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - numpy
    - nanobind >=1.6
    - cmake >=3.16
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - datasketches
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://datasketches.apache.org
  summary: The Apache DataSketches Library for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - rxm7706

