# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.2.0"

package:
  name: openai
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/openai/openai-${{ version }}.tar.gz
  sha256: 1d26bd6f49738f6848bcce370794ee03acc0561d468070df010b44178da8e797

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling ==1.26.3
    - hatch-fancy-pypi-readme
  run:
    - python >=${{ python_min }}
    - anyio <5,>=4.10.0
    - distro <2,>=1.7.0
    - httpx2 <3,>=2.7.0
    - jiter <1,>=0.10.0
    - pydantic <3,>=1.9.0
    - sniffio
    - tqdm >4
    - typing_extensions <5,>=4.14

tests:
  - python:
      imports:
        - openai
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/openai/openai-python
  license: Apache-2.0
  license_file: LICENSE
  summary: The official Python library for the openai API
  description: |
    The official Python library for the openai API
  repository: https://github.com/openai/openai-python

extra:
  recipe-maintainers:
    - timkpaine
    - BastianZim

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: openai
  cfe-upstream-registry: pypi
  cfe-upstream-name: openai
  cfe-purls:
    - pkg:conda/openai@${{ version }}?channel=conda-forge
    - pkg:pypi/openai@${{ version }}
  cfe-upstream-repo: https://github.com/openai/openai-python
  cfe-upstream-homepage: https://github.com/openai/openai-python
  cfe-import-names: [openai]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/openai-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-3.2.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T02:12:35Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T02:12:35Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T02:12:35Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
