# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: jupyter-server-documents
  version: "0.1.0a9"
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/dd/03/4d449e2d8c4f04a857d053375cc55c2e9fd13463fea3da8770e4ad052997/jupyter_server_documents-${{ version }}.tar.gz
  sha256: 44dd509ccb41263ff5f676816aaaab05ba5c37ac67de994cf82c974e8351076d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - nodejs
  run:
    - python >=${{ python_min }}
    - jupyter-collaboration-ui >=2.0.2,<3
    - jupyter_server_fileid >=0.9.0,<0.10.0
    - jupyter_server >=2.4.0,<3
    - jupyter_ydoc >=3.0.0,<4.0.0
    - pycrdt >=0.12.0,<0.13.0

tests:
  - python:
      imports:
        - jupyter_server_documents
      pip_check: true

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter_server_documents
  repository: https://github.com/jupyter-ai-contrib/jupyter-server-documents
  documentation: https://github.com/jupyter-ai-contrib/jupyter_server_documents
  summary: Enhanced JupyterLab notebooks with server-side document state and real-time collaboration
  description: |
    An extension that enhances JupyterLab notebooks by moving the state of documents
    to the server. It provides real-time collaborative editing capabilities, optimized
    memory management for large outputs, improved kernel reliability, and lazy loading
    of outputs for improved responsiveness.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
