# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: interrogate
  version: "1.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: a320d6ec644dfd887cc58247a345054fc4d9f981100c45184470068f4b3719b0

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - interrogate = interrogate.cli:main

requirements:
  host:
    - python ${{ python_min }}
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - attrs
    - click
    - colorama
    - py
    - tabulate
    - tomli

tests:
  - python:
      imports:
        - interrogate
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - interrogate --help

about:
  summary: Interrogate a codebase for docstring coverage.
  license: MIT
  license_file: LICENSE
  homepage: https://interrogate.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
