# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.0.0"
  python_min: "3.11"

package:
  name: metakernel
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/metakernel/metakernel-${{ version }}.tar.gz
  sha256: 76f2b8926cbad5a089deb6f727399c4e34e8915af97896a8bb7968ebe02da21c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python 3.11.*
    - pip
    - poetry >=2.3.1
  run:
    - ipykernel >5.5.6
    - jedi >=0.18
    - jupyter_core >=4.9.2
    - pexpect >=4.8
    - python >=${{ python_min }}
    # extras
    - ipyparallel
    - portalocker

tests:
  - python:
      imports:
        - metakernel
        - metakernel.magics
        - metakernel.utils
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Metakernel for Jupyter.
  homepage: https://github.com/Calysto/metakernel

extra:
  recipe-maintainers:
    - ocefpaf
    - ericdill
    - mariusvniekerk
    - blink1073
    - dsblank
