# Generated by Django for warden_fabric — initial + app-label cutover (steward 19.1)
from __future__ import annotations

import uuid

from django.db import migrations
from django.db import models

OLD_TABLE = "compliance_face_compliancejob"
NEW_TABLE = "warden_fabric_compliancejob"
LEGACY_APP_LABEL = "_".join(("compliance", "face"))  # noqa: FLY002

_CREATE_FIELDS = [
    (
        "id",
        models.UUIDField(
            default=uuid.uuid4,
            editable=False,
            primary_key=True,
            serialize=False,
        ),
    ),
    ("storage_key", models.CharField(max_length=512)),
    ("original_name", models.CharField(max_length=255)),
    (
        "status",
        models.CharField(
            choices=[
                ("pending", "Pending"),
                ("running", "Running"),
                ("succeeded", "Succeeded"),
                ("failed", "Failed"),
            ],
            default="pending",
            max_length=16,
        ),
    ),
    ("phase_index", models.PositiveSmallIntegerField(default=0)),
    ("error", models.TextField(blank=True, default="")),
    ("report_json", models.TextField(blank=True, default="")),
    ("sbom_json", models.TextField(blank=True, default="")),
    ("created_at", models.DateTimeField(auto_now_add=True)),
    ("updated_at", models.DateTimeField(auto_now=True)),
]


def _table_names(schema_editor) -> set[str]:
    return set(schema_editor.connection.introspection.table_names())


def forwards(apps, schema_editor) -> None:
    existing = _table_names(schema_editor)
    qn = schema_editor.quote_name
    if OLD_TABLE in existing:
        with schema_editor.connection.cursor() as cursor:
            if NEW_TABLE in existing:
                cursor.execute(f"DROP TABLE {qn(NEW_TABLE)}")
            cursor.execute(f"ALTER TABLE {qn(OLD_TABLE)} RENAME TO {qn(NEW_TABLE)}")

    content_type = apps.get_model("contenttypes", "ContentType")
    for old in content_type.objects.filter(app_label=LEGACY_APP_LABEL):
        taken = content_type.objects.filter(
            app_label="warden_fabric",
            model=old.model,
        ).first()
        if taken is None:
            old.app_label = "warden_fabric"
            old.save(update_fields=["app_label"])
        else:
            old.delete()


def backwards(apps, schema_editor) -> None:
    existing = _table_names(schema_editor)
    qn = schema_editor.quote_name
    if NEW_TABLE in existing and OLD_TABLE not in existing:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE {qn(NEW_TABLE)} RENAME TO {qn(OLD_TABLE)}")
    content_type = apps.get_model("contenttypes", "ContentType")
    content_type.objects.filter(app_label="warden_fabric").update(
        app_label=LEGACY_APP_LABEL,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceJob",
            fields=_CREATE_FIELDS,
            options={"ordering": ("-created_at",)},
        ),
        migrations.RunPython(forwards, backwards),
    ]
