# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: djangorestframework-guardian
  version: "0.4.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/djangorestframework_guardian-${{ version }}.tar.gz
  sha256: a8113659e062f65b74cc31af6982420c382642e782d38581b3fdc748a179756c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77,<81.0.0
    - pip
  run:
    - python >=${{ python_min }},<4
    - django
    - djangorestframework
    - django-guardian

tests:
  - python:
      imports:
        - rest_framework_guardian
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: django-guardian support for Django REST Framework
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/rpkilby/django-rest-framework-guardian

extra:
  recipe-maintainers:
    - rxm7706
