# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "26.8.0"
  python_min: "3.11"

package:
  name: dask-cuda
  version: ${{ version }}

source:
  url: https://pypi.org/packages/py3/d/dask-cuda/dask_cuda-26.8.0-py3-none-manylinux_2_28_aarch64.manylinux_2_28_x86_64.whl
  sha256: c797f0ecc9ec9d05f432fa01c19f2db11ca561e515375bb7124599ab131611a0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click >=8.1
    - cuda-core <2,>=0.5.1
    - numpy <3.0,>=2.0
    - nvidia-ml-py >=12
    - pandas >=1.3
    - rapids-dask-dependency ==26.8.*
    - zict >=2.0.0

tests:
  - python:
      imports:
        - dask_cuda
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/rapidsai/dask-cuda
  license: Apache-2.0
  license_file: LICENSE
  summary: Utilities for Dask and CUDA interactions
  description: |
    Utilities for Dask and CUDA interactions
  repository: https://github.com/rapidsai/dask-cuda
  documentation: https://docs.rapids.ai/api/dask-cuda/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: dask-cuda
  cfe-upstream-registry: pypi
  cfe-upstream-name: dask-cuda
  cfe-purls:
    - pkg:conda/dask-cuda@${{ version }}?channel=conda-forge
    - pkg:pypi/dask-cuda@${{ version }}
  cfe-upstream-repo: https://github.com/rapidsai/dask-cuda
  cfe-upstream-homepage: https://github.com/rapidsai/dask-cuda
  cfe-import-names: [dask_cuda]
  cfe-source-kind: pypi-wheel
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/dask-cuda-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-26.8.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T07:30:26Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T07:30:26Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-17T07:30:26Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
