# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: jupyterlab-slideshow
  version: "0.3.4"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jupyterlab_slideshow-${{ version }}.tar.gz
  sha256: 285300a4139d26ea4e31f517fa6f3b734edc9c3910ae5ea8ec96a5591f636f85

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.9.0,<4.0.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - jupyterlab >=4.1,<5.0.0a0
    - jupyterlab-fonts >=3.0.0

tests:
  - python:
      imports:
        - jupyterlab_slideshow
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A lightweight presentation mode for JupyterLab.
  homepage: https://github.com/jupyterlab-contrib/jupyterlab-slideshow
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - js/jupyterlab-slideshow/LICENSE
  repository: https://github.com/jupyterlab-contrib/jupyterlab-slideshow

extra:
  recipe-maintainers:
    - rxm7706
