{% set name = "peewee-migrate" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/peewee_migrate-{{ version }}.tar.gz
  sha256: 1ab67f72a0936006155e1b310c18a32f79e4dff3917cfeb10112ca92518721e5

build:
  entry_points:
    - pw_migrate = peewee_migrate.cli:cli
    - pw-migrate = peewee_migrate.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - peewee >=3.0.0,<4.0.0
    - click

test:
  imports:
    - peewee_migrate
  commands:
    - pip check
    - pw_migrate --help
    - pw-migrate --help
  requires:
    - pip

about:
  home: https://github.com/klen/peewee_migrate
  summary: Support for migrations in Peewee ORM
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
