# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pinecone-plugin-assistant
  version: "3.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pinecone_plugin_assistant-${{ version }}.tar.gz
  sha256: 53f548ede60a95d79ff48d7865a3d0afd665ced9e77758272e62ba0c6c63bd26

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - requests >=2.32.3,<3.0.0

tests:
  - script:
      interpreter: python
      content: |
        import pinecone_plugins.assistant
    requirements:
      run:
        - python ${{ python_min }}.*
        - pinecone
  - script:
      - python -m pip check
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip

about:
  summary: Assistant plugin for Pinecone SDK
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://www.pinecone.io
  documentation: https://docs.pinecone.io/guides/get-started/overview

extra:
  recipe-maintainers:
    - xylar
