# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: "acp-sdk"
  python_check_max: "3.14"
  python_min: '3.11'
  version: 1.0.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/acp_sdk-${{ version }}.tar.gz
  sha256: 3736cd496f63f6aa337814179728e8303d84b4124161e955ebfd013220144ade

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4
    - opentelemetry-api >=1.31
    - pydantic >=2.0
    - httpx >=0.26
    - httpx-sse >=0.4
    - opentelemetry-instrumentation-httpx >=0.52b1
    - fastapi >=0.115
    - opentelemetry-exporter-otlp-proto-http >=1.31
    - opentelemetry-instrumentation-fastapi >=0.52b1
    - opentelemetry-sdk >=1.31
    - janus >=2.0
    - redis-py >=6.1
    - psycopg >=3.2
    - obstore >=0.6
    - async-lru >=2.0.5
    - cachetools >=5.5

tests:
  - python:
      imports:
        - acp_sdk
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*

about:
  summary: Agent Communication Protocol SDK
  license: Apache-2.0
  homepage: https://pypi.org/project/acp-sdk/
  repository: https://github.com/i-am-bee/acp
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
