#!/usr/bin/env python3
"""Shared helpers for the Story 30.3 doc generators (spec-pyforge-doctor
CAP-84): ``scripts/docs_pixi_tasks.py``, ``docs_station_cli.py``,
``docs_detectors.py``, ``docs_skills_catalog.py``, ``docs_environments.py``.

Not itself a pixi task or a detector -- no ``DETECTOR`` marker, no
``_check.py`` suffix, so ``scripts/detectors.py``'s ``discover()`` never
scans it (mirrors ``docs_map_render.py``'s own plain-mutator status). The
pieces genuinely shared across all five generators: the ``derived_at``/
``tree`` stamp (herald ``facts.yaml``'s shape, ported from
``scripts/deck_facts.py``'s own ``head_info``), a minimal frontmatter
reader, and the write+stamp+``--check`` plumbing every generator's
``main()`` drives identically.

Determinism (mirrors ``deck_facts.py`` verbatim): ``tree`` is the HEAD sha
(suffixed ``-dirty`` when tracked files are uncommitted) and ``derived_at``
is the HEAD commit DATE -- never wall-clock generation time -- so re-running
a generator on an unchanged tree writes byte-identical output no matter
when it is run.

Deliberately does not import ``pyforge.doctor``: these generators must run
correctly in whichever environment invokes their own pixi task, without
depending on Doctor's package being importable there (the ``--check`` side
of the contract lives IN Doctor, via ``cli_bridge.run_check_script``
running this generator as a subprocess -- see ``sources/docs_currency.py``,
Story 30.3's ``generated-page-stale`` check).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

# A top-level, single-line `description:` value -- the one field a failed
# frontmatter parse most needs to recover (see parse_frontmatter's fallback).
_DESCRIPTION_LINE_RE = re.compile(r"^description:[ \t]*(.+)$", re.MULTILINE)


def git(root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=root, check=True, capture_output=True, text=True
    ).stdout.strip()


def head_stamp(root: Path) -> dict[str, str]:
    """``{"derived_at": ..., "tree": ...}`` -- HEAD commit date (ISO-8601,
    ``%cI``) and HEAD sha, ``-dirty``-suffixed when tracked files carry
    uncommitted changes. Both come from the commit, not the clock, so two
    runs against the same tree state produce the identical pair."""
    dirty = bool(git(root, "status", "--porcelain", "--untracked-files=no"))
    return {
        "derived_at": git(root, "log", "-1", "--format=%cI"),
        "tree": git(root, "rev-parse", "HEAD") + ("-dirty" if dirty else ""),
    }


def render_header(generator_rel: str, task: str, stamp: dict[str, str]) -> str:
    """The GENERATED banner every page opens with -- names the generator,
    the pixi task that reruns it, and the stamp (facts.yaml's shape)."""
    return (
        f"<!-- GENERATED by {generator_rel} -- do not hand-edit. Regenerate with:\n"
        f"         pixi run -e pyforge-guild {task}\n"
        f"     derived_at: {stamp['derived_at']}\n"
        f"     tree: {stamp['tree']} -->\n"
    )


def _description_fallback(block: str) -> dict:
    """When ``block`` fails to parse as YAML, recover just the single-line
    ``description:`` value via regex rather than silently losing it.

    A plain-scalar ``description:`` value containing a mid-value ``": "``
    (e.g. ``description: Measure before optimizing. Five-step workflow:
    Measure -> ...``) is invalid unquoted YAML -- it reads as the start of a
    nested mapping -- so the WHOLE frontmatter block fails to parse. Found
    live 2026-09-24: ``idea-refine``, ``performance-optimization``,
    ``security-and-hardening`` and ``spec-driven-development`` all render
    blank descriptions in the skills catalog this way, with no finding
    raised anywhere (a caller's ``name`` fallback to the skill directory
    name already covers that field; ``description`` has no such fallback).
    Narrow on purpose: recovers the one field every caller actually needs
    when the full parse fails, not a general line-by-line re-parse."""
    match = _DESCRIPTION_LINE_RE.search(block)
    return {"description": match.group(1).strip()} if match else {}


def parse_frontmatter(text: str) -> dict:
    """Minimal ``---``-fenced YAML frontmatter reader. A second small copy
    of ``pyforge.doctor.sources.docs_currency``'s own
    ``_parse_page_frontmatter``, deliberately not imported from there: these
    generators must not depend on ``pyforge.doctor`` being importable in
    whichever environment runs their own pixi task."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            block = "\n".join(lines[1:index])
            try:
                data = yaml.safe_load(block)
            except yaml.YAMLError:
                return _description_fallback(block)
            return data if isinstance(data, dict) else {}
    return {}


def update_map_stamp(root: Path, page_rel: str, stamp: dict[str, str]) -> None:
    """Write ``stamp`` into ``docs/map.yaml``'s entry for ``page_rel`` (the
    ``docs/``-relative path, e.g. ``how-to/pixi-tasks.md``).

    Silently a no-op when ``map.yaml`` is missing/invalid or carries no
    entry for this page -- the generator's own page write already
    succeeded by the time this runs; a missing or malformed registry row is
    ``docs-map-hygiene``'s/``docs-currency``'s territory to report, not
    this helper's to raise over."""
    map_yaml = root / "docs" / "map.yaml"
    if not map_yaml.is_file():
        return
    try:
        data = yaml.safe_load(map_yaml.read_text(encoding="utf-8"))
    except yaml.YAMLError:
        return
    if not isinstance(data, dict):
        return
    pages = data.get("pages")
    if not isinstance(pages, list):
        return
    changed = False
    for page in pages:
        if isinstance(page, dict) and page.get("path") == page_rel:
            if page.get("stamp") != stamp:
                page["stamp"] = stamp
                changed = True
            break
    if changed:
        map_yaml.write_text(
            yaml.safe_dump(data, sort_keys=False, default_flow_style=False, allow_unicode=True),
            encoding="utf-8",
        )


def write_generated_page(
    root: Path,
    page_rel: str,
    content: str,
    *,
    check: bool,
    stamp: dict[str, str] | None = None,
) -> int:
    """The write+``--check`` plumbing every generator's ``main()`` shares.

    ``check=True``: compare ``content`` (a fresh in-memory render, stamp
    included) against the page currently on disk; print + return 0 when
    they match, 1 when they differ (stale -- a source moved past the
    stamp, a hand edit, or the page was never generated). Never writes,
    never touches ``docs/map.yaml`` -- this is the mode ``docs-currency``'s
    generated-page-stale check invokes via ``cli_bridge.run_check_script``.

    ``check=False``: write ``content`` (creating parent directories as
    needed), advance ``docs/map.yaml``'s stamp for this page to ``stamp``
    (the SAME dict the caller already embedded into ``content`` via
    :func:`render_header` -- passed through rather than recomputed, so a
    write is exactly one extra git read, not three), print whether the
    page's bytes actually changed, and return 0 -- writing always succeeds
    once the render itself didn't raise. ``stamp=None`` skips the
    ``docs/map.yaml`` update entirely (a caller with no stamp to record).
    """
    page_path = root / "docs" / page_rel
    current = page_path.read_text(encoding="utf-8") if page_path.is_file() else None

    if check:
        if current == content:
            print(f"[{page_rel}] current")
            return 0
        print(
            f"[{page_rel}] STALE -- regenerate with the matching guild-tasks pixi task",
            file=sys.stderr,
        )
        return 1

    page_path.parent.mkdir(parents=True, exist_ok=True)
    changed = current != content
    page_path.write_text(content, encoding="utf-8")
    if stamp is not None:
        update_map_stamp(root, page_rel, stamp)
    print(f"[{page_rel}] {'wrote' if changed else 'unchanged'} ({'changed' if changed else 'no content change'})")
    return 0
