#!/usr/bin/env python3
"""bmad-estate-check — the derived BMAD-estate catalog matches its sources (Story 24.2, CAP-32).

WHAT IT CHECKS
--------------
`docs/reference/bmad-estate-llms-full.md` is GENERATED by `scribe catalog bmad-estate`
from in-tree sources (the installed manifests, every `.claude/skills/*/SKILL.md`,
`bmad-help.csv`, `suite-members.yaml` joined with steward's adoption register, the
`bmad-*` pins in `pixi.toml`, the marshal harness range, the release-cadence steps).
Each section of the rendered file carries a digest of its derived facts; this detector
re-derives the facts and reds when any section's digest moved -- structured, not
byte-exact (OQ-CAP-32-1, decided here): a prose tweak in the generator template is not
drift, a moved fact always is. The reconcile is the regeneration command in the
catalog's own header, stated once.

A thin wrapper: the verdict is `scribe catalog bmad-estate --check`'s (the CLI entry,
never `pyforge.scribe` internals), run in-process through the same interpreter so the
registry's environment is the one judged.

EXIT
    0  the catalog matches its sources
    1  at least one section drifted (each named with its source paths)
    2  could not run -- `pyforge.scribe` is not importable here, or a source cannot be read
"""

from __future__ import annotations

# Registry declaration -- see scripts/detectors.py. `repo`: reads tracked files only.
DETECTOR = {"scope": "repo"}

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PREFIX = "[bmad-estate]"


def run_check(root: Path) -> tuple[int, list[str]]:
    """Return (exit_code, output_lines) from the scribe CLI's own check."""
    command = [sys.executable, "-m", "pyforge.scribe.cli", "catalog", "bmad-estate", "--check", "--root", str(root)]
    try:
        proc = subprocess.run(command, capture_output=True, text=True, check=False)
    except OSError as exc:
        return 2, [f"{PREFIX} could-not-run: {exc}"]
    lines = [line for line in (proc.stdout + proc.stderr).splitlines() if line.strip()]
    if proc.returncode not in (0, 1, 2):
        return 2, [f"{PREFIX} could-not-run: scribe exited {proc.returncode}", *lines]
    if proc.returncode == 2 and not any("could-not-run" in line for line in lines):
        # `python -m pyforge.scribe.cli` itself failed to start (module missing, import error).
        return 2, [f"{PREFIX} could-not-run: `pyforge.scribe` is not importable in this environment", *lines]
    return proc.returncode, lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--root", type=Path, default=ROOT, help="Repository root (default: this checkout).")
    parser.add_argument("--json", action="store_true", help="Emit {status, findings} as JSON.")
    args = parser.parse_args(argv)
    code, lines = run_check(args.root)
    status = {0: "ok", 1: "findings", 2: "could-not-run"}[code]
    if args.json:
        print(json.dumps({"detector": "bmad-estate-check", "status": status, "exit": code, "findings": lines}))
    else:
        for line in lines:
            print(line)
    return code


if __name__ == "__main__":
    sys.exit(main())
