#!/usr/bin/env python3
"""Push every loop home's branches on an interval, for as long as a run is live.

WHY. A bmad-loop dev phase commits 1,000-2,000 lines in one go and then moves
straight into review. Nothing pushes it. On 2026-07-31 marshal story 1.8 sat as
a local-only commit of 1,748 lines across 11 files for ~40 minutes, and was
found only because the operator asked a second time — the first "everything is
saved" was true when it was said and false forty minutes later. That window is
not a backlog to clear once: it REOPENS every time any of nine stations finishes
a dev phase, roughly every 60-90 minutes each.

The exposure is not just lost code. A discarded story is lost compute, tokens
and wall-clock — marshal 1.8 alone was 8.8M weighted tokens and about an hour.

WHY NOT A HOOK. `.bmad-loop/bmad_loop_hook.py` is bmad-loop's own event relay,
regenerated by `bmad-loop init`; anything added there is overwritten on the next
provision. bmad-loop itself is a git-pinned external dependency, so its
completion path is not ours to edit either. A watcher alongside the run touches
nothing either owns, and covers all nine homes uniformly.

WHAT IT PUSHES. For every home under ~/.bmad-loops: the station branch
(loop/pyforge-*) and every per-story worktree branch under
.bmad-loop/runs/*/worktrees/. Push is read-only with respect to working trees —
it cannot disturb a live session, which is what makes this safe to run
concurrently with the fleet.

LIFECYCLE. Exits by itself once no bmad-loop engine process remains, so it never
outlives the fleet — the same contract dashboard-watch follows. Run it detached
beside a fleet launch.

This bounds worst-case loss to one interval. It does not eliminate it: the
durable fix is for the loop to push at its own stage boundaries, and this is the
stopgap that makes the next dev phase survivable in the meantime.
"""
from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys
import time

HOMES = pathlib.Path.home() / ".bmad-loops"


def sh(args: list[str], cwd: pathlib.Path | None = None, timeout: int = 180) -> tuple[int, str]:
    try:
        p = subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return p.returncode, (p.stdout + p.stderr).strip()
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 1, f"{type(exc).__name__}: {exc}"


def engine_running() -> bool:
    rc, out = sh(["pgrep", "-af", "bmad-loop"])
    if rc != 0:
        return False
    # `bmad-loop run` is the engine; anything else (status, attach, this
    # watcher's own pgrep) does not keep the fleet alive.
    return any(" run" in ln and "pgrep" not in ln for ln in out.splitlines())


def branches_for(home: pathlib.Path) -> list[str]:
    """The station branch plus every live per-story worktree branch."""
    refs: list[str] = []
    rc, cur = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=home)
    if rc == 0 and cur and cur != "HEAD":
        refs.append(cur)
    rc, out = sh(["git", "worktree", "list", "--porcelain"], cwd=home)
    if rc == 0:
        for line in out.splitlines():
            if line.startswith("branch refs/heads/"):
                br = line.split("refs/heads/", 1)[1].strip()
                if br and br not in refs:
                    refs.append(br)
    return refs


def push_cycle(verbose: bool) -> tuple[int, int]:
    pushed = failed = 0
    for home in sorted(p for p in HOMES.glob("*") if (p / ".git").exists()):
        refs = branches_for(home)
        if not refs:
            continue
        # One push per home: git resolves already-up-to-date refs as no-ops, so
        # the steady-state cost is a single network round trip per home.
        rc, out = sh(["git", "push", "--porcelain", "origin", *refs], cwd=home)
        if rc == 0:
            moved = [ln for ln in out.splitlines()
                     if ln and not ln.startswith("=") and "[up to date]" not in ln
                     and not ln.startswith("Done")]
            pushed += 1
            if verbose and moved:
                print(f"  {home.name}: {len(moved)} ref(s) advanced")
                for ln in moved[:6]:
                    print(f"      {ln}")
        else:
            failed += 1
            print(f"  {home.name}: PUSH FAILED — {out.splitlines()[-1] if out else 'unknown'}")
    return pushed, failed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--interval", type=int, default=180,
                    help="seconds between cycles (default 180 — bounds worst-case loss)")
    ap.add_argument("--once", action="store_true", help="one cycle, then exit")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not HOMES.exists():
        print(f"no loop homes at {HOMES} — nothing to watch.")
        return 0

    if args.once:
        p, f = push_cycle(not args.quiet)
        print(f"pushed {p} home(s), {f} failure(s)")
        return 1 if f else 0

    print(f"loop-push-watch: every {args.interval}s while a bmad-loop engine runs")
    print("(exits by itself when the last run finishes)\n")
    cycle = 0
    while True:
        if not engine_running():
            print("no live run — final cycle, then exiting.")
            push_cycle(not args.quiet)
            return 0
        cycle += 1
        stamp = time.strftime("%H:%M:%S")
        p, f = push_cycle(not args.quiet)
        if not args.quiet:
            print(f"[{stamp}] cycle {cycle} — {p} home(s) pushed"
                  + (f", {f} FAILED" if f else ""))
        time.sleep(args.interval)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
