"""The single, enforced list of every place a pixi version is pinned in this
repo. Shared by `scripts/pixi_version_check.py` (detector) and
`scripts/bump_pixi_version.py` (mutator) so there is exactly one registry,
never two that can drift apart from each other.

WHY THIS EXISTS. `pixi.toml`'s own `requires-pixi` comment used to be that
registry -- a hand-maintained enumeration, explicit that "NOTHING ENFORCES
ANY OF THIS." It drifted three times before this file existed (wrong site
COUNT twice, one whole site -- this repo's `dbgpt-sidecar` Containerfile --
never registered at all, which is exactly how it silently sat at the OLD
floor and broke `container-dbgpt` CI the first push after the 2026-08-21
upgrade). This module is the promised "detector is the durable fix."

Each `Site` names a file and a regex with exactly one capture group around
the version string. `expected_hits` guards against silent drift in the
registry itself: a file that used to contain 3 identical pins and now
contains 2 (or 4) is a finding, not a quiet mismatch.

`environment.yaml` is deliberately covered by the CHECK but never rewritten
by the MUTATOR here -- it is DERIVED (`pixi project export conda-environment
-e build > environment.yaml`), and hand-patching it would fight the real
generator the moment pixi's own export format changes anything else in the
file. `bump_pixi_version.py` shells out to the real command instead.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

_PIXI_VERSION = r"(\d+\.\d+\.\d+)"


@dataclass(frozen=True)
class Site:
    name: str
    path: Path
    pattern: re.Pattern[str]
    expected_hits: int
    kind: str  # "exact" (must equal the floor byte-for-byte) or "floor" (same, by this repo's own convention -- see requires-pixi's "kept in step")
    derived: bool = False  # True: check only, never hand-rewritten (regenerated by its own real command instead)


def _site(name: str, rel: str, pattern: str, *, hits: int = 1, kind: str, derived: bool = False) -> Site:
    return Site(name, REPO_ROOT / rel, re.compile(pattern, re.MULTILINE), hits, kind, derived)


SITES: tuple[Site, ...] = (
    _site("pixi.toml $schema URL", "pixi.toml",
          r'"\$schema" = "https://pixi\.sh/v' + _PIXI_VERSION + r'/schema/manifest/schema\.json"',
          kind="exact"),
    _site("pixi.toml requires-pixi", "pixi.toml",
          r'requires-pixi = ">=' + _PIXI_VERSION + r'"', kind="floor"),
    _site("pixi.toml feature pixi floors (python/local-recipes/build)", "pixi.toml",
          r'^pixi = ">=' + _PIXI_VERSION + r'"\s+# Pixi package & environment manager$',
          hits=3, kind="floor"),
    _site("environment.yaml", "environment.yaml",
          r"^- pixi >=" + _PIXI_VERSION + r"$", kind="floor", derived=True),
    _site("dashboard.yml setup-pixi", ".github/workflows/dashboard.yml",
          r"pixi-version: v" + _PIXI_VERSION, kind="exact"),
    _site("kedro-viz-publish.yml setup-pixi", ".github/workflows/kedro-viz-publish.yml",
          r"pixi-version: v" + _PIXI_VERSION, kind="exact"),
    _site("detectors.yml setup-pixi", ".github/workflows/detectors.yml",  # PR #1043: pixi-first detectors env
          r"pixi-version: v" + _PIXI_VERSION, kind="exact"),
    _site("docsite-check.yml setup-pixi", ".github/workflows/docsite-check.yml",  # herald 24.2's PR lane (2026-09-18) sat unregistered at v0.80.0 through the 0.81.0 bump (2026-09-20) -- found by a grep sweep, the registry's own recurring failure mode
          r"pixi-version: v" + _PIXI_VERSION, kind="exact"),
    _site("platform-ci.yml setup-pixi (4 jobs)", ".github/workflows/platform-ci.yml",  # PR #1043: four jobs sat on 0.77.0 unregistered while requires-pixi said >=0.78.0
          r"pixi-version: v" + _PIXI_VERSION, hits=4, kind="exact"),
    _site("platform-deploy.yml setup-pixi", ".github/workflows/platform-deploy.yml",
          r"pixi-version: v" + _PIXI_VERSION, kind="exact"),
    _site("herald-live-demo.yml setup-pixi (3 jobs)", ".github/workflows/herald-live-demo.yml",
          r"pixi-version: v" + _PIXI_VERSION, hits=3, kind="exact"),
    _site("sync-pypi-mappings/action.yml setup-pixi", ".github/actions/sync-pypi-mappings/action.yml",
          r"pixi-version: v" + _PIXI_VERSION, kind="exact"),
    _site("platform-test-setup/action.yml setup-pixi", ".github/actions/platform-test-setup/action.yml",
          r"pixi-version: v" + _PIXI_VERSION, kind="exact"),
    _site("staged-recipes-linter.yml micromamba create-arg", ".github/workflows/staged-recipes-linter.yml",
          r"pixi>=" + _PIXI_VERSION, kind="floor"),
    _site("root Containerfile builder stage", "Containerfile",
          r"ghcr\.io/prefix-dev/pixi:" + _PIXI_VERSION + r" AS builder", kind="exact"),
    _site("src/platform/Containerfile builder stage", "src/platform/Containerfile",
          r"ghcr\.io/prefix-dev/pixi:" + _PIXI_VERSION + r" AS builder", kind="exact"),
    _site("src/platform/compose/dbgpt/Containerfile builder stage",
          "src/platform/compose/dbgpt/Containerfile",
          r"ghcr\.io/prefix-dev/pixi:" + _PIXI_VERSION + r" AS builder", kind="exact"),
    _site("src/platform/compose/mcp-host/Containerfile builder stage",
          "src/platform/compose/mcp-host/Containerfile",
          r"ghcr\.io/prefix-dev/pixi:" + _PIXI_VERSION + r" AS builder", kind="exact"),
)


def master_version() -> str:
    """The version every site is judged against: pixi.toml's own requires-pixi floor."""
    for site in SITES:
        if site.name == "pixi.toml requires-pixi":
            text = site.path.read_text(encoding="utf-8")
            m = site.pattern.search(text)
            if not m:
                raise RuntimeError("pixi.toml requires-pixi not found -- cannot determine the master version")
            return m.group(1)
    raise AssertionError("requires-pixi site missing from SITES")


def read_versions(site: Site) -> tuple[list[str], bool]:
    """(versions found, path existed). A missing file is distinguished from a
    file with zero matches -- the caller must not conflate them."""
    if not site.path.is_file():
        return [], False
    text = site.path.read_text(encoding="utf-8")
    return [m.group(1) for m in site.pattern.finditer(text)], True
