# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.4.2"

package:
  name: cmake
  version: ${{ version }}

source:
  url: https://github.com/Kitware/CMake/releases/download/v${{ version }}/cmake-${{ version }}.tar.gz
  sha256: 1db9e61e60b6e0874c86386340b910382f3c5e75b9fbfb44d122063129a2789d

build:
  number: 0
  script:
    env:
      MAJOR_MINOR: ${{ ".".join(version | split(".")[:2]) }}

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: unix
      then: cmake-no-system
    - ninja
    - if: win
      then: 7zip
  host:
    - bzip2
    - libcurl
    - expat
    - if: unix
      then: ncurses
    - liblzma-devel
    - zlib
    - libuv
    - if: unix
      then: rhash
    - zstd
  ignore_run_exports:
    by_name:
      - vc

tests:
  - script:
      - cmake --version
      - ctest --version
      - cpack --version
      - ccmake --version
      - if: unix
        then: test ! -d $PREFIX/doc
      - if: win
        then: if exist %LIBRARY_PREFIX%\\doc exit 1

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE.rst
    - if: win
      then: Utilities/cmlibrhash/COPYING
    - if: win
      then: Utilities/cmpdcurses/README.md
    - if: win
      then: Utilities/cmpdcurses/wincon/README.md
    - Utilities/cmcppdap/LICENSE
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmjsoncpp/LICENSE
  summary: CMake is an extensible, open-source system that manages the build process
  homepage: http://www.cmake.org/
  repository: https://gitlab.kitware.com/cmake/cmake
  documentation: https://cmake.org/documentation

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
