# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.12.1"

package:
  name: jupyter-events
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-events/jupyter_events-${{ version }}.tar.gz
  sha256: faff25f77218335752f35f23c5fe6e4a392a7bd99a5939ccb9b8fbf594636cf3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5
  run:
    - python >=${{ python_min }}
    - jsonschema >=4.18.0
    - packaging
    - python-json-logger >=2.0.4
    - pyyaml >=5.3
    - referencing
    - rfc3339-validator
    - rfc3986-validator >=0.1.1
    - traitlets >=5.3

tests:
  - python:
      imports:
        - jupyter_events
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Event System library
  description: |
    Jupyter Event System library
  documentation: https://jupyter-events.readthedocs.io/

extra:
  recipe-maintainers:
    - Zsailer
    - blink1073
    - afshin
    - bollwyvl

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: jupyter_events
  cfe-upstream-registry: pypi
  cfe-upstream-name: jupyter-events
  cfe-purls:
    - pkg:conda/jupyter_events@${{ version }}?channel=conda-forge
    - pkg:pypi/jupyter-events@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: http://jupyter.org
  cfe-import-names: [jupyter_events]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/jupyter_events-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T00:30:48Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T00:30:48Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T00:30:48Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
