{% set name = "shot-scraper" %}
{% set version = "1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shot_scraper-{{ version }}.tar.gz
  sha256: 2174f5a23a8e43f4f47bda9eb65f39d0d86c4cfd3930450499daa88ecf1ee2fd

build:
  entry_points:
    - shot-scraper = shot_scraper.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.9.7,<0.10.0
  run:
    - python >={{ python_min }}
    - click
    - pyyaml
    - playwright
    - click-default-group

test:
  imports:
    - shot_scraper
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonw/shot-scraper
  summary: A command-line utility for taking automated screenshots of websites
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
