# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: attrs
  version: "26.1.0"
  sha256: d03ceb89cb322a8fd706d4fb91940737b6642aa36998fe130a9bc96c985eff32

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  noarch: python
  number: 0
  script: "python -m pip install . -vv"

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - attr
      pip_check: true

about:
  homepage: https://attrs.readthedocs.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: attrs is the Python package that will bring back the joy of writing classes by relieving you from the drudgery of implementing object protocols (aka dunder methods).
  description: |
    attrs is the Python package that will bring back the joy of writing
    classes by relieving you from the drudgery of implementing object
    protocols (aka dunder methods). Its main goal is to help you to write
    concise and correct software without slowing down your code. For that, it
    gives you a class decorator and a way to declaratively define the
    attributes on that class:
  documentation: https://attrs.readthedocs.io/en/stable/
  repository: https://github.com/python-attrs/attrs

extra:
  recipe-maintainers:
    - CJ-Wright
    - licode
    - nicoddemus
    - jochym
