# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: djangorestframework
  version: "3.18.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/djangorestframework-${{ version }}.tar.gz
  sha256: 2323a5111837e0b784dcb8323abc78ecc54fa2a5af7aff2677cf50cdd849477f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - django >=5.2

tests:
  - python:
      imports:
        - rest_framework
        - rest_framework.authtoken
        - rest_framework.authtoken.migrations
        - rest_framework.templatetags
        - rest_framework.utils
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Web APIs for Django, made easy.
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://www.django-rest-framework.org/
  repository: https://github.com/encode/django-rest-framework

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
