schema_version: 1

context:
  name: robotcode-modifiers
  version: 1.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robotcode_modifiers-${{ version }}.tar.gz
  sha256: 88611c3e90db35646c4a06838e1b8278bf6a6b15384f603872edae34563a0f99

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - robotframework >=4.1.0

tests:
  - python:
      imports:
        - robotcode_modifiers
      pip_check: true

about:
  summary: Some Robot Framework Modifiers for RobotCode
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/robotcodedev/robotcode

extra:
  recipe-maintainers:
    - rxm7706
