# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.0"

package:
  name: jupyterlab-pygments
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-pygments/jupyterlab_pygments-${{ version }}.tar.gz
  sha256: 721aca4d9029252b11cfa9d185e5b5af4d54772bb8072f9b7036f4170054d35d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - jupyterlab_pygments
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/jupyterlab/jupyterlab_pygments
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Pygments theme using JupyterLab CSS variables
  description: |
    Pygments theme using JupyterLab CSS variables
  repository: https://github.com/jupyterlab/jupyterlab_pygments.git

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - martinRenou

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: jupyterlab_pygments
  cfe-upstream-registry: pypi
  cfe-upstream-name: jupyterlab-pygments
  cfe-purls:
    - pkg:conda/jupyterlab_pygments@${{ version }}?channel=conda-forge
    - pkg:pypi/jupyterlab-pygments@${{ version }}
  cfe-upstream-repo: https://github.com/jupyterlab/jupyterlab_pygments.git
  cfe-upstream-homepage: https://github.com/jupyterlab/jupyterlab_pygments
  cfe-import-names: [jupyterlab_pygments]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/jupyterlab_pygments-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.3.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T00:43:12Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T00:43:12Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-18T00:43:12Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
