# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ydata-synthetic
  version: "2.0.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ydataai/ydata-synthetic/archive/${{ version }}.tar.gz
  sha256: 101b7400e984f6f9c71eadf97772bd6a5c9cf6b5a3c4be505d1c843847d400b2

build:
  number: 0
  noarch: python
  script:
    #- cp $RECIPE_DIR/requirements.txt $SRC_DIR/requirements.txt
    #- echo "__version__ = '${{ version }}'" > version.py
    #- export $SRC_DIR/VERSION=${{ version }}
    #- ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    -  script: SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    #- setuptools
    - setuptools >=67.4.0,<68.0.0
    - setuptools-scm >=7.1.0,<8.0.0
    - wheel >=0.38.4,<1.0.0
  run:
    - python >=${{ python_min }},<4.0
    - requests >=2.30
    - pandas >=2.0.0
    - numpy >=1.23.0
    - scikit-learn >=1.3.0
    - matplotlib-base >=3.7.0
    - tensorflow-cpu >=2.12.0
    - tensorflow-probability >=0.19.0
    - easydict >=1.10
    - pmlb >=1.0.0
    - tqdm <5.0
    - typeguard >=4.0.0
    - pytest >=7.4.0
    - ydata-sdk >=1.1.4

tests:
  - python:
      imports:
        - ydata
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/ydataai/ydata-synthetic
  summary: Synthetic data generation methods with different synthetization methods.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
