# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pyjwkest
  version: "1.4.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyjwkest-${{ version }}.tar.gz
  sha256: 5560fd5ba08655f29ff6ad1df1e15dc05abc9d976fcbcec8d2b5167f49b70222

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - pycryptodomex
    - requests
    - six
    - future

tests:
  - python:
      imports:
        - jwkest
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/IdentityPython/pyjwkest
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python implementation of JWT, JWE, JWS and JWK

extra:
  recipe-maintainers:
    - mariusvniekerk
    - rxm7706
