# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pyIsEmail
  version: "1.3.2"
  sha256: 665af6de136868b3aceea9198d3f0fe673582492ad7d3e863108118b2296e551

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dnspython >=1.15.0

tests:
  - python:
      imports:
        - pyisemail
        - pyisemail.diagnosis
        - pyisemail.validators
      pip_check: false

about:
  license: MIT
  license_file: LICENSE
  summary: Simple, robust email validation
  homepage: https://github.com/michaelherold/pyIsEmail

extra:
  recipe-maintainers:
    - mrakitin
