# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.2.7"

package:
  name: dataframe-image
  version: ${{ version }}

source:
  url: https://github.com/dexplo/dataframe_image/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6d96368cbf64e8291587242bd6442ed2961cc021a06d2ccf1d309fe460e77831

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pandas >=0.24
    - nbconvert >=5
    - aiohttp >=3.10.2
    - requests
    - pillow
    - packaging
    - mistune
    - lxml
    - beautifulsoup4
    - cssutils
    - playwright
    - cssselect

tests:
  - python:
      imports:
        - dataframe_image
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/dexplo/dataframe_image
  license: MIT
  license_file: LICENSE
  summary: Embed pandas DataFrames as images in pdf and markdown files when converting from Jupyter Notebooks
  description: |
    Embed pandas DataFrames as images in pdf and markdown files when converting from Jupyter Notebooks

extra:
  recipe-maintainers:
    - tdpetrou

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: dataframe_image
  cfe-upstream-registry: pypi
  cfe-upstream-name: dataframe-image
  cfe-purls:
    - pkg:conda/dataframe_image@${{ version }}?channel=conda-forge
    - pkg:pypi/dataframe-image@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/dexplo/dataframe_image
  cfe-import-names: [dataframe_image]
  cfe-source-kind: github-tag
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/dataframe_image-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.2.7

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T07:31:12Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T07:31:12Z
  cfe-local-build-status: build-clean-test-blocked
  cfe-local-build-datetime: 2026-08-17T07:31:12Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
