{% set name = "wagtail-color-panel" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aca26f8b7178ff596aa2eac8982167396bbbc222fadbae4b6b1f18291b33473a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pytest-runner
    - pip
    - setuptools
  run:
    - python-dotenv
    - django
    - python >={{ python_min }}
    - wagtail >=6.3

test:
  imports:
    - wagtail_color_panel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marteinn/wagtail-color-panel
  summary: A package that adds new panels for selecting colors, works both on regular page fields and stream field.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
