# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pi-heif
  version: "1.1.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pi_heif-${{ version }}.tar.gz
  sha256: 42ece7c3b40569f295fd4d2b10f38d1cd5012ca548446a2ca33895f0d6900c4f

build:
  number: 0
  skip:
    - match(python, "<3.10")
    - match(python, ">=3.14")
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler("c") }}
    #- ${{ stdlib("c") }}
  host:
    - python
    - setuptools >=67.8
    - wheel
    - pip
    - libheif
  run:
    - python
    - pillow >=11.1.0

tests:
  - python:
      # python_version: ${{ python_min }}.*
      imports:
        - pi_heif
      pip_check: true
  - requirements:
      run:
        - pip
        #- python {{ python_min }}
    script:
      - pip check
      - python -c "import pi-heif; print(pi-heif.__version__)"

about:
  summary: Python interface for libheif library
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - tests/images/heif_other/nokia/COPYRIGHT.txt
  homepage: https://github.com/bigcat88/pillow_heif
  repository: https://github.com/bigcat88/pillow_heif

extra:
  recipe-maintainers:
    - rxm7706
