{% set name = "pymoo" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymoo-{{ version }}.tar.gz
  sha256: 6f497c00d7cf7598d176a5cd244b4cc66661811a6e81a715a83e2cd545fefe7d

build:
  number: 0

  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - autograd >=1.4
    - cma >=3.4.0
    - matplotlib-base >=3
    - numpy >=1.19.3
    - python
    - python-moocore >=0.1.7
    - scipy >=1.1
    - dill
    - alive-progress
    - Deprecated

test:
  imports:
    - pymoo
    - pymoo.algorithms
  commands:
    - pip check
    - python -c "from pymoo.functions import is_compiled; exit(is_compiled()!=True)"
  requires:
    - pip

about:
  home: https://pymoo.org
  summary: Multi-Objective Optimization in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyrilpic
    - d-cunningham
    - mxr-conda
