# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "9.2.0"

package:
  name: ipyparallel
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/ipyparallel/ipyparallel-${{ version }}.tar.gz
  sha256: 2b31bb4e94708e7ffb4ee6501d7f5f664df7e1c4c572e91e9e0d12484c6a6910

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - jupyterlab ==4.*
    - hatchling >=0.25
  run:
    - python >=${{ python_min }}
    - decorator
    - ipykernel >=6.9.1
    - ipython >=5
    - jupyter-client >=7
    - psutil
    - python-dateutil >=2.1
    - pyzmq >=25
    - tornado >=6.1
    - tqdm
    - traitlets >=5

tests:
  - python:
      imports:
        - ipyparallel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://ipython.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Interactive Parallel Computing with IPython
  description: |
    Interactive Parallel Computing with IPython

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - bollwyvl

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: ipyparallel
  cfe-upstream-registry: pypi
  cfe-upstream-name: ipyparallel
  cfe-purls:
    - pkg:conda/ipyparallel@${{ version }}?channel=conda-forge
    - pkg:pypi/ipyparallel@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://ipython.org
  cfe-import-names: [ipyparallel]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/ipyparallel-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T00:01:17Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T00:01:17Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-18T00:01:17Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
