# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: RapidOCR
  version: "3.3.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/RapidAI/RapidOCR/archive/v${{ version }}.tar.gz
  sha256: 13fd2d0db1e33383d284f63a249ebba1143e0b7f5ddea1b10951a9ee17703f46

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install python/ -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - rapidocr=rapidocr.main:main

requirements:
  host:
    - python ${{ python_min }}.*
    #- get_pypi_latest_version
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - pyclipper >=1.2.0
    - opencv_python >=4.5.1.48
    - numpy >=1.19.5,<3.0.0
    - six >=1.15.0
    - shapely >=1.7.1,!=2.0.4
    - pyyaml
    - pillow
    - tqdm
    - omegaconf
    - requests
    - colorlog

tests:
  - python:
      imports:
        - cal_rec_boxes
        - ch_ppocr_cls
        - ch_ppocr_det
        - ch_ppocr_rec
        - inference_engine
        - models
        - networks
        - utils
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - rapidocr --help

about:
  summary: Awesome OCR Library
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/RapidAI/RapidOCR

extra:
  recipe-maintainers:
    - rxm7706
