# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.9.29"

package:
  name: concurrent-log-handler
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/concurrent-log-handler/concurrent_log_handler-${{ version }}.tar.gz
  sha256: bc37a76d3f384cbf4a98f693ebd770543edc0f4cd5c6ab6bc70e9e1d7d582265

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - portalocker >=2.6.0

tests:
  - python:
      imports:
        - concurrent_log_handler
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/Preston-Landers/concurrent-log-handler
  license: Apache-2.0
  license_file: LICENSE
  summary: RotatingFileHandler replacement with concurrency, gzip and Windows support. Size and time based rotation.
  description: |
    RotatingFileHandler replacement with concurrency, gzip and Windows support. Size and time based rotation.

extra:
  recipe-maintainers:
    - mariusvniekerk

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: concurrent-log-handler
  cfe-upstream-registry: pypi
  cfe-upstream-name: concurrent-log-handler
  cfe-purls:
    - pkg:conda/concurrent-log-handler@${{ version }}?channel=conda-forge
    - pkg:pypi/concurrent-log-handler@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/Preston-Landers/concurrent-log-handler
  cfe-import-names: [concurrent_log_handler]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/concurrent-log-handler-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-0.9.29

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T08:31:37Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T08:31:37Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-18T08:31:37Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
