#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by conda-smithy. Any changes here
# will be lost next time ``conda smithy rerender`` is run. If you would like to make permanent
# changes to this script, consider a proposal to conda-smithy so that other feedstocks can also
# benefit from the improvement.

set -xeuo pipefail

export FEEDSTOCK_ROOT="${FEEDSTOCK_ROOT:-/home/conda/staged-recipes}"
source "${FEEDSTOCK_ROOT}/.scripts/logging_utils.sh"

# This closes the matching `startgroup` on `run_docker_build.sh`
( endgroup "Start Docker" ) 2> /dev/null

( startgroup "Configuring conda" ) 2> /dev/null

export PYTHONUNBUFFERED=1
export CI_SUPPORT="/home/conda/staged-recipes-copy/.ci_support"
export RATTLER_CACHE_DIR="${FEEDSTOCK_ROOT}/build_artifacts/pkg_cache"

cat >~/.condarc <<CONDARC
always_yes: true

channels:
 - conda-forge

conda-build:
  root-dir: ${FEEDSTOCK_ROOT}/build_artifacts

pkgs_dirs:
  - ${FEEDSTOCK_ROOT}/build_artifacts/pkg_cache
  - /opt/conda/pkgs

show_channel_urls: true

solver: libmamba
CONDARC

# Workaround for errors related to "unsafe" directories:
# https://github.blog/2022-04-12-git-security-vulnerability-announced/#cve-2022-24765
git config --global --add safe.directory "${FEEDSTOCK_ROOT}"

# Copy the host recipes folder so we don't ever muck with it
# Skip build_artifacts and other big items because it gets huge with time
mkdir -p ~/staged-recipes-copy
shopt -s extglob dotglob
cp -r "${FEEDSTOCK_ROOT}"/!(.|..|build_artifacts|.pixi|miniforge3|MacOSX*.sdk.tar.xz|SDKs|output) ~/staged-recipes-copy
shopt -u extglob dotglob

# Remove any macOS system files
find ~/staged-recipes-copy/recipes -maxdepth 1 -name ".DS_Store" -delete

# Select which recipes to build.
#
# `build_all.py` has no recipe selector -- it builds every folder under
# `recipes/`. In conda-forge/staged-recipes the SELECTION is therefore done by
# deletion: `recipes/` on `main` holds only recipes not yet graduated to a
# feedstock, so removing everything already on `main` leaves exactly the new
# recipe the PR added.
#
# That premise is FALSE in this repo, in two ways, and both are fatal:
#   1. `main` here permanently carries every recipe (7,867 paths as of
#      2026-09-09), including the one being built -- so the staged-recipes
#      pruning deletes the build target and `build_all.py` then "succeeds"
#      having built nothing.
#   2. `git fetch --force origin main:main` assumes an anonymous fetch works.
#      staged-recipes is public; this repo is PRIVATE, so inside the container
#      (which has no credential helper) it dies with
#      `fatal: could not read Username for 'https://github.com'` -- exit 128,
#      which is how this surfaced.
#
# So when TEST_RECIPE names a recipe, select it POSITIVELY and skip the fetch
# entirely. The staged-recipes path is kept verbatim as the `else` branch so an
# upstream-shaped checkout still behaves exactly as conda-smithy generated it.
echo "Pending recipes."
ls -la ~/staged-recipes-copy/recipes
if [ -n "${TEST_RECIPE:-}" ]; then
    echo "TEST_RECIPE=${TEST_RECIPE}: keeping only that recipe in the build copy."
    if [ ! -d ~/staged-recipes-copy/recipes/"${TEST_RECIPE}" ]; then
        echo "ERROR: recipes/${TEST_RECIPE} is not in the build copy." >&2
        exit 1
    fi
    find ~/staged-recipes-copy/recipes -mindepth 1 -maxdepth 1 -type d \
        ! -name "${TEST_RECIPE}" -exec rm -rf {} +
    ls -la ~/staged-recipes-copy/recipes
else
    echo "Finding recipes merged in main and removing them from the build."
    pushd "${FEEDSTOCK_ROOT}/recipes" > /dev/null
    if [ "${CI:-}" != "" ]; then
        git fetch --force origin main:main
    fi
    shopt -s extglob dotglob
    git ls-tree --name-only main -- !(example|example-v1)  | xargs -I {} sh -c "rm -rf ~/staged-recipes-copy/recipes/{} && echo Removing recipe: {}"
    shopt -u extglob dotglob
    popd > /dev/null
fi

# Update environment
mv /opt/conda/conda-meta/history /opt/conda/conda-meta/history.$(date +%Y-%m-%d-%H-%M-%S)
echo > /opt/conda/conda-meta/history
micromamba install --root-prefix ~/.conda --prefix /opt/conda \
    --yes --override-channels --channel conda-forge --strict-channel-priority \
    --file "${FEEDSTOCK_ROOT}/environment.yaml"

setup_conda_rc "${FEEDSTOCK_ROOT}" "/home/conda/staged-recipes-copy/recipes" "${CI_SUPPORT}/${CONFIG}.yaml"
source run_conda_forge_build_setup

# yum installs anything from a "yum_requirements.txt" file that isn't a blank line or comment.
find ~/staged-recipes-copy/recipes -mindepth 2 -maxdepth 2 -type f -name "yum_requirements.txt" \
    | xargs -n1 cat | { grep -v -e "^#" -e "^$" || test $? == 1; } | \
    xargs -r /usr/bin/sudo -n yum install -y

# Make sure build_artifacts is a valid channel
conda index "${FEEDSTOCK_ROOT}/build_artifacts"

( endgroup "Configuring conda" ) 2> /dev/null

echo "Building all recipes"
python "${CI_SUPPORT}/build_all.py"

( startgroup "Inspecting artifacts" ) 2> /dev/null
# inspect_artifacts was only added in conda-forge-ci-setup 4.6.0; --all-packages in 4.9.3
command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts --all-packages || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.3"
( endgroup "Inspecting artifacts" ) 2> /dev/null

( startgroup "Final checks" ) 2> /dev/null

touch "${FEEDSTOCK_ROOT}/build_artifacts/conda-forge-build-done"
