# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  build_number: 1
  name: numba
  version: 0.66.0
  sha256: b900e63a0e26c05ea9a6d5a3a5a0a177cb64c5011887bf43edb8c3ed2c38d363
  fast_tests: "1"

package:
  name: numba
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: ${{ build_number }}
  skip: match(python, "<3.10")
  script:
    - if: linux
      then: export CC="${CC} -pthread"
    - if: linux
      then: export CXX="${CXX} -pthread"
    - ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  python:
    entry_points:
      - numba = numba.misc.numba_entry:main

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy >=1.24,<2.5
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    # llvm is needed for the headers
    - if: osx
      then: llvm-openmp
    - if: linux
      then: libgomp
  host:
    - python
    - pip
    - setuptools
    - llvmlite 0.48.*
    - numpy >=1.24,<2.5
    - tbb-devel 2021.6.0.*
  run:
    - python
    - ${{ pin_compatible('llvmlite', upper_bound='x.x') }}
    # NumPy has lower and upper limits
    - numpy >=1.22.3,<2.5
  ignore_run_exports:
    by_name:
      - tbb
  run_constraints:
    - ${{ pin_compatible('tbb', upper_bound=None) }}
    - if: x86_64
      then: libopenblas !=0.3.6
    - if: arm64
      then: libopenblas >=0.3.18,!=0.3.20
    - cuda-version >=11.2
    - cudatoolkit >=11.2
    - scipy >=1.0
    - cuda-python >=11.6

tests:
  - python:
      imports:
        - numba
        - numba.core.annotations
        - numba.core.datamodel
        - numba.core.rewrites
        - numba.core.runtime
        - numba.core.typeconv
        - numba.core.typing
        - numba.core.unsafe
        - numba.cuda
        - numba.cuda.cudadrv
        - numba.cuda.kernels
        - numba.cuda.simulator
        - numba.cuda.simulator.cudadrv
        - numba.cuda.tests
        - numba.cuda.tests.cudadrv
        - numba.cuda.tests.cudapy
        - numba.cuda.tests.cudasim
        - numba.cuda.tests.nocuda
        - numba.experimental.jitclass
        - numba.np.ufunc
        - numba.scripts
        - numba.testing
        - numba.tests
        - numba.tests.npyufunc
      pip_check: true

  - script:
      - numba -h
      - numba -s

  - script:
      content:
        - ${{ "bash run_test.sh" if unix else "cmd /c run_test.bat" }}
      env:
        FAST_TESTS: ${{ "0" if build_number == 0 else fast_tests }}
        build_platform: ${{ build_platform }}
        target_platform: ${{ target_platform }}
    files:
      recipe:
        # On non-unix, rattler-build (Issue 2657 upstream), fails to clean large testsuite
        # Use multiple CI rerun or FAST_TEST: 1
        - run_test.${{ "sh" if unix else "bat" }}
    requirements:
      run:
        - pip
        - jinja2
        - cffi
        - scipy
        - if: linux and x86_64
          then: numpy !=1.26.0
        - ipython
        - setuptools
        - tbb
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}

  - script:
      - numba -h

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: NumPy aware dynamic Python compiler using LLVM
  description: |
    Numba is an Open Source NumPy-aware optimizing compiler for Python
    sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler
    infrastructure to compile Python syntax to machine code."
  homepage: http://numba.pydata.org
  repository: https://github.com/numba/numba
  documentation: http://numba.pydata.org/

extra:
  recipe-maintainers:
    - souravsingh
    - marcelotrevisani
    - henryiii
    - mbargull
    - jakirkham
    - step21
    - esc
    - MementoRC
    
