# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: httpx-ws
  version: "0.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/httpx_ws-${{ version }}.tar.gz
  sha256: 797373326f70eec1ae96f6e43ae9f12002fd7d73aee139a4985eaab964338a08

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - hatchling
    - hatch-regex-commit
    - pip
  run:
    - python >=${{ python_min }}
    - anyio >=4
    - httpx >=0.23.1
    - httpcore >=1.0.4
    - wsproto

tests:
  - python:
      imports:
        - httpx_ws
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: MIT
  license_file: LICENSE
  summary: WebSocket support for HTTPX
  homepage: https://github.com/frankie567/httpx-ws
  repository: https://github.com/frankie567/httpx-ws
  documentation: https://frankie567.github.io/httpx-ws

extra:
  recipe-maintainers:
    - davidbrochart
    - frankie567
