# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: guidance
  version: "0.2.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/guidance-${{ version }}.tar.gz
  sha256: df95538387b1ea5a011b87e3965042a6a4ad83651a3f2a8a6f22e97b036da680

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - pybind11 >=2.10.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - numpy
    - pydantic
    - requests
    - psutil
    - guidance-stitch ==0.1.5
    - llguidance ==1.1.0

tests:
  - python:
      imports:
        - guidance
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/microsoft/guidance
  summary: 'A guidance language for controlling large language models'
  description: |
    Guidance enables you to control modern language models more effectively and efficiently
    than traditional prompting or chaining. Guidance programs allow you to interleave generation,
    prompting, and logical control into a single continuous flow matching how the language model
    actually processes the text. Simple output structures like Chain of Thought and its many
    variants (e.g., ART, Auto-CoT, etc.) have been shown to improve LLM performance.
    The advent of more powerful LLMs like GPT-4 allows for even richer structure, and guidance
    makes that structure easier and cheaper.
  license: MIT
  license_file: LICENSE.md
  repository: https://github.com/microsoft/guidance

extra:
  recipe-maintainers:
    - johnhany97
    - rxm7706
