# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: guidance
  version: "0.2.5"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/guidance-${{ version }}.tar.gz
  sha256: df95538387b1ea5a011b87e3965042a6a4ad83651a3f2a8a6f22e97b036da680

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - pybind11 >=2.10.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - numpy
    - pydantic
    - requests
    - psutil
    - guidance-stitch ==0.1.5
    - llguidance ==1.1.0

tests:
  - python:
      imports:
        - guidance
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A guidance language for controlling large language models.
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/guidance-ai/guidance

extra:
  recipe-maintainers:
    - rxm7706
