schema_version: 1

context:
  name: robotcode-jsonrpc2
  version: 1.9.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robotcode_jsonrpc2-${{ version }}.tar.gz
  sha256: 8f6ab79967e7ea3c6d91b5957248f35dc78a633103fa0bc5a15b1d84bb065992

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - robotcode-core ==1.9.0

tests:
  - python:
      imports:
        - robotcode_jsonrpc2
      pip_check: true

about:
  summary: JSONRPC Server for RobotCode
  license: Apache-2.0
  license_file: LICENSE.txt
  repository: https://github.com/robotcodedev/robotcode

extra:
  recipe-maintainers:
    - rxm7706
