{% set name = "django-compressor" %}
{% set version = "4.5.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/django-compressor/django-compressor/archive/{{ version }}.tar.gz
  sha256: 929ae0dee4801d257fc2b299ac5ece7edd6e7becd1cfbe10b816efe24f936968

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0.3,<81.0.0
  run:
    - python >={{ python_min }},<4.0
    - django >=4.2
    - django-appconf >=1.0.3
    - rcssmin ==1.1.2
    - rjsmin ==1.2.2

test:
  imports:
    - compressor
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(DEBUG=True, STATIC_URL='/',STATIC_ROOT='',MEDIA_ROOT='media',MEDIA_URL='/media/',COMPRESS_PRECOMPILERS = (('text/x-scss', 'django_libsass.SassCompiler'),),INSTALLED_APPS=['compressor', 'django.contrib.contenttypes', 'django.contrib.auth']); django.setup(); import compressor"
    # Not Working - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-compressor/django-compressor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Compresses linked and inline javascript or CSS into a single cached file.'
  description: Django Compressor processes, combines and minifies linked and inline Javascript or CSS in a Django template into cacheable static files. It supports compilers such as coffeescript, LESS and SASS and is extensible by custom processing steps. Django Compressor is compatible with Django 1.8 and newer.
  doc_url: https://django-compressor.readthedocs.io/en/latest/
  dev_url: https://github.com/django-compressor/django-compressor

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
