# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ibm-platform-services
  version: "0.77.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: fc7848310160d55ca55b4386a095db70f8badcc88890f3c1bbba0e41d4f000b2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools >=67.7.2
  run:
    - python >=${{ python_min }}
    - ibm-cloud-sdk-core >=3.24.4,<4.0.0

tests:
  - python:
      imports:
        - ibm_platform_services
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Python client library for IBM Cloud Platform Services
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/IBM/platform-services-python-sdk

extra:
  recipe-maintainers:
    - wshanks
