{% set name = "ark-sdk-builder" %}
{% set version = "0.1.43" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mckinsey/agents-at-scale-ark/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3a06157d62b413adb1a71c4da1973ca5f0925aac0d7b9d6f9e8a940b79b1d906

build:
  number: 0
  noarch: python
  script: cd lib/ark-sdk && {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - build
    - pytest
    - pyyaml
    - python-kubernetes >=32.0.0
    - pydantic >=2

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mckinsey/agents-at-scale-ark
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ARK SDK builder toolkit for Kubernetes-based AI agent runtime
  description: |
    ARK (Agentic Runtime for Kubernetes) SDK builder provides tools and utilities
    for building and managing AI agents on Kubernetes. This package includes the
    builder toolkit that codifies patterns and practices developed across dozens
    of agentic application projects.

    The ARK SDK builder provides:
    - Testing infrastructure for agent development
    - YAML processing for Kubernetes resources
    - Kubernetes API integration
    - Data validation through Pydantic
    - Build automation tools

    ARK provides abstraction layers for agent operations with built-in Custom
    Resource Definitions (CRDs) for agents, models, memory, tools, and evaluation.
  doc_url: https://mckinsey.github.io/agents-at-scale-ark
  dev_url: https://github.com/mckinsey/agents-at-scale-ark

extra:
  recipe-maintainers:
    - rxm7706
