# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: groovy
  version: "0.1.2"

package:
  # Add -python suffix to not collide with the (more) popular programming language.
  name: ${{ name|lower }}-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/groovy-${{ version }}.tar.gz
  sha256: 25c1dc09b3f9d7e292458aa762c6beb96ea037071bf5e917fc81fb78d2231083

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - groovy
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A small Python library created to help developers protect their applications from Server Side Request Forgery (SSRF) attacks.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/gradio-app/groovy
  repository: https://github.com/gradio-app/groovy

extra:
  feedstock-name: groovy-python
  recipe-maintainers:
    - xhochy
