# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: pymongoarrow
  version: "1.11.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymongoarrow-${{ version }}.tar.gz
  sha256: 42c45f9f47ca7a2cc9e858dc39a9dae06d562b731f5678577c5fe0de36e485ba

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=70,<72.2
    - cython >=3.0
    - numpy >=2.0
    - pyarrow >=22.0,<22.1.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - pyarrow >=22.0,<22.1
    - pymongo >=4.4,<5
    - numpy >=2.0.1
    - packaging >=23.2

tests:
  - python:
      imports:
        - benchmarks
        - pymongoarrow
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Tools for using NumPy, Pandas, Polars, and PyArrow with MongoDB
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/mongodb-labs/mongo-arrow/tree/main/bindings/python
  homepage: https://github.com/mongodb-labs/mongo-arrow

extra:
  recipe-maintainers:
    - rxm7706
