# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: jurigged
  version: "0.6.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jurigged-${{ version }}.tar.gz
  sha256: 840a53bee6963a85d0a4ea5055472526c6b1114ed78ef5a91bde146e9280b04b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - jurigged = jurigged.live:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - blessed >=1.20.0
    - codefind >=0.1.7,<0.2.dev0
    - ovld >=0.4.0
    - watchdog >=4.0.2

tests:
  - python:
      imports:
        - jurigged
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - jurigged --help

about:
  summary: Live update of Python functions
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/breuleux/jurigged

extra:
  recipe-maintainers:
    - rxm7706
