{% set name = "opentelemetry-semantic-conventions" %}
{% set version = "0.61b0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_semantic_conventions-{{ version }}.tar.gz
  sha256: 072f65473c5d7c6dc0355b27d6c9d1a679d63b6d4b4b16a9773062cb7e31192a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:

    - python >={{ python_min }}
    - opentelemetry-api ==1.40.0
    - typing-extensions >=4.5.0

test:
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  summary: OpenTelemetry Semantic Conventions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api

