# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: wagtail-ai
  version: "3.0.0"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/wagtail_ai-${{ version }}.tar.gz
  sha256: 4e1dd7c8dc6dc7a2a0a2a26a13536a61834cbcce9723500996287409b4176937

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - wagtail >=7.1
    - django-ai-core
    - llm >=0.12

tests:
  - python:
      imports:
        - wagtail_ai
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Get a hand writing your content with AI super powers!
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/wagtail/wagtail-ai

extra:
  recipe-maintainers:
    - rxm7706
