# =============================================================================
# Apache Tika 3.2.3 All-In-One Conda-Forge Recipe
# =============================================================================
# This single meta.yaml builds ALL 66+ packages as outputs in one conda-build.
# Similar pattern to: https://github.com/conda-forge/airflow-feedstock
# All SHA256 checksums VERIFIED from Maven Central on 2024-12-07
# Dependency versions from tika-parent-3.2.3.pom
#
# Usage:
#   conda-build . --channel conda-forge
#
# Maintainer: rxm7706
# =============================================================================

{% set tika_version = "3.2.3" %}

package:
  name: apache-tika-all
  version: {{ tika_version }}

source:
  # =========================================================================
  # TIER 1: Zero Dependencies (41 JARs)
  # =========================================================================
  - url: https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.17/slf4j-api-2.0.17.jar
    sha256: 7b751d952061954d5abfed7181c1f645d336091b679891591d63329c622eb832
    folder: slf4j-api

  - url: https://repo1.maven.org/maven2/commons-io/commons-io/2.20.0/commons-io-2.20.0.jar
    sha256: df90bba0fe3cb586b7f164e78fe8f8f4da3f2dd5c27fa645f888100ccc25dd72
    folder: commons-io

  - url: https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0.jar
    sha256: 4eeeae8d20c078abb64b015ec158add383ac581571cddc45c68f0c9ae0230720
    folder: commons-lang3

  - url: https://repo1.maven.org/maven2/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0.jar
    sha256: 5c3881e4f556855e9c532927ee0c9dfde94cc66760d5805c031a59887070af5f
    folder: commons-codec

  - url: https://repo1.maven.org/maven2/org/apache/commons/commons-collections4/4.5.0/commons-collections4-4.5.0.jar
    sha256: 00f93263c267be201b8ae521b44a7137271b16688435340bf629db1bac0a5845
    folder: commons-collections4

  - url: https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0.jar
    sha256: e1522945218456f3649a39bc4afd70ce4bd466221519dba7d378f2141a4642ca
    folder: commons-compress

  - url: https://repo1.maven.org/maven2/commons-logging/commons-logging/1.3.5/commons-logging-1.3.5.jar
    sha256: 6d7a744e4027649fbb50895df9497d109f98c766a637062fe8d2eabbb3140ba4
    folder: commons-logging

  - url: https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar
    sha256: 1e56d7b058d28b65abd256b8458e3885b674c1d588fa43cd7d1cbb9c7ef2b308
    folder: commons-math3

  - url: https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.14.1/commons-csv-1.14.1.jar
    sha256: 32be0e1e76673092f5d12cb790bd2acb6c2ab04c4ea6efc69ea5ee17911c24fe
    folder: commons-csv

  - url: https://repo1.maven.org/maven2/commons-cli/commons-cli/1.10.0/commons-cli-1.10.0.jar
    sha256: 1b273d92160b9fa69c3e65389a5c4decd2f38a697e458e6f75080ae09e886404
    folder: commons-cli

  - url: https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.5.0/commons-exec-1.5.0.jar
    sha256: d52d35801747902527826cca30734034e65baa7f36836cc0facf67131025f703
    folder: commons-exec

  - url: https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar
    sha256: 8a8f81cf9b359e3f6dfa691a1e776985c061ef2f223c9b2c80753e1b458e8064
    folder: failureaccess

  - url: https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
    sha256: b372a037d4230aa57fbeffdef30fd6123f9c0c2db85d0aced00c91b974f33f99
    folder: listenablefuture

  - url: https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.36.0/error_prone_annotations-2.36.0.jar
    sha256: 77440e270b0bc9a249903c5a076c36a722c4886ca4f42675f2903a1c53ed61a5
    folder: error-prone-annotations

  - url: https://repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/3.0.0/j2objc-annotations-3.0.0.jar
    sha256: 88241573467ddca44ffd4d74aa04c2bbfd11bf7c17e0c342c94c9de7a70a7c64
    folder: j2objc-annotations

  - url: https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.43.0/checker-qual-3.43.0.jar
    sha256: 3fbc2e98f05854c3df16df9abaa955b91b15b3ecac33623208ed6424640ef0f6
    folder: checker-qual

  - url: https://repo1.maven.org/maven2/jakarta/activation/jakarta.activation-api/2.1.3/jakarta.activation-api-2.1.3.jar
    sha256: 01b176d718a169263e78290691fc479977186bcc6b333487325084d6586f4627
    folder: jakarta-activation-api

  - url: https://repo1.maven.org/maven2/com/sun/istack/istack-commons-runtime/4.2.0/istack-commons-runtime-4.2.0.jar
    sha256: 21025b7a096ef93f74de659c1be5990fa0c24e59a0f98a706e392e7088725ff6
    folder: istack-commons-runtime

  - url: https://repo1.maven.org/maven2/org/glassfish/jaxb/txw2/4.0.5/txw2-4.0.5.jar
    sha256: 917355bc451481f30d043b24d123110517966af34383901773882810dca480e5
    folder: txw2

  - url: https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.24.3/log4j-api-2.24.3.jar
    sha256: 5b4a0a0cd0e751ded431c162442bdbdd53328d1f8bb2bae5fc1bbeee0f66d80f
    folder: log4j-api

  - url: https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox-io/3.0.5/pdfbox-io-3.0.5.jar
    sha256: 6df3f3b4db4fd55ef502847ea4e4ebc58e28908800e86eab031345efe219b705
    folder: pdfbox-io

  - url: https://repo1.maven.org/maven2/org/apache/pdfbox/jempbox/1.8.17/jempbox-1.8.17.jar
    sha256: ded9c81038dd1bbcba18f07e1028d70c9ceaf0b48ac56cea8ab6ec2c255fc1b3
    folder: jempbox

  - url: https://repo1.maven.org/maven2/com/github/jai-imageio/jai-imageio-core/1.4.0/jai-imageio-core-1.4.0.jar
    sha256: 8ad3c68e9efffb10ac87ff8bc589adf64b04a729c5194c079efd0643607fd72a
    folder: jai-imageio-core

  - url: https://repo1.maven.org/maven2/com/adobe/xmp/xmpcore/6.1.11/xmpcore-6.1.11.jar
    sha256: 8f7033c579b99fa0d9d6ddcb9448875b5e4b577c350002278ce46997d678b737
    folder: xmpcore

  - url: https://repo1.maven.org/maven2/com/github/virtuald/curvesapi/1.08/curvesapi-1.08.jar
    sha256: ad95b08b8bbf9d7d17e5e00814898fa23324f32bc5b62f1a37801e6a56ce0079
    folder: curvesapi

  - url: https://repo1.maven.org/maven2/com/zaxxer/SparseBitSet/1.3/SparseBitSet-1.3.jar
    sha256: f76b85adb0c00721ae267b7cfde4da7f71d3121cc2160c9fc00c0c89f8c53c8a
    folder: sparsebitset

  - url: https://repo1.maven.org/maven2/org/jsoup/jsoup/1.21.2/jsoup-1.21.2.jar
    sha256: f05496e255734759f0d4b5632da7b24f81313147c78c69e90ad045d096191344
    folder: jsoup

  - url: https://repo1.maven.org/maven2/com/github/albfernandez/juniversalchardet/2.5.0/juniversalchardet-2.5.0.jar
    sha256: ceb271653ed99e15ffe52e4aedecdef8918434f19a4378a67f7ebe0ea8439058
    folder: juniversalchardet

  - url: https://repo1.maven.org/maven2/com/drewnoakes/metadata-extractor/2.19.0/metadata-extractor-2.19.0.jar
    sha256: e51bb454ed08ea2bfcc3ad147d088ad1aa73a999e0072563f8ae50021a2fcadb
    folder: metadata-extractor

  - url: https://repo1.maven.org/maven2/com/optimaize/languagedetector/language-detector/0.6/language-detector-0.6.jar
    sha256: f53ecc3d71da9ebc82edd10fb35638d32e8b9d849273dd717a021eca02f2278d
    folder: language-detector

  - url: https://repo1.maven.org/maven2/org/tallison/jmatio/1.5/jmatio-1.5.jar
    sha256: 70db8cf9a1818072f290fd464f14a8369c9c58993e6640128a6e8a6379d67ac7
    folder: jmatio

  - url: https://repo1.maven.org/maven2/com/googlecode/plist/dd-plist/1.28/dd-plist-1.28.jar
    sha256: 88ed8e730f7386297485176c4387146c6914a38c0e58fc296e8a01cdc3b621e1
    folder: dd-plist

  - url: https://repo1.maven.org/maven2/info/picocli/picocli/4.7.6/picocli-4.7.6.jar
    sha256: ed441183f309b93f104ca9e071e314a4062a893184e18a3c7ad72ec9cba12ba0
    folder: picocli

  - url: https://repo1.maven.org/maven2/com/pff/java-libpst/0.9.3/java-libpst-0.9.3.jar
    sha256: 039cd61635ded94dba67f909d3b1763e13f9c23d02f9750eb6259af10e1dabdb
    folder: java-libpst

  - url: https://repo1.maven.org/maven2/org/apache/james/apache-mime4j-core/0.8.12/apache-mime4j-core-0.8.12.jar
    sha256: b2180c13b97ade21edb5f52581ade0a6f82b5084bb9ca5bdf83584deb6225a69
    folder: apache-mime4j-core

  - url: https://repo1.maven.org/maven2/org/gagravarr/vorbis-java-core/0.8/vorbis-java-core-0.8.jar
    sha256: 879bb0c8923fea686609e207fd9050ab246e001868341c725929405e755cf68e
    folder: vorbis-java-core

  - url: https://repo1.maven.org/maven2/org/brotli/dec/0.1.2/dec-0.1.2.jar
    sha256: 615c0c3efef990d77831104475fba6a1f7971388691d4bad1471ad84101f6d52
    folder: dec

  - url: https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.81/bcprov-jdk18on-1.81.jar
    sha256: 249f396412b0c0ce67f25c8197da757b241b8be3ec4199386c00704a2457459b
    folder: bcprov-jdk18on

  - url: https://repo1.maven.org/maven2/org/ow2/asm/asm/9.8/asm-9.8.jar
    sha256: 876eab6a83daecad5ca67eb9fcabb063c97b5aeb8cf1fca7a989ecde17522051
    folder: asm

  - url: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.20.0/jackson-core-2.20.0.jar
    sha256: bc0cf46075877201f8406ee7de2741ae7df6c066f5f0457bd80632a718c06e72
    folder: jackson-core

  - url: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.20/jackson-annotations-2.20.jar
    sha256: 959a2ffb2d591436f51f183c6a521fc89347912f711bf0cae008cdf045d95319
    folder: jackson-annotations

  # =========================================================================
  # TIER 2: Simple Dependencies (12 JARs)
  # =========================================================================
  - url: https://repo1.maven.org/maven2/com/google/guava/guava/33.4.8-jre/guava-33.4.8-jre.jar
    sha256: f3d7f57f67fd622f4d468dfdd692b3a5e3909246c28017ac3263405f0fe617ed
    folder: guava

  - url: https://repo1.maven.org/maven2/org/eclipse/angus/angus-activation/2.0.2/angus-activation-2.0.2.jar
    sha256: 6dd3bcffc22bce83b07376a0e2e094e4964a3195d4118fb43e380ef35436cc1e
    folder: angus-activation

  - url: https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/4.0.2/jakarta.xml.bind-api-4.0.2.jar
    sha256: 0d6bcfe47763e85047acf7c398336dc84ff85ebcad0a7cb6f3b9d3e981245406
    folder: jakarta-xml-bind-api

  - url: https://repo1.maven.org/maven2/org/apache/pdfbox/fontbox/3.0.5/fontbox-3.0.5.jar
    sha256: e8a62be2df27a0d44191b6669c0b18df6efe5271232db8dcb8745d5d9774755b
    folder: fontbox

  - url: https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/2.0.17/jcl-over-slf4j-2.0.17.jar
    sha256: affd06771589ebfe454bb11315a4f466ecaa135b95f3e7939534cf1d2fd7064c
    folder: jcl-over-slf4j

  - url: https://repo1.maven.org/maven2/com/rometools/rome-utils/2.1.0/rome-utils-2.1.0.jar
    sha256: 6e1c3b022dff4cf7492acddbba22356f424ade3d869a42a2a4d74a28454334a4
    folder: rome-utils

  - url: https://repo1.maven.org/maven2/org/apache/james/apache-mime4j-dom/0.8.12/apache-mime4j-dom-0.8.12.jar
    sha256: d8de21f9091a0109bdfe68d323f2a5ffb326922f8493f88b1203a04a69198940
    folder: apache-mime4j-dom

  - url: https://repo1.maven.org/maven2/org/gagravarr/vorbis-java-tika/0.8/vorbis-java-tika-0.8.jar
    sha256: a1b62281a99aec10dc69db1d2f8250952dca5841eedf1167b6b6f9585e2d0d26
    folder: vorbis-java-tika

  - url: https://repo1.maven.org/maven2/org/apache/pdfbox/jbig2-imageio/3.0.4/jbig2-imageio-3.0.4.jar
    sha256: 29cb2951622f10acf61fd0656c4e6fa5562194a9095f7a1d26aa426e2f6b17eb
    folder: jbig2-imageio

  - url: https://repo1.maven.org/maven2/org/netpreserve/jwarc/0.32.0/jwarc-0.32.0.jar
    sha256: 5750789c900dee69744f0d5d72204e4e6414e1d9c36a22f19c7652a550d8c237
    folder: jwarc

  - url: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.20.0/jackson-databind-2.20.0.jar
    sha256: a70e146a6bf2cba4f9cd367169787f50adcfbb57122bc2e9c8390cd0b397ac30
    folder: jackson-databind

  - url: https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.24.3/log4j-core-2.24.3.jar
    sha256: 7eb4084596ae25bd3c61698e48e8d0ab65a9260758884ed5cbb9c6e55c44a56a
    folder: log4j-core

  # =========================================================================
  # TIER 3: Medium Dependencies (5 JARs)
  # =========================================================================
  - url: https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-core/4.0.5/jaxb-core-4.0.5.jar
    sha256: ad3fd9bf00de3eda9859f70b6cfb011e2fe9904804e16a2665092888ece0fdca
    folder: jaxb-core

  - url: https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox/3.0.5/pdfbox-3.0.5.jar
    sha256: f0e5d3a1e573c707e4fbcc2ee8e42ea8ca1d5261bdcb3a05a08d2118553c1e5a
    folder: pdfbox

  - url: https://repo1.maven.org/maven2/com/rometools/rome/2.1.0/rome-2.1.0.jar
    sha256: d4e0bb6857a25ee15e2082be6e83e1da897cfbabb025bfe01ae00346d7db7c78
    folder: rome

  - url: https://repo1.maven.org/maven2/com/healthmarketscience/jackcess/jackcess/4.0.8/jackcess-4.0.8.jar
    sha256: bb84e5c7367dedf3a5cea7ad2d37e6874bb688f9003edb92749ef032be25671e
    folder: jackcess

  - url: https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-slf4j2-impl/2.24.3/log4j-slf4j2-impl-2.24.3.jar
    sha256: cdaac22e40ec30c4096e1ebe8c454c8826c0d1c378d7db5d7b3ad166354b0bd3
    folder: log4j-slf4j2-impl

  # =========================================================================
  # TIER 4: Complex Dependencies (5 JARs)
  # =========================================================================
  - url: https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/4.0.5/jaxb-runtime-4.0.5.jar
    sha256: 485d8940e76373a7f300815ea5504bf5b726c234425ad30971019d133124cca4
    folder: jaxb-runtime

  - url: https://repo1.maven.org/maven2/org/apache/xmlbeans/xmlbeans/5.2.2/xmlbeans-5.2.2.jar
    sha256: 0fb2fa9e43800f0411c1363c606cc1355e7e3592d97400b4f6e80db53d2e66a4
    folder: xmlbeans

  - url: https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox-tools/3.0.5/pdfbox-tools-3.0.5.jar
    sha256: 234a81bb54196d83b34f67b48e60cd65586db79306fdeec53a1c045cb0910984
    folder: pdfbox-tools

  - url: https://repo1.maven.org/maven2/org/apache/pdfbox/xmpbox/3.0.5/xmpbox-3.0.5.jar
    sha256: 017899b2fb5c2af714d30c52cca92cde8f12999abf3140d4f0d5f11334f62fdd
    folder: xmpbox

  - url: https://repo1.maven.org/maven2/com/healthmarketscience/jackcess/jackcess-encrypt/4.0.3/jackcess-encrypt-4.0.3.jar
    sha256: d40a7871ac1dc6343cd2e433c3ee484eb59cdff728b7a1e22dcfc8b3f400a18a
    folder: jackcess-encrypt

  # =========================================================================
  # TIER 5: Apache Tika 3.2.3 (3 JARs)
  # =========================================================================
  - url: https://repo1.maven.org/maven2/org/apache/tika/tika-core/{{ tika_version }}/tika-core-{{ tika_version }}.jar
    sha256: 4b697ae09a76b50102750816e9bd3ad26d89161ba65ddabdeee7ef3830428fd1
    folder: tika-core

  - url: https://repo1.maven.org/maven2/org/apache/tika/tika-app/{{ tika_version }}/tika-app-{{ tika_version }}.jar
    sha256: 80c20c085e2c0976bbd55969e5bf90dda2b7155db31068639fbc871d0369e7e7
    folder: tika-app

  - url: https://repo1.maven.org/maven2/org/apache/tika/tika-parsers-standard-package/{{ tika_version }}/tika-parsers-standard-package-{{ tika_version }}.jar
    sha256: 6c780c1bd3ef42d7df386a2587a71c7f92e8cc84c3f18d3548b049352dd04851
    folder: tika-parsers

build:
  number: 0

outputs:
  - name: apache-tika-app
    version: {{ tika_version }}
    build:
      noarch: generic
      script:
        - mkdir -p ${PREFIX}/share/java/apache-tika  # [unix]
        - mkdir -p ${PREFIX}/bin  # [unix]
        - cp ${SRC_DIR}/tika-app/tika-app-{{ tika_version }}.jar ${PREFIX}/share/java/apache-tika/  # [unix]
        - sed "s/@VERSION@/{{ tika_version }}/g" ${RECIPE_DIR}/tika.sh > ${PREFIX}/bin/tika  # [unix]
        - chmod +x ${PREFIX}/bin/tika  # [unix]
    requirements:
      run:
        - openjdk >=17
    test:
      commands:
        - test -f ${PREFIX}/share/java/apache-tika/tika-app-{{ tika_version }}.jar  # [unix]
        - test -f ${PREFIX}/bin/tika  # [unix]
        - tika --help  # [unix]
    about:
      home: https://tika.apache.org/
      license: Apache-2.0
      license_family: Apache
      summary: Apache Tika Application uber-jar with CLI- - complete bundled toolkit

  - name: apache-tika
    version: {{ tika_version }}
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('apache-tika-app', exact=True) }}
    test:
      commands:
        - tika --help  # [unix]
    about:
      home: https://tika.apache.org/
      license: Apache-2.0
      license_family: Apache
      summary: Apache Tika (metapackage)

# =============================================================================
# ABOUT SECTION
# =============================================================================
about:
  home: https://tika.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Tika 3.2.3 - Content detection and analysis toolkit with all Java dependencies - builds 66+ packages in one recipe
  description: |
    Apache Tika 3.2.3 - The Apache Tika toolkit detects and extracts 
    metadata and text from over a thousand different file types.
    
    Dependency versions from tika-parent-3.2.3.pom.
    All SHA256 checksums verified from Maven Central.
    This mega-recipe builds Apache Tika and all 60+ Java dependencies
    in a single conda-build command. Pattern based on airflow-feedstock.

    Outputs include:
    - 42 Tier 1 packages (zero dependencies)
    - 14 Tier 2 packages (simple dependencies)
    - 5 Tier 3 packages (medium dependencies)
    - 5 Tier 4 packages (complex dependencies)
    - 4 Apache Tika packages (core, parsers, app, metapackage)
  dev_url: https://github.com/apache/tika
  doc_url: https://tika.apache.org/documentation.html

extra:
  feedstock-name: apache-tika-all
  recipe-maintainers:
    - rxm7706
