schema_version: 1

context:
  name: jupyter-server-ydoc
  version: 2.1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jupyter_server_ydoc-${{ version }}.tar.gz
  sha256: 2b0995cdc1d1ff9f46a38b00352c29c29d7b3c703038163a73e9cf0a72f9077b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling >=1.4.0
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.15.0,<3.0.0
    - jupyter_ydoc >=3.0.3,<4.0.0
    - pycrdt
    - pycrdt-websocket >=0.16.0,<0.17.0
    - jupyter_events >=0.11.0
    - jupyter_server_fileid >=0.7.0,<1
    - jsonschema >=4.18.0

tests:
  - python:
      imports:
        - jupyter_server_ydoc
      pip_check: true

about:
  summary: jupyter-server extension integrating collaborative shared models.
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/jupyterlab/jupyter-collaboration/tree/main/projects/jupyter-server-ydoc

extra:
  recipe-maintainers:
    - rxm7706
