"""Story 24.1 / spec-pyforge-scribe CAP-32 -- the derived BMAD-estate catalog.

Fixture-driven and offline: a miniature repo tree under ``tmp_path`` carries
every source the generator reads, so the tests prove the readers, the
disagreement rendering, the structured digests and the CLI exit codes
without touching the live tree or the network.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest
from typer.testing import CliRunner

from pyforge.scribe import catalog
from pyforge.scribe.cli import app

runner = CliRunner()

_MANIFEST = """installation:
  version: 6.12.0
  installDate: 2026-04-30T17:24:22.503Z
  lastUpdated: 2026-09-07T01:39:38.942Z
  installShims: false
modules:
  - name: core
    version: 6.12.0
    source: built-in
  - name: skf
    version: main
    source: custom
    repoUrl: https://example.invalid/skf
ides:
  - claude-code
"""

_SKF_MANIFEST = """# SKF Installation Manifest - Generated by installer
version: 2.1.0
installed_at: '2026-09-07T01:39:39.614Z'
ides:
  - other
"""

_HELP_CSV = """module,skill,display-name,menu-code,description,action,args,phase,preceded-by,followed-by,required,output-location,outputs
BMad Method,_meta,,,,,,,,,false,https://docs.bmad-method.org/,
BMad Method,bmad-spec,Spec,SPC,"Condense any input into a spec.",,[path],anytime,,,false,{output_folder}/specs,SPEC.md
Core,bmad-help,Help,H,"Answer BMad questions.",,,anytime,,,false,,
"""

_MEMBERS = """# Canonical bmad-suite population
members:
  # --- Active ---
  - name: bmad-method
    description: '"Build More Architect Dreams" - Agile Ai Driven Development.'
    urls:
      - https://github.com/bmad-code-org/BMAD-METHOD
  - name: bmad-method-test-architecture-enterprise
    description: TEA (Murat).
    urls:
      - https://example.invalid/tea
    notes: tag-sourced
  - name: bmad-method-wds-expansion
    deprecated: true
    notes: upstream deprecated
"""

_REGISTER = """# Adoption register

## 1. Members

| # | Member (version) | Install class | Wired 2026-09-06 | Verdict | Wielder | Provisioning path | Hazards | Status / story |
|---|---|---|---|---|---|---|---|---|
| 1 | `bmad-method` 6.12.0 | installer-tree | present | wield (substrate) | all stations | steward Epic 14 | installed-stage caveat | 30.1 |
| 6 | `bmad-method-test-architecture-enterprise` 1.24.0 | module | unwired | wield — full adoption | marshal, warden | `steward provision --module tea` | none | 46.3 |

## 2. Skill routing (CAP-3) — one wielding station per adopted skill

| Skill | Source member | Wielding station | Where the routing note lives | Story |
|---|---|---|---|---|
| `bmad-os-changelog` | utility-skills | herald | `bmad-agent-herald` | herald 18.2 |

## 3. Posture changes
"""

_CADENCE = """# Release cadence

## Trigger

## Steps (owner → verb → gate)

1. **Doctor — detect.** `bmad-method-version-drift-check`.

   **Verified pass (6.12.0, 2026-09-06):** owner **doctor** | exit **0**.

2. **Steward — catalog.** Author the release catalog.
"""

_HARNESS = '''"""marshal harness."""

HARNESS_VERSION_RANGE_TEXT = ">=0.11.0,<0.13"
'''

_PIXI = """[workspace]
name = "fixture"

[dependencies]
bmad-method = ">=6.12.0"

[feature.guild.dependencies]
bmad-method-test-architecture-enterprise = ">=1.26.0"
bmad-loop = { version = ">=0.12.0", channel = "conda-forge" }

[feature.guild.tasks.bmad-drift-check]
cmd = "python -m pyforge.doctor.sources bmad-drift"

[environments]
bmad-ui = { features = ["bmad-ui"], no-default-feature = true }
"""


def _skill(root: Path, name: str, description: str, *, nested: bool = False) -> None:
    if nested:
        target = root / catalog.SKILLS_RELPATH / name / "active" / name
    else:
        target = root / catalog.SKILLS_RELPATH / name
    target.mkdir(parents=True)
    (target / "SKILL.md").write_text(
        f"---\nname: {name}\ndescription: {description}\n---\n\n# {name}\n", encoding="utf-8"
    )


@pytest.fixture
def estate_root(tmp_path: Path) -> Path:
    root = tmp_path / "repo"
    for rel, text in (
        (catalog.MANIFEST_RELPATH, _MANIFEST),
        (catalog.SKF_MANIFEST_RELPATH, _SKF_MANIFEST),
        (catalog.HELP_CSV_RELPATH, _HELP_CSV),
        (catalog.SUITE_MEMBERS_RELPATH, _MEMBERS),
        (catalog.REGISTER_RELPATH, _REGISTER),
        (catalog.CADENCE_RELPATH, _CADENCE),
        (catalog.HARNESS_RELPATH, _HARNESS),
        (catalog.PIXI_RELPATH, _PIXI),
    ):
        path = root / rel
        path.mkdir(parents=True, exist_ok=True)
        path.rmdir()
        path.write_text(text, encoding="utf-8")
    _skill(root, "bmad-spec", '"Condense any input into a spec."')
    _skill(root, "bmad-help", "Answer BMad questions.")
    _skill(root, "bmad-agent-dev", "Amelia, the developer.")
    _skill(root, "bmad-agent-builder", "Builds agents (a BMB skill).")
    _skill(root, "bmad-os-changelog", "Draft the changelog.")
    _skill(root, "bmad-testarch-ci", "Scaffold a CI pipeline.")
    _skill(root, "skf-forger", "Forge a skill.")
    _skill(root, "mcp-builder", "Build an MCP server.")
    _skill(root, "conda-forge-expert", "|\n  Autonomous conda-forge packaging agent.\n  Second line.")
    _skill(root, "pyforge-steward", "Steward station skill.", nested=True)
    (root / catalog.SKILLS_RELPATH / "shared").mkdir()
    recipe = root / catalog.RECIPES_RELPATH / "bmad-method" / "recipe.yaml"
    recipe.parent.mkdir(parents=True)
    recipe.write_text('context:\n  name: bmad-method\n  version: "6.12.0"\n', encoding="utf-8")
    return root


def test_derive_reads_every_source(estate_root: Path) -> None:
    estate = catalog.derive(estate_root)
    assert estate.installed["core_version"] == "6.12.0"
    assert estate.installed["install_shims"] == "false"
    assert [m["name"] for m in estate.installed["modules"]] == ["core", "skf"]  # type: ignore[index]
    assert estate.installed["skf_version"] == "2.1.0"
    families = {s.name: s.family for s in estate.skills}
    assert families["bmad-help"] == catalog.FAMILY_CORE
    assert families["bmad-spec"] == catalog.FAMILY_BMM
    assert families["bmad-agent-dev"] == catalog.FAMILY_PERSONAS
    assert families["bmad-agent-builder"] == catalog.FAMILY_BMB
    assert families["bmad-os-changelog"] == catalog.FAMILY_UTILITY
    assert families["bmad-testarch-ci"] == catalog.FAMILY_TEA
    assert families["skf-forger"] == catalog.FAMILY_SKF
    assert families["mcp-builder"] == catalog.FAMILY_LABS
    assert families["conda-forge-expert"] == catalog.FAMILY_OTHER
    assert families["pyforge-steward"] == catalog.FAMILY_STATIONS
    described = {s.name: s.description for s in estate.skills}
    assert described["conda-forge-expert"] == "Autonomous conda-forge packaging agent."
    assert described["bmad-spec"] == "Condense any input into a spec."
    assert estate.skill_dirs_without_skill_md == ["shared"]
    assert [r["skill"] for r in estate.help_rows] == ["bmad-spec", "bmad-help"]
    assert estate.module_docs == {"BMad Method": "https://docs.bmad-method.org/"}
    assert [(m.name, m.deprecated) for m in estate.members] == [
        ("bmad-method", False),
        ("bmad-method-test-architecture-enterprise", False),
        ("bmad-method-wds-expansion", True),
    ]
    assert estate.members[0].description == '"Build More Architect Dreams" - Agile Ai Driven Development.'
    assert estate.members[1].notes == "tag-sourced"
    assert estate.register["bmad-method"].wielder == "all stations"
    assert estate.register["bmad-method-test-architecture-enterprise"].version == "1.24.0"
    assert estate.routing[0].station == "herald"
    assert estate.pins["bmad-loop"] == {"feature.guild.dependencies": ">=0.12.0"}
    assert "bmad-drift-check" not in estate.pins and "bmad-ui" not in estate.pins
    assert estate.recipe_versions == {"bmad-method": "6.12.0"}
    assert estate.harness_range == ">=0.11.0,<0.13"
    assert estate.cadence_steps == ["1. Doctor — detect.", "2. Steward — catalog."]


def test_disagreement_is_rendered_never_resolved(estate_root: Path) -> None:
    estate = catalog.derive(estate_root)
    assert [d.member for d in estate.disagreements] == ["bmad-method-test-architecture-enterprise"]
    versions = estate.disagreements[0].versions
    assert versions[catalog.REGISTER_RELPATH.as_posix()] == "1.24.0"
    assert versions["pixi.toml"] == "1.26.0"
    text = catalog.render(estate, today=date(2026, 9, 29))
    assert "### Sources disagree" in text
    assert "`bmad-method-test-architecture-enterprise` | `_bmad-output/" in text
    assert "→ 1.24.0" in text and "→ 1.26.0" in text
    assert "never this generator's" in text


def test_render_carries_header_sections_and_digests(estate_root: Path) -> None:
    estate = catalog.derive(estate_root)
    text = catalog.render(estate, today=date(2026, 9, 29))
    assert text.startswith("# local-recipes — the BMAD estate, derived")
    assert "Generated: 2026-09-29" in text
    assert catalog.REGENERATE_COMMAND in text
    assert catalog.DETECTOR_NAME in text
    for heading in (
        "## 1. Installed core and modules",
        "## 2. Skills by family",
        "## 3. BMAD phases and sequence",
        "## 4. The bmad-suite roster",
        "## 5. Pins",
        "## 6. Marshal ↔ bmad-loop harness",
        "## 7. The release cadence",
        "## 8. Pipeline truth",
    ):
        assert heading in text, heading
    assert "`6.12.0` — `installShims: false`" in text
    assert f"### {catalog.FAMILY_PERSONAS} (1)" in text
    assert f"### {catalog.FAMILY_BMB} (1)" in text
    assert "| `bmad-method` | 6.12.0 | installer-tree | wield (substrate) | all stations |" in text
    assert "Deprecated catalog rows" in text and "`bmad-method-wds-expansion`" in text
    assert "| `bmad-loop` | `feature.guild.dependencies` | `>=0.12.0` |" in text
    assert "Supported bmad-loop range: `>=0.11.0,<0.13`" in text
    assert "- 1. Doctor — detect." in text
    assert "with no `SKILL.md` (not skills): `shared`" in text
    recorded = catalog.recorded_digests(text)
    assert recorded == catalog.digests(estate)
    assert set(recorded) == set(catalog.SECTION_SOURCES)


def test_write_then_check_is_clean_and_prose_is_exempt(estate_root: Path) -> None:
    target = catalog.write(estate_root)
    assert target == estate_root / catalog.CATALOG_RELPATH
    assert catalog.check(estate_root) == []
    # A prose-only change (the generation date, a reworded sentence) is not drift.
    edited = target.read_text(encoding="utf-8").replace("Generated: ", "Rendered on: ")
    target.write_text(edited, encoding="utf-8")
    assert catalog.check(estate_root) == []


def test_check_names_the_drifted_section_and_its_source(estate_root: Path) -> None:
    catalog.write(estate_root)
    manifest = estate_root / catalog.MANIFEST_RELPATH
    manifest.write_text(
        _MANIFEST.replace("version: 6.12.0\n  installDate", "version: 6.13.0\n  installDate"), encoding="utf-8"
    )
    findings = catalog.check(estate_root)
    assert len(findings) == 1
    assert "section `installed` drifted" in findings[0]
    assert catalog.MANIFEST_RELPATH.as_posix() in findings[0]
    _skill(estate_root, "bmad-walkthrough", "Walk the user through a change.")
    findings = catalog.check(estate_root)
    assert {f.split("`")[1] for f in findings} == {"installed", "skills"}


def test_check_reports_a_missing_catalog_as_drift(estate_root: Path) -> None:
    findings = catalog.check(estate_root)
    assert len(findings) == 1 and "catalog missing" in findings[0]


def test_missing_source_raises_never_false_green(estate_root: Path) -> None:
    (estate_root / catalog.SUITE_MEMBERS_RELPATH).unlink()
    with pytest.raises(catalog.CatalogSourceError, match="suite-members.yaml"):
        catalog.derive(estate_root)


def test_pipeline_truth_input_adds_stage_columns(estate_root: Path, tmp_path: Path) -> None:
    truth = tmp_path / "truth.json"
    truth.write_text(
        json.dumps(
            {
                "packages": [
                    {
                        "name": "bmad-method",
                        "install_class": "installer-tree",
                        "recipe": {"value": "6.12.0", "ok": True, "detail": ""},
                        "channel": {"value": "6.12.0", "ok": True, "detail": ""},
                        "installed": {"value": "6.12.0", "ok": True, "detail": ""},
                        "wired": {"value": "present", "ok": True, "detail": ""},
                        "upstream_npm": {"value": "6.12.0", "ok": True, "detail": ""},
                        "upstream_github": {"value": "v6.12.0", "ok": True, "detail": ""},
                        "drifts": [],
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    estate = catalog.derive(estate_root, pipeline_truth=truth)
    assert estate.pipeline_truth["bmad-method"]["wired"] == "present"
    text = catalog.render(estate)
    assert "| `bmad-method` | 6.12.0 | 6.12.0 | 6.12.0 | present | 6.12.0 | v6.12.0 | — |" in text
    with pytest.raises(catalog.CatalogSourceError, match="pipeline-truth"):
        catalog.derive(estate_root, pipeline_truth=tmp_path / "absent.json")


def test_cli_write_check_and_exit_codes(estate_root: Path) -> None:
    printed = runner.invoke(app, ["catalog", "bmad-estate", "--root", str(estate_root)])
    assert printed.exit_code == 0, printed.output
    assert "## 4. The bmad-suite roster" in printed.output

    written = runner.invoke(app, ["catalog", "bmad-estate", "--root", str(estate_root), "--write"])
    assert written.exit_code == 0, written.output
    assert (estate_root / catalog.CATALOG_RELPATH).is_file()

    clean = runner.invoke(app, ["catalog", "bmad-estate", "--root", str(estate_root), "--check"])
    assert clean.exit_code == 0, clean.output
    assert "ok -- the catalog matches its sources" in clean.output

    (estate_root / catalog.HARNESS_RELPATH).write_text(_HARNESS.replace("<0.13", "<0.14"), encoding="utf-8")
    drifted = runner.invoke(app, ["catalog", "bmad-estate", "--root", str(estate_root), "--check"])
    assert drifted.exit_code == 1, drifted.output
    assert "section `harness` drifted" in drifted.output

    both = runner.invoke(app, ["catalog", "bmad-estate", "--root", str(estate_root), "--write", "--check"])
    assert both.exit_code == 2

    (estate_root / catalog.HELP_CSV_RELPATH).unlink()
    broken = runner.invoke(app, ["catalog", "bmad-estate", "--root", str(estate_root), "--check"])
    assert broken.exit_code == 2, broken.output
    assert "could-not-run" in broken.output


def test_cli_output_option_targets_another_file(estate_root: Path, tmp_path: Path) -> None:
    target = tmp_path / "elsewhere.md"
    written = runner.invoke(
        app, ["catalog", "bmad-estate", "--root", str(estate_root), "--write", "--output", str(target)]
    )
    assert written.exit_code == 0, written.output
    assert target.is_file()
    checked = runner.invoke(
        app, ["catalog", "bmad-estate", "--root", str(estate_root), "--check", "--output", str(target)]
    )
    assert checked.exit_code == 0, checked.output
