# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.1.1"

package:
  name: simplejson
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/simplejson/simplejson-${{ version }}.tar.gz
  sha256: c08eb9f7a90f77ae470e19a07472e9a79ebc0d1c2315d86a72767665bd5ba79f

build:
  number: 0
  skip: match(python, "<3.6")
  script:
    - if: not win
      then: export REQUIRE_SPEEDUPS=1
    - if: win
      then: set REQUIRE_SPEEDUPS=1
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - simplejson
        - if: python_impl != 'pypy'
          then: simplejson._speedups
        - simplejson.tests
      pip_check: true

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <http://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  homepage: http://github.com/simplejson/simplejson
  repository: https://github.com/simplejson/simplejson
  documentation: http://simplejson.readthedocs.io/

extra:
  recipe-maintainers:
    - ainafp
    - ocefpaf
