# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: neuralcoref
  version: "4.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/neuralcoref-${{ version }}.tar.gz
  sha256: 23aee7418edf5c2e90b3f9f15931563b07ded8c59de386ae654b403322430ad9

build:
  number: 0
  #noarch: python
  #skip: True  # [(py27) or (win and vc<14)]
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
    - ${{ compiler('cxx') }}
    - ${{ compiler('c')}}
    - #- ${{ stdlib('c') }}
    - cython >=0.25,<3.0.0
    - if: build_platform == 'win-64'
      then:
        - posix
    - cmake
    - if: unix
      then:
        - make
  host:
    - python
    - python-abi3
    - pip
    - setuptools <65
    - jsonschema >=2.6.0
    - spacy >=2.1.1,<3.0.0
    - numpy >=1.15.0,<2.0
  run:
    - python
    - numpy >=1.15.0,<2.0
    - boto3
    - requests >=2.13.0,<3.0.0
    - jsonschema >=2.6.0
    - spacy >=2.1.1,<3.0.0

tests:
  - python:
      imports:
        - neuralcoref
        #- neuralcoref.tests
        #- neuralcoref.train
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/huggingface/neuralcoref
  license: MIT
  license_file: LICENSE.txt
  summary: "Coreference Resolution in spaCy with Neural Networks"
  documentation: https://huggingface.co/coref/
  repository: https://github.com/huggingface/neuralcoref

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
    - rxm7706
