# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.10.0"
  python_min: "3.11"
  python_check_max: "3.14"
  pytest_k: not (pandas_index or truncated_index or ignored_columns_are_untouched or missing_values or unknown_value or cat_boost_missing)

package:
  name: category_encoders
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/c/category_encoders/category_encoders-${{ version }}.tar.gz
    sha256: 28e28a01813ac56d4ed068bb8561f523a527b04abf4261be890ab9adbc5fd143
    target_directory: dist
  - url: https://github.com/scikit-learn-contrib/category_encoders/archive/${{ version }}.tar.gz
    sha256: b839d137611767ba53ec82c3b5a2e5c8568719560b72d2d6271567a27dc5325a
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install -vv . --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core
  run:
    - numpy >=1.14.0
    - pandas >=1.0.5
    - patsy >=0.5.1
    - python >=${{ python_min }}
    - scikit-learn >=1.6.0
    - scipy >=1.0.0
    - statsmodels >=0.9.0

tests:
  - python:
      imports: category_encoders
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - coverage
        - python ${{ python_min }}.*
        - pytest
        - pytest-subtests
    script:
      - coverage run --source=category_encoders --branch -m pytest src -vv --color=yes --tb=long -k "${{ pytest_k }}"
      - coverage report --show-missing --skip-covered --fail-under=89

about:
  license: BSD-3-Clause
  license_file: dist/LICENSE.md
  summary: A collection of sklearn transformers to encode categorical variables as numeric
  description: |-
    A set of scikit-learn-style transformers for encoding categorical variables
    into numeric with different techniques. While ordinal, one-hot, and hashing
    encoders have similar equivalents in the existing scikit-learn version, the
    transformers in this library all share a few useful properties:

    - First-class support for pandas dataframes as an input (and optionally as
    output)

    - Can explicitly configure which columns in the data are encoded by name or
    index, or infer non-numeric columns regardless of input type

    - Can drop any columns with very low variance based on training set
    optionally

    - Portability: train a transformer on data, pickle it, reuse it later and
    get the same thing out.

    - Full compatibility with sklearn pipelines, input an array-like dataset
    like any other transformer


  homepage: https://github.com/scikit-learn-contrib/category_encoders
  documentation: https://contrib.scikit-learn.org/category_encoders/

extra:
  recipe-maintainers:
    - bollwyvl
    - nirajd
    - wdm0006
