# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: langsmith-pyo3
  version: "0.1.0rc5"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langsmith_pyo3-${{ version }}.tar.gz
  sha256: 50088d21a6a52a5b2365a02df7ad38f8fd52afe11477dbc636d76afd2921cbe0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - maturin >=1.7,<2.0
    - pip
    - puccinialin
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - langsmith_pyo3
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python bindings for LangSmith internals using PyO3.
  homepage: https://pypi.org/project/langsmith-pyo3/
  license: MIT AND Apache-2.0
  license_file:
    - vendor/pyo3/LICENSE-APACHE
    - vendor/pyo3/LICENSE-MIT
    - vendor/pyo3/pyo3-macros/LICENSE-APACHE
    - vendor/pyo3/pyo3-macros/LICENSE-MIT
    - vendor/pyo3/pyo3-ffi/LICENSE-APACHE
    - vendor/pyo3/pyo3-ffi/LICENSE-MIT
    - vendor/pyo3/pyo3-macros-backend/LICENSE-APACHE
    - vendor/pyo3/pyo3-macros-backend/LICENSE-MIT
    - vendor/pyo3/pyo3-runtime/LICENSE-APACHE
    - vendor/pyo3/pyo3-runtime/LICENSE-MIT
    - vendor/pyo3/pyo3-build-config/LICENSE-APACHE
    - vendor/pyo3/pyo3-build-config/LICENSE-MIT
    - vendor/orjson/LICENSE-APACHE
    - vendor/orjson/LICENSE-MIT
    - vendor/orjson/include/pyo3/LICENSE-APACHE
    - vendor/orjson/include/pyo3/LICENSE-MIT

extra:
  recipe-maintainers:
    - rxm7706
