# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-treenode
  version: "0.23.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_treenode-${{ version }}.tar.gz
  sha256: 3c5a6ff5e0c83e34da88749f602b3013dd1ab0527f51952c616e3c21bf265d52

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<4

tests:
  - python:
      imports:
        - treenode
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: probably the best abstract model/admin for your tree based stuff.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/fabiocaccamo/django-treenode

extra:
  recipe-maintainers:
    - rxm7706
