{% set name = "spec-workflow-mcp" %}
{% set npm_name = "@pimzino/spec-workflow-mcp" %}
{% set version = "2.0.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ npm_name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 462be30e36b4ce36f61b6182cb77ae3b6b46bd832f62fbd28216aee0b256239e

build:
  number: 0

requirements:
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - spec-workflow-mcp --help
    - test -f $PREFIX/bin/spec-workflow-mcp  # [not win]
    - if not exist %PREFIX%\bin\spec-workflow-mcp exit 1  # [win]

about:
  home: https://github.com/Pimzino/spec-workflow-mcp
  license: GPL-3.0-only
  license_file: LICENSE
  summary: MCP server for spec-driven development workflow with real-time web dashboard
  description: |
    A Model Context Protocol (MCP) server that implements structured spec-driven
    development workflow tools for AI-assisted software development, featuring
    a real-time web dashboard and VSCode extension.
  dev_url: https://github.com/Pimzino/spec-workflow-mcp

extra:
  recipe-maintainers:
    - rxm7706
