# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: import-linter
  version: "2.5.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/import_linter-${{ version }}.tar.gz
  sha256: d8f2dc6432975cc35edc4cc0bfcf1b811f05500b377ce0c3f62729d68f46c698

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - lint-imports = importlinter.cli:lint_imports_command

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - click >=6
    - grimp >=3.12
    - if: match(python, "<3.11")
      then: tomli >=1.2.1
    - typing_extensions >=3.10.0.0

tests:
  - python:
      imports:
        - import_linter
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - lint-imports --help

about:
  homepage: https://pypi.org/project/import-linter/
  summary: Enforces rules for the imports within and between Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - millsks
    - rxm7706
    - cshaley
