# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.1"

package:
  name: dill
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dill/dill-${{ version }}.tar.gz
  sha256: 423092df4182177d4d8ba8290c8a5b640c66ab35ec7da59ccfa00f6fa3eea5fa

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=42
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - dill
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/uqfoundation/dill
  license: BSD-3-Clause
  license_file: LICENSE
  summary: serialize all of Python
  description: |
    serialize all of Python
  repository: https://github.com/uqfoundation/dill
  documentation: http://dill.rtfd.io

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: dill
  cfe-upstream-registry: pypi
  cfe-upstream-name: dill
  cfe-purls:
    - pkg:conda/dill@${{ version }}?channel=conda-forge
    - pkg:pypi/dill@${{ version }}
  cfe-upstream-repo: https://github.com/uqfoundation/dill
  cfe-upstream-homepage: https://github.com/uqfoundation/dill
  cfe-import-names: [dill]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/dill-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-17T07:45:51Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-17T07:45:51Z
  cfe-local-build-status: success
  cfe-local-build-datetime: 2026-08-17T07:45:51Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
