# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "15.5.0"

package:
  name: aioboto3
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/aioboto3/aioboto3-${{ version }}.tar.gz
  sha256: ea8d8787d315594842fbfcf2c4dce3bac2ad61be275bc8584b2ce9a3402a6979

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=68.2.0
    - setuptools-scm >=8
  run:
    - python >=${{ python_min }}
    - aiobotocore ==2.25.1
    - aiofiles >=23.2.1

tests:
  - python:
      imports:
        - aioboto3
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/terricain/aioboto3
  license: Apache-2.0
  license_file: LICENSE
  summary: Async boto3 wrapper
  description: |
    Async boto3 wrapper
  documentation: https://readthedocs.org/projects/aioboto3/

extra:
  recipe-maintainers:
    - peterbygrave
    - dgasmith
    - skrsna
    - markllama

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: aioboto3
  cfe-upstream-registry: pypi
  cfe-upstream-name: aioboto3
  cfe-purls:
    - pkg:conda/aioboto3@${{ version }}?channel=conda-forge
    - pkg:pypi/aioboto3@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://github.com/terricain/aioboto3
  cfe-import-names: [aioboto3]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/aioboto3-feedstock
  cfe-forge-recipe-updates-needed: 
    - meta-yaml-to-recipe-yaml
    - version-update-to-15.5.0

  cfe-forge-blocker-list: []
  cfe-last-checked: 2026-08-18T07:46:10Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T07:46:10Z
  cfe-local-build-status: build-clean-test-blocked
  cfe-local-build-datetime: 2026-08-18T07:46:10Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
####
