# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.1"

package:
  name: leather
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/leather/leather-${{ version }}.tar.gz
  sha256: 67119c2aee93be821f077193bd8534e296c05b38bd174d9c5a80c4aa31d1a4d3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - leather
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://leather.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: Python charting for 80% of humans.
  description: |
    Python charting for 80% of humans.

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen

#### CFE metadata AND comments
# CFE metadata
  cfe-conda-name: leather
  cfe-upstream-registry: pypi
  cfe-upstream-name: leather
  cfe-purls:
    - pkg:conda/leather@${{ version }}?channel=conda-forge
    - pkg:pypi/leather@${{ version }}
  cfe-upstream-repo: none
  cfe-upstream-homepage: https://leather.readthedocs.io/
  cfe-import-names: [leather]
  cfe-source-kind: pypi-sdist
  cfe-noarch: python
  cfe-pip-check: "true"
  cfe-on-conda-forge-status: confirmed-on-conda-forge
  cfe-on-conda-forge-feedstock: https://github.com/conda-forge/leather-feedstock
  cfe-forge-recipe-updates-needed: none
  cfe-forge-blocker-list:
    - missing-license-file
    - missing-license-file
    - missing-license-file
    - missing-license-file

  cfe-last-checked: 2026-08-18T01:14:04Z
  cfe-generated-by-version: 8.81.0
  cfe-generated-at-datetime: 2026-08-18T01:14:04Z
  cfe-local-build-status: failed
  cfe-local-build-datetime: 2026-08-18T01:14:04Z
  cfe-local-build-platform: linux-64
  cfe-local-build-tool: rattler-build
####
# CFE comments
# Header:
#    # license: rattler-build did not copy a license file; recorded, retrying common names
#    # blocker: missing-license-file
####
