"""Steward Story 66.1 / 66.2 (spec-pyforge-steward CAP-153 / CAP-154): the lint /
type gate's registry check, the pre-commit set's existence check, and the
commit-msg hook -- the parts that are pure functions over files. The tools
themselves (ruff / mypy) are exercised by the `lint-types` task in CI and
`pr-preflight`, not here."""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts"


def _load(name: str):
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


# ---- target_version_check --------------------------------------------------------

def test_target_version_check_is_a_repo_detector_with_a_task() -> None:
    mod = _load("target_version_check")
    assert mod.DETECTOR == {"scope": "repo"}
    assert "[feature.guild-tasks.tasks.target-version-check]" in (ROOT / "pixi.toml").read_text(encoding="utf-8")


def test_target_version_findings_name_the_drift(tmp_path: Path) -> None:
    mod = _load("target_version_check")
    good = tmp_path / "good.toml"
    good.write_text('[tool.ruff]\ntarget-version = "py314"\n[tool.mypy]\npython_version = "3.14"\n', encoding="utf-8")
    assert mod.findings_for(good, (3, 14)) == []
    drift = tmp_path / "drift.toml"
    drift.write_text('[tool.ruff]\ntarget-version = "py312"\n[tool.mypy]\npython_version = "3.12"\n', encoding="utf-8")
    out = mod.findings_for(drift, (3, 14))
    assert len(out) == 2 and "py312" in out[0] and "3.12" in out[1]
    bare = tmp_path / "bare.toml"
    bare.write_text('[project]\nname = "x"\n', encoding="utf-8")
    assert mod.findings_for(bare, (3, 14)) == ["no [tool.ruff] section", "no [tool.mypy] section"]


def test_live_tree_targets_match_the_interpreter() -> None:
    mod = _load("target_version_check")
    assert mod.main() == 0


# ---- precommit_config_check -------------------------------------------------------

def test_precommit_config_check_is_a_repo_detector_with_a_task() -> None:
    mod = _load("precommit_config_check")
    assert mod.DETECTOR == {"scope": "repo"}
    assert "[feature.guild-tasks.tasks.precommit-config-check]" in (ROOT / "pixi.toml").read_text(encoding="utf-8")


def test_precommit_config_live_file_passes_and_a_missing_file_fails(tmp_path: Path) -> None:
    mod = _load("precommit_config_check")
    assert mod.findings() == []
    missing = ROOT / ".pre-commit-config.does-not-exist.yaml"
    (out,) = mod.findings(missing)
    assert out.startswith(missing.name) and out.endswith("installs nothing without it")


def test_precommit_config_missing_hook_type_and_hook_are_named(tmp_path: Path) -> None:
    mod = _load("precommit_config_check")
    cfg = tmp_path / ".pre-commit-config.yaml"
    cfg.write_text(
        "default_install_hook_types: [commit-msg]\nrepos:\n  - repo: local\n    hooks:\n"
        "      - id: commit-msg-no-attribution\n        entry: python scripts/commit_msg_hook.py\n        language: system\n        stages: [commit-msg]\n",
        encoding="utf-8",
    )
    out = mod.findings(cfg)
    assert any("pre-push" in f and "default_install_hook_types" in f for f in out)
    assert any("hook `pre-push-preflight` is missing" == f for f in out)


# ---- commit_msg_hook --------------------------------------------------------------

@pytest.mark.parametrize(
    "message",
    [
        "fix: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
        "fix: thing\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n",
        "feat: x\n\nGenerated by Copilot\n",
    ],
)
def test_commit_msg_hook_refuses_attribution(tmp_path: Path, message: str, capsys: pytest.CaptureFixture[str]) -> None:
    mod = _load("commit_msg_hook")
    f = tmp_path / "MSG"; f.write_text(message, encoding="utf-8")
    assert mod.main([str(f)]) == 1
    assert "AGENTS.md § Policy" in capsys.readouterr().out


def test_commit_msg_hook_accepts_a_clean_message_and_ignores_comments(tmp_path: Path) -> None:
    mod = _load("commit_msg_hook")
    f = tmp_path / "MSG"
    f.write_text("steward: land 66.2\n\nBody.\n# Co-Authored-By: this is a git comment line, ignored\n", encoding="utf-8")
    assert mod.main([str(f)]) == 0


def test_pre_push_hook_script_exists_and_names_the_opt_out() -> None:
    hook = SCRIPTS / "pre_push_preflight.sh"
    text = hook.read_text(encoding="utf-8")
    assert hook.stat().st_mode & 0o111, "pre-push hook must be executable"
    assert "pixi run --frozen -e pyforge-guild pr-preflight" in text
    assert "PYFORGE_PREFLIGHT_SKIP" in text and "preflight-skips.log" in text
    # git exports GIT_DIR & co. to hooks; a preflight that inherits them breaks every test that
    # `git init`s a temp repo (seen live 2026-09-20) -- the hook must scrub them first.
    assert "unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE" in text
    assert "branch delete -- nothing to preflight" in text  # `git push --delete` carries no commits
    # Under pre-commit a pre-push hook gets no stdin; the refs arrive as PRE_COMMIT_* env vars.
    assert "PRE_COMMIT_REMOTE_BRANCH" in text and "PRE_COMMIT_TO_REF" in text


@pytest.mark.parametrize(
    ("env", "stdin", "expect"),
    [
        ({"PRE_COMMIT_REMOTE_BRANCH": "refs/heads/dispatch/pyforge-marshal/53.2", "PRE_COMMIT_TO_REF": "abc"}, "", "dispatch/* branch"),
        ({"PRE_COMMIT_REMOTE_BRANCH": "refs/heads/x", "PRE_COMMIT_TO_REF": "0" * 40}, "", "branch delete"),
        ({}, "HEAD\tabc\trefs/heads/dispatch/pyforge-doctor/1.1\tdef\n", "dispatch/* branch"),
        ({}, "(delete)\t" + "0" * 40 + "\trefs/heads/x\tabc\n", "branch delete"),
    ],
    ids=["env-dispatch", "env-delete", "stdin-dispatch", "stdin-delete"],
)
def test_pre_push_hook_skips_dispatch_branches_and_deletes(tmp_path: Path, env: dict, stdin: str, expect: str) -> None:
    """Both skips must fire in BOTH invocation forms; run inside a throwaway git repo so the
    hook's own `git rev-parse` calls and its journal never touch the real checkout."""
    import os
    import shutil
    import subprocess

    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", "-b", "main", str(repo)], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-q", "--allow-empty", "-m", "x"], check=True, env={**os.environ, "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@x", "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@x"})
    hook = repo / "hook.sh"
    shutil.copy(SCRIPTS / "pre_push_preflight.sh", hook)
    clean_env = {k: v for k, v in os.environ.items() if not k.startswith(("PRE_COMMIT_", "GIT_", "PYFORGE_PREFLIGHT"))}
    proc = subprocess.run(["bash", str(hook)], cwd=repo, input=stdin, capture_output=True, text=True, env={**clean_env, **env})
    assert proc.returncode == 0, proc.stderr
    assert expect in proc.stderr


# Story 68.2 (spec-pyforge-steward CAP-156): every skip is journaled with the pushed ref(s) and
# sha(s), never the checked-out branch. There is deliberately NO hook-side "nothing new" skip
# (review 1, high): under pre-commit the hook sees only the FIRST ref of a multi-ref push, so it
# cannot prove what the others carry -- a push already on origin/main still runs the preflight
# unless the pushing tool sets the journaled opt-out with its own proof (marshal Story 57.1).
# A fake failing `pixi` on PATH stands in for the real preflight, so "ran it" is observable.
_GIT_ID = {"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@x", "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@x"}


def _hook_repo(tmp_path: Path, *, with_origin_main: bool = True) -> tuple[Path, dict, str]:
    """A throwaway repo on `main` with one commit, optionally pushed to a bare `origin`, a
    `loop/x` branch at main's tip, the hook copied in, and a fake failing `pixi` on PATH."""
    import os
    import shutil
    import subprocess

    env = {k: v for k, v in os.environ.items() if not k.startswith(("PRE_COMMIT_", "GIT_", "PYFORGE_PREFLIGHT"))}
    env.update(_GIT_ID)
    fakebin = tmp_path / "bin"
    fakebin.mkdir()
    (fakebin / "pixi").write_text("#!/usr/bin/env bash\necho PREFLIGHT-RAN >&2\nexit 1\n", encoding="utf-8")
    (fakebin / "pixi").chmod(0o755)
    env["PATH"] = f"{fakebin}:{env['PATH']}"
    repo = tmp_path / "repo"
    subprocess.run(["git", "init", "-q", "-b", "main", str(repo)], check=True, env=env)
    subprocess.run(["git", "-C", str(repo), "commit", "-q", "--allow-empty", "-m", "base"], check=True, env=env)
    if with_origin_main:
        origin = tmp_path / "origin.git"
        subprocess.run(["git", "init", "-q", "--bare", str(origin)], check=True, env=env)
        subprocess.run(["git", "-C", str(repo), "remote", "add", "origin", str(origin)], check=True, env=env)
        subprocess.run(["git", "-C", str(repo), "push", "-q", "origin", "main"], check=True, env=env)
    subprocess.run(["git", "-C", str(repo), "branch", "loop/x"], check=True, env=env)
    shutil.copy(SCRIPTS / "pre_push_preflight.sh", repo / "hook.sh")
    main_sha = subprocess.run(["git", "-C", str(repo), "rev-parse", "main"], check=True, capture_output=True, text=True).stdout.strip()
    return repo, env, main_sha


def _run_hook(repo: Path, env: dict, *, stdin: str = "", extra: dict | None = None):
    import subprocess

    return subprocess.run(["bash", "hook.sh"], cwd=repo, input=stdin, capture_output=True, text=True, env={**env, **(extra or {})})


def _journal(repo: Path) -> list[list[str]]:
    log = repo / ".steward" / "preflight-skips.log"
    return [line.split("\t") for line in log.read_text(encoding="utf-8").splitlines()] if log.exists() else []


@pytest.mark.parametrize("form", ["env", "stdin"])
def test_pre_push_hook_still_preflights_a_push_already_on_origin_main(tmp_path: Path, form: str) -> None:
    """The hook cannot see a multi-ref push's other refs under pre-commit, so it never skips on
    "the first ref is on main" -- in either invocation form."""
    repo, env, sha = _hook_repo(tmp_path)
    if form == "env":
        proc = _run_hook(repo, env, extra={"PRE_COMMIT_REMOTE_BRANCH": "refs/heads/loop/x", "PRE_COMMIT_TO_REF": sha})
    else:
        proc = _run_hook(repo, env, stdin=f"refs/heads/loop/x\t{sha}\trefs/heads/loop/x\t{'0' * 40}\n")
    assert proc.returncode == 1
    assert "PREFLIGHT-RAN" in proc.stderr
    assert _journal(repo) == []


def test_pre_push_hook_manual_opt_out_journals_the_pushed_ref_not_the_checked_out_branch(tmp_path: Path) -> None:
    import subprocess

    repo, env, _ = _hook_repo(tmp_path)
    subprocess.run(["git", "-C", str(repo), "commit", "-q", "--allow-empty", "-m", "new"], check=True, env=env)
    new = subprocess.run(["git", "-C", str(repo), "rev-parse", "HEAD"], check=True, capture_output=True, text=True).stdout.strip()
    proc = _run_hook(
        repo,
        env,
        extra={
            "PRE_COMMIT_REMOTE_BRANCH": "refs/heads/feature",
            "PRE_COMMIT_TO_REF": new,
            "PYFORGE_PREFLIGHT_SKIP": "1",
            "PYFORGE_PREFLIGHT_SKIP_REASON": "operator reason",
        },
    )
    assert proc.returncode == 0, proc.stderr
    assert "PREFLIGHT-RAN" not in proc.stderr
    (row,) = _journal(repo)
    assert row[1] == "refs/heads/feature"  # the pushed ref, never the checked-out `main`
    assert row[2] == new[:10]
    assert row[3] == "operator reason"


@pytest.mark.parametrize(
    ("extra", "stdin", "ref", "reason"),
    [
        ({"PRE_COMMIT_REMOTE_BRANCH": "refs/heads/dispatch/pyforge-marshal/53.2", "PRE_COMMIT_TO_REF": "a" * 40}, "",
         "refs/heads/dispatch/pyforge-marshal/53.2", "dispatch/* branch: supervisor-gated"),
        ({}, "(delete)\t" + "0" * 40 + "\trefs/heads/gone\tabc\n", "refs/heads/gone", "branch delete: nothing to preflight"),
    ],
    ids=["dispatch", "delete"],
)
def test_pre_push_hook_automatic_skips_journal_the_pushed_ref(tmp_path: Path, extra: dict, stdin: str, ref: str, reason: str) -> None:
    repo, env, _ = _hook_repo(tmp_path)
    proc = _run_hook(repo, env, stdin=stdin, extra=extra)
    assert proc.returncode == 0, proc.stderr
    assert "PREFLIGHT-RAN" not in proc.stderr
    (row,) = _journal(repo)
    assert row[1] == ref
    assert row[3] == reason
