"""Unit tests for ``scripts/docs_pixi_tasks.py`` (Story 30.3,
spec-pyforge-doctor CAP-84): docs/how-to/pixi-tasks.md generated from
pixi.toml's own task tables and [environments].

``pytest.importorskip("yaml")`` mirrors ``test_docs_map_render.py`` --
see ``test_docs_gen_common.py``'s own docstring for why. Real coverage runs
from ``docs-gen-test`` (guild-tasks).
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

pytest.importorskip("yaml")

REPO_ROOT = Path(__file__).resolve().parents[2]
_SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import _docs_gen_common as common  # noqa: E402
import docs_pixi_tasks as m  # noqa: E402

_STAMP = {"derived_at": "2026-01-01T00:00:00", "tree": "deadbeef"}

_PIXI_TOML = """\
[environments]
alpha = ["python", "alpha-feature"]
beta = { features = ["python", "beta-feature"], no-default-feature = true }

[feature.alpha-feature.tasks.hello]
description = "say hello"
cmd = "echo hello"

[feature.alpha-feature.tasks.goodbye]
cmd = "echo bye"

[feature.beta-feature.tasks.undocumented]
description = "a | pipe and a\\nnewline"
cmd = "echo undocumented"
"""


def _write_pixi_toml(root: Path) -> None:
    (root / "pixi.toml").write_text(_PIXI_TOML, encoding="utf-8")


def test_render_groups_tasks_by_feature_and_lists_composing_environments(tmp_path: Path):
    _write_pixi_toml(tmp_path)

    content = m.render(tmp_path, _STAMP)

    assert "## Feature: `alpha-feature`" in content
    assert "Environments: `alpha`" in content
    assert "| `hello` | say hello |" in content
    assert "| `goodbye` | *(no description)* |" in content
    assert "## Feature: `beta-feature`" in content
    assert "Environments: `beta`" in content


def test_render_escapes_pipes_and_collapses_newlines_in_description(tmp_path: Path):
    _write_pixi_toml(tmp_path)

    content = m.render(tmp_path, _STAMP)

    assert "a \\| pipe and a newline" in content


def test_render_embeds_the_stamp_header(tmp_path: Path):
    _write_pixi_toml(tmp_path)

    content = m.render(tmp_path, _STAMP)

    assert "derived_at: 2026-01-01T00:00:00" in content
    assert "tree: deadbeef" in content
    assert content.startswith("<!-- GENERATED by scripts/docs_pixi_tasks.py")


def test_render_is_deterministic_given_the_same_stamp(tmp_path: Path):
    _write_pixi_toml(tmp_path)

    assert m.render(tmp_path, _STAMP) == m.render(tmp_path, dict(_STAMP))


def test_main_writes_then_check_agrees_then_a_pixi_toml_edit_reds_check(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    _write_pixi_toml(tmp_path)
    monkeypatch.setattr(common, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(common, "head_stamp", lambda root: dict(_STAMP))
    monkeypatch.setattr(sys, "argv", ["docs_pixi_tasks.py"])

    assert m.main() == 0
    page = tmp_path / "docs" / m.PAGE_REL
    assert page.is_file()

    monkeypatch.setattr(sys, "argv", ["docs_pixi_tasks.py", "--check"])
    assert m.main() == 0  # unchanged tree -> current

    # A task added to pixi.toml, not yet regenerated -> --check reds it.
    (tmp_path / "pixi.toml").write_text(
        _PIXI_TOML + '\n[feature.alpha-feature.tasks.new-task]\ndescription = "new"\ncmd = "echo new"\n',
        encoding="utf-8",
    )
    assert m.main() == 1
