schema_version: 1

context:
  name: reactpy-github-buttons
  version: 0.0.14

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/reactpy_github_buttons-${{ version }}.tar.gz
  sha256: 109faa217c5b11844a6c69d042a7ee2105fcbbfc3ad44eba6d2c173b31036cb0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0.0
    - reactpy >=1.0.2,<2.0.0

tests:
  - python:
      imports:
        - reactpy_github_buttons
      pip_check: true

about:
  summary: ReactPy wrapper for react-github-btn
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/stevej2608/reactpy-github-buttons

extra:
  recipe-maintainers:
    - rxm7706
